### ISSUE TITLE
poor error handling when reaching Amplify app limit

### ISSUE THREAD

**Issue by jhockett** [aws-amplify/amplify-cli#10063]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

Applies to all installations

### If applicable, what version of Node.js are you using?

N/A

### Amplify CLI Version

7.6.26

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

N/A

### Amplify Categories

Not applicable

### Amplify Commands

add, update

### Describe the bug

At time of writing, there's a 25 Amplify application limit for a single AWS account in a given region. When this limit is reached, the CLI will not fail gracefully and can result in a misleading error message about a missing appId and a stack trace dump.

### Expected behavior

A helpful error message with next steps.

### Reproduction steps

Create 25 Amplify apps
Initialize a new Amplify app and try to run various operations with the CLI

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

![image](https://user-images.githubusercontent.com/1815789/160024514-1f23c0a4-4697-40b7-8b8c-160dc3453a38.png)
![image (1)](https://user-images.githubusercontent.com/1815789/160024519-e810a840-9f83-489f-a4e5-94c4a3c0ac22.png)

**Comment by SebasRod23** [comment]
Hello, if nobody is working on this I would like to give it a try

**Comment by jhockett** [comment]
Awesome @SebasRod23! Before opening a pull request, could you provide an overview of your solution in this issue? That way we can align on an approach before you spend time working on it.

**Comment by SebasRod23** [comment]
Hi @jhockett. I was able to reproduce the issue and I have an idea for a possible solution that I would like to discuss before start coding it. I think we can add some validation for the `amplify init` command that will check that the `amplify-meta.json` has the attribute `"AmplifyAppId"` (the reason for this is because every new project, once the application limit has been reached, will not have this ID) and if it doesn't, it will throw an error explaining that the application limit has been reached. 

To make this validation we can use the `getAppId` function from `secretName.ts` and wrap it in a try-catch to throw the new and more helpful error message if the attribute is not found, an alternative would be to make a similar function that would throw the new error message.

**Comment by jhockett** [comment]
Hi @SebasRod23, apologies for the late response.

I think the approach you laid out can work, but for now let's stick to printing a warning message since it won't affect existing behavior. The exact behavior and messaging will be decided in an API review, so I wouldn't bother implementing anything more complex than a warning for now.

I think a more ideal solution would be to check the total number of apps present in the given region before init begins, but it's more complicated and beyond the scope of this PR.

**Comment by SebasRod23** [comment]
Perfect, I will start working on this solution with these changes.
