### ISSUE TITLE
Moving from Amplify Dev to Prod in new Account (code in CodeCommit)

### ISSUE THREAD

**Issue by samburton4655** [aws-amplify/amplify-cli#10181]
**Which Category is your question related to?**
Amplify CLI

**Amplify CLI Version**
7.6.23

**What AWS Services are you utilizing?**
Amplify, Cognito, DynamoDB, AppSync, S3, EC2, CodeCommit, Control Tower

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
I currently have an Amplify Dev project that is in a development account. My code for this project lives in a CodeCommit repo that's also in this development account. I have Control Tower set up and would like for this project to be moved to my production account. What are best practices regarding getting my architecture set up for a shift into production?

**Comment by josefaidt** [comment]
Hey @samburton4655 :wave: thanks for raising this and apologies for the delay here! While we will be able to create another environment that points to the production AWS account, since the code lives in the dev account you will not be able to hook up to Amplify Hosting CI/CD pipeline running in your production account. Please let me know if this does not answer your question and we can re-open to investigate further 🙂
