### ISSUE TITLE
How to set up auth without username

### ISSUE THREAD

**Issue by janhesters** [aws-amplify/amplify-cli#1041]
** Which Category is your question related to? **
Auth

** What AWS Services are you utilizing? **
Cognito

** Provide additional details e.g. code snippets **
I'm building an app using React. I ran `aws add auth` and chose the defaults. I added the `withAuthenticator` HOC. When I created a new account I noticed, that I have to sign up with a user name. I want my auth flow to be just email, password and telephone. How do I do that?

**Comment by undefobj** [comment]
@janhesters I transfered this issue to the CLI repo as this is being actively worked on already. Please see the RFC here: https://github.com/aws-amplify/amplify-cli/issues/766

cc @kaustavghosh06

**Comment by janhesters** [comment]
@undefobj Thank you!

**Comment by kaustavghosh06** [comment]
@janhesters With our new version of the CLI we've introduced the ability for users to select how they want users to sing in upfront as a part of the default flow instead of setting the username attribute as a default in the default flow (which is immutable unfortunately after the creation of the userpool since that is a restriction from the Cognito service). Please feel free to check it out and re-open/comment on this issue if you see a problem with it.
