### ISSUE TITLE
Permission and Installation issues

### ISSUE THREAD

**Issue by jkwalsh127** [aws-amplify/amplify-cli#10825]
I am having permission and installation issues when trying to install in a new react app.

`npm install -g @aws-amplify/cli` leads to EACCES error

`sudo npm install -g @aws-amplify/cli --unsafe-perm=true` allows the install to commence, but it gets stuck at "reify:axios: timing reifyNode:node_modules/@aws-amplify/cli/node_modules/readable-stream"

running without the global flag gets stuck on "reify:axios timing reifyNode:node_modules/@aws-amplify/cli"

npm 8.11.0
node 16.16.0
macOS Big Sur 11.5.2

**Comment by jhockett** [comment]
Hi @jkwalsh127,

Amplify CLI does not work unless it is installed globally. I also do not recommend using `sudo` to install if possible because it can lead to other file access issues.

You can try installing the binary directly without npm using `curl -sL https://aws-amplify.github.io/amplify-cli/install | bash && $SHELL`. [Documentation](https://docs.amplify.aws/cli/start/install/)

If that doesn't work, can you post the full error message?

**Comment by jkwalsh127** [comment]
This worked beautifully! Thank you very much for the explanation and quick response.
