### ISSUE TITLE
Amplify may affect the free tier.

### ISSUE THREAD

**Issue by alphonse92** [aws-amplify/amplify-cli#10873]
I just realized the usage of amplify could affect the free-tier because Amplify storages configuration files in S3. After a couple of weeks of ussaging, I noticed I'm close to reaching my free tier limit in s3 because Amplify pushing/pulling operations. 

Is there a way to mitigate those effects, since I'm not using s3?

![image](https://user-images.githubusercontent.com/18203585/184026499-0e1a2ab9-0905-4c2d-903b-e30917b037f2.png)

**Comment by ykethan** [comment]
Hey @alphonse92, By default amplify stores your deployment files in S3 storage. Amplify generates the #current-cloud-backend.zip in the bucket which acts as a source of truth for your deployment.

**Comment by alphonse92** [comment]
Hi! Thanks for reply.

Yes, I know, but that's the point. Amplify recurrently make requests to s3 to handle the project every deployment. Is there a way to mitigate that situation? For example, extending the S3 free tier limits out the normal if we uses amplify

**Comment by modelorona** [comment]
I was also caught by this and incurred some unexpected costs. Now I've gotten into the habit of pushing a lot less to avoid all those calls for tiny changes. Additionally I go into S3 and delete old lambda versions as they take up space. I'm hoping to automate this in the future on my end, not sure if there's already existing functionality on Amplify's/AWS's side to set how many versions to keep.

Had a shell script to delete old lambda layers back when I was still using them, will drop it below in case anyone finds it useful. It deletes all old versions except the current one and worked for my use case because all my lambdas were configured to use the newest version. Requires [```jq```](https://stedolan.github.io/jq/)
```bash
layer='your_layer_name_here'

aws lambda list-layer-versions --layer-name "$layer" | jq '.LayerVersions | .[1:] | to_entries[] | .value | .Version' | xargs -n 1 aws lambda delete-layer-version --layer-name "$layer" --version-number
```

**Comment by ykethan** [comment]
Hey @alphonse92, thank you for the information. I believe this would make a great improvement on Amplify CLI. I have created a feature request for improvements, please refer to https://github.com/aws-amplify/amplify-cli/issues/10893. 
To prevent any miscommunication between issues, I will close this issue. Please do subscribe to the issue and add any information about your use case.
