### ISSUE TITLE
Auth Trigger Template still uses Node 12

### ISSUE THREAD

**Issue by SebastianStamm** [aws-amplify/amplify-cli#10887]
### Is this feature request related to a new or existing Amplify category?

auth

### Is this related to another service?

Lambda

### Describe the feature you'd like to request

With Node 12 being EOL, the runtime for the auth trigger function should be updated to Node 14 to be consistent with the runtime used in other environments. It currently still uses Node 12:

https://github.com/aws-amplify/amplify-cli/blob/aaf22103548a329b3092f52736c28c9b5c5b8b8b/packages/amplify-category-auth/src/provider-utils/awscloudformation/utils/generate-auth-trigger-template.ts#L91

### Describe the solution you'd like

Simply updating to `lambda.Runtime.NODEJS_14_X` should do the trick.

### Describe alternatives you've considered

-

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by josefaidt** [comment]
Hey @SebastianStamm :wave: thanks for raising this! While I was not able to see the Node 12.x runtime version be applied to a few of the auth triggers I added to my sample auth resource, I do think this is a great callout and should be updated. Perhaps we can also consider bumping to [Node 16](https://aws.amazon.com/about-aws/whats-new/2022/05/aws-lambda-adds-support-node-js-16/) across all functions. 

Marking as a bug 🙂

**Comment by joekiller** [comment]
It nice to see the PR #10890 to fix this. I was going to comment re @josefaidt's idea of considering Node 16 in case anyone else reviews this issue. The current CDK sdk behind the cli and dependent https://github.com/joekiller/amplify-category-api only go to node 14. I attempted to do a slightly heavier lift to 1.168.0 but ran into some test breakage on amplify-category-api and just dropped the effort due to timeboxing. just an FYI why node 16 is "harder".

**Comment by christian-weiss-df** [comment]
AWS notification e-mail recommends to migrate from NodeJS 12 to NodeJS 16.
We should skip NodeJS 14. My2ct
