### ISSUE TITLE
Having trouble sharing Amplify based application to teammate

### ISSUE THREAD

**Issue by Noks2808** [aws-amplify/amplify-cli#1116]
** Which Category is your question related to? **
AWS Amplify CLI

** What AWS Services are you utilizing? **
AWS Pinpoint

** Provide additional details e.g. code snippets **

I integrated pinpoint analytics into one of our Android apps. (by following the GettingStarted guide https://aws-amplify.github.io/docs/android/start ). I added a few events and they got submitted successfully to pinpoint console after deploying this app. to an Android Phone. 

So I committed the changes and asked a teammate to try this out. When he built the app. and ran it, it crashed with the following error:
java.lang.RuntimeException: Failed to read awsconfiguration.json please check that it is correctly formed

I was hoping that after committing the amplify files along with the .gitignore suggestions by amplify , the amplify environment and authentication details would get saved , but it doesn't seem so as the code looks for an awsconfiguration.json file but that isn't committed due to .gitignore changes by amplify.  I am sharing a list of the amplify files that got committed and .gitignore updates below.

Amplify files that got committed:

```
amplify/.config/project-config.json
amplify/backend/analytics/helixandroid/parameters.json
amplify/backend/analytics/helixandroid/pinpoint-cloudformation-template.json
amplify/backend/auth/cognito*/*-cloudformation-template.yml
amplify/backend/auth/cognito*/parameters.json
amplify/backend/backend-config.json
amplify/team-provider-info.json 
```

Amplify updates to my .gitignore file:

```
#amplify
amplify/\#current-cloud-backend 
amplify/.config/local-*
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
build/ 
dist/ 
node_modules/ 
aws-exports.js
awsconfiguration.json
```

So, two questions here:

1)I know that if my colleagues run amplify init and select the environment that i created earlier, it will lead them to authenticate with an AWS account(to create aws credentials on his machine), then creating a new IAM user and then it would be all set. 
But ideally, i would like my teammate to get the entire setup as soon as he clones the code ; unless he wants to modify the amplify env. in which case he should work with amplify environments.

2)Also, if additional steps are needed to setUp the project after cloning the code, this means that whatever CI/CD approach we use , the built app. would fail with the same error because the current code doesn't seem to be self sufficient.

What is the suggested way of achieving the above ? I didnt find any specific details around this in the general or Multi-env section of amplify.

**Comment by kaustavghosh06** [comment]
@Noks2808 

1) This is a one time setup, which your colleague would have to do to setup the IAM user and Profile (per env) and then from next-time onwards the amplify init command would pick the corresponding profile tied to the env. It's difficult to share the "entire setup" since there are things in your project which are locally referencable like "AWS profiles", "Project Paths" and that needs to be re-created using the `amplify init` command per system/machine. You wouldn't want to share aws creds when sharing a project.

2) For CI/CD, you could refer to https://aws-amplify.github.io/docs/cli/init#headless-usage-of-the-cli for headless implementation of your project. Amplify Console currently used this for CI/CD deployments of Amplify generated projects.
