### ISSUE TITLE
Documentation for adding social providers using override is wrong?

### ISSUE THREAD

**Issue by lucasoares** [aws-amplify/amplify-cli#11178]
Hello.

In the documentation, the key for the AttributeMapping for the preferred username is `preferredUsername`.

I tried to follow the documentation and add social providers in the `override` command but I got an error saying that the `preferred_username` attribute was missing and not mapped. I changed the key to `preferred_username` and the error stopped.

What is the correct way to configure it?

The documentation:
https://docs.amplify.aws/cli/auth/override/#customize-amplify-generated-cognito-auth-resources-with-social-providers

```
AttributeMapping: {
          preferredUsername: "email",
          email: "email"
        },
```

or

```
AttributeMapping: {
          preferred_username: "email",
          email: "email"
        },
```

**Comment by josefaidt** [comment]
Hey @lucasoares :wave: thanks for raising this! I believe you are correct, referencing [this document for UserPool aliases](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html#user-pool-settings-aliases) we see the proper attribute is `preferred_username` rather than `preferredUsername`, and the doc should be updated to reflect this. Would you be open to making this quick adjustment?

**Comment by lucasoares** [comment]
Here you are @josefaidt
