### ISSUE TITLE
API Schema for Unauthenticated users and Groups of users

### ISSUE THREAD

**Issue by amlcodes** [aws-amplify/amplify-cli#1117]
** Which Category is your question related to? **
amplify api, appsync
** What AWS Services are you utilizing? **
appsync, ampify
** Provide additional details e.g. code snippets **

**I just want users to be able to see data when they are not logged in, and when they are logged in, to have certain permissions tied to their identity.** 

While using amplify api graphql, appsync backend I'm running across a usage issue
for what seems to be a pretty sensible schema: posts, with comments and replies on a certain blog or discussion.
with this in mind: 
A: unauthenticated users would have a role with permissions to be able to make certain queries
B: Ideally i'd use cognito user pools to allow users to sign in with their own credentials, and hook up federated identities to that user pool to allow FB or google sign in.
C: Id want 3 groups of authenticate users defined in my user pool to make certain queries and 
mutations: Authenticated Users making queries and mutations on their own data, Moderators making making queries and mutations also on other peoples data, and Admins to be able to do all that and make a blog or discussion mutation.

I just want users to be able to see data when they are not logged in, and when they are logged in, to have certain permissions tied to their identity. 

This seems to be referenced in a proposal by @mikeparisstuff 'multiple auth types in the same api' where a aws_api_key auth directive is used to signify a change in auth types for certain types or fields.

There are always 3 different approaches pointed to work around it, as far as i seem to understand: 
 1. creating a 2nd api for unauthenticated users with IAM auth - which is unsustainable to maintain.
2. creating a fake cognito user for unauthenticated users which is near impossible to lock down permissions for, and would have to build logic inside the app to catch.
3. My current approach - using IAM, and attaching permission policies to assumed role from jwt token, Then add custom resolvers to the new operations to check the group of the cognito user? 

Am I missing something?

**Comment by fsommers** [comment]
It seems I'm also doing what you're describing in #3. But this is a very common use-case:

_Some data is publicly viewable without any kind of authentication (list, get), but privately editable (create, update, delete)._
 
Basically, I don't want users to have to authenticate for list and get, since the data is presented via a public Web site that does not require authentication for reading. 

Having to configure low-level IAM permissions for the AppSync API, and then not being able to use the @auth directive, is a major PITA. 

Is this really the only way to accomplish the above?

Ideally, I'd like to be able to control this via the @auth directive. Currently, the following already accomplishes this for authenticated users:

`{ allow: owner, mutations: [create, update, delete], queries: []}`

It'd be nice to have another value for allow, "unauth", which would do the same for the unauthenticated user. 

`{ allow: unauth, queries: [get, list]}`

Any alternatives of how to perform this use-case would be greatly appreciated.

**Comment by amlcodes** [comment]
yes that is currently the only way I have found ATM. adding in IAM permissions by ARN

**Comment by mikeparisstuff** [comment]
Work is already underway to enable this type of workflow although there is no specific launch date yet. For reference this has been discussed here #54 and will be addressed.

**Comment by dancomanlive** [comment]
This feature is essential. How come it was not built in from the start?
