### ISSUE TITLE
GraphQL API connection to local Dynamo DB

### ISSUE THREAD

**Issue by s-hood** [aws-amplify/amplify-cli#1172]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
GraphQL and Dynamo DB

** What AWS Services are you utilizing? **
Amplify CLI / AppSync / DynamoDB

** Provide additional details e.g. code snippets **
Hi, sorry if this is a basic/misguided question, I'm just getting started. 
I've managed to setup the backend of my React app using Amplify and have deployed via the Amplify Console. I created a GraphQL API using the Amplify CLI and have been able to connect to the created DynamoDB table. I want to continue developing the front-end locally (running yarn start) and would like my GraphQL queries to be against a local DynamoDB as I'm pulling data on every refresh and don't want this taking up my monthly calls. I'm not really sure where to begin, and any guidance is much appreciated! Thanks in advance.

**Comment by kaustavghosh06** [comment]
@s-hood We currently don't have support for local testing but we're actively working on it.

cc: @yuth

**Comment by s-hood** [comment]
Thanks for your reply! That's good to hear.
For now is there a global variable set or some other way I can determine if the app is running locally or not (i.e. from 'yarn start' or from publishing to aws)?

**Comment by jkeys-ecg-nmsu** [comment]
@s-hood take a look at AWSAppSyncClient and/or Apollo Client. You shouldn't need to query over the wire on every refresh -- that implies to me that your query is just initializing your application -- because of Apollo caching. https://www.apollographql.com/docs/react/advanced/caching

Are you querying your Dynamo table directly or via a GraphQL query?

>For now is there a global variable set or some other way I can determine if the app is running locally or not (i.e. from 'yarn start' or from publishing to aws)?

I suppose you could check to see if `window.location.origin` includes "localhost" or is exactly equal to your test URL (including port). https://www.w3schools.com/jsref/prop_loc_origin.asp Not sure if this opens up any security concerns for your particular application. 

You could also just check whether or not your application is online or offline, but it's a different question and may lead to unintended behavior or just not work the way you want it to. https://developer.mozilla.org/en-US/docs/Web/API/NavigatorOnLine/onLine

**Comment by s-hood** [comment]
Okay thanks, I've managed a hacky work around for my local testing but I'll take a look at AWSAppSyncClient and try to cache that data instead.

> Are you querying your Dynamo table directly or via a GraphQL query?

Via GraphQL

**Comment by jkeys-ecg-nmsu** [comment]
@s-hood mind sharing your local solution? I'm curious.

I asked b/c I initially got tripped up on AppSync subscriptions, which are not fired when Dynamo is directly manipulated instead of through AppSync mutations.

**Comment by s-hood** [comment]
@jkeys-ecg-nmsu It's literally just a matter of running different Javascript to load in some local JSON files rather than running a GraphQL query in React's ComponentDidMount lifecyle method. I need to work on some front-end functionality so that does the job for now, when I need to work on my DB structure and querying I might run a local Dynamo and query that.

**Comment by jkeys-ecg-nmsu** [comment]
Oh, so you're mocking your data. I was confused by your OP which made me think you were concerned about the actual details of mocking Dynamo (as opposed to just mocking a generic key-value store). 

I think that the fact that AppSync subscriptions are not fired on direct mutations of underlying data sources is (1) theoretically sound and secure and (2) a minor hassle for developers. It means a developer has to convince Dynamo/NoSQL/RDS devs in their shops (as do I in my own organization) to learn GraphQL and the intricacies of AppSync in order to affect my designed front-end. It would be nice if Dynamo mutations took an AppSync API ARN as an optional parameter and broadcast subscriptions if it was passed with proper IAM authorization.

**Comment by s-hood** [comment]
Okay, apologies for the misunderstanding. Agreed, that would be a useful feature. 
Thanks for your time and help!

**Comment by undefobj** [comment]
https://github.com/aws-amplify/amplify-cli/issues/1433

**Comment by kaustavghosh06** [comment]
@s-hood We released support fo local testing of GrpahQL API with a local DynamoDB table. Please take a look at our launch blog to know more - https://aws.amazon.com/blogs/mobile/amplify-framework-local-mocking/
