### ISSUE TITLE
Error login using 'Local setup instructions'

### ISSUE THREAD

**Issue by shai21** [aws-amplify/amplify-cli#11869]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

19.4.0

### Amplify CLI Version

10.6.2

### What operating system are you using?

Ubuntu server

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No Changes

### Describe the bug

When I'm running the command:
amplify pull --appId APP-ID --envName staging

I'm getting this error:
Opening link:  <link to the cli login key>
⠋ Confirm login in the browser or manually paste in your CLI login key:
🛑 spawn xdg-open ENOENT

Resolution: Please report this issue at https://github.com/aws-amplify/amplify-cli/issues and include the project identifier from: 'amplify diagnose --send-report'
Learn more at: https://docs.amplify.aws/cli/project/troubleshooting/

The only way to get out of this issue is to close terminal.

### Expected behavior

follow to the setup instructions page.

### Reproduction steps

every time I'm running the amplify pull --appId APP-ID --envName staging

### Project Identifier

I couldn't get the project Identifier:

amplify diagnose --send-report

Learn more at https://docs.amplify.aws/cli/reference/diagnose/
⠋ Creating Zip
File at path: '/home/ubuntu/projects/amplifyapp/amplify/backend/backend-config.json' does not exist
✖ Creating Zip

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

I'm running the project on ec2 Ubuntu instance.

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by evcodes** [comment]
Hey @shai21, thank you for reporting this. 

What seems to be happening here is as you're running amplify pull from an EC2 instances, your current session is not authenticated so one of the CLI's method of authentication is federated through the browser. Since you are on an EC2 instance, you will not be able to authenticate this way. Instead, you will likely have to store AWS credentials in your filesystem.

You can run `amplify configure` and add your AWS Access Key ID and Secret Access Key. 

Please let me know if this helps for this issue.
