### ISSUE TITLE
Speed up amplify push for faster development iterations

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#1190]
**Is your feature request related to a problem? Please describe.**
I'm creating custom resolvers, etc.. through nested stacks and doing amplify push to see the results in the backend. `amplify push` takes longer than I want to do its things (several minutes - and longer if there's a rollback). Would be great if it was faster. This impacts developer productivity. 

**Describe the solution you'd like**
Faster amplify pushes. Or, more advanced syntax checking of my nested stack, or some kind of amplify pull so I can do my changes in the AppSync console and it's just pulled to my local files.

**Comment by kaustavghosh06** [comment]
@hisham We rely on Cloudformation directly for our deployment and we cannot directly impact the speed at which Cloudformation deploys. 
Having said that we're going to have an RFC out soon for `amplify appsync pull`. I'll update this thread once we have that out for you to review and comment on it.

**Comment by jkeys-ecg-nmsu** [comment]
>@hisham We rely on Cloudformation directly for our deployment and we cannot directly impact the speed at which Cloudformation deploys.

@kaustavghosh06 do you mean technically speaking? I'm wondering if CloudFormation could integrate with Amplify by detecting an Amplify push and lift (or soften) whatever internal limits AWS has on CF concurrency or compute power. 

I think prioritizing fixing #836 can resolve this issue. `push` speed is only an issue because the CLI currently seems to runs the entire template (including nested templates). It seems like @hisham is only iteratively developing his AppSync (GraphQL) schema, but also has other categories (e.g. auth and hosting) configured for his environment, and his push speed is being limited by the lack of working `amplify api push` command.

**Comment by hisham** [comment]
Calling `aws cloudformation validate-template` on the nested stack template before doing a push catches some errors btw very quickly. It seems this should be called all the time before push and is a quick win.

**Comment by kaustavghosh06** [comment]
Hey guys, we enabled individual category and resource name push. Please give it a try by installing the latest version of the CLI.

**Comment by acisser** [comment]
Even if using the "individual category and resource name push" feature to send my lambda code. It's still taking a lot of time and the whole cloudformation stack is being run. 

For any project initialization this is important and the amplify push times are just inadmissible. I would say that this fact is reducing my productivity around 500% against de 250% that was boosting initially compared against other solutions and architectures.
