### ISSUE TITLE
Changing dynamodb tablename in generated cloudformation template

### ISSUE THREAD

**Issue by vjindalaurea** [aws-amplify/amplify-cli#1227]
Hi, in our case we want different env to share same dynamodb tables . As this feature is not available as of now , so is there any possibility that i can change generated cloud formation templated to point all env to same dynamodb tables  ?

**Comment by kaustavghosh06** [comment]
@vjindalaurea We don't support this use-case of sharing resurces accross since we consider every env to be a it's own sandbox environment. You could however manually modify your aws_exports.js file (for JS projects) or awsconfiguration.json file (for native projects), to point to your desires pre-configured resources.
