### ISSUE TITLE
Use same `git` branch for different amplify backends

### ISSUE THREAD

**Issue by Krishnakumar-Santhanam** [aws-amplify/amplify-cli#12326]
### Amplify CLI Version

10.8.1

### Question

We have our `testing` amplify environment in an AWS account and we have the `production` amplify environment in another AWS account. We are using `master` branch to deploy our backend changes to `testing` environment and `production` branch to deploy our backend changes to `production` environment.

Is it possible to use the same `master` branch to deploy backend changes to both `testing` and `production` account because we often get merge conflicts when we merge `master` branch to our `production` branch? If so, what are the things to be taken care of to prevent the environment from breaking?

**Comment by josefaidt** [comment]
Hey @Krishnakumar-Santhanam :wave: thanks for raising this! While we'll aim to answer this here, this also seems like a great question for our [Discord community](https://discord.gg/invite/amplify)!

Would you say the merge conflicts you are experiencing align with this issue? https://github.com/aws-amplify/amplify-cli/issues/7938

In any event, yes, you can connect the same repo in multiple accounts to use the same branch to deploy both environments. The caveat would be that these projects will deploy at the same time rather than in sequence

**Comment by Krishnakumar-Santhanam** [comment]
@josefaidt We are using Github Actions as our CI/CD pipeline and we want to use the same branch for backend deployments to our `testing` and `production` amplify environments which are residing in different AWS accounts.

**Comment by josefaidt** [comment]
Hey @Krishnakumar-Santhanam are you deploying manually with `amplify publish`?

**Comment by Krishnakumar-Santhanam** [comment]
@josefaidt We are only using `amplify push` to deploy our backend changes.

**Comment by josefaidt** [comment]
Hey @Krishnakumar-Santhanam thanks for clarifying! To your note regarding the new Lambda functions, it appears the specific issue is a side effect of https://github.com/aws-amplify/amplify-cli/issues/8090 and https://github.com/aws-amplify/amplify-cli/issues/10764.

**Comment by josefaidt** [comment]
Closing in favor of tracking existing items, #8090 and #10764
