### ISSUE TITLE
User Pool duplication after editing CF template.

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#1251]
**Describe the bug**
Busy setting up auth. When I had to make manual changes to the configuration. Leading me to create this issue https://github.com/aws-amplify/amplify-cli/issues/1241. The help I got was to update the CF templates in the amplify backend folder. This unfortunately duplicated my User Pool.

**To Reproduce**
1. amplify add auth
2. amplify push
3. Edit the CF template in amplify/backend/auth/cognit*****.yml
4. Add a custom attribute, example:
```
        -
          AttributeDataType: "String"
          Mutable: true
          Name: roles
          StringAttributeConstraints:
            MaxLength: 256
            MinLength: 1
```
to UserPool -> Schema as another attribute.
5. amplify push

**Expected behavior**
I expected the existing User Pool to have updated with the custom attributes. I do understand the resource is replaced, but the old resource has to be deleted then. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac
 - Browse N/A
 - Version N/A

**Additional context**
$ amplify -v
1.1.8

**Comment by kaustavghosh06** [comment]
@jarrettj We added a "Tetain" flag in our Cloudformation file since it's disastrous to delete a user pool (with users in it) when modfying a field in the Cloudformation file and we had many customer complaints regarding the auto-deletion of user-pools, based on which we added the "Retain" flag recently to the Auth Cloudformation file.

**Comment by jarrettj** [comment]
No worries, I understand. Makes total sense. Thanks
