### ISSUE TITLE
deployment-state.json

### ISSUE THREAD

**Issue by vgthoppae** [aws-amplify/amplify-cli#12754]
### Amplify CLI Version

11.1.1

### Question

Hope I'm not going crazy, but I'm not able to locate `deployment-state.json` file anymore in the S3 deployment bucket. I have deleted this file several times manually in the past to get over the legendary problem of "A deployment is already in progress", but I'm not able to locate it anymore unfortunately. Has anything changed recently with amplify upgrades?

**Comment by nathanthorpe** [comment]
I would check the status of your amplify CloudFormation stack to see if it's in `UPDATE_CLEANUP_IN_PROGRESS`. 
This issue just happened to me, and it turns out it was getting stuck on deleting the lambda layer version.

The managed amplify policy needed the `lambda:GetLayerVersionPolicy` action. I added it to the build role, and it completed successfully.

**Comment by vgthoppae** [comment]
Interestingly I did see a layer stack stuck on `UPDATE_CLEANUP_IN_PROGRESS`. Currently Amplify uses the default role with the managed policy `AdministratorAccess-Amplify`, which doesn't seem to have the permission for `lambda:GetLayerVersionPolicy` action. Just curious, did you manually add the additional permission to the role or figured out a way to codify it?

**Comment by nathanthorpe** [comment]
Yeah I had to manually add the permission as an inline policy to the service role.

**Comment by vgthoppae** [comment]
I did the same and it worked like a charm, yeah hope this issue has gets priority in the backlog. Strangely this issue is only sporadic and not consistent.

The other part of my question where I'm not able to locate the `deployment-state.json `still remains a mystery.

**Comment by endymion** [comment]
Related: Is there already a feature request somewhere for a CLI command to fix this problem automatically, so that we don't need a highly-trained DevOps engineer to come to the rescue and [shudder] manually screw with the contents of deployment S3 buckets in order to recover mission-critical production environments?

I find myself struggling daily to defend the idea that Amplify is production-ready and that we can depend on it.  We had a defect in production for over six hours yesterday due to this problem.  PLEASE provide a working `amplify env update` command of some kind.  Production operators demand it.

**Comment by fvisticot** [comment]
> AdministratorAccess-Amplify

Same issue, can you please detail the complete procedure to fix the issue ?

**Comment by vgthoppae** [comment]
> Hey @vgthoppae, thank you for reaching out. This is currently being tracked on [aws-amplify/amplify-studio#969](https://github.com/aws-amplify/amplify-studio/issues/969) to have this added to `AdministratorAccess-Amplify` policy and the Amplify team is currently investigating this behaviour.

Thank you @ykethan

**Comment by vgthoppae** [comment]
> > AdministratorAccess-Amplify
> 
> Same issue, can you please detail the complete procedure to fix the issue ?

- Find the Service role attached to your amplify app (App -> App Settings -> General)
- Look up that role in IAM - you will find `AdministratorAccess-Amplify` policy attached to it
- Add an inline policy as below
<img width="1041" alt="image" src="https://github.com/aws-amplify/amplify-cli/assets/4568997/7406e675-4ed9-4f09-8475-7ab4e02be7be">

**Comment by ykethan** [comment]
Hey everyone, thank you for your patience while the Amplify team investigates this behaviour, wanted provide an update on this issue. The behaviour occurred due to a recent update on the Lambda service. The Lambda team has provided an update that this issue has been mitigated and subsequent `amplify push` executions should work as expected. To summarize, Amplify CLI utilizes CloudFormation to deploy resources and due to the Lambda service update, CloudFormation did not return the correct status. 
Please do let us know if you are still experiencing this issue.

**Comment by vgthoppae** [comment]
Thanks @ykethan and everyone responding in this thread. I'm gonna close this issue as there is a workaround available with additional permission.
