### ISSUE TITLE
Self signed certificate error in Amplify CLI

### ISSUE THREAD

**Issue by janardhan1729** [aws-amplify/amplify-cli#12963]
### How did you install the Amplify CLI?

Curl command

### If applicable, what version of Node.js are you using?

18.6.1

### Amplify CLI Version

12.1.1

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes are made

### Describe the bug

I am trying to pull the backend application using amplify pull command. It is throwing an error saying that "Failed to pull backend". It is not even opening the browser for login confirmation. If I run the command amplify configure it is saying that self signed certificate in certificate chain. I am carrying out this process in my work laptop.

### Expected behavior

It should pull my backend into the local machine

### Reproduction steps

NA

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by ykethan** [comment]
Hey @janardhan1729, thank you for reaching out. The issue appears to be similar to https://github.com/aws-amplify/amplify-cli/issues/8361 and https://github.com/aws-amplify/amplify-cli/issues/12961. 

As suggested in the comment https://github.com/aws-amplify/amplify-cli/issues/12961#issuecomment-1640530891 could you try setting the `NODE_EXTRA_CA_CERTS` path and if that does not mitigate the issue try setting `NODE_TLS_REJECT_UNAUTHORIZED` to `0`. 
I will be closing this issue as duplicate to prevent any miscommunication between issues. It would be great if could you let us know if utilizing an older version of Amplify CLI mitigates the issue on https://github.com/aws-amplify/amplify-cli/issues/12961.

**Comment by josefaidt** [comment]
:wave: to anyone finding this thread --

If you are working on a company-owned machine it is fairly common to see a self-signed certificate in your certificate chain, for example when your company requires HTTP traffic to go through a proxy. However if this is your personal computer and you have not encountered this issue with other Node.js-based tools please confirm the self-signed certificate is intentional before modifying `NODE_TLS_REJECT_UNAUTHORIZED` or adding certificates to the trust store.

Please consult with your IT team before modifying the trust store or disabling TLS checks in Node. And note, disabling TLS checks is _not recommended_.
