### ISSUE TITLE
amplify pull sandbox fails with amplify-meta.json does not exist error

### ISSUE THREAD

**Issue by ykethan** [aws-amplify/amplify-cli#13215]
### How did you install the Amplify CLI?

curl

### Amplify CLI Version

12.4.0

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Describe the bug

Creating a sandbox application and running a pull causes the following error

```
Error: File at path: '/Users/<path>/myapp/amplify/backend/amplify-meta.json' does not exist
Successfully generated models. Generated models can be found in /Users/<path>/rn/myapp/src
```

causing being unable to add resources to the project

### Expected behavior

not error on pull

### Reproduction steps

1. cerate a app on https://sandbox.amplifyapp.com/
2. copy and run the pull command example: `amplify pull --sandboxId a51fb968-6335-4d95-9ad3-b024878001e7`
3. observe error

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by josefaidt** [comment]
confirmed this is a bug

**Comment by josefaidt** [comment]
note for fix: this flow does a partial "pull" in the sense that gitignored files such as `amplify-meta` are not created (likely because we do not yet have an App ID). If `amplify codegen models` is the operation that is dependent on `amplify-meta.json` we can remove this execution.

It is also important to note that Amplify Studio no longer automatically enables DataStore, removing the need for modelgen

**Comment by ykethan** [comment]
closing as wont fix
