### ISSUE TITLE
Invoke the same function

### ISSUE THREAD

**Issue by gbacskai** [aws-amplify/amplify-cli#13303]
### Is this feature request related to a new or existing Amplify category?

function

### Describe the feature you'd like to request

amplify update function -> Resource -> function excludes the function I update

I would like to authorise the function to invoke itself.

For long running jobs (more than 15 mins) I would split up to multiple Lamabda executions in the same function.
E.g. for moving dynamodb data from one table to an other table.

Currently it is not possible to select the same function and as default it is not in role

Error:
AccessDeniedException: User: arn:aws:sts::*****:assumed-role/***LambdaRole****-dev/FunctionName000-dev is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:****:****:function:FunctionName000-dev because no identity-based policy allows the lambda:InvokeFunction action

Or an other case is to scale out to multiple Lambda functions.

### Describe the solution you'd like

Update cli not to exclude the same function or enable the role to invoke the function itself as default.

amplify update function

### Describe alternatives you've considered

I do not see any alternative for now.
Error: Cannot add Function000 due to a cyclic dependency

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by ykethan** [comment]
Hey @gbacskai, thank you for reaching out. We should able to the permission in the function `custom-policies.json` file.

For example:
```
[
  {
    "Action": ["lambda:InvokeFunction"],
    "Resource": [
      "arn:aws:lambda:us-east-1:<account-id>:function:<function-name>-${env}"
    ]
  }
]

```

From the use case, while splitting long running jobs into multiple runs could assist with this, several factor like cost and complexity may need to considered. Because we will need to chunk the task which could introduce memory issues and incur additional cost.
As an alternative, I was hoping to suggest looking into AWS ECS/Fargate for long running tasks, DynamoDB streams with Lambda function should also assist in the replication task where the change is captured in the stream and the Lambda function replicates to the destination table, and additionally StepFunctions may assist with long running tasks where state management and error handling are made easier but this can be a tad costly depending on the use case.

**Comment by ykethan** [comment]
closing the issue due to inactivity. please feel free in reaching out to us, we would be happy in diving deeper.
