### ISSUE TITLE
Documentation Updates for "Migrate from Legacy FCM APIs to HTTP v1"

### ISSUE THREAD

**Issue by SwhiteMHC** [aws-amplify/amplify-cli#13688]
### Amplify CLI Version

12.4.0

### Question

On 06/20/2024, the Cloud Messaging API (Legacy) will be deprecated and everyone will be required to update to Firebase Cloud Messaging API (V1). In the aws-amplify documentation, all instructions point to using the Cloud Messaging API (Legacy). Is there a date for the documentation to be updated and/or are there resources for setting up integration with this API using Amplify?

Thank you.

**Comment by jinfanzon** [comment]
Same issue

**Comment by mpark1** [comment]
Same issue here. Tried generating a service account key and passing that into Amplify CLI but had no success.

**Comment by dwrynngs** [comment]
This has become a blocking issue for me and the project I am working on. I have a new FCM project which will not allow me to use a legacy key.  There is no option on the amplify cli to add the v1 json file that FCM only allows.  therefore I cannot now use FCM notifications with amplify.  Will need to look at moving implementing a more complex SNS event if this isn't fixed.  SNS has supported FCM V1 since January 2024.  pity amplify still doesn't support it.

Is there any response as to when amplify will support FCM V1?  There is 1 week to legacy being turned off and then a lot more people and projects are going to be severely affected

**Comment by MichaelCBarilla** [comment]
Same issue here. My Flutter project is using existing AWS resources and would like to stick within the AWS ecosystem for push notifications.

**Comment by awsluja** [comment]
12.12.3 is live and docs updated https://docs.amplify.aws/gen1/android/build-a-backend/push-notifications/set-up-push-service/
