### ISSUE TITLE
How do i randomly select an AppSync table entry?

### ISSUE THREAD

**Issue by chai86** [aws-amplify/amplify-cli#1400]
I have a table in GraphQL that has 2 columns. One is the Key, and the other is the URL associated with the key.

How can i randomly select one of the keys to retrieve the URL from? 

I don't want to copy the whole list of keys/urls to the client side in an array and use a random() on it, it would be more efficiently done in AWS. Especially as the array could be multiple thousands over time.

Ideally i'd like to then call the below with my key (not an 'id' that i don't know):

`await API.graphql(graphqlOperation(queries.getUrl), {myKey: "786shjvg987"})`

**Comment by mikeparisstuff** [comment]
@chai86 To fetch a random item from a table you are going to need to build some randomness into your key structure. Once the PR for #1062 has been merged this will get easier. In the shorter term, as soon as the new version of the CLI (includes #1358) is released early this week, you will be able to do something like the following.

```graphql
type Category @model {
  id: ID!
  name: String!
  randomUrl(randomNumber: Float!): UrlConnection 
    @connection(name: "RandomUrls", keyField: "categoryId", sortField: "randomNumber")
}
type Url @model {
  id: ID!
  categoryId: ID!
  randomNumber: Float!
  url: String
  category: Category
    @connection(name: "RandomUrls", keyField: "categoryId", sortField: "randomNumber")
}
```

When you create `Url` objects, include a random float:

```graphql
mutation {
  createUrl(input: { url: "www.website.com", randomNumber: 19.13481, categoryId: COMEDY }) { ... }
}
```

Then add these mapping template on the `Category.randomUrl` field.

```json
# Category.randomUrl.req.vtl
{
  "query": {
    "expression": "categoryId = :catId AND randomNumber > :rand",
    "expressionValues": {
      ":catId": { "S": "$ctx.source.id" },
      ":rand": { "S": "$ctx.args.randomNumber" }
    }
  }
}

# Category.randomUrl.res.vtl
$util.toJson($ctx.result)
```

You can then lookup a random url for a category with:

```
query {
  getCategory(id: "comedy") {
    randomUrl(randomNumber: 17.182432) {
      url
    }
  }
}
```


I just made up the **category** concept here because you need some way to group the random urls by a single hash key such that you can use a range query on the sort key to implement the random lookup. You could alternatively use a constant value as a hash key if you did not need the category concept. You can also avoid going through `Query.getCategory` by writing a custom resolver that targets the GSI on the UrlTable data source. Once #1062 is complete, you will be able to build patterns like this without using `@connection`.

**Comment by kaustavghosh06** [comment]
@chai86 Closing this issue for now. If you're still having more questions regarding this, please feel free to re-opne or comment on this thread.
