### ISSUE TITLE
Restricting resources created by `amplify auth`

### ISSUE THREAD

**Issue by jhw** [aws-amplify/amplify-cli#1423]
Hi,

Is it possible to pass args to `amplify auth` to limit what it creates to the bare minimum, ie maybe Cognito UserPool and associated roles ? I notice a ton of Cloudformation stuff being created - user/identify pools, roles, email stuff, sms stuff .. I'd like to strip it down to the bare minimum (ideally username/password only, created directly on the console backend) so I can better understand what is going on. Is this possible ?

Thx

**Comment by kaustavghosh06** [comment]
@jhw All the stuff got created because you chose "Default configurations" which encrourages best practices for authentication. If you instead choose "Manual Configuration" during the auth setup, you could've selected bare minimum resources that you needed. Please re-opne this issue if you have more questions.
