### ISSUE TITLE
How to connect existing Pinpoint project in the new iOS project

### ISSUE THREAD

**Issue by dakeshi** [aws-amplify/amplify-cli#1446]
** What AWS Services are you utilizing? **
Pinpoint

** Issue Description **
I'd like to connect the existing Pinpoint project with the new iOS project(I don't have the existing project source including configured aws resources). But I can not find out the exact instruction about it. And it seems that it doesn't have some options to use the existing Pinpoint resource in amplify cli commands list.

(Question 1) Is it possible to use the existing Pinpoint project with the new iOS project? 

(Question 2) If it is not supported on amplify cli, what kinds of files should I modify manually?

in the [document](https://aws-amplify.github.io/docs/ios/push-notifications#manual-configuration), it just mentioned about manual configuration with awsconfiguration.json. So, can I use the existing Pinpoint resources if I change values in awsconfiguration.json only?

or 

should I update team-provider-info.json and backend-config.json too?

**Comment by kaustavghosh06** [comment]
Answer 1: Amplify CLI uses Cloudformation to deploy and manage resources and since Cloudformation doesn't support managing of existing resources, hence the CLI doesn't support it either, but if you just want to use it in your app (and not manage it via the CLI), look at Answer 2:

Answer 2: You can modify the awsconfiguration.json file and add your pinpoint configurations to it. On an `amplify push`, the CLI won't overwrite this configuration and you could consume these values from your client SDK's.

**Comment by dakeshi** [comment]
Thank you for your response. So, what is the best practice to use the existing resources?

e.g)
(1) amplify init
(2) amplify push(to create awsconfiguration.json)
(3) amplify add notifications(to update awsconfiguration.json about notification service)
(4) manually update awsconfiguration.json with existing resources
(5) delete unused cloud resources(I'm not sure this phrase is needed)

**Comment by kaustavghosh06** [comment]
@dakeshi Yes, that's correct.
