### ISSUE TITLE
Why so many S3 requests?

### ISSUE THREAD

**Issue by yareyaredesuyo** [aws-amplify/amplify-cli#1453]
** Which Category is your question related to? **
Amplify push

** What AWS Services are you utilizing? **
Amplify 

** Provide additional details e.g. code snippets **

I'm now researching amplify and have some question.

1. What i found that everytime when using `amplify push ` takes so long time and looks like  checking everything and updating everything. Is there any way to reduce updating time? 

2. Is there no option to simulate offline ? like serverless offline.  Current development environment looks not effective. Change one line and checking and updating evetyghing (it takes some minutes). 

3. Why there is so many S3 push requests when updating? 

4. When developing using amplify, it requires some knowledge about AWS (dynamodb, appsync, cloudformation, cognito). But current docs lacks in these information, so how about adding additional tutorial or links pages to documents ?

**Comment by vparpoil** [comment]
For your first point, Leave a +1 here: https://github.com/aws-amplify/amplify-cli/issues/836

**Comment by kaustavghosh06** [comment]
@yareyaredesuyo Please find the answers inline to your questions out here:

1. What i found that everytime when using amplify push takes so long time and looks like checking everything and updating everything. Is there any way to reduce updating time?

Answer: We use Cloudformation nested stacks behind the scenes for all of our deployments. It is just one Cloudformation stack with all the resources as it's children (bundled as nested stacks) which we deploy everytime you do a push. The Cloudformation templates for a resource is updated (to S3), only when there is an "Update" operation on it (which you can observe before every push) and only then an  "UPDATE" operation is triggered on the Cloudformation side, otherwise there is no real "UPDATES" happening on your resource, although Cloudformation might be displaying an "UPDATE_COMPLETE" operation in your logs for a resource which you haven't updated, just because that resource is a nested stack and part of the parent stack which is getting deployed.
We're working on individual category push commands as mentioned by @vparpoil and as mentioned in #836 to enable per category push functionality, but this won't directly affect the "UPDATE" times for a resource directly since it has a direct dependency on Cloudformation.

2. Is there no option to simulate offline ? like serverless offline. Current development environment looks not effective. Change one line and checking and updating evetyghing (it takes some minutes).

Answer: We're actively working on it and you can find an RFC for what we're working on, out here #1433 

3. Why there is so many S3 push requests when updating?

Answer: Everytime there is an update to your resource, we update the corresponding cloudformation files, appsync resolvers and schema and put it into your S3 deployment buckets which is in turn used by Cloudformation for it's deployments.  We also maintain some metadata files stored in the S3, which we push/pull from when the user is switching environments in the CLI.

4. When developing using amplify, it requires some knowledge about AWS (dynamodb, appsync, cloudformation, cognito). But current docs lacks in these information, so how about adding additional tutorial or links pages to documents ?

Answer: I would love to know more details about this. We're constantly working towards making our docs better and making it customer friendly. Could you give some examples/details, so that we can understand your use-case better?

**Comment by kaustavghosh06** [comment]
Please feel free to comment or re-open this issue if you have more questions regarding your questions! Thanks.
