### ISSUE TITLE
@function directive not working with Mutation types

### ISSUE THREAD

**Issue by kevinwolfcr** [aws-amplify/amplify-cli#1519]
**Describe the bug**
The `@function` directive is not working with `Mutation` types.

**To Reproduce**
1. Run `amplify init api` and select `graphql`
2. Edit `schema.graphql` (code below)
3. Run `amplify push -y`

**schema.graphql**
```graphql
type Mutation {
  postLogin(user: String): String @function(name: "postlogin-${env}")
}
```

**Error**
```
Resource Name: io2olktiijgjnozbjvcj5eyrxuGraphQLSchema (AWS::AppSync::GraphQLSchema)
Event Type: update
Reason: Schema Creation Status is FAILED with details: Failed to parse schema document - ensure it's a valid SDL-formatted document.
```

**Expected behavior**
To work the same as with `Query` types.

```graphql
type Query {
  postLogin(user: String): String @function(name: "postlogin-${env}")
}
```

**Comment by kaustavghosh06** [comment]
@kevinwolfcr What's the version of the CLI that you're using?

**Comment by mikeparisstuff** [comment]
Can you please copy and paste your `schema.graphql`? I was just able to deploy this simple schema: 

```graphql
type Mutation {
    echo(msg: String): String @function(name: "echofunc-${env}")
}
```

I suspect this may be an edge case.

**Comment by mikeparisstuff** [comment]
@kevinwolfcr Looking at this again. The reason for the failure is that you need to include a Query definition because the query operation is required in GraphQL servers (see https://github.com/graphql/graphql-spec/blob/master/spec/Section%203%20--%20Type%20System.md#root-operation-types). If you do not have a need for queries you can add a noop field to satisfy the GraphQL validator.

```graphql
type Mutation {
  postLogin(user: String): String @function(name: "postlogin-${env}")
}
type Query {
  noop: Int
}
```
