### ISSUE TITLE
Use parent get query or @key directive?

### ISSUE THREAD

**Issue by aireater** [aws-amplify/amplify-cli#1632]
** Which Category is your question related to? **
GraphQL transform

** What AWS Services are you utilizing? **
AppSync, DynamoDB

** Provide additional details e.g. code snippets **
I have an Account object and Document object defined with a 1-to-many named connection with createdAt sortField.

```
type Account @model
{
  id: ID!
  # ...
  documents: [Document!]
    @connection(name: "AccountDocuments", sortField: "createdAt")
  # ...
}
```

and 

```
type Document @model
{
  id: ID!
  account: Account!
    @connection(name: "AccountDocuments", sortField: "createdAt")
  createdAt: AWSDateTime
  # ...
}
```

In my UI, Documents is a separate tab so I'm running the getAccount query with the account details needed for the main tab on load. 

```
query GetAccount($id: ID!) {
  getAccount(id: $id) {
    id
    # ... other fields needed
  }
}
```
When the Documents tab is selected I run the getAccount again but with only the documents. 

```
query GetAccount($id: ID!) {
  getAccount(id: $id) {
    documents {
      items {
        id
        # ... fields needed
      }
    }
  }
}
```

I went with this approach because I don't think I need another `@key` if AppSync already has the access pattern to the data. Are there any implications like cost or performance to using the parent object to query for the children?

For this use case above, is it better to define a `@key` or just use what's already created from the `@connection`?

**Comment by mikeparisstuff** [comment]
@aireater There is nothing wrong with using the parent/child relationship created by `@connection` as long as you do not try to change the structure of the `@connection`. We found that in practice users had trouble with `@connection` because it manages the GSI under the hood and then when you tried to change the structure of the `@connection` throws an errors because it is unable to move from state A -> state B even though the table definition is entirely valid, has it been created from scratch. The `@key` directive 

I discuss how to move from a `@connection` to a `@key` in #1656 and perhaps that helps provide more context.
