### ISSUE TITLE
Function category update bug

### ISSUE THREAD

**Issue by UnleashedMind** [aws-amplify/amplify-cli#1747]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Describe the bug**
When trying to update the lambda function, the CLI errors out.

**To Reproduce**
1. `amplify init`
2. `amplify add function`
3. `amplify push`
4. make some modifications on the function resource, for example, update the xxx-cloudformation-template.json file's setting and change the nodejs version from nodejs8.10 to nodejs10.x
5. `amplify push`

I got the following error: 

ENOENT: no such file or directory, lstat '/Users/\<username\>/workspace/\<project-name\>/amplify/backend/function/lambdaversion33320d73/dist/lambdaversion33320d73-726d2f32382f71397377-build.zip'

**Expected behavior**
`amplify push` should be successful

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Sierra version 10.12.6
- Amplify CLI version: 1.7.6

**Comment by NelsonG-C** [comment]
I also am battling with a potentially the same problem. The error i receive is:
`ENOENT: no such file or directory, lstat 'C:\Users\nelso\Coding\logisticusMaximusV3\stock-system-v3\amplify\backend\function\logisticusmaximusd5431cce\dist\latest-build.zip'`

I have made some changes to the functions I use, and also the graphQL schema. I was previously receiving an error that may have been caused by using an old version of amplify-cli 1.1.7. I updated to 1.7.8.

 Unsure if this old issue has been fixed since once I upgraded the cli, the error above came along.
In the file path above, there is a file, but it is named `logisticusmaximusd5431cce-1562027910-latest-build.zip`, as it has always been previously.

I'm fairly new to this, so unsure what steps I should work through to debug, or if there is something I'm required to do after an amplify-cli update that I'm missing. Any suggestions would be great!

**Comment by kaustavghosh06** [comment]
We’ve fixed this issue in v1.7.8. Please install the latest version and let us know if you’re still seeing this.

**Comment by NelsonG-C** [comment]
Unfortunately I'm on v1.7.8 and still receiving the error. Is it just that the filename doesn't match? No clue why it would be different though. 

![image](https://user-images.githubusercontent.com/41055112/60632908-8275ba00-9e4b-11e9-9abd-487da83da9c3.png)

Error received:
ENOENT: no such file or directory, lstat 'C:\Users\nelso\Coding\logisticusMaximusV3\stock-system-v3\amplify\backend\function\logisticusmaximusd5431cce\dist\latest-build.zip'

**Comment by jarrettj** [comment]
Yup, same here. I am having to rename the zip to latest-build.zip to proceed with every amplify push after updating to 1.7.8. At least it has a workaround :).

**Comment by kanerogers** [comment]
I was able to resolve this by going through `amplify-meta.json` and setting `distZipFilename` to `latest-build.zip`. See if it works for you!
