### ISSUE TITLE
Missing semicolon when generating lambda permissions

### ISSUE THREAD

**Issue by diegoromoli-ip** [aws-amplify/amplify-cli#1776]
When running `amplify update function` to add permissions to a function to execute another function, the generated CloudFormation template section is missing a semicolon:

```
{
    "Effect": "Allow",
    "Action": [
        "lambda:Create*",
        "lambda:Put*",
        "lambda:Add*",
        "lambda:Get*",
        "lambda:List*",
        "lambda:Invoke*",
        "lambda:Update*",
        "lambda:Delete*",
        "lambda:Remove*"
    ],
    "Resource": [
        {
            "Fn::Join": [
                "",
                [
                    "arn:aws:lambda:",
                    {
                        "Ref": "AWS::Region"
                    },
                    ":",
                    {
                        "Ref": "AWS::AccountId"
                    },
                    ":function",
                    {
                        "Ref": "functionGoalFunctionName"
                    }
                ]
            ]
        }
    ]
}
```

The line ":function" should actually be ":function:"

**Comment by WhiteAbeLincoln** [comment]
The offending line of code seems to be https://github.com/aws-amplify/amplify-cli/blob/3bda2852ef0433e80f8e415d8ca34a340d25588b/packages/amplify-category-function/provider-utils/awscloudformation/service-walkthroughs/lambda-walkthrough.js#L632

See also #1595, which had the same issue with invalid arn generation. Perhaps `Fn::Sub` should be used instead of `Fn::Join` since it provides a more complete view of the whole arn string, which means simple typos are more easily caught

```json
"Resource": {
    "Fn::Sub": [
       "arn:aws:cognito-idp:${region}:${account}:userpool/${userpool}",
	{
	   "region": {
		"Ref": "AWS::Region"
	   },
	   "account": {
		"Ref": "AWS::AccountId"
	   },
           "userpool": {
	      "Ref": "UserPoolIDRef"
	   }
	}
    ]
}
```

Or better yet, write some tests for the template generation. A shared utility function for generating this template code would also be super useful, since it would reduce the likelihood of typos like this. Something like `generateResourceArn(service: string, resourceType: string, resourceId: string): StringJsonFn` (StringJsonFn is just a type representing a json function like "Fn::Sub" or "Fn::Join" which returns a string).

The policy generation line for this issue would then be 
```javascript
policy = {
    Effect: 'Allow',
    Action: actions,
    Resource: [
      generateResourceArn('lambda', 'function', `${categoryName}${resourceName}Name`),
    ],
  }
```

and the policy generation for the cognito issue would be

```javascript
policy = {
    Effect: 'Allow',
    Action: actions,
    Resource: [
      generateResourceArn('cognito-idp', 'userpool', `${category}${resourceName}UserPoolId`),
    ],
  }
```

Obviously this is harder than just saying "make a function". The function needs to be a little smart: the lambda arn separates the resourceType and the resourceId with a colon, while the cognito-idp arn uses a slash. Ideally the function would have some internal logic (and tests for that logic) which would determine which format to use based on the parameters.

We could go even further and generate the entire policy through a function `makePolicy(effect: 'Allow' | 'Deny' | ..., actions: string[], resources: Array<string | StringJsonFn>)`. In an untyped codebase shared functions like this really help reduce the chances of bugs due to typos.

**Comment by SwaySway** [comment]
Closing this issue as the fix has been merged.

@WhiteAbeLincoln Thanks for the suggestions. I'll review these with the team.
Should you have a specific implementation in mind, PRs are welcome.
