### ISSUE TITLE
@aws_api_key removed after using "amplify push"

### ISSUE THREAD

**Issue by anarerdene** [aws-amplify/amplify-cli#1804]
First thank your for multiple Auth access. I adding auth permission on cloud Schema then i changed some query on schema.graphql then pushed using amplify CLI. After that cloud Schema removed @aws_api_key (auth permission). I have no idea.

Im using amplify CLI - 1.7.8

**Comment by janhesters** [comment]
@anarerdene The Amplify CLI doesn't yet support this feature [(though they are working on it).](https://github.com/aws-amplify/amplify-cli/pull/1524)

Until they are finished any change that you make for AppSync in the cloud console will be overwritten once you push a new schema using the CLI.

**Comment by attilah** [comment]
@anarerdene As @janhesters responded, this is not yet supported and the CLI is removing the unknown directives upon transform, that's why you see this behavior. With the multi-auth support, you'll get pass-through directive support for the new directives, so your use case will be unblocked.

I'm closing the issue as the requested feature is already being worked on. If something new comes up, please feel free to re-open it.
