### ISSUE TITLE
Feature Request: Manage multiple bucket by amplify storage

### ISSUE THREAD

**Issue by bokuweb** [aws-amplify/amplify-cli#1923]
>**Note**: If your feature-request is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Is your feature request related to a problem? Please describe.**

### related https://github.com/aws-amplify/amplify-cli/issues/1549

I would like to manage multiple S3 bucket by `amplify storage` command.
However It is not able now.

**Describe the solution you'd like**

Please support multiple bucket by `amplify storage add`

**Describe alternatives you've considered**

**Additional context**

**Comment by kaustavghosh06** [comment]
@bokuweb As a best practice, the Amplify Framwork allows you to have multiple prefixes in the bucket as a best practice instead of having multiple buckets.
You could partition your bucket by prefixes like the following:
`mybucket/partition1` and `mybucket/partition2` which can potentially have different auth policies and lambda triggers.

Knowing your use-case better would let me help you better

**Comment by askpatrickw** [comment]
> As a best practice, the Amplify Framwork allows you to have multiple prefixes in the bucket as a best practice instead of having multiple buckets.
> You could partition your bucket by prefixes like the following:
> `mybucket/partition1` and `mybucket/partition2` which can potentially have different auth policies and lambda triggers.

Hi @kaustavghosh06 I assume you closed this because the original poster didn't reply. I think you should re-open this request.

At a minimum, If this is a best practice please add it to the documentation. https://aws-amplify.github.io/docs/js/storage

## Question
You mention that permissions can be managed at the partition level. Can you explain how that is done with Amplify? I believe you can only grant READ, CREATE\UPDATE, DELETE to the entire bucket with Amplify.

**Comment by zhalloran** [comment]
@askpatrickw A decent, if somewhat incomplete, explanation of how the amplify prefix based access model works can be found here: https://docs.amplify.aws/lib/storage/configureaccess/q/platform/js. Hope that helps.

**Comment by askpatrickw** [comment]
I'm not actively using Amplify right now, but I hope your comment helps the next person. Cheers!
