### ISSUE TITLE
Best practices for Multi-Tenant Apps?

### ISSUE THREAD

**Issue by stevelizcano** [aws-amplify/amplify-cli#2035]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

** Which Category is your question related to? **
Amplify CLI and Amplify-js

** What AWS Services are you utilizing? **
AppSync, Cognito, and Lambda

** Provide additional details e.g. code snippets **

Let's say we follow the common model shown in the docs, with @auth rules:

```
type Blog @model  {
  id: ID!
  name: String!
  posts: [Post] @connection(name: "BlogPosts")
}
type Post @auth(rules: [ { allow: owner, ownerField: "editors", operations: [update] }]) @model {
  id: ID!
  title: String!
  blog: Blog @connection(name: "BlogPosts")
  comments: [Comment] @connection(name: "PostComments")
}
type Comment @model {
  id: ID!
  content: String
  post: Post @connection(name: "PostComments")
}
```

What if we want to take this a step higher, and want to have separate organizations here? I.e. Customer A has their own Blog, posts, and editors. Company B is a customer, with their own editors, but can't see or access company A's Blog,  etc. How can we use Amplify here (including Auth) to login users, and have data be separated by Organization? (i.e. Company A's team doesn't share access rights with Company B's team)

Thanks!

**Comment by attilah** [comment]
@stevelizcano Multi-tenancy support is a hard topic and very specific to the customers' requirements, so it is hard to add generic support to it in the CLI. From Cognito perspective, the CLI only supports having a single Cognito User Pool configured, so that is a blocking fact for your scenario.

Cognito: You can use a single Cognito User Pool and still guarantee that now cross tenant access can be done, but putting the TenantId into custom attributes for the Users during registration/creation. Also by leveraging Pre Token* handlers you can add the TenantId to the claims in the generated Tokens, and since claims are available in the resolvers you can add that to your DynamoDB operations as additional filter. More info on the handlers can be found [here](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html).
  
GraphQL: Using composite keys with TenantId + Id with ```@key```, and custom resolvers can help with the filtering of data based on the aforementioned claims from the ```$identity```.

I hope this helps, I'm closing the issue, but feel free to reopen if something comes up. On general usage of AppSync service itself - since CLI does not support your scenario - the Amplify forums are a better place to ask the community.
