### ISSUE TITLE
Circular dependency between resources: [functionauthPreSignup, apiapi, authauth, UpdateRolesWithIDPFunctionOutputs, UpdateRolesWithIDPFunction]

### ISSUE THREAD

**Issue by oste** [aws-amplify/amplify-cli#2076]
**Describe the bug**

Seeing the following error after updating Auth PreSignup Trigger function to have API access permission:

```
⠼ Updating resources in the cloud. This may take a few minutes...Error updating cloudformation stack
✖ An error occurred when pushing the resources to the cloud

Circular dependency between resources: [functionauthPreSignup, apiapi, authauth, UpdateRolesWithIDPFunctionOutputs, UpdateRolesWithIDPFunction]
```

**To Reproduce**
1. amplify init
2. amplify add auth - add a preSignup trigger function
3. amplify add api
4. amplify api add-graphql-datasource - add RDS resource to the API
5. amplify push

This is where it goes bad
6. amplify function update
7. Give the preSignup trigger function(functionauthPreSignup) create permission on the api created in step 3
8. amplify push - **This results in the error described above**

**Expected behavior**
Push works as expected

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: n/a
 - Version: 1.12.0

**Comment by kaustavghosh06** [comment]
@oste Yes, this is because of a circular dependency between the pre-signup-trigger (auth is depndent on this to complete first ) and then this trigger now would depend on API to complete first  (Which is dependent on auth to complete first), causing a deadlock and a circular dependency:
You can unblock yourself by using a custom resource in Cloudformation to unblock and we're already tracking this as a part of this issue - #1874

**Comment by thedgbrt** [comment]
@kaustavghosh06 would you have any example of how to write that custom resource in CLoudFormation? And where to add it?

**Comment by patspam** [comment]
@kaustavghosh06 can you provide an example of the workaround? The issue you linked to is unresolved and does not show how to solve this - these sorts of issues are incredibly frustrating because they stop you dead in your tracks.

**Comment by increment-upskilling** [comment]
Another workaround: switch to using IAM authentication only for the API if you can, that'll break the cycle

**Comment by cybercussion** [comment]
I just had this circular issue happen to me and I allowed a lambda trigger to access dynamo and somehow now it can't do anything in S3.  I can't seem to put it back so the whole thing is defunct.  I'm trying to edit out the new function-parameters.json that showed up or the CloudFormation.  I've even gone thru the CLI to try to undo things but it either lets me edit the DynamoDB resource access or fails to edit the S3 bucket access.  I manually am removing the Amplify Resource Policy now but this is super confusing.

**Comment by danielesalvatore** [comment]
Just had the same kind of issue using Amplify  `v4.41.1`.

Trying to implement a pre-token trigger that it is supposed to read from a DynamoDB table.

The trigger is created using `amplify auth update`.
Lambda permissions are granted using `amplify update function`
The steps to reproduce the issue are equals to the original issue description.

**Comment by danielesalvatore** [comment]
Hi @cybercussion, did you manage to grant DynamoDB access to your Cognito lambda trigger? Thanks!

**Comment by cybercussion** [comment]
> Hi @cybercussion, did you manage to grant DynamoDB access to your Cognito lambda trigger? Thanks!

Hi, I did.  But I switched it up for GraphQL so I could get the event stream back to Angular.

**Comment by vineethbhargavan** [comment]
Had a similar problem.
- Lambda trigger - PostAuthentication had to talk to an Appsyc model /Dynamo DB table.
- Because the appsyc depends on the Auth stack and one of the resource(in this case lambda trigger) wants to talk to Appsycn , the circular dependency was identified and prevented from a successful execution of amplify push.
- the error was also not going , irrespective of manually removing the api dependency on the lambda trigger Cloudformation.

So here is what i did:
- did a amplify pull <env> . This restored the amplify to the last know state. This will override the local changes - so ensure you take a back or git commit your changes!
- taking a cue from the custom resource implementation for circular dependency , i then tried to create one..my choice was a SQS queue ...since i already had one..it was easy to prototype! This worked.
- so the workflow is : lambda trigger from cognito -> sqs -> lambda -> DB.

**Comment by danielesalvatore** [comment]
Hello @vineethbhargavan, thank you for sharing your solution! Which Cognito trigger are you using? From what I understand you solve the issue using an async flow, in which the Cognito trigger response is resolved before your DynamoDB table is queried (the trigger is resolved - response returns to Cognito - once SQS accepts the request). If this is confirmed I fear this cannot be applied to the PreToken generation trigger as the resultset of the DynamoDB table has to be included in the Cognito response. Did I get it right?

**Comment by vineethbhargavan** [comment]
Yep! The solution will not work for Pre-token trigger. I used for Pre-
Authentication trigger with the combination of custom cognito attributes.
Since I didn’t require real-time response(hence async) it worked for me!!
Maybe a custom resource in amplify to build a lambda function which takes
in Param inputs of Db(api/storage) and auth and construct the pre- token
trigger? Not sure if this will work in your case.I wish there was a more
elegant solution . Will be interested to know if you can come up with a
solution - that is scalable across different amplify environment.

**Comment by StackTrac3** [comment]
Thank you @vineethbhargavan. Your comment led me to [this medium article](https://medium.com/@navvabian/how-to-add-an-sqs-queue-to-your-amplify-cli-bootstrapped-project-cb7781c636ed) on using SQS in this fashion. It works **great**.

 I, like many of you, have been on several of these issue threads looking into how to use the app API for user creation in the generated lambda triggers. This method with SQS has several good side effects, and allows you to still manage **all** of the involved functions with Amplify, as well as deploy the SQS resource with amplify. 
 
 A little guidance for future hubbers: Follow the medium guide closely. Check out the libraries `sqs-consumer` and `sqs-producer` for working with SQS in node. I use the SQS lambda trigger to `invoke` other functions depending on one of the sqs `messageAttributes`.

It's a shame that in such a common place for business logic, it is so difficult. I believe that the docs could use quite a bit more guidance regarding customizing the lambda triggers for cognito. However - there are fixes in code review **right now** on how how the templates are generated regarding these dependencies.
