### ISSUE TITLE
Use of @key directive on schema.graphql

### ISSUE THREAD

**Issue by rodhoff** [aws-amplify/amplify-cli#2105]
** Which Category is your question related to? **
aws-amplify, appsync and graphql

** What AWS Services are you utilizing? **
developing in Cloud9

** Provide additional details e.g. code snippets **

My schema is created successfully. I have created the following type:
```
type Formula @model 
			 @key(name:"ByName", fields: ["name"]) 
{
	id: ID!
	name: String!
	description: String
...
```
Then I have ran codegen.
I see the index created according to my direction on @key like above - I see it on the DynamoDB table, exactly like I described.

But it doesn't seem to have added to the resolver automatically the possibility of using this index. So right now I don't know exactly how to "sort" my content by name, instead of relyng on the order by ID, which is not friendly at all.

I'm using the Connect component.

Could you please clarify how is this usage? I didn't find docs covering this...

Thanks!

**Comment by attilah** [comment]
@rodhoff It is by design, the documentation says: "The first field in the list will always be the HASH key.".

Please take a look at the [docs](https://aws-amplify.github.io/docs/cli-toolchain/graphql#key) for more details. For general usage questions like this Amplify forums are a better place to ask, but if you find an issue don't hesitate to open it here.
