### ISSUE TITLE
validation issues when build app via amplify-cli

### ISSUE THREAD

**Issue by Hpark11** [aws-amplify/amplify-cli#216]
**Describe the bug**
auto generated graphql queries and mutations by ampify-cli have validation issues

**To Reproduce**
1. Make schema in AWS Appsync and then codegen via amplify cli (in Android)
   (especially list type parameter in queries and mutations)
2. amplify codegen
3. build android app (aws-appsync-sdk installed)

**Expected behavior**
Should be [Type] not just Type

**Screenshots**
<img width="522" alt="2018-09-26 11 20 51" src="https://user-images.githubusercontent.com/8099899/46053541-47d54780-c17e-11e8-8bc1-7fa5d2730f57.png">
<img width="555" alt="2018-09-26 11 13 22" src="https://user-images.githubusercontent.com/8099899/46053505-19576c80-c17e-11e8-8609-c108ba9ea552.png">

**Additional context**
Now I have to edit manually every time i make changes in graphql schema in AppSync

**Comment by yuth** [comment]
Could you share a sample schema and the generated queries/mutation and subscription

**Comment by yuth** [comment]
I have fixed the issue in #336. This fix is pending release and should be included in `0.1.30`

**Comment by natebushman** [comment]
@yuth

Thanks for your help on this issue.

I tested your latest code and there are still problems, but I will provide the solution below.  When dealing with array/list parameters in GraphQL, there are actually **four** permutations that must be dealt with.  They are:

1. Nullable List Type:  [<type>]    e.g.   [String]
2. Nullable List of Non-null Types:  [<type>!]     e.g .  [String!]
3. Non-null List Type: [<type>]!     e.g.   [String]!
4. Non-null List of Non-null Types:  [<type>!]!    e.g   [String!]!

In order for all four of the above permutations to be treated properly by the GraphQL generator code in amplify CLI, the following three changes must be made to the code.  I have tested this code below (it works) for all of these permutations:

1)
File: packages/amplify-graphql-docs-generator/src/generator/types.ts
Change:  The GQLTemplateArgDeclaration type must be changed so it looks like this (the isList and isListRequired fields must be added):

```
export type GQLTemplateArgDeclaration = {
  name: string
  type: string
  isRequired: boolean
  isList: boolean
  isListRequired: boolean
  defaultValue: string | null
}
```

2)
File:  packages/amplify-graphql-docs-generator/src/generator/utils/isRequired.ts
Change:  The function isRequired() must be altered so that it handles Nullable Lists of Non-null Types.  It should look like this:

```
import { GraphQLType, isNonNullType, isListType } from "graphql";
export default function isRequired(typeObj: GraphQLType): boolean {
  // See if it's a Non-null List of Non-null Types
  if (isNonNullType(typeObj) && isListType(typeObj.ofType)) {
    return isRequired(typeObj.ofType.ofType)
  }
  // See if it's a Nullable List of Non-null Types
  else if (isListType(typeObj)) {
    return isNonNullType(typeObj.ofType);
  }
  return isNonNullType(typeObj);
}
```

3) 
File: packages/amplify-graphql-docs-generator/templates/_renderArgDeclaration.hbs
Change:  This template has a typo.  The text "isRequiredList" must be changed to be "isListRequired".  It should look like this:

`{{#if args.length}}
  (
    {{#each args as |arg index|}}
      ${{ arg.name }}:{{#if isList}}[{{/if}}{{arg.type}}{{#if arg.isRequired}}!{{/if}}{{#if isList}}]{{#if isListRequired}}!{{/if}}{{/if}}{{#if arg.defaultValue}}={{arg.defaultValue}}{{/if}}{{#unless @last}},{{/unless}}
    {{/each}}
  )
{{/if}}`


I would have embodied these in a pull request but I'm having some git issues at the moment.  It's a small enough change I figured I'd just post the details here so that you can inject them manually.  Sorry about the inconvenience.

**Comment by kaustavghosh06** [comment]
@OtterFlip The PR seems to have been merged and available in the latest NPM release. Please feel free to re-open this issue if the problem still persists.
