### ISSUE TITLE
Cognito pre-token claim attributes are missing from Graphql resolver

### ISSUE THREAD

**Issue by dahersoftware** [aws-amplify/amplify-cli#2192]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I am using pre-token generation trigger in Cognito that set tenantContext value to identify user tenant relationship.
After login to cognito via Auth.signIn, I am trying to execute API.graphql(graphqlOperation(...))
everything works fine except I do not see my tenantContext attribute inside resolver function.

$ctx.identity.claims.get("tenantContext") --> This value always comes null. 
I checked my Cognito pre-token trigger response and it correctly sets the value inside signInUserSession.idToken.payload but this value is absent inside graphql resolver.

I tried to see what values graphql resolver gets and it gets all the values for accessToken (inside $ctx.identity.claims.get) but not for identity token , pre-token-trigger sets the context values inside identity token.

**How do I access my value set by pre-token-trigger inside resolver correctly? Do I need to change the way API.graphql works or is there something I am missing inside resolver.**

**Note**: My graphql schema use @auth directive and rules are pre-populated inside resolver so I haven't changed anything.

My amplify cli version is : 1.12.0

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mrducky4** [comment]
I have the same question. In my case the graphql request from the browser puts the access token in the HTTP Authorization header. I assume this is what eventually gets to a resolver to handle authorization. I am new to all this, following the [getting started tutorial](https://aws-amplify.github.io/docs/js/start?ref=amplify-js-btn&platform=purejs).  I changed the tutorial a bit to use AMAZON_COGNITO_USER_POOLS instead of the api key.
Simplified client javascript:
`import API, { graphqlOperation } from '@aws-amplify/api'`
`import Amplify, { Auth } from 'aws-amplify'`
`import awsconfig from './aws-exports';`
`API.configure(awsconfig);`
`await Auth.signIn('username', 'password');`
`API.graphql({
      query: createTodo,
      variables: { input: todo },
      authMode: 'AMAZON_COGNITO_USER_POOLS'
  })`

Is there perhaps a different way to set up authentication/authorization at the client side so it uses the ID token instead of the Access token?

**Comment by yuth** [comment]
Pre-token generation trigger in Cognito updates `idToken` of the user and Amplify API uses `accessToken` when making a request to AppSync. This is what is  causing your `$ctx.identity.claims.get` method to return null for `tenantContext`. You could update your code to set custom authorization header as mentioned in the [docs](https://aws-amplify.github.io/docs/js/api#set-custom-request-headers-for-graphql) and send idToken and you should be able to get the `tenantContext`

```javascript
Amplify.configure({
  API: {
    graphql_headers: async () => {
    const session = await await Amplify.Auth.getCurrentUser()
    return ({
        'Authorization': session.getIdToken().getJwtToken()
    })}
  }
});

```

**Comment by mrducky4** [comment]
Thanks, that worked for me. I added that to my app.js. But I had to change one line to:
```javascript
const session = await Amplify.Auth.currentSession()
```

**Comment by yuth** [comment]
Please feel free to comment if this does not answer your question.

**Comment by dahersoftware** [comment]
Thanks @yuth for providing a solution to this. Sorry for the late response.
