### ISSUE TITLE
@connection does not respect required type fields

### ISSUE THREAD

**Issue by blbradley** [aws-amplify/amplify-cli#221]
**Describe the bug**
If you create a required, @connected field, you can do a create mutation without the field.

**To Reproduce**
1. Create a project with this schema:
```
type Project
  @model
  @auth(rules: [
      {allow: owner}
    ])
{
  id: ID!
  title: String!
  codefile: ProjectCodeFile! @connection
}

type ProjectCodeFile
  @model
{
  id: ID!
  location: AWSURL!
}
```

2. Run this mutation in your AppSync Queries console:
```
mutation myMutation {
  createProject(input: {title:"P1"}) {
    id
    title
  }
}
```
3. A project is created

**Expected behavior**
The schema and mutation above should throw an error. Probably a validation exception.

**Additional context**
Not yet but will look for a solution.

**Comment by mikeparisstuff** [comment]
You are correct. I believe the issue is here: https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts#L158. The definition for `updateCreateInputWithConnectionField` already expects a nonNull argument but is not being passed it https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-connection-transformer/src/definitions.ts#L7. It looks like we will need to update these two lines https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-connection-transformer/src/definitions.ts#L19 & https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-connection-transformer/src/ModelConnectionTransformer.ts#L164

**Comment by blbradley** [comment]
Hey Michael! Thank you for the analysis.
