### ISSUE TITLE
What is the correct way to handle server-side data verification in AppSync?

### ISSUE THREAD

**Issue by ilyador** [aws-amplify/amplify-cli#2297]
Let's say I have an app that for some user action they increment a score by 1 point. I must make sure that the user cannot increment the value in the DB by more than 1 at a time.

Using a REST server I'd simply do that in the handling function, however I have no idea where in the AppSync pipeline is the correct place to handle such logic.

**Comment by amirmishani** [comment]
@ilyador so basically you need Appsync to call a lambda function instead of directly going to the database. Inside your lambda function you can handle custom data and custom logic.

[Check out the docs for examples of handling custom data and custom logic.](https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js#function)

**Comment by chrisco255** [comment]
There's no need to use a lambda for this simple use case. You can simply edit your request mapping template in VTL to increment the value. See: https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-dynamodb-resolvers.html for more info.

**Comment by attilah** [comment]
Thanks for answering @amirmishani @chrisco255! @ilyador these are your choices, pick what would be the best fit your environment/project.
