### ISSUE TITLE
How to migrate from aws mobile cli to amplify cli?

### ISSUE THREAD

**Issue by ianpogi5** [aws-amplify/amplify-cli#241]
According to https://aws.amazon.com/blogs/mobile/announcing-the-aws-amplify-cli-toolchain/

"If you’re using the AWS Mobile CLI for existing projects, you can also continue to use that older CLI. However, going forward, new features will be added to the AWS Amplify CLI toolchain which does not use Mobile Hub."

We've invested a lot of time working on our project using aws-mobile. We used it because we were expecting for aws-mobile to be continue receiving updates as it was still lacking many features. But now it becomes obsolete and we don't know how long it will keep on working. I'm frustrated by this and feel that we've wasted a lot of time. I'm sure we're not the only one. At least give us instructions on how migrate to this new cli.

**Comment by sambomcd** [comment]
Agree completely with @ianpogi5 - we have a project that we set up under AWS Mobile that was on pause for a while, now we are looking to move forward with it. Would appear to make no sense to carry on with AWS Mobile CLI, so have been trying to switch to AWS Amplify CLI. But there is not much information out there, not can I find options in the new CLI for things like pointing at an existing Cognito User Pool. Would be helpful to know how to migrate off of AWS Mobile CLI if this is the new direction.

**Comment by sambomcd** [comment]
Understood @mlabieniec thank you. Different architectures aside, I would make the observation that every single piece of documentation for AWS Mobile CLI I have come across, such as [here](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-cli-reference.html), [here](https://github.com/aws/awsmobile-cli) and [here](https://www.npmjs.com/package/awsmobile-cli) are all prefaced recommending that new projects use Amplify CLI. This seems to signal that the AWS Mobile CLI (and maybe Mobile Hub?) won't be around much longer. So it is easy to understand how people in the early stages of their projects might want to switch early.

**Comment by kaustavghosh06** [comment]
@sambomcd That is correct. Please feel free to re-open this issue if you think this is still an issue. Thanks!

**Comment by ngault** [comment]
The silence on this is deafening.

**Comment by fchau-arrdude** [comment]
I would like a way to easily transfer my work that I've done with awsmobile to amplify. I'm running into issues pushing changes to awsmobile and it seems like amplify will be the more supported framework so i'm eager to transfer over.

**Comment by gentleShark** [comment]
AWS releases half-baked SaaS, promises the world, and offers limited documentation. Do yourself a favor and don't lock yourself into their SaaS

**Comment by ohsik** [comment]
At least give us instructions on how migrate to this new cli. +1

**Comment by swaminator** [comment]
@ianpogi5 @sambomcd @sadooghi @ohsik  @gentleShark @fchau-arrdude @ngault We just released a Mobile Hub to Amplify CLI migrator that you can access here: https://github.com/awslabs/amplify-mobilehub-migrator. This will help you import your Mobile Hub resources into an Amplify project, give you an exports file, and allow you to leverage Amplify CLI features such as GraphQL APIs, Codegen, and the GraphQL Transform. Would love your feedback.

**Comment by sambomcd** [comment]
Thanks Nikhil - we ended up starting from scratch, rather than try and figure it out. I’m sure this will be of use to others, but we no longer have a migration path to try and provide feedback. Sorry.





On 6/03/2019, at 1:34 AM, Nikhil Swaminathan <notifications@github.com> wrote:

@ianpogi5 <https://github.com/ianpogi5> @sambomcd <https://github.com/sambomcd> @sadooghi <https://github.com/sadooghi> @ohsik <https://github.com/ohsik> @gentleShark <https://github.com/gentleShark> @fchau-arrdude <https://github.com/fchau-arrdude> @ngault <https://github.com/ngault> We just released a Mobile Hub to Amplify CLI migrator that you can access here: https://github.com/awslabs/amplify-mobilehub-migrator <https://github.com/awslabs/amplify-mobilehub-migrator>. This will help you import your Mobile Hub resources into an Amplify project, give you an exports file, and allow you to leverage Amplify CLI features such as GraphQL APIs, Codegen, and the GraphQL Transform. Would love your feedback.
