### ISSUE TITLE
Unable to install @aws-amplify/cli

### ISSUE THREAD

**Issue by ntanduc2288** [aws-amplify/amplify-cli#2431]
Following this tip https://aws-amplify.github.io/docs/?fromawsmobiledocs=true
My mac is running Node 12.10.0.
While trying to run this command: "npm install -g @aws-amplify/cli" I got the following error:

FEBS requires node 8 to run. (You're on v12.10.0)

Could you please help me out? Thanks in advance!

**Comment by mooser** [comment]
There is no way to run npm install -g @aws-amplify/cli and expect it to work on a modern mac.  Amplify-CLI is basically alpha release use at your own risk.  

But, this might work:
`sudo npm install -g @aws-amplify/cli --unsafe-perm=true`

**Comment by kaustavghosh06** [comment]
@ntanduc2288 Lately we've seen some installation issues for specific versions of node/npm and we're working on fixing these issues. In the mean while, could you try `npm install -g @aws-amplify/cli --unsafe-perm=true` and see if that helps?

**Comment by attilah** [comment]
@ntanduc2288 I've checked our yarn.lock file and none of our dependencies are referencing @rei/FEBS, I assume that is the package npm install complaining about. Do you've it installed on your machine?

I've checked their ```package.json``` file and they require node>=8.3.0 which node 12 satisfies, so that error message seems to be unusual.
