### ISSUE TITLE
Migrating an Amplify application to a new AWS account

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-cli#2432]
Is there an supported way of migrating an Amplify application to a new AWS account?

If not, what manual steps would we need to take? We don't need to migrate any DynamoDB data but would like to migrate or re-create all the objects (schema tables, lambda functions, s3 storage etc.)

Thanks.

**Comment by nikhname** [comment]
Hi @blairtaylor, you can do this by running amplify env add. Create a new environment and use the new AWS account, then run amplify push.

For more information feel free to checkout our multi-env docs: https://aws-amplify.github.io/docs/cli-toolchain/quickstart#environments--teams

**Comment by blairtaylor** [comment]
Thanks. Could you explain what you mean when you say "use the new AWS account"? Do you need to change settings in one of the files?

**Comment by nikhname** [comment]
When you run amplify env add and you create a new env, you will be prompted to choose which AWS profile you want to use. There you can choose the AWS account that you want to migrate to if it is configured. If you haven't configured the new account you want to use, just run amplify configure and follow the steps to set up that account.

**Comment by blairtaylor** [comment]
Ok. Thanks we will give this a try.

**Comment by nikhname** [comment]
Sure, feel free to comment/re-open if you have further questions.

**Comment by jkeys-ecg-nmsu** [comment]
@nikhname @blairtaylor this will not do a full migration if you're using the API category with Dynamo, because it will not trigger any data pipeline or stream solution or anything to copy records over to the new account. I ran into this recently and had to spend a few hours spinning up EMR clusters and fiddling with read and write capacities.

**Comment by kaustavghosh06** [comment]
@jkeys-ecg-nmsu, @blairtaylor mentioned in his description that he doesn't to copy over his data for his records/data and just wants to create a clone of his resource configurations in a new AWS account.

**Comment by blairtaylor** [comment]
@jkeys-ecg-nmsu @nikhname thanks for your comments.  You are correct, we are spinning up a new environment so we won't need any data migrated. It does pose a couple of good questions - 

1. What is the best way to migrate data across environments (using DynamoDB).
2. When we make schema changes going forward what types of changes would incur a data loss? For example, converting a String field to Array or AWSJSON?

**Comment by jkeys-ecg-nmsu** [comment]
@kaustavghosh06 sorry, I missed that.

@blairtaylor maybe @kaustavghosh06 can weigh in on it, but here's my initial thoughts:

1. Rather than sending data to multiple endpoints, send all of your data to a single AppSync endpoint, then use Dynamo Streams to trigger lambdas that copy over the new records to the other databases. If you need to this be near real-time and don't get much traffic you can set the batch size of your stream to 1. 

2. Great question, no idea. Our rule is that we don't delete fields, we deprecate them. My guess though is that it won't actually drop your Dynamo data, it will just make it impossible to query that data from AppSync until you scan your table and transform each changed field.

**Comment by blairtaylor** [comment]
@jkeys-ecg-nmsu thanks. 

1. The scenario I was thinking of was more to do with populating what would be static tables in a sql database... list of cities/states/countries etc. A one time copy. Your use case is interesting though, thanks for the idea.

2. Yes this makes sense and is consistent with what we have experienced. Our main concern was making a schema change and losing data in production. Seems that we should be able to script a copy in that case.

**Comment by jkeys-ecg-nmsu** [comment]
@blairtaylor you can also do your SQL transactions through Lambda. If it's static and doesn't need high granularity of updates then you could get away with setting a high batch size and doing more efficient inserts into your relational database.

On (2) there is a FR for that. https://github.com/aws-amplify/amplify-cli/issues/2567 Please add your +1 on that issue!
