### ISSUE TITLE
Trying to get source level debugging working with amplify mock + backend/function

### ISSUE THREAD

**Issue by mooser** [aws-amplify/amplify-cli#2482]
I have not been successful at hitting a breakpoint in my backend/function lambda using vscode and attaching the debugger to amplify mock via process id.

1. Is this possible with amplify mock?

2. The documentation, and all the examples I have found use very simple use cases that don't actually query graphql api from backend/function.  Has anyone tried to create an example project that features querying graphql and authenticate with Cognito in a backend lambda?

I attempted it, but I'm stuck now.

```
// HACK: hardcode the region, otherwise amplify mock will supply "fake-region" and cause errors.
const cognitoSP = new CognitoIdentityServiceProvider(
  {region: 'us-east-1'}   //process.env.REGION}
)
// ...
cognitoSP.adminInitiateAuth(initiateAuthParams, (authErr, authData) => {
```

Locally with amplify mock the error is:  
Error: 
```
{ message: 'User pool us-east-1_xxxxxxxxxx does not exist.',
  code: 'ResourceNotFoundException',
  time: '2019-10-02T22:57:19.593Z',
  requestId: 'd2076d47-1dd6-4589-9282-791448d7928b',
  statusCode: 400,
  retryable: false,
  retryDelay: 35.715768678455404 }
```

(but it works in the real deployed lambda)

**Comment by yuth** [comment]
@mooser 

> I have not been successful at hitting a breakpoint in my backend/function lambda using vscode and attaching the debugger to amplify mock via process id.

Mock server creates a new child process every time it invokes lambda. This is done so that the lambda function can pick up any change that might have happened in disk. So attaching a debugger using process id won't be possible. But if you use `console.log` statements they should get printed on to the terminal where you are running the mock server.

Can you please clarify the following
1. Is the userpool already pushed and available in cloud?
2. When making request using AWS SDK what credentials get used?

**Comment by mooser** [comment]
@yuth Thanks!  You solved it for me, it was the credentials. 

This is my solution currently to get mock working:
```
const IS_AMPLIFY_MOCK = (graphQLAPIEndpointOutput.indexOf('20002') >= 0)
if (IS_AMPLIFY_MOCK) {
  aws.config.credentials = new aws.SharedIniFileCredentials({profile: 'app-role'});
  region = 'us-east-1'  // hardcode region for mocking, otherwise there will be errors from a non-existent region provided by amplify mock
}
```
