### ISSUE TITLE
How to reference custom resources?

### ISSUE THREAD

**Issue by DanielMuller** [aws-amplify/amplify-cli#2562]
** Which Category is your question related to? **
CLI, Custom Resources

** What AWS Services are you utilizing? **
S3, Cloudfront, Lambda

** Provide additional details e.g. code snippets **
In my Amplify Project, I created a custom resource (S3 and Cloudfront) under `backend/cache/S3AndCloudFront/`. Since it's very similar to the "hosting" setup, in `backend-config.json`, I use `service=S3AndCloudFront`.
```
{
"cache": {
  "S3AndCloudFront": {
    "service": "S3AndCloudFront",
    "providerPlugin": "awscloudformation"
  }
}
```

This part works, S3 and CF are created as expected.

Now I want to add a lambda@edge function on this custom S3-CF.

`amplify add function` asks me what access-rights I want. For API and Storage, no problem. For the Custom stack, CLI gives me an error. The function is still created, just missing the access-rights to my custom bucket.

My questions:
- How can I reference the "Custom Bucket Name" in my function CF-template?
  I tried adding (without luck) to the parameters:
  ```
  {
    "cacheS3AndCloudFrontBucketName": {
      "Type": "String",
      "Default": "cacheS3AndCloudFrontBucketName"
  }
}
```
- What is the importance of "service", Should I avoid using S3AndCloudFront?
- How to deploy the function to us-east-1, the rest of the stack is deployed in ap-southeast-1
  I hardcoded the region in the template as us-east-1, but the function is still deployed to ap-southeast-1. That's probably a CF limitation, but is there some work around?

Thanks,
Daniel

**Comment by UnleashedMind** [comment]
- Answer 1: 
To the Amplify CLI, the backend resources are structured as `category/service`, and it has to be handled by a specific plugin. By merely adding to the backend-configure an object like you put up there doesn't do much, because no plugin is handling that piece of information. 
Currently the Amplify CLI does not provide you to set permission for the function category to access resources not setup by the CLI. But you can edit the template file under `amplify/function/<resource-name>/xxxx-template.json` if you understand how CloudFormation template works and really know what you are doing. 

- Answer 2: 
The Amplify CLI does not promote cross region references because it's inefficient, it is only done when it's absolutely necessary and it is done by the CLI itself, such as when analytics or notifications categories are added in a region where Pinpoint is not available, the CLI will map to a region that's closest to the region the project's backend is in.

**Comment by kaustavghosh06** [comment]
@DanielMuller Are you still stuck with this or are you unblocked based on @UnleashedMind's response?

**Comment by DanielMuller** [comment]
Thanks @UnleashedMind for the explanations.
@kaustavghosh06 It's not a blocking issue for me, the question was more about understanding how the pieces can fit together.
I could either create a plugin to handle to case or using "custom function" in my custom Cloudformation.
