### ISSUE TITLE
Field-level @auth with Array ownerField and @connection not working

### ISSUE THREAD

**Issue by marlonmarcello** [aws-amplify/amplify-cli#2650]
**Describe the bug**
According to the docs I should be able to have @auth at a field-level with @connection fields.
But when using the following schema, only the signed in user information is retrieved, so only the messages from the signed in user are coming through.
```
type Chat
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: owner }
      { allow: owner, ownerField: "members", operations: [read] }
    ]
  ) {
  id: ID!
  name: String!
  owner: String
  members: [String]
  messages: [Message]
    @connection(name: "ChatMessages", sortField: "createdAt", limit: 50)
    @auth(rules: [{ allow: owner, ownerField: "members", operations: [read] }])
  createdAt: AWSDateTime!
}

type Message @model(subscriptions: null) @auth(rules: [{ allow: owner }]) {
  id: ID!
  text: String
  owner: String
  chat: Chat @connection(name: "ChatMessages")
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
```

Generated query by Amplify being used:
```
query GetChat($id: ID!) {
  getChat(id: $id) {
    id
    name
    owner
    members
    messages {
      items {
        id
        text
        owner
        chatId
        createdAt
        updatedAt
      }
      nextToken
    }
    createdAt
  }
}
```

**To Reproduce**
1. Create new project with amplify
2. add api
3. use the above described schema or similar, with field-level @auth on a @connection with ownerfield as an array

**Expected behavior**
The loggedin user should get all of the messages of the Chat from all members.

Thanks in advance and I am so sorry if this is a mistake on the schema that I didn't catch.

**Comment by Tigerspike-Mike** [comment]
I have the exact same problem. Any direction on how to work around this (custom resolver) would be great. Seems like a pretty standard use case

**Comment by sihaya** [comment]
It seems that the @auth rule from the target type of the @connection is used in the generation of the response part of the field resolver.

For example In the schema above the template for the response part of the resolver ("Chat.messages.res.vtl") will only contain the @auth rule that is defined in the Message type (so only the owner of the Message gets access).

If you remove the @auth rule from the Message type in the schema then it should work. Of course you need to then disable direct access to the Message. This is also what the documentation is saying (https://aws-amplify.github.io/docs/cli-toolchain/graphql#field-level-authorization) although it is not very explicit about it.

I'm not sure if this intended behaviour because the actual request part of the resolver does contain a different authorization rule. In any case it would be nice if one could completely override the @auth defined on the target type.

**Comment by attilah** [comment]
@marlonmarcello the behavior you're experiencing is as intended. Having ```@auth``` on the connection works as expected, but since you've a rule for owners on the ```Message```  type itself that will be also evaluated as you're accessing that type through the connection. With 2 modifications you can achieve what you like:

- Disable queries on messages if you only intend to access it through the chat type
- Constrain the ```owner``` rules on ```Message``` type for only create, update, delete operations

Lets assume that you've user1, user2, user3 - which is easy to test out with ```amplify mock``` and have this schema:

```graphql
type Chat
  @model(subscriptions: null)
  @auth(
    rules: [
      { allow: owner }
      { allow: owner, ownerField: "members", operations: [read] }
    ]
  )
{
  id: ID!
  name: String!
  owner: String
  members: [String]
  messages: [Message]
    @connection(name: "ChatMessages", sortField: "createdAt", limit: 50)
    @auth(rules: [{ allow: owner, ownerField: "members", operations: [read] }])
  createdAt: AWSDateTime!
}

type Message
  @model(subscriptions: null, queries: null)
  @auth(rules: [{ allow: owner, operations: [create, update, delete] }])
{
  id: ID!
  text: String
  owner: String
  chat: Chat @connection(name: "ChatMessages")
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
```

Auth as ```user1``` and create a chat and some messages:
```graphql
mutation CreateItems1 {
  c1: createChat(input: {
    id: "c1"
    name: "Chat #1"
    members: ["user1", "user2"]
    createdAt: "2020-01-01T00:00:00Z"
  }) {
    id
  },
  m1: createMessage(input: {
    id: "m1"
    messageChatId: "c1"
    text: "Message #1"
    createdAt: "2020-01-01T00:00:00Z"
    updatedAt: "2020-01-01T00:00:00Z"
  }) {
    id
  },
  m3: createMessage(input: {
    id: "m3"
    messageChatId: "c1"
    text: "Message #3"
    createdAt: "2020-01-01T00:00:00Z"
    updatedAt: "2020-01-01T00:00:00Z"
  }) {
    id
  }
}
```

Auth as ```user2``` and create a message:
```graphql
mutation CreateItems2 {
  m2: createMessage(input: {
    id: "m2"
    messageChatId: "c1"
    text: "Message #2 - User2"
    createdAt: "2020-01-01T00:00:00Z"
    updatedAt: "2020-01-01T00:00:00Z"
  }) {
    id
  },
}
```

Auth as ```user1```, ```user2```, ```user3``` and test the query below:

```graphql
query ListChats {
  listChats {
    items {
      id
      owner
      messages {
        items {
	        id
  	      owner
    	    text
        }
      }
    }
  }
}
```

You'll see that ```user1``` and ```user2``` gets all the messages and the chat data as well, but ```user3``` receives an empty result.

I hope it helps to understand better how ```@auth``` on  ```@connection```s are working.
