### ISSUE TITLE
Ability to use short ID instead of UUID v4

### ISSUE THREAD

**Issue by ChristopheBougere** [aws-amplify/amplify-cli#2674]
**Is your feature request related to a problem? Please describe.**
I am using GraphQL resource IDs in my app URL. However they aren't SEO friendly (UUID v4 is 36 chars). I would like to replace them by short IDs instead, but IDs are automatically generated on create mutations.

**Describe the solution you'd like**
In my `schema.graphql`, I would like having the choice between let say `ID` and `ShortID` types.

**Describe alternatives you've considered**
I thought about creating my own `ShortID` type, but in generated resolvers it seems to be using a `$util.autoId()` function (see [docs](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-util-reference.html)). I don't know how I could generate an ID without a VTL function. And I don't want to have custom functions for each of my resolvers.

**Additional context**
I am not sure this issue only depends on the Amplify team, maybe as well on AppSync team. But maybe this is already planned (because SEO is quite important when running in production), or someone has a great workaround ?

**Comment by kaustavghosh06** [comment]
@ChristopheBougere You could use @key and specify your own primary key.

**Comment by ChristopheBougere** [comment]
Oh that's interesting I totally missed that directive.
So instead of having this:
```graphql
type Customer @model {
    id: ID!
    email: String!
    username: String
}
```
I would have this:
```graphql
type Customer @model @key(fields: ["id"]) {
    id: String!
    email: String!
    username: String
}
```
And I would need to generate the id from the frontend and pass it during the create mutation?
That looks great, I am just wondering if this could be risky to generate the ID from the frontend?

Thanks for your help @kaustavghosh06

**Comment by attilah** [comment]
@ChristopheBougere the resolver only assigns a value to ```id``` during create if it was not specified in the input. If you decide to control it, it works fine, that is something you can control, how you want to do it. I'd suggest that for database storage stick to uuidv4 and use shortid as an additional attribute and populate it from the "client" (API facade?). Since probably you'll need to query it I'd define a named ```@key``` to have a GSI generated for it.

The main reason I suggest this, that it is much easier to hit a collision with shortid because of its lower entropy.
