### ISSUE TITLE
Upgraded from cli v3.9 to v3.17 - get error on push: "Invalid request template given, must be less than 64kb in size"

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#2698]
**Describe the bug**
I upgraded the cli from v3.9 to v3.17 then did an amplify push. The push is failing with: 

`UPDATE_FAILED               Update<redact>RequestResolver                                                                AWS::AppSync::Resolver     Wed Nov 06 2019 14:36:46 GMT-0700 (Mountain Standard Time) Invalid request template given, must be less than 64kb in size. (Service: AWSAppSync; Status Code: 400; Error Code: BadRequestException; Request ID: d2eec6ea-649e-4dea-b188-d4464fd52e1c)`

**Amplify CLI Version**
v3.17

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 10.9

**Additional context**

**Comment by hisham** [comment]
This is an auto-generated resolver with lots of field-level auth directives. Perhaps this is why the resolver is so big? This seems like a new limitation? 

`-rw-r--r--  1 hisham  staff    64K  6 Nov 14:34 Mutation.updateQuestionnaireRequest.req.vtl
`

**Comment by hisham** [comment]
Looking at the resolver size uploaded by the v3.9 cli, it is 50kb: 

`-rw-r--r--  1 hisham  wheel    50K  6 Nov 15:10 Mutation.old.vtl
`

I bet the changes involved in implementing https://github.com/aws-amplify/amplify-cli/issues/766 pushed this over the 64kb limit.

**Comment by hisham** [comment]
I simplified my auth directives a bit and managed to get the file down to 57kb. Good enough for now but it seems like a fix is needed here to optimize your code or use pipeline resolvers or just get rid of this limit. Limits on code size is weird..

To reproduce just put a lot of auth directives on fields in models in the graphql schema. The code will keep growing and growing...

**Comment by attilah** [comment]
@hisham could you please check the diff of the two resolvers and share it with us? If it's confidential, send it to amplify-cli@amazon.com if possible.

**Comment by hisham** [comment]
Sure @attilah I just sent the files.

**Comment by jkeys-ecg-nmsu** [comment]
@hisham those limits are (presumably) b/c AppSync users don't pay for compute/storage time used in VTL resolvers, and they want to minimize the potential for someone to abuse that. I would not be surprised if those limits are removed in the future and VTL charges are added to the AppSync billing model. But you may be able to open a ticket with the AppSync team and ask them for a code size limit increase, not sure if that's currently a soft or hard limit.

**Comment by rinosamakanata** [comment]
Any updates? I got the same problem..

**Comment by hisham** [comment]
> But you may be able to open a ticket with the AppSync team and ask them for a code size limit increase, not sure if that's currently a soft or hard limit.

fyi I did contact AWS Support and they are not able to change these limits at this time. So the solution is to reduce the number of field-level auths until amplify cli comes up with reduced code to enforce field auths.

**Comment by rinosamakanata** [comment]
Thank you @hisham for the update!
Hmm, the solution AWS offers is hard to do, so I will try override a resolver to make small and optimize...

**Comment by RossWilliams** [comment]
@rinosamakanata the resolvers have comments blocks, you could run a script to strip the comments?

**Comment by rinosamakanata** [comment]
@RossWilliams 
Yes, this way is a little hack, but can reduce comment lines in resolver templates. 

https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-mapping-template/src/print.ts#L138

Changes:

```
function printComment(node: CommentNode, indent: string = ''): string {
  return '';
}
```

**Comment by CodySwannGT** [comment]
Yikes. Never got a resolution to this?

**Comment by lexfaraday** [comment]
+1
Please, I pay it without problem, just give us a solution, modifying the Graphql model is not an option.
Thanks in Advance!

**Comment by GeorgeBellTMH** [comment]
A quick solution to this would be to make a feature flag that makes the VTL file be written with no comments if they get too big...

An even better solution would be to optionally run a minimization script on large files so that variable names are as short as possible...$ownerAuthExpressions => $o

**Comment by hisham** [comment]
Still an issue I believe.

**Comment by fkunecke** [comment]
how can this possibly be closed? huge issue when adding any amount of field level authorization rules.

**Comment by simon-lanf** [comment]
Yes this is a really big problem and probably the reason why we will stop using Amplify.

**Comment by IsaacTrevino** [comment]
I'm running into this issue again, any leads?
![image](https://user-images.githubusercontent.com/13424971/107562456-76b0b480-6ba5-11eb-8306-e7f4dc693c3d.png)

**Comment by bacon1097** [comment]
Just ran into this issue. Really unfortunate when trying to create a project of some size.

**Comment by danielblignaut** [comment]
I would suggest optimising the file size by the following, especially if you have recursive code in your vtl templates as I do:
* rename variables to "minified names"
* replace all tabs and white spaces with a single white space
* replace all multi new lines with a single new line

I managed to get a 50kb template (which still failed when uploaded via cloudformation due to the 69kb error?????) down to 40kb pretty easily.

**Comment by arturocanalda** [comment]
I run into the same problem. Not I have too many fields, but 30-40% of them require field level @auth.
At this moment I can still optimise it. But at some point I will hit this wall again. 
What's left then... remove auth rules? rename fields/refactor?
I understand why there are limitations, and at this moment we can by-pass them. But these sort of limitations can get your ass kicked when a product is out there and already mature.

**Comment by simon-lanf** [comment]
@IsaacTrevino

> This is not an amplify problem, but an aws problem.

It absolutely is. Amplify could easily use Appsync's lambda pipelines to get this through. But currently it's a dead end.

**Comment by IsaacTrevino** [comment]
I'm currently using lambda pipelines by using the @function. Ofcourse this forces me to use graphql operations within them.

I discuss more here:
 https://link.medium.com/ANsTxKtJcgb

**Comment by simon-lanf** [comment]
@IsaacTrevino

> I'm currently using lambda pipelines by using the @function. Ofcourse this forces me to use graphql operations within them.
> 
> I discuss more here:
> https://link.medium.com/ANsTxKtJcgb

This defeats the purpose of Amplify.

The good news is that they are working on it: https://github.com/aws-amplify/amplify-cli/issues/6217

**Comment by hhemmati81** [comment]
This issue should be reopened. This is a major flaw. We are building a healthcare platform that has many fields which require different authorization levels. We can't compromise security because there is a 64kb file size limit. AWS has to offer a larger size even if it requires to be on a paid plan.

**Comment by fkunecke** [comment]
As @IsaacTrevino pointed out, this doesn't appear to be something easily resolved with a pull request in this repo:

https://docs.aws.amazon.com/general/latest/gr/appsync.html

<html>
<body>
<div class="table-container" style="margin: 2rem 0px; display: flex; flex-flow: row nowrap;"><div class="table-contents" style="display: inline-block; overflow: auto; max-height: 60vh; border-top: 1px solid rgb(59, 64, 66); border-right-color: rgb(59, 64, 66); border-bottom-color: rgb(59, 64, 66); border-left-color: rgb(59, 64, 66); box-shadow: 0 1px 1px 0 var(--darkreader-bg--awsui-color-shadow-medium),1px 1px 1px 0 var(--darkreader-bg--awsui-color-shadow-side),-1px 1px 1px 0 var(--darkreader-bg--awsui-color-shadow-side);">

Resource | Description | Default
-- | -- | --
API keys per API | The maximum number of API keys per GraphQL API | 50
APIs per region | The maximum number of APIs per region per account | 25You can request a quota increase.
Authentication providers per API | The maximum number of authentication providers per API | 50
Schema document size | The maximum size of the schema document | 1 MB
Functions per pipeline resolver | The maximum number of functions per pipeline resolver | 10
Throttle rate per GraphQL API | The maximum number of GraphQL queries per API per second | 1,000You can request a quota increase.
GraphQL request execution timeout | The maximum GraphQL request execution time for queries, mutations, and subscriptions | 30 seconds
Evaluated resolver template size | The maximum size of the evaluated resolver template | 5 MB
Request mapping template size | The maximum request mapping template size | 64 KB
Response mapping template size | The maximum response mapping template size | 64 KB
Iterations in a foreach loop in mapping templates | The maximum number of iterations in a #foreach...#end loop in mapping templates | 1000
Resolvers executed in a single request | The maximum number of resolvers that can be executed in a single request | 10,000
Subscription payload size | The maximum size of the message received from subscriptions (WebSockets) | 240 KB
Subscription payload size | The maximum size of the message received from subscriptions (MQTT over WebSockets) | 128 KB
Number of caching keys | The maximum number of caching keys | 10You can request a quota increase.

</div></div><awsdocs-thumb-feedback right-edge="" class="ng-isolate-scope"><div ng-show="$ctrl.showfeedbackThumbs" style="position: sticky; z-index: 2000; bottom: 15px;"><div style="display: flex; flex-direction: row; position: absolute; top: -37px; right: -83px;"><div style="position: relative;"><awsui-popover class="feedback-thumb up-thumb" size="small" position="top" trigger-type="custom" dismiss-button="false" initialized="true" style="position: relative; left: 5px; color: rgb(215, 212, 207); font-family: &quot;Amazon Ember&quot;, &quot;Helvetica Neue&quot;, Roboto, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 26, 27); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="awsui-popover" style="display: inline-block;"><span class="awsui-popover__trigger" style="display: inline-block;"><span awsui-popover-region="trigger" style="display: inline-block;"><span dom-region="trigger" class="ng-scope" style="display: inline-block;"><awsui-button aria-label="This page is helpful" ng-class="{selected: $ctrl.thumbIsUp}" ng-click="$ctrl.up($event)" ng-mouseenter="$ctrl.onMouseenterTrigger('up')" ng-mouseleave="$ctrl.onMouseleaveTrigger('up')" initialized="true" style="color: var(--darkreader-text--awsui-color-text-body-default, #d7d4cf); direction: ltr; font-family: &quot;Amazon Ember&quot;, &quot;Helvetica Neue&quot;, Roboto, Arial, sans-serif; font-feature-settings: initial; font-kerning: initial; font-optical-sizing: initial; font-size: initial; font-stretch: initial; font-style: initial; font-variant: initial; font-variation-settings: initial; font-weight: 400; forced-color-adjust: initial; text-orientation: initial; text-rendering: initial; -webkit-font-smoothing: initial; -webkit-locale: initial; -webkit-text-orientation: initial; -webkit-writing-mode: initial; writing-mode: initial; zoom: initial; place-content: initial; place-items: initial; place-self: initial; alignment-baseline: initial; animation: initial; appearance: initial; aspect-ratio: initial; backdrop-filter: initial; backface-visibility: initial; background: initial; background-blend-mode: initial; baseline-shift: initial; block-size: initial; border-block: initial; border: initial; border-radius: initial; border-collapse: initial; border-end-end-radius: initial; border-end-start-radius: initial; border-inline: initial; border-start-end-radius: initial; border-start-start-radius: initial; inset: initial; box-shadow: initial; box-sizing: border-box; break-after: initial; break-before: initial; break-inside: initial; buffered-rendering: initial; caption-side: initial; caret-color: initial; clear: initial; clip: initial; clip-path: initial; clip-rule: initial; color-interpolation: initial; color-interpolation-filters: initial; color-rendering: initial; color-scheme: initial; columns: initial; column-fill: initial; gap: initial; column-rule: initial; column-span: initial; contain: initial; contain-intrinsic-size: initial; content: initial; content-visibility: initial; counter-increment: initial; counter-reset: initial; counter-set: initial; cursor: initial; cx: initial; cy: initial; d: initial; display: inline-block; dominant-baseline: initial; empty-cells: initial; fill: initial; fill-opacity: initial; fill-rule: initial; filter: initial; flex: initial; flex-flow: initial; float: initial; flood-color: initial; flood-opacity: initial; grid: initial; grid-area: initial; height: initial; hyphens: initial; image-orientation: initial; image-rendering: initial; inline-size: initial; inset-block: initial; inset-inline: initial; isolation: initial; letter-spacing: initial; lighting-color: initial; line-break: initial; line-height: initial; list-style: initial; margin-block: initial; margin: initial; margin-inline: initial; marker: initial; mask: initial; mask-type: initial; max-block-size: initial; max-height: initial; max-inline-size: initial; max-width: initial; min-block-size: initial; min-height: initial; min-inline-size: initial; min-width: 0px; mix-blend-mode: initial; object-fit: initial; object-position: initial; offset: initial; opacity: initial; order: initial; origin-trial-test-property: initial; orphans: initial; outline: initial; outline-offset: initial; overflow-anchor: initial; overflow-clip-margin: initial; overflow-wrap: initial; overflow: initial; overscroll-behavior-block: initial; overscroll-behavior-inline: initial; overscroll-behavior: initial; padding-block: initial; padding: initial; padding-inline: initial; page: initial; page-orientation: initial; paint-order: initial; perspective: initial; perspective-origin: initial; pointer-events: initial; position: initial; quotes: initial; r: initial; resize: initial; ruby-position: initial; rx: initial; ry: initial; scroll-behavior: initial; scroll-margin-block: initial; scroll-margin: initial; scroll-margin-inline: initial; scroll-padding-block: initial; scroll-padding: initial; scroll-padding-inline: initial; scroll-snap-align: initial; scroll-snap-stop: initial; scroll-snap-type: initial; shape-image-threshold: initial; shape-margin: initial; shape-outside: initial; shape-rendering: initial; size: initial; speak: initial; stop-color: initial; stop-opacity: initial; stroke: initial; stroke-dasharray: initial; stroke-dashoffset: initial; stroke-linecap: initial; stroke-linejoin: initial; stroke-miterlimit: initial; stroke-opacity: initial; stroke-width: initial; tab-size: initial; table-layout: initial; text-align: initial; text-align-last: initial; text-anchor: initial; text-combine-upright: initial; text-decoration: none; text-decoration-skip-ink: initial; text-indent: initial; text-overflow: initial; text-shadow: initial; text-size-adjust: initial; text-transform: initial; text-underline-offset: initial; text-underline-position: initial; touch-action: initial; transform: initial; transform-box: initial; transform-origin: initial; transform-style: initial; transition: initial; unicode-bidi: normal; user-select: initial; vector-effect: initial; vertical-align: initial; visibility: initial; -webkit-app-region: initial; border-spacing: initial; -webkit-border-image: initial; -webkit-box-align: initial; -webkit-box-decoration-break: initial; -webkit-box-direction: initial; -webkit-box-flex: initial; -webkit-box-ordinal-group: initial; -webkit-box-orient: initial; -webkit-box-pack: initial; -webkit-box-reflect: initial; -webkit-highlight: initial; -webkit-hyphenate-character: initial; -webkit-line-break: initial; -webkit-line-clamp: initial; -webkit-mask-box-image: initial; -webkit-mask: initial; -webkit-mask-composite: initial; -webkit-perspective-origin-x: initial; -webkit-perspective-origin-y: initial; -webkit-print-color-adjust: initial; -webkit-rtl-ordering: initial; -webkit-ruby-position: initial; -webkit-tap-highlight-color: initial; -webkit-text-combine: initial; -webkit-text-decorations-in-effect: initial; -webkit-text-emphasis: initial; -webkit-text-emphasis-position: initial; -webkit-text-fill-color: initial; -webkit-text-security: initial; -webkit-text-stroke: initial; -webkit-transform-origin-x: initial; -webkit-transform-origin-y: initial; -webkit-transform-origin-z: initial; -webkit-user-drag: initial; -webkit-user-modify: initial; white-space: initial; widows: initial; width: initial; will-change: initial; word-break: break-word; word-spacing: initial; x: initial; y: initial; z-index: initial;"><button class="awsui-button awsui-button-variant-normal awsui-hover-child-icons" type="submit" override-focus="" style="background-color: transparent; border-color: var(--darkreader-border--awsui-color-border-button-normal-default); color: var(--darkreader-text--awsui-color-text-interactive-default); font-family: inherit; font-size: 1.4rem; line-height: 2rem; margin: 0px; overflow: visible; text-transform: none; appearance: button; text-decoration: none; border-radius: 2px; border-width: initial; border-style: none; border-image: initial; padding: 0.4rem 2rem; font-weight: 700; letter-spacing: 0.25px; display: inline-block; cursor: pointer; text-align: left; position: relative; height: 40px; width: 40px; background-image: ; background-position-x: ; background-position-y: ; background-size: ; background-repeat-x: ; background-repeat-y: ; background-attachment: ; background-origin: ; background-clip: ; word-break: normal;"><span awsui-button-region="text"><span><div class="feedback-thumb-circle ng-binding ng-scope" ng-bind-html="$ctrl.thumbUpSvg" style="position: absolute; box-sizing: border-box; height: 30px; width: 30px; inset: 5px; border-radius: 20px; border: 1px solid rgb(0, 154, 194); background-color: rgba(27, 29, 30, 0.5); box-shadow: rgb(42, 45, 47) 0px 1px 3px 1px;"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 130 130"><path class="st0" d="M53.6,57.8L53.6,57.8c1.9,0,3.8-0.8,5.2-2.2l9.5-9.5l2.5-5l2-4.6c0.5-1.2,1.6-1.9,2.9-1.9
  c2.3,0,4.2,1.9,4.2,4.2l0,0c-0.1,2.1-0.5,4.3-1.1,6.3L74,55.9c-0.2,0.5-0.1,1.1,0.3,1.5l0,0c0.3,0.3,0.6,0.4,1,0.4h16.3
  c1.7,0,3.3,1,4,2.5c1,2.2,0,4.9-2.2,5.9c-0.6,0.3-1.2,0.4-1.8,0.4h2.1c2.1,0,3.9,1.5,4.2,3.6c0.2,2.2-1.4,4.1-3.6,4.3
  c-0.1,0-0.3,0-0.4,0h-2.4c2.4,0,4.4,2,4.4,4.5c0,0.6-0.1,1.2-0.4,1.8c-0.7,1.6-2.3,2.6-4,2.6h-2.2c2.4,0,4.3,1.9,4.3,4.2
  c0,0.1,0,0.1,0,0.2c-0.3,2.1-2.1,3.7-4.2,3.6h-25c-1.5-0.1-3-0.5-4.5-1l0,0c-1.5-0.6-3-1.1-4.5-1.4l-1.8-0.2"></path><polyline class="st0" points="34.8,68.2 34.8,56.2 50,56.2 50,92.2 34.8,92.2 34.8,68.2 "></polyline></svg></div></span></span></button></awsui-button></span></span></span><div class="awsui-popover__tab-trap" tabindex="-1"></div><div class="awsui-popover__tab-trap" tabindex="-1"></div></div></awsui-popover><span style="color: rgb(215, 212, 207); font-family: &quot;Amazon Ember&quot;, &quot;Helvetica Neue&quot;, Roboto, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 26, 27); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"></span><awsui-popover class="feedback-thumb hover-popover" size="small" position="top" trigger-type="custom" dismiss-button="false" initialized="true" style="position: absolute; left: 0px; top: 0px; pointer-events: none; color: rgb(215, 212, 207); font-family: &quot;Amazon Ember&quot;, &quot;Helvetica Neue&quot;, Roboto, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(24, 26, 27); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="awsui-popover" style="display: inline-block;"><span class="awsui-popover__trigger" style="display: inline-block;"><span awsui-popover-region="trigger" style="display: inline-block;"><span dom-region="trigger" class="ng-scope" style="display: inline-block;"><br class="Apple-interchange-newline">
</body>
</html>

Maybe we can put together a script to minify the .graphql file? Or some kind of script that automatically splits it into multiple AppSync instances, and a lambda that maps /graphql requests to the right endpoint. I don't see this getting resolved any time soon otherwise.

If we could get someone from the AppSync team involved this might get resolved.

**Comment by GeorgeBellTMH** [comment]
#6008 is still open...I believe a lot of additional work can be done on this...

1) Remove comments
2) Minimize where possible
3) Ability to request/pay for bigger VTL
4) Chaining VTL files if necessary...

**Comment by fkunecke** [comment]
@GeorgeBellTMH I really like your idea of creating a minification function. I bet with a few days of work we could put something like this together. Pretty soon I need to go through a security audit for my app, and I may have to add field level auth to all the models, which will invariably exceed the 64kb template size. If I end up implementing a solution for this I will try to encapsulate it into an amplify CLI extension

**Comment by l-hendriks** [comment]
I worked around this by not doing `amplify push` anymore, but doing `amplify api gql-compile && node scripts/minifyVtlTemplates.js && amplify push --no-gql-override`

with `minifyVtlTemplates.js` being a script that minifies the vtl templates. I only do this now: 

```
    // Replace space
    vtl = vtl.replace(/ +/g, ' ');

    // Remove comments
    vtl = vtl.replace(/##.*/g, '');

    // Remove double newlines
    vtl = vtl.replace(/\n+/g, '\n');
```
looping over these two folders:

```
const folder = './amplify/backend/api/website/build/resolvers';
const folder2 = './amplify/#current-cloud-backend/api/website/build/resolvers';
```

this is already enough for me to be able to resolve this. You can also rename variable names etc to minify further (I couldn't find a VTL minifier).

In the build pipeline I did something similar

**Comment by raffibag** [comment]
+1 especially as this is an issue you're not likely going to run into until you're well into development. It's like hitting a brick wall.

**Comment by ykethan** [comment]
Hello everyone, With the new GraphQL Transformer v2 we've introduced the use of pipeline resolvers, which now splits logic into multiple VTL resolvers rather than one. 
On replication with a model containing over 30 fields with field level `@auth` rules we observed no VTL template exceeded 5 KB.

For more information please see the following documentation. 
- https://docs.amplify.aws/cli/graphql/overview/
- https://docs.amplify.aws/cli/migration/transformer-migration/

Closing issue, if you are experiencing continued issues, please do reply on this thread with an example schema.
