### ISSUE TITLE
After adding GSI via @key, previous data not displaying in @key query

### ISSUE THREAD

**Issue by blairtaylor** [aws-amplify/amplify-cli#2712]
We have a type in our schema ServiceType. After some initial use by customers, we made an enhancement to add a Category field and needed to sort by category. To achieve this we added the field as well as a @key which generated a GSI. @key for reference was:

  @key(
    name: "ByCompanySortedByCategoryNameName"
    fields: ["companyId", "categoryName", "name"]
    queryField: "serviceTypeByCompany"
  )

This all has worked well expect for one thing. The original service type data was not migrated over to the GSI. When we called serviceTypeByCompany the query initially returned no values. Once we repopulated the data, the values displayed and all is well. Unfortunately this will be a pretty major issue going forward - introducing a GSI for a type which had a significant number of existing rows.

In researching, we came across this question which seems to ask about the same issue.

https://stackoverflow.com/questions/50311154/does-creating-dynamodb-gsi-on-existing-table-indexes-old-records

The response is that a new DynamoDB GSI does index old records. That was not our experience. 

Is there a way to preserve access to old records when introducing a new @key / GSI in AWS Amplify using DynamoDB? In our case is there a way to default the values for a new field and if so, would this have migrated the older records to the GSI?

**Comment by attilah** [comment]
@blairtaylor This is true for DynamoDB when you're using s PK and SK, but when ```@key``` is used with more than 2 fields, a new attribute is created, ```categoryName#name``` in your case, and DynamoDB does not know anything about it, because it is managed by the custom resolvers, you've to populate it with data if you create this GSI, when the table has existing data.

**Comment by blairtaylor** [comment]
Thanks @attilah. Could you explain what the difference would have been if we had used an @key directive with 2 fields?

**Comment by attilah** [comment]
Take a look at the docs: https://aws-amplify.github.io/docs/cli-toolchain/graphql#evolving-apis-with-key

It explicitly states this:
> If adding a @key with 3 or more fields, you will need to back-fill the new composite sort key for existing data.

When you are specifying 3 fields, since DynamoDB only supports a single SK, Amplify CLI creates a new attribute for you where the merge of those input fields in the mutation resolver are merged, enable you to do filtering/sorting on the combined value. When you've 2 fields, Amplify CLI does not have to introduce a new attribute into your schema, so the index itself can be built on top of it.

**Comment by blairtaylor** [comment]
ok. thanks.
