### ISSUE TITLE
Fundamental Issues with Deployment Process

### ISSUE THREAD

**Issue by zjullion** [aws-amplify/amplify-cli#2784]
**Describe the bug**
There are some fundamental issues with the `#current-cloud-backend.zip` and `amplify-cfn-templates` folder in the deployment S3 bucket. Consider the following (which happened to us in production, ouch):

1. A bad value is put in a cloudformation template (for example, `hosting/template.json`)
2. `amplify publish` fails (as it should), but `amplify-cfn-templates/hosting/template.json` is still updated with the bad template
3. `hosting/template.json` is reset locally, and other changes are added - when `amplify status` is run, `hosting/template.json` appears to not have any changes to deploy, but other changes will be deployed
4. When `amplify publish` is run, the local `hosting/template.json` is not uploaded to the S3 deployment bucket (since it matches up with what is in `#current-cloud-backend.zip`)
5. The bad template in `amplify-cfn-templates/hosting/template.json` is deployed as part of the cloudformation change set, and the deployment fails
6. As long as `amplify publish` is run with an unmodified (and correct) local `hosting/template.json`, the deployment will fail
7. Only once local `hosting/template.json` is modified will the deployment succeed

**Amplify CLI Version**
3.17.0 (although this issue has existed for a long time)

**To Reproduce**
See above

**Expected behavior**
I expect the local cloudformation templates to be deployed when I run `amplify publish` every time, regardless of the state of files in the S3 deployment bucket.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - MacOS (not relevant)
 - Node Version v10.14.1 (not relevant)

**Additional context**
I think the best fix for this issue is to upload all local cloudformation templates to the deployment bucket every time `amplify publish` is run, regardless of whether or not there are diffs with `current-cloud-backend`

**Comment by rrrix** [comment]
I've had something similar happen to me too! 

It would be really nice if Amplify ran something like [ValidateTemplate](https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_ValidateTemplate.html) on all the templates it is about to upload/use. Especially in production. 

Even better (but likely not happening) would be to use [cfn-lint](https://github.com/aws-cloudformation/cfn-python-lint) across everything (since ValidateTemplate has various limitations, like 51KB maximum file size). I have a feeling that using a Python dependency in a TypeScript application might not make all of the Amplify userbase very happy. Maybe it could be an optional (if present run check) pre-push/publish hook.

**Comment by zjullion** [comment]
We actually do run `cfn-lint` on all our templates before uploading them - it doesn't prevent you from uploading a non-existent (but syntactically valid) value, and then you can still end up in this state.

**Comment by josefaidt** [comment]
Closing as we have since added `cfn-lint` to run on push, promoting validation errors as warnings to the deployment process. We do have another item in our backlog to validate the CFN templates and parameters to further ensure invalid templates are not uploaded and fail fast.
