### ISSUE TITLE
amplify codegen generates recursive mutation 

### ISSUE THREAD

**Issue by henrysachs** [aws-amplify/amplify-cli#2977]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**

Amplfy CLI / Amplify Codegen

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.6.0

**What AWS Services are you utilizing?**

Appsync 
Cognito 
S3
Lambda

**Provide additional details e.g. code snippets**

so my Schema looks like the following (shortened): 

``` graphql
  type TrainingSession  @model 
    @key(fields: ["id", "mygoalid", "date"])
    @key(name: "ByMyGoalID", fields: ["mygoalid", "date", "position"], queryField: "SessionByMyGoal")
    @key(name: "ByDate", fields: ["date","mygoalid", "position"], queryField: "SessionByDate") {
    id: ID!
    date: AWSDate!
    mygoalid: ID!
    title: String!
    description: String
    instructions: [TrainingInstruction] @connection(name: "SessionInstructions", keyField:"trainingsessionid", sortField: "position")
    done: Boolean
  }

  type TrainingInstruction @model {
    id: ID
    title: String
    trainingsessionid: ID!
    trainingsession: TrainingSession @connection(name: "SessionInstructions", keyField:"trainingsessionid", sortField: "position")
    createdAt: AWSDateTime
    updatedAt: AWSDateTime
  }
```

everythings fine when generating a List Query with a depth of 4 but when i take a look at the mutations i have the problem that the following query is generated:

``` javascript

mutation UpdateTrainingSession($input: UpdateTrainingSessionInput!) {
        updateTrainingSession(input: $input) {
          __typename
          id
          date
          mygoalid
          title
          description
          sport
          duration
          position
          instructions {
            __typename
            items {
              __typename
              id
              title
              position
              description
              duration
              load
              trainingsessionid
              trainingsession {
                __typename
                id
                date
                mygoalid
                title
                description
                sport
                duration
                position
                done
                createdAt
                updatedAt
                keysession
              }
              createdAt
              updatedAt
            }
            nextToken
          }
          done
          createdAt
          updatedAt
          keysession
        }
      }
```

with this query i get the following aws error: `The provided key element does not match the schema (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: ***)`because instructions dont have nested traininsessions. 

Its a one to many connection i tried to create maybe my schema isn't designed correctly. But my short Solution would be that i can specify different max-depths for mutations and queries. 

Thanks in advance happy to provide more info.

**Comment by henrysachs** [comment]
For anyone having similar problems: 

I'm using angular where Amplify generates the API Service. I took the relevant part and moved it into a Custom Api Service Service Class. Then I just changed the statement itself and took the imports from the original API Service. I think this does the less "damage" on the surface because i just change what is returned to my client. In my client i just check if there weren't any errors so this was fine.

**Comment by henrysachs** [comment]
I don't want to rush it but how is this going further? Do i need to provide more info? How can I help you? :)

**Comment by nikhname** [comment]
@henrysachs just to be clear, the error is caused by the trainingsession block within instructions?

**Comment by henrysachs** [comment]
Yeah it’s exactly this. If I would reduce the depth it would go away but somehow in the generated query for the List Operation this depth is needed.

**Comment by edwardfoyle** [comment]
Hey @henrysachs the nested data structure that is generated is the expected format of the output rather than the input. Can you provide more details about how you are using the mutation and specifying the `UpdateTrainingSessionInput` when you call your API?

For reference, I was able to get this working with the latest version of the CLI and the following graphql schema:
```graphql
type TrainingSession  @model {
  id: ID!
  title: String
  instructions: [TrainingInstruction] @connection(keyName: "byTrainingSession", fields:["id"])
}

type TrainingInstruction @model
  @key(name: "byTrainingSession", fields: ["trainingSessionID"]) {
  id: ID!
  title: String
  trainingSessionID: ID!
  trainingsession: TrainingSession @connection(fields: ["trainingSessionID"])
}
```
(note, I am using the new parameterization of @connection documented [here](https://aws-amplify.github.io/docs/cli-toolchain/graphql#connection). I noticed you are using the old parameterization and it's possible that some issue is arising from that)
Setting the codegen depth to 4 generated the following mutation:
```javascript
export const updateTrainingSession = /* GraphQL */ `
  mutation UpdateTrainingSession(
    $input: UpdateTrainingSessionInput!
    $condition: ModelTrainingSessionConditionInput
  ) {
    updateTrainingSession(input: $input, condition: $condition) {
      id
      title
      instructions {
        items {
          id
          title
          trainingSessionID
          trainingsession {
            id
            title
          }
        }
        nextToken
      }
    }
  }
`;
```
This mutation has the self-referential behavior that you noted above, but I was able to use it without issue in the following way:
```javascript
async function updateSession() {
    const updateTrainingSessionInput: UpdateTrainingSessionInput = {id: "session id here", title: "new title"};
    return await API.graphql(graphqlOperation(updateTrainingSession, {input: updateTrainingSessionInput}))
}
```
The nested nature of the query is by design because while it is redundant in this case where a TrainingInstruction will always point back to the same TrainingSession that pointed to it in the first place, this isn't the case in general. For example, a file structure where the model is something like
```graphql
type Directory @model {
  parent: Directory
  children: Directory[]
  files: File[]
}
```
In this case it makes sense to recursively generate the return data structure (up to the limit specified to codegen) so that a caller could traverse as much of the file structure as they wanted. If you want a query / mutation that does not return all fields, it is expected that you would add those in a separate file from the ones generated by codegen.

I was unable to repro the DynamoDB exception you mentioned but if you are still running into the issue after trying the above suggestions please follow up below.

**Comment by henrysachs** [comment]
ho @edwardfoyle  I will try to use the new @connection annotation but at the time I was developing this, it didn't exist. :D 
But i saw that you seem to be using vanilla js and I used the generated angular service maybe it could be related to that but i will check this. :)
