### ISSUE TITLE
Send push notifications/emails when a query/mutation happens in AppSync/Aurora

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#3106]
Hello world,

I am using AppSync with Aurora/RDS.
I would like that in some cases, when a query/mutation is sent to the db, then, after that, I want to send an email and push notification, but this is detached from the query/mutation, that is, it does not matter if it fails or it works. 
At the moment I see several options options:
Can you tell me which one I should use or do you recommend me? Thanks

- Create a query that calls a lambda function that sends the push/email and call it from the client once the actual query/mutation is done. 
I don't like this because the logic is in the client rather than the server. Seems easy to implement, and I guess it is easy to ignore the result of the second operation from a client point of view.

- A variation of the previous one. Pack both operations in a single network request. With GraphQL, that is easy, but I don't want the client waits for the second operation. (Is it possible to create lambda functions that return immediately, like a trigger of other functions?)

- Attach my queries/mutations to lambda functions instead of RDS directly. Then, those lambda functions call other lambda functions for notifications.
Seems more difficult to program, but more micro-services architecture friendly. Probably this is the best one, not sure.

- Use SQL triggers and call lambda functions from those triggers. I don't know if this is even possible. Researching...

- Use pipelines resolvers. The first one is the query/mutation, the second one is the lambda function that sends the push/email.
I would say this is a bad option because I don't want the client to wait for the second operation or manage the logic when the second resolver fails.

- Amazon RDS Events: It appears it is possible to attach lambda functions to specific AWS RDS events.
https://docs.aws.amazon.com/lambda/latest/dg/services-rds.html
It seems it is about creating DBs, restoring... and that kind of things. I don't see anything like creating a row, updating a row... So, I discard this unless I am wrong.

- Invoking a Lambda Function with an Aurora MySQL Stored Procedure (CALL mysql.lambda_async)
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Integrating.Lambda.html
"For example, you might want to send a notification using Amazon Simple Notification Service (Amazon SNS) whenever a row is inserted into a specific table in your database."
That is exactly what I am looking for. I like this idea, but I don't know if that is possible with Aurora Serverless. Researching...
It seems it is not possible when using serverless:
https://www.reddit.com/r/aws/comments/a9szid/aurora_serverless_call_lambda/

- Use step functions: No idea about how to use it.

- Somehow, attach this lamdba notification function to GraphQL/Appsync instead of the database, but I guess it is not a good idea because I need to read the database to the push notification token and the email of the use who is going to receive the notifications.

What do you think? I would like to know your opinion. Thanks a lot.

**Which Category is your question related to?**
amplify CLI and databases

**Amplify CLI Version** 
4.2.0

**What AWS Services are you utilizing?**
amplify CLI, appsync, aurora serverless

**Comment by ammarkarachi** [comment]
> Create a query that calls a lambda function that sends the push/email and call it from the client once the actual query/mutation is done.
I don't like this because the logic is in the client rather than the server. Seems easy to implement, and I guess it is easy to ignore the result of the second operation from a client point of view.

I believe since you aren't concerned with success of the query/mutation this would be the way to go but you are also keeping the logic on the client and there is no guarantee the client would execute the second function

> Attach my queries/mutations to lambda functions instead of RDS directly. Then, those lambda functions call other lambda functions for notifications.
Seems more difficult to program, but more micro-services architecture friendly. Probably this is the best one, not sure.

I like this approach the most, this way the query/mutation part is decoupled from the notifications part. Also you can make async calls from your function to make sure hte client is not waiting on the query/mutation to complete.

> Use SQL triggers and call lambda functions from those triggers. I don't know if this is even possible. Researching...

You still have to wait for query/mutation to complete for the sql trigger to execute.

> Amazon RDS Events: It appears it is possible to attach lambda functions to specific AWS RDS events.
https://docs.aws.amazon.com/lambda/latest/dg/services-rds.html
It seems it is about creating DBs, restoring... and that kind of things. I don't see anything like creating a row, updating a row... So, I discard this unless I am wrong.

True, I only see control events for RDS so that's a no

> Invoking a Lambda Function with an Aurora MySQL Stored Procedure (CALL mysql.lambda_async)
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Integrating.Lambda.html
"For example, you might want to send a notification using Amazon Simple Notification Service (Amazon SNS) whenever a row is inserted into a specific table in your database."
That is exactly what I am looking for. I like this idea, but I don't know if that is possible with Aurora Serverless. Researching...
It seems it is not possible when using serverless:
https://www.reddit.com/r/aws/comments/a9szid/aurora_serverless_call_lambda/

This seems like the case for serverless but I will confirm it again with you

> Use step functions: No idea about how to use it.

It's an overkill to use step functions for this.

**Comment by Ricardo1980** [comment]
Thanks for your reply @ammarkarachi

Please, let me know about "Invoking a Lambda Function with an Aurora MySQL Stored Procedure (CALL mysql.lambda_async)"

If that approach is not possible, I will follow a micro-services architecture.

Thanks a lot for your help.

**Comment by ammarkarachi** [comment]
@Ricardo1980 Aurora Serverless doesn't support Lambda call, Thanks!

**Comment by Ricardo1980** [comment]
@ammarkarachi Thanks.
Where can I open a request to add that feature?
When creating an information system, this kind of reactive behaviour is common, and right now there is no easy easy way to implement it.
Thanks.

**Comment by ammarkarachi** [comment]
@Ricardo1980 I submitted a ticket to the team directly on your behalf I will inform you of any updates.

**Comment by ammarkarachi** [comment]
@Ricardo1980 I am closing this, don't hesitate to reopen it if you have any other questions
