### ISSUE TITLE
Datastore Question

### ISSUE THREAD

**Issue by pl4yradam** [aws-amplify/amplify-cli#3110]
Are there any guides to using datastore for manual users - im not a fan of using the cli, and also the tutorials are react based, although I get the idea im just wondering if anyone has used it manually, there doesn't seem to be any configurables needed apart from installing it?

Am I missing something? Where does the data store too? is it your federated users device?

**Comment by darrenfurr** [comment]
@Amplifiyer - should it be possible to setup a backend using another IaC beside Cloud Formation & have DataStore work?

**Comment by attilah** [comment]
@pl4yradam there is no documentation page about this, since it is quite complex and the intended usage was through the CLI, but of course there is no "magic", you can use the CLI to learn what is generated and you can write your own CloudFormation templates, resolvers and handwrite the code what we're generating and then use the client library for your chosen platform to run the code.

I'm closing the issue as the question was answered if something new comes up, feel free to re-open it

**Comment by darrenfurr** [comment]
@attilah - that's exactly what I was trying to do. However, I didn't quite understand the purpose of the DataSource dynamodb that is created. I wasn't sure if there was additional resolvers for that.
I'll give it a shot. I'd love to be able to contribute a "terraform" provider to amplify cli, but not real clear on where to start.

**Comment by pl4yradam** [comment]
So the answer here is basically no apart from reverse engineer what the cli
reproduces? Not very helpful that. Ill stick to the sdk as the cli is not
practical.
