### ISSUE TITLE
Questions about pagination when using AppSync with Aurora RDS.

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#3111]
Hello,

I don't see anything about pagination when using Aurora and AppSync in the official documentation:
https://docs.aws.amazon.com/appsync/latest/devguide/appsync-dg%20.pdf

I see a lot of documetation about pagination when using DynamoDB:
https://docs.aws.amazon.com/appsync/latest/devguide/designing-your-schema.html
This `getTodos(limit: Int, nextToken: String): TodoConnection` is using pagination using tokens (cursors instead of offset)
But in the RDS section, there is nothing
https://docs.aws.amazon.com/appsync/latest/devguide/tutorial-rds-resolvers.html
https://docs.aws.amazon.com/appsync/latest/devguide/appsync-dg%20.pdf
The sample project does not use pagination (listPets: [Pet]), that is, if there are 2 million of pets, that's what you receive. That's bad.

Here it is mentioned a way to add cursor pagination with SQL and GraphQL, but it requires incremental ids. In my case, I am using UUIDs in order to use the GraphQL caching system, so, it seems I am stuck.
https://slack.engineering/evolving-api-pagination-at-slack-1c1f644f8e12
Is there any way to solve this?

At this point, I am going to try offset pagination:
I guess I can implement offset pagination following this steps;
Queries like:
```
query {
  products(limit: 10, offset: 20) {
    id
    name
  }
}
```
SQL statements in the velocity resolver like:
```
SELECT * FROM User
ORDER BY createdAt DESC
LIMIT 10 OFFSET 10;
```
And pass limit and offset as parameters from the graphql query to the resolver.

Note: My iPhone app implements infinite scrolling, I don't have to know the number of pages or the total number of items.
I guess I have to stop sending requests when the number of items I receive is less than the number of elements I am requesting, is that correct?

Is my approach right? Given that I cannot implement cursor pagination.
Is it normal not to use anything like Connection in the same way we see in the DynamoDb examples?
Is it OK not to have pagination metadata in the GraphQL response when using this approach?

Thanks for suggestions.

**Which Category is your question related to?**
Paginated collections

**Amplify CLI Version** 
4.2.0

**What AWS Services are you utilizing?**
AppSync and Aurora

**Comment by attilah** [comment]
@Ricardo1980 this is more of a MySQL problem then connected to the CLI or AWS services, I try to help you to solve your problem and provide some guidance on the topic:
From GraphQL perspective, semantically you need to supply the same data what we're using in case of DynamoDB: a token for query continuation and an item count you want to return, this is the same for MySQL too.

By using OFFSET you can run into issues as data grows, and if you search for it you'll see that people are not recommending it as a scalable solution, LIMIT is fine as that's a "cheap" restriction for your query.

Since you don't have an incrementing ID in your table you can't use that for paging in your WHERE clause, so you observation was correct in that as well!

One approach that could work is a query like this:

For first page:
```SQL
SELECT * FROM [User]
ORDER BY createdAt DESC, id DESC
LIMIT $pageSize
```

Further pages:
```SQL
SELECT * FROM [User]
WHERE createdAt<= $createdAt AND id< $id
ORDER BY createdAt DESC, id DESC
LIMIT $pageSize
```

where:
- ```$pageSize``` is your page size :-)
- ```$createdAt``` is the last value you saw in your previous result, these are not guaranteed to be unique, this is your "major" filter component
- ```$id``` is the list value you saw in your previous result, these are unique and sortable in case you'd have the same createAt value for 2 records (there are chances), this is your "minor" filter component

Make sure that you run your and my suggestion through query profiler to see the query plans, required indexes and such, remember to always measure.

So for GraphQL paginated query you need to have $createdAt and $id as optional params and in your resolver logic you can have a branch to determine if it is the first page or not and issue different queries based on the params values are supplied or not. 

I hope it helps and gives you enough to move on with your solution.

A few pointers in the topic:
- https://use-the-index-luke.com/sql/partial-results/fetch-next-page
- https://use-the-index-luke.com/no-offset
- https://www.slideshare.net/Eweaver/efficient-pagination-using-mysql

I'm closing the issue as the question is answered, if something comes up feel free to reopen this issue or open a new one.

**Comment by Ricardo1980** [comment]
@attilah 
Thanks a lot.

I am going to try that.

Some questions. 

Because my createdAt has 3 decimals, I think I don't need to use that id, and even if I see a duplicated element, from time to time, it is not an issue, as my use case is a social network (not a bank).

As far as I understand, my "nextToken" is just the createdAt field, that is, a AWSTimestamp, right?

If I want 10 items per page, I have to retrieve 11, and that 11th element, I use it to get the createdAt, and use it as the nextToken, correct? 
If there is no 11th element, it means there are no more pages, right?
I mean, shouldn't I use `LIMIT $pageSize + 1` instead of `LIMIT $pageSize`

Last question, should I implement that using a Connection type similar to this?:

```
schema {
    query:Query
}

type Todo {
    id: ID!
    name: String
}

type Query {
    getTodos(limit: Int!, nextToken: AWSTimestamp): TodoConnection
}

type TodoConnection {
    todos: [Todo]
    nextToken: AWSTimestamp
}
```

Thank you very much for your help, I appreciate it a lot :)

BTW, how can I measure when using Aurora? Perhaps checking CloudWatch logs?
