### ISSUE TITLE
DataStore generates subscriptions for all @model types

### ISSUE THREAD

**Issue by giovas94** [aws-amplify/amplify-cli#3114]
**Describe the bug**
DataStore generates the subscriptions for onCreate, onUpdate & onDelete of all models. We are trying to disable the subscriptions of certain models because our schema is large and generates more than 50 subscriptions and we do not need all of them.

We add **@model(subscriptions: null)** to disable. The schema compiles correctly and not generates the subscriptions but Datastore expects those not generated subscriptions and returns **Sync Error Subscription failed Connection**

**Expected behavior**
We are trying to avoid some realtime subscriptions in DataStore because of the max 50 subscriptions.

**Screenshots**

<img width="623" alt="Captura de Pantalla 2019-12-28 a la(s) 9 49 51" src="https://user-images.githubusercontent.com/11933312/71545977-6d3f9b00-2957-11ea-949e-e64b12521591.png">

<img width="775" alt="Captura de Pantalla 2019-12-28 a la(s) 9 42 36" src="https://user-images.githubusercontent.com/11933312/71545917-a9263080-2956-11ea-8949-7b0ffc86bb35.png">
<details>
  <summary><strong>Environment</strong></summary>

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
    Memory: 442.50 MB / 8.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 13.3.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 79.0.3945.88
    Safari: 13.0.4
  npmPackages:
    @aws-amplify/core: ^2.2.1 => 2.2.1
    @aws-amplify/datastore: ^1.0.3 => 1.0.3
    @testing-library/jest-dom: ^4.2.4 => 4.2.4
    @testing-library/react: ^9.4.0 => 9.4.0
    @testing-library/user-event: ^7.2.1 => 7.2.1
    aws-amplify: ^2.2.1 => 2.2.1
    aws-amplify-react: ^3.1.2 => 3.1.2
    formik: ^2.0.8 => 2.0.8
    ini: ^1.3.5 => 1.3.5
    inquirer: ^6.5.1 => 6.5.2
    lodash: ^4.17.15 => 4.17.15
    moment: ^2.24.0 => 2.24.0
    prop-types: ^15.7.2 => 15.7.2
    react: ^16.12.0 => 16.12.0
    react-dom: ^16.12.0 => 16.12.0
    react-scripts: 3.3.0 => 3.3.0
    yup: ^0.28.0 => 0.28.0
  npmGlobalPackages:
    @aws-amplify/cli: 4.6.0
    aws-api-gateway-cli-test: 1.3.0
    aws-sam-local: 0.2.8
    awsmobile-cli: 1.1.4
    cloc: 2.5.0
    create-next-app: 0.5.9
    create-react-native-app: 1.0.0
    expo-cli: 3.11.1
    firebase-tools: 3.17.4
    gatsby-cli: 2.5.12
    live-server: 1.2.0
    localtunnel: 1.9.0
    node-gyp: 3.6.2
    now: 15.0.4
    npm: 6.13.2
    npx: 10.2.0
    react-native-cli: 2.0.1
    react-native-git-upgrade: 0.2.7
    serverless: 1.26.1
```

</details>

**Comment by attilah** [comment]
The DataStore sync is a per API capability, so unfortunately you cannot opt-out types from it. Since sync capability depends on subscriptions, you cannot do it today. I mark it as an enhancement to keep track of it.

**Comment by gabrielpoamaneagra** [comment]
Any idea how we can overcome the 50 subscriptions limit ?
@giovas94 did you find a solution/alternative ? 

We would really like to use datastore but this limit ( or the opt-out option ) seems to make it unusable

**Comment by undefobj** [comment]
The 50 subscription default limit is currently under review with the AppSync team to see if it might be raised, however in the interim you can cut a support ticket with your AWS account to ask for a raise. Alternatively you can set `subscriptions: null` as outlined in a similar issue here: https://github.com/aws-amplify/amplify-js/issues/5050#issuecomment-596978353

**Comment by abdielou** [comment]
I've been heavily modifying the DataStore package in order to circumvent these types of issues, and then shipping the custom version into a private registry. For example, there are 2 main issues being discussed here. The first and obvious one is an argument against the DataStore trying to build and subscribe to models that have specifically turned off subscriptions. If you are fine with the consequences, you could modify the source code to skip these subscriptions.

This is the code that will fail the subscription if `owner` was required but not provided. What I do is that, at this same point, I check the schema definition for the current model and validate if the subscription is `"off"`. Works just fine.

https://github.com/aws-amplify/amplify-js/blob/958f61ef2918728cc46b9b210d60e868edd87f39/packages/datastore/src/sync/processors/subscription.ts#L313

Now, you must understand that you are basically turning off Real-Time updates for that model. That will cause a couple of side-effects that you must be fully aware of. I don't think turning off subscriptions bodes well with the goal of the DataStore and can understand if it never makes it as a feature.

The second issue is the subscription limit. This is a though one with the **DataStore**. What I did was to implement a centralized PubSub mechanism (not GQL subscriptions) that would create a single subscription per user, and channel all events through it. On the DataStore I would then inject a `customObservable` object that basically replaces GQL Subscription observables. Events coming from this single **PubSub** will be unpacked and then fed through the `customObservalbe` into the DataStore **SyncEngine**. So, it's basically extracting subscription handling out of the DataStore. The DataStore would still SYNC with a local DB and you keep the simplicity of working with the DataStore.

**Comment by lucaslrf** [comment]
@giovas94 Did you find one solution? 
I have the same problem!

**Comment by 3m** [comment]
Any updates on when this issue might be resolved?  I have a similar issue in that I guess I have too many models.  Even though I turn all of the subscriptions off (null), it still gives subscription error and won't sync unless I manually comment out the models in AmplifyModels.swift (registerModels).

**Comment by felixolivares** [comment]
Are there any updates or further information about this issue, I'm facing the same situation, where I get more that 100 subscriptions and by adding `(subscriptions: null)` to the model definition I get the same warning and most of the times I can not load the data in the Admin UI, it just says:
`There was an error loading your data.
We’d love to address this issue. Please provide your console log and other details here .`

**Comment by josefaidt** [comment]
Hey y'all as mentioned by @undefobj in [this comment on an issue in the amplify-js repository](https://github.com/aws-amplify/amplify-js/issues/5050#issuecomment-632210401), this subscriber limit of 50 has since been doubled to 100. Fortunately subscriptions the user is not authorized to access will fail gracefully and log warnings to the console.

Closing issue based on update provided in the linked, similar issue.
