### ISSUE TITLE
reusing an existing ID field in a connection leads to error: All fields provided to an @connection must be non-null scalar or enum fields.

### ISSUE THREAD

**Issue by AndreasEK** [aws-amplify/amplify-cli#3275]
**Which Category is your question related to?**
AppSync / GraphQL

**Amplify CLI Version** 
4.12.0

**What AWS Services are you utilizing?**
AppSync, DynamoDB, Cognito, S3

**Provide additional details e.g. code snippets**
Given an existing model:

```
type Order
  @model
  @key(
    name: "ByUser"
    fields: ["userId", "createdAt"]
    queryField: "ordersByUser"
  )
  id: ID!
  …
  userId: ID
}
```

Why would the addition of a new connection like this

```
  user: User @connection(fields: ["userId"])
```

Lead to the error: All fields provided to an @connection must be non-null scalar or enum fields.

When adding the connection without the fields parameter, the generated orderUserId would have the same properties as the already existing userId, but it would work with the connection.

**Comment by hirochachacha** [comment]
dup of https://github.com/aws-amplify/amplify-cli/issues/1657

**Comment by AndreasEK** [comment]
Thanks for linking the other issue. I fail to see the connection between these two, though. Without the new user connetion our "Order" was behaving as expected. 'createdAt' was automatically set on creation, as one would suspect. Isn't that what #1657 is about? 

In this issue, I was asking, why adding a connection claims to require non-null scalar fields, while the provided field (userId) has those properties.

**Comment by hirochachacha** [comment]
Oh, sorry for misreading. If I  understand correctly, you pointed that @key and @connection have inconsistency - @key accepts nullable fields, on the other hand @connection rejects nullable fields.
That's not dup of #1657.

**Comment by lenarmazitov** [comment]
I have same issue. 
I have table which have self connected attribute **toId**, which is can be leaved unset, because there is two entities in table: **User**  and **Subscription**.
If I leave it nullable I have error:
**All fields provided to an @connection must be non-null scalar or enum fields**
Otherwise I should set **toId** attribute for **User** entity, but it  will be better to leave it empty and only remember it when I use **Subscription** entity.
```
type Entity
    @model(mutations: null, subscriptions: {level: off})
    @key(fields: ["pk", "sk"]) 
{
    pk: ID!
    sk: String!
    toId: ID
    to: Entity @connection(fields: ["toId"])
}
```

Before it worked fine, but now I can not have @connection with nullable field.

**Comment by mdebo** [comment]
@AndreasEK  I ask myself the same question: why adding a connection require a non nullable field?

**Comment by AndreasEK** [comment]
I read the replies so far as a temporary inconsistency, which hopefully will be resolved at some point.

**Comment by CodySwannGT** [comment]
+1 this is a major oversight and prevents a model from having optional connections

**Comment by mdebo** [comment]
CodySwannGT  Yes really it's really painfull to deal with these kind of oversight.
Having optional connections is often necessary. Imagine I have an application to manage teachers, and each teachers can belongs to a classroom. Actually, how could i create a teacher not linked to a classroom yet? Should I specify a dummy classroomId in the connection field to bypass validation?

**Comment by ajhool** [comment]
@hirochachacha The #1657 issue is related in the sense that it would resolve our problem but this is a separate issue and not a duplicate. This is simply two undocumented issues that result in a catch-22 and prevent basic usage of this framework.

1. You can't make a model's primary ID non-nullable because then you would need to set it on the client side during object creation, as opposed to leveraging AppSync's autogeneration. (#1657)

2. You can't use a connection for a primary ID if the ID is nullable (this issue).

3. Thus, you can't use a model's primary ID if you want to leverage AppSync's autogeneration.

4. Thus, you can't use appsync autogeneration for ID if your API uses the connection directive.

Yet another undocumented issue (notably, every single example from Amplify uses mandatory ID's without ever mentioning that that is, in fact, necessary) that prevents basic functionality and makes the amplify cli experience brutal. If you're running into this issue when creating your first schema, I highly recommend finding an alternative product

**Comment by hirochachacha** [comment]
@ajhool I already stand corrected at https://github.com/aws-amplify/amplify-cli/issues/3275#issuecomment-579203618.

**Comment by elgutierrez** [comment]
Hey, do we have any update on this issue or any valid workaround? It's an important requirement for my app to have optional connections, and simply using `@connection` without `fields` create some other problems for me.

**Comment by jskrt** [comment]
Bump

**Comment by vrambo8** [comment]
I guess a workaround could be having a dummy instance of the type you need to connect to and create that connection when in theory it should be null.

Nonetheless this is a major feature that needs to be implemented ASAP.

**Comment by mattstobber** [comment]
I was creating a nested tree and need to have optional connections.

**Comment by tomhirschfeld** [comment]
bump please, just running into this issue here

**Comment by maximelebastard** [comment]
Same issue here, the API seems inconsistent on that point

**Comment by blydewright** [comment]
To get around this issue, explicitly declare the amplify internally generated FK property as optional (make sure to use their naming convention so it maps the data correctly):

`
orderUserId: ID
user: User @connection
`

The naming convention is: {camel-cased model name - `order`}{property name `user`}`Id`

**Comment by raffibag** [comment]
> @tomhirschfeld
> 
> To get around this issue, explicitly declare the amplify internally generated FK property as optional (make sure to use their naming convention so it maps the data correctly):
> 
> ```
> orderUserId: ID
> user: User @connection
> ```
> 
> The naming convention is: {camel-cased model name - `order`}{property name with capital - `User`}`Id`
> 
> When this property has been explicitly declared, it now becomes available in queries, mutations and filters and can be used in `@key` directives.

Can you please link to the documentation where this is explained (provided it exists)? I tried what you proposed and it didn't work.

**Comment by blydewright** [comment]
@raffibag I didn't find this in any documentation, but figured it out through trial and error. Can you share some code and what you're trying to achieve so I can help?

**Comment by raffibag** [comment]
Thanks, @blydewright - I may have misunderstood the implications of your solution... I was assuming that if implemented correctly, you'd be able to access the association when calling the parent object. In my case (though I was able to figure out another solution that ended up working better for our project), I had two associations under a `Plan` model: `app` and `bundle`. In my code (under the `Plan` model) I originally represented these associations as:

`
appId: ID!
app: App @connection(fields: ["appId"])
bundleId: ID!
bundle: Bundle @connection(fields: ["bundleId"])
`
This, of course, caused the error that's the subject of this thread... So I adopted your strategy and tried: 

`
orderAppId: ID
app: App
orderBundleId: ID
bundle: Bundle @connection
`

The problem was when I tried creating the associations (using a GraphQL mutation), the parent object (Plan) returns `null` for the app and bundle objects. 

Again, I may have totally misunderstood the expected outcome of your solution, but that's why I was asking for a link to the docs.

**Comment by blydewright** [comment]
Hi @raffibag no problem :) We're all trying to figure this out with limited documentation and examples since it's so new!

Glad to here you sorted out a solution. Perhaps it may help to point out a few things in your example code above:

1. Your `orderSparkId` and `orderWidgetId` fields would only work if the model they reside in is called `Order`. But based on what you described, they should be `planSparkId` and `planWidgetId`. The rest of your implementation looks good.
2. Creating/updating by passing the `planSparkId` or `planWidgetId` is the only way I know of that will allow the underlying model to persist the change. The internal resolvers (created due to the `@connection` directive), will take care of building the appropriate `widget` and `spark` data for the graphql payload.
3. Setting things up in this way (using `planWidgetId` and `planSparkId`) is only necessary when needing OPTIONAL relations. Had `spark` and `widget` been mandatory at the time of creating the model, you could have stuck to your original `sparkId: ID!` implementation

Does this help and make sense?

**Comment by raffibag** [comment]
Absolutely, makes sense @blydewright. Thanks for the explanation! I went back and tried it out and it worked perfectly - was able to get the optional associations to show up simply by writing the respective ID to the parent model. I didn't read the previous posts closely enough and assumed "order" was an Amplify directive (or something like that). 

Hopefully this gets documented, as my concern now is that any breaking changes will likely not get relayed to those who used this as a workaround / solution.

**Comment by blydewright** [comment]
Glad it works :) I don't believe that this "workaround" will result in future errors, unless the amplify team change the way they internally name relational IDs. We're simply plugging into their way of doing things to accommodate optional relations which in my opinion should be catered for when defining your own foreign key fields: i.e. using `widgetId: ID` (without `!`) and `widget: Widget @connection (fields: ["widgetId"])`.

Good luck with your development!

**Comment by hutber** [comment]
Oh boy, this is a scary situation as any changes down the road will invalidate my current data. 
Sometimes I really regret using Amplify, other times I think "oh this is seriously cool" But I certainly shouldn't have used it in a production environment
!

**Comment by econtentmaps** [comment]
Yep just hit this, too. +1.

**Comment by blazinaj** [comment]
A dirty way around this is to just provide non-existing IDs for the required ID fields that are null.
```
createPlan {
  widgetID: "thisWidgetIDneverExists"
  sparkID: "thisSparkIDneverExists"
}
```
This (surprisingly) does not cause an error. And when you query Plan, the connections will return null.

**Comment by gregoryforel** [comment]
> The naming convention is: {camel-cased model name - `order`}{property name with capital - `User`}`Id`

Hi @blydewright , I'm trying to implement your solution, I'm halfway there. I am discovering the internals of Amplify right now, created a schema from the Amplify admin UI, and when doing this way, the ids are camel-cased then caps ID, eg: `doctorID`, as opposed to `doctorId`.

Am I missing something? You can see my attempt at implementing your idea in Appointment with an optional patientID field, and `patient: Patient @connection`.

```
type Appointment
    @model
    @aws_iam
    @auth(rules: [{ allow: owner }])
    @key(name: "byPatient", fields: ["patientID"])
    @key(name: "byDoctor", fields: ["doctorID"]) {
    id: ID!
    start: AWSDateTime!
    end: AWSDateTime!
    doctorID: ID!
    patientID: ID #This is where I'm trying to implement your idea 
    doctor: Doctor @connection(fields: ["doctorID"])
    patient: Patient @connection
}

type Patient
    @model
    @aws_iam
    @auth(rules: [{ allow: owner }])
    @key(name: "byOrganization", fields: ["organizationID"]) {
    id: ID!
    legacyPatientId: String
    legacySystem: String
    firstName: String    
    Appointments: [Appointment]
        @connection(keyName: "byPatient", fields: ["id"])
    organizationID: ID!
}

```

It lets me create Appointments without specifying patientID, however, querying the list of appointments returns an empty patient even when I provided the patientID during the creation of the appointment:
```
{
  "data": {
    "listAppointments": {
      "items": [
        {
          "id": "a778269e-f504-4828-9881-03312d311fef",
          "start": "2021-01-06T09:00:00Z",
          "end": "2021-01-06T11:00:00Z",
          "doctorID": "5d7a1734-a317-471e-a470-62dc6479f184",
          "patientID": "95e97098-dbc8-41b8-ba73-b8c66c479b99",
          "owner": "8bb20a0e-6063-43e1-b344-bc55c7cbdfe7",
          "report": null,
          "note": "1er rdv",
          "patient": null
        }
      ]
    }
  }
}
```
Not sure what I'm doing wrong, thanks in advance!

**Comment by yaquawa** [comment]
Thanks @blydewright 
Your solution works for me.
me too was wondering what happens if only use `@connection` without any arguments (https://github.com/aws-amplify/amplify-js/discussions/7593)

The doc given an example like this:
```
type Project @model {
  id: ID!
  name: String
  team: Team @connection
}

type Team @model {
  id: ID!
  name: String!
}
```

But after I saw your solution, I think the doc's example code should be this???
```
type Project @model {
  id: ID!
  name: String
  team: Team @connection
  projectTeamId: ID
}

type Team @model {
  id: ID!
  name: String!
}
```

I'm not should if the doc's example will work(not tried yet), 
There is no description in the doc..
Hope the Amplify team put this in the docs..

**Comment by blydewright** [comment]
@yaquawa no problem :)

You can use the structure as the docs describe without issue. Internally, a field called `projectTeamId` will automatically be created for the mapping to exist. The only real purpose for manually declaring that field (in an optional `@connection` relationship), was if you, like me, want the field to have a specific name so that you can refer to it in some way. I would refer to the field explicitly for defining `@key`s and/or query filtering or other use cases in my app. From my experience, you can only do this if the field is explicitly declared.

If you don't need to refer to the `@connection` field in any way, you can just define your `@model` in the way the docs describe.

**Comment by yaquawa** [comment]
@blydewright Thanks for your kindly explanation! Hop the team can fix this issue too..!

**Comment by edwardfoyle** [comment]
Nullable connection fields are now supported in the latest version of the CLI. Please upgrade to try it out!

**Comment by tomhirschfeld** [comment]
@edwardfoyle yee haw! thanks!

**Comment by anthonymoretti** [comment]
> Nullable connection fields are now supported in the latest version of the CLI. Please upgrade to try it out!

@edwardfoyle I just submitted [#558](https://github.com/aws-amplify/amplify-flutter/issues/558) because in Flutter I'm still having issues with nullable connection fields.
