### ISSUE TITLE
How to handle Amplify auto created DynamoDB table data schema migration...

### ISSUE THREAD

**Issue by DahiyaVipin** [aws-amplify/amplify-cli#3303]
I am using Amplify cli to develop my react/react native app. 

1. The problem that start bothering me is , once you have millions of rows in your Dynamodb table that was auto created by amplify add api command, what process one should follow if I need to update the schema, considering my schema update will impact my users.

Any best practices which is followed by Amplify community ?

**Comment by edwardfoyle** [comment]
Hi @DahiyaVipin, there's no one right answer to this question -- a lot depends on your exact use case. But here are some things to consider...

In general, you should never make backwards incompatible changes to an API once it is in use. Making such changes would typically be done through API versioning so that clients can choose which version to use. Currently Amplify does not have a built-in way to version a GraphQL API.

As long as you are only making additive changes to a model you can safely update the schema. However you would also need to backfill this new field in the database, otherwise an error will occur when fetching that field from an existing entry.

If you are removing a field, changing an existing field type or modifying the primary index of the table these would all be breaking changes and should not be done without thorough testing for your particular use case.
