### ISSUE TITLE
Empty Bucket After Push

### ISSUE THREAD

**Issue by rick-faletto** [aws-amplify/amplify-cli#3307]
**Describe the bug**
Amplify "push"ing a React application with GraphQL creates an empty bucket.

**Amplify CLI Version**
4.11.0

**To Reproduce**

1. Ensure you have:
a) a AWS profile b) awscloudformation as default provider c) a pre-existing React project with GraphQL
2. Navigate to the project's directory
3. amplify configure project
4. name : test | editor : Atom | type : javascript | framework : react | Source : default | Distribution : default | Build : default | Start : default
5. update or remove? : update | profile? : yes | choose : yours
6. amplify env add
7. use existing env?: no | name: test | profile?: yes | choose: yours
8. amplify status returns:
---
 Current Environment: test

| Category | Resource name   | Operation | Provider plugin   |
| -------- | --------------- | --------- | ----------------- |
| Api      | project_name    | Create    | awscloudformation |
| Hosting  | S3AndCloudFront | Create    | awscloudformation |

---
9. amplify push
10. continue?: yes | update code for GraphQL?: yes | generate GraphQL statements?: no
11. after executing successfully, amplify push returns GraphQL endpoint, GraphQL API KEY, and Hosting endpoint
11. Go to S3 web console & click bucket: "This bucket is empty."

**Expected behavior**
Pushing the application results in the associated S3 bucket being populated with the application's build.
So that, for example, Static website hosting can be turned on and the application can be accessed at a URL.

**Desktop:**
 - OS: Windows
 - Node Version: 12.13.1

**Comment by SwaySway** [comment]
Hello @rick-faletto 
Does the bucket get populated after an `amplify publish` ?

**Comment by annasedlar** [comment]
Hi @SwaySway - @rick-faletto and I are on the same team/project but he is rolling off so I can be point-person for this issue. No, the bucket did not get populated after an amplify publish OR amplify push.

**Comment by UnleashedMind** [comment]
@annasedlar @rick-faletto 
According to @rick-faletto 's original description, `amplify push` was executed instead of the `amplify publish`. They are different Amplify CLI commands. 

`amplify publish` is a compound command, it sequentially carries out these steps.
- `amplify push`
- execute the frontend build command, the CLI expect the distribution folder to be filled with the frontend build artifacts
- the CLI uploads the contents in the frontend distribution folder to the S3 hosting bucket

Please run to run `amplify publish` and see if that resolves your issue, if NOT, please check on these: 
- open the `amplify/.config/project-config.json` file, make sure the `"frontend"` configuration is correct for a javascript react project. Note the `"BuildCommand"` and `"DistributionDir"`. The configuration can be changed by executing `amplify configure project`
- manually run the `"BuildCommand"`, see if it fills in the `"DistributionDir"`

**Comment by UnleashedMind** [comment]
Closing the issue due to no response. 
Feel free to open another issue if you still have the problem.
