### ISSUE TITLE
AWS Amplify SDL Transformers vs DynamoDB Best Practices

### ISSUE THREAD

**Issue by andrestone** [aws-amplify/amplify-cli#3311]
**Which Category is your question related to?**
amplify-cli

Hi there,

Aren't the `@model` and subsequent directives a dangerous simplification considering DynamoDB / NoSQL best practices? After reading some material on NoSQL and actually official DynamoDB documentation it is pretty clear that is recommended to always keep the data *as close together as possible* as well as *avoid creating unnecessary tables*.

So, shouldn't Amplify team have considered those statements when designing the `@model` directive? 
Shouldn't there be a system to define relations without necessarily creating a table for each entity, which is pretty much mimicking RDBMS functionality at the API level and pushing that effect (multiple tables) to DynamoDB?

By the way, if I'm completely off track here, also please let me know.

Thanks.

**Comment by ambientlight** [comment]
@andrestone: please refer to https://github.com/aws-amplify/amplify-cli/issues/2071#issuecomment-522272663

**Comment by RossWilliams** [comment]
Aside from the Cloudformation team, AWS in general does not share feature roadmaps or timelines, so I don't know what AWS is planning. The linked comment above may have been accurate at the time, but also sometimes the right design takes awhile to emerge. Good single table designs are possible with graphql and do allow flexibility; I have been working on an alternative to the @key, @connection, and @model directives to support a single table design by using adjacency list patterns and automated denormalisation of models. Performance is drastically improved, but its not without trade-offs, and some of these may be unsatisfactory to the Amplify project.

I'd also be careful in thinking that "Single Table Design" means just combining all data into a single table. There are very few performance gains from simple using a single table. The gains come structuring data so that all the data you want is logically sorted to be next to each other. I like to imagine dynamodb as a VHS tape library. You can tell it which tape to insert into the player (partition key), which position to move the tape into (sort key), and you get to play the tape for 1 second forwards or backwards (scan index forward up to 1MB). Single table design requires capturing everything you need to satisfy the query within that 1 second play window, and hitting the play button as few times as possible, ideally once.
