### ISSUE TITLE
GraphQL transform - warns when owner is missing

### ISSUE THREAD

**Issue by mlecoq** [aws-amplify/amplify-cli#3325]
Hi,

I have created the following model 

```gql
type Project @model @auth(rules: [{ allow: owner }]) {
  id: ID!
  """
  Title of the project.
  """
  title: String!
  """
  Description of the project
  """
  description: String
}
```

Have made the generation (`amplify push`) and I use it with DataStore. 

This works fine for querying, saving but fails when I try to observe (see https://github.com/aws-amplify/amplify-js/issues/4810)

Could CLI warn us when owner field is missing (or other fields related to @auth directive) ?

**Comment by tomrum** [comment]
I too am having a lot of problems here. My schema:

type Video @model {
id: ID!
video: String!
links: [BuyLink] @connection(keyName: "buyLinks", fields: ["id"])

_version: String
_lastChangedAt: String
_deleted: String
}

type BuyLink @model( subscriptions: { level: public }), @auth (rules: [
{allow: owner, operations: [create, update, delete, read]}]),
@key(name: "buyLinks", fields: ["videoId", "link", "second"])  {
id: ID!
videoId: ID!
link: String!
second: Int!
votes: [Vote] @connection(keyName: "votes", fields: ["id"])
show: Boolean!
owner: String
_version: String
_lastChangedAt: String
_deleted: String
}

type Vote @model
@key(name: "votes", fields: ["BuyLinkId", "vote"]) {
id: ID!
BuyLinkId: ID!
vote: Int!

_version: String
_lastChangedAt: String
_deleted: String
}

Get error message : Sync error subscription failed Connection failed: {"errors":[{"message":"Validation error of type UnknownArgument: Unknown field argument owner @ 'onDeleteBuyLink'"}]}

There is no owner on onDeleteBuyLink in the generated code.

Also get errors if I don't supply:

_version: String
_lastChangedAt: String
_deleted: String

on @models, I thought this should be automatic

Plus many other issues. Thinking of abandoning this framework because of lack of helpful error messages or non at all/bugs

**Comment by kbanashek** [comment]
Any update on this issue? I'm facing the same issue.

**Comment by josefaidt** [comment]
Closing as this issue has since been resolved. Today, the GraphQL Transformer will automatically create an `owner` field and add it to the necessary input types.
