### ISSUE TITLE
Primary Index with Sort Key requiring sort key field to be used when it should not be

### ISSUE THREAD

**Issue by malcomm** [aws-amplify/amplify-cli#3347]
**Please note:** this is a blocker.

**Describe the bug**
Given the following schema:
```
type Foo
  @model
  @key(fields: ["id", "updatedAt"])
{
  id: ID!,
  updatedAt: AWSDateTime!
```

The get on the generated code is requiring the sort field to be supplied:

```
  async GetFoo(
    id: string,
    updatedAt: string
  ): Promise<GetFooQuery> {
```
```updatedAt``` should not be used on the main getter at all.

**Amplify CLI Version**

4.13.1

**To Reproduce**

Create a model with above primary index with a sort key.

**Expected behavior**

see above

**Additional context**

amplify-cli, DynamoDB, AppSync

**Comment by SwaySway** [comment]
Hello @malcomm 
These fields are normally not mandatory however when you add `@key` the fields listed in that directive then become mandatory. Since we do auto-populate the fields for id, createdAt, and updatedAt we can potentially add these in a whitelist when adding `@key` so they are not set to nonnullable.

**Comment by malcomm** [comment]
@SwaySway - Just to be sure, you are saying that to get a single record by index, you are requiring that they send in the sort key?

In my mind, the sort key should not be involved the ```GetFoo``` method. Take my example, I have a primary key of ```id``` and then a sort key of ```updatedAt```.  So in order to get a record, I would have to not only know the ```id``` but also the date it was updated? This doesn't make sense to me.

**Comment by edwardfoyle** [comment]
Hi @malcomm when performing a get operation on a DynamoDB table, if the primary key has a partition key and sort key (which this table does because two fields are specified in the @key directive) then both must be specified on a get operation. For more information regarding that, you can take a look at the DynamoDB docs for GetItem [here](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_GetItem.html).

It seems to me that in your use case you should have a single "id" as the primary key and a compound GSI with partition key `__typename` and sort key `updatedAt`. In terms of a graphql schema, this would look like
```graphql
type Foo @model 
  @key(name: "byTypeUpdatedAt", fields: ["__typename", "updatedAt"], queryField: "byUpdatedAt") {
  id: ID!
  __typeName: string!
  updatedAt: AWSDateTime!
}
```
There are still a couple things that will be odd about this. One, it doesn't solve the problem that you mentioned in #3348. The solution there will be for us to add overrides to all autogenerated fields to make them not required on create / update operations. The second is that specifying `__typename` in the byUpdatedAt input is a bit redundant but it's a byproduct of how [DynamoDB Query](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html) operations work

**Comment by malcomm** [comment]
Interesting. So this whole thing got kicked off because of #3331. Basically I tried to do this:

```
type Foo
  @model

  @key(name: "FooStatusUpdatedAt", fields: ["status", "updatedAt"], queryField: "fooStatusUpdatedAt")
{
  id: ID!,
  updatedAt: AWSDateTime,
  status: PublicationStatus,
```

But there's no way that I was able to see to search on multiple status values. On #3331 you can see the discussion there and the issues related to this. Basically, at this time, the code generated or limitations of system put me in a corner for how to do this.

That's what led me to putting a default sort key on the table. Having a table indexed by a date seems like a pretty common use case and I'm trying to understand why someone would be forced to supply a Date when trying to get a single item. I mean, the whole reason for supplying a sort key of a date (in a lot of cases) is to make list queries more efficient and do what we want.

I'm perfectly OK with not putting the sort key on the primary index, but then can we look at #3331 so that I can search on multiple values?

**Comment by edwardfoyle** [comment]
@malcomm Can you explain what your use cases are? For example, "get all Foos updated in the past week with publication status = PENDING". I think there's probably a way to do what you are trying to do, I just need more context into what the query patterns are going to be.

As an aside, you certainly can have updatedAt be the sort key for the primary index and run queries against that index but then you lose the ability to get a single entity without specifying the updatedAt value.

**Comment by malcomm** [comment]
@edwardfoyle - sure thing. I will have a few use cases related to this, but my current use case is that I need all the most recent Foos that do not have 3 statuses (draft, inactive or unknown) and then limited by a date. Here are my statuses:

```
enum PublicationStatus {
  draft
  submitted
  reviewed
  modified
  resubmitted
  verified
  inactive
  unknown
}
```

**Comment by malcomm** [comment]
@edwardfoyle - I liked your ```__typeName``` workaround and was hoping to use it; however, I got this error when trying to do that:

```
Name "__typeName" must not begin with "__", which is reserved by GraphQL introspection.
An error occured during the push operation: Name "__typeName" must not begin with "__", which is reserved by GraphQL introspection.
```

This is with a schema with this:

```
type Foo
  @model
  @key(name: "byTypeUpdatedAt", fields: ["__typename", "updatedAt"], queryField: "byUpdatedAt")
{
  id: ID!,
  __typeName: String!
```

**Comment by malcomm** [comment]
@edwardfoyle - ok thank you for that.

Any input on allowing for multiple statuses on this type of key:

```
@key(name: "FooStatusUpdatedAt", fields: ["status", "updatedAt"], queryField: "fooStatusUpdatedAt")
```

I could avoid all this if I could just search on multiple status fields.

**Comment by edwardfoyle** [comment]
@malcomm Unfortunately that's a limitation of DynamoDB queries. The primary key of a query can only be an equality operation. You can read more about DynamoDB queries [here](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html).

The only way to do what you are suggesting is to do multiple queries, but even then I don't think that solves your use case because you need to find entities where status is NOT equal to certain values rather than equal to.

**Comment by karldanninger** [comment]
Hey @edwardfoyle I'm just coming across this now and have similar needs. Could you point me in the direction of how to make a resolver to just set `type` to something on all creations/updates?

(never made a resolver before)

**Comment by edwardfoyle** [comment]
Hi @karldanninger you can read our docs on custom resolvers here: https://docs.amplify.aws/cli/graphql-transformer/resolvers#custom-resolvers

The easiest way to get started is probably to copy the autogenerated resolver from `backend/api/<yourAPIName>/build/resolvers` into the custom resolvers folder in `backend/api/<yourAPIName>/resolvers`. Then modify the resolver to unconditionally set the type field. You can mimic the way that the resolver sets the __typename field already:
```vtl
$util.qr($context.args.input.put("__typename", "Todo"))
```
