### ISSUE TITLE
Error: Local mocking does not support AWS_LAMBDA data source that is not provisioned in the project.

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-cli#3362]
**Is your feature request related to a problem? Please describe.**
Getting the following error: 

> Error: Local mocking does not support AWS_LAMBDA data source that is not provisioned in the project.

which causes mocking to fail to start. 

**Describe the solution you'd like**
Warn that the function is not local and continue to start up local mocking. 

**Describe alternatives you've considered**
commenting out that code when testing locally.

**Comment by MontoyaAndres** [comment]
Any news about this? :(

**Comment by sbue** [comment]
Bump on this!

**Comment by yuth** [comment]
When using `@function` directives in your schema, in order to use an function that is added in the project, you will have to [add](https://docs.amplify.aws/cli/usage/mock#function-mocking-setup)  `-${env}` to the function name. Mock supports functions that are added using the Function category and does not support the functions that were added in a different project

```gql
type Query {
  echo(msg: String): String @function(name: "echofunction-${env}")
}
```

Feel free to comment here if the mock is not working with `-${env}` in the function name.
