### ISSUE TITLE
Commit 4fb26498 is the last that actually passes `yarn test`

### ISSUE THREAD

**Issue by kevcam4891** [aws-amplify/amplify-cli#3364]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I cannot successfully run `yarn test` on any commit after `4fb26498c6eb266ffe11bdb276f5e91a46f1f65d`

**Amplify CLI Version**
Usually 4.12

**To Reproduce**
Check out any commit made after 4fb26498c6eb266ffe11bdb276f5e91a46f1f65d, then run `yarn clean && yarn production-build && yarn test`. To be clear, commit 4fb26498c6eb266ffe11bdb276f5e91a46f1f65d PASSES. Commit a8cdac5aabc3bf7cc2457b1cd0d454b6e4e4bfa2 and beyond fail for me.

**Expected behavior**
All tests run, complete, and PASS.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v12.11.1

**Additional context**

**Comment by attilah** [comment]
@kevcam4891 please make sure that you're running a ```git clean -fdx``` on your repo, since one thing changes in recent commits, we're not compiling tests anymore and it can happen that you're running stale test code from the ```lib``` folder of your enlistment.

```yarn test``` running as part of the pre-commit/pre-push hooks that's the reason I can think of stale files. I just ran it on prod build and clean repo and the tests are passing on the latest master.

Please get back to us with the result.

**Comment by kevcam4891** [comment]
@attilah Success! Thank you sir 😃
