### ISSUE TITLE
Query: Nested List Items Return Empty 

### ISSUE THREAD

**Issue by anarerdene** [aws-amplify/amplify-cli#3436]
** Which Category is your question related to? **
@key with @connection.
** What AWS Services are you utilizing? **
AWS AppSync
** Provide additional details e.g. code snippets **
Im Using @key but nested list return empty ?

this is my schema:

![image](https://user-images.githubusercontent.com/2210568/74571199-755fa280-4fb8-11ea-88c4-79ba09d18fe5.png)

and this is result:

![image](https://user-images.githubusercontent.com/2210568/74571300-988a5200-4fb8-11ea-9472-11f22dd6b006.png)

PS: I also tested with filters and my mex depth is 6

**Comment by attilah** [comment]
@anarerdene I created the API with the schema you shared above:

```gql
type Shop
  @model
  @auth(rules: [
    { allow: private },
    { allow: public, provider: iam, operations: [read] }
   ]) {
    id: ID!
    title: String!
    slug: String!
    categories: [Category] @connection(keyName: "byCategory", fields: ["id", "slug"])
}

type Category
  @model
  @key(name: "byCategory", fields: ["shopId", "slug"])
  @auth(rules: [
    { allow: private },
    { allow: public, provider: iam, operations: [read] }
   ]) {
    id: ID!
    shopId: ID!
    title: String!
    slug: String!
}
```

And used the following mutations to populate the data:

```gql
mutation Create {
  S1: createShop(input: {
    id: "S1"
    title: "Shop1"
    slug: "shop1"
  }) {
    id
  }

  S1C1: createCategory(input: {
    id: "C1"
    shopId: "S1"
    title: "S1C1"
    slug: "category-s1c1"
  }) {
    id
  }

  S1C2: createCategory(input: {
    id: "C2"
    shopId: "S2"
    title: "S1C2"
    slug: "category-s1c2"
  }) {
    id
  }

  # Correct data with matching slugs

  S2: createShop(input: {
    id: "S2"
    title: "Shop2"
    slug: "shop2"
  }) {
    id
  }

  S2C3: createCategory(input: {
    id: "C3"
    shopId: "S2"
    title: "S2C3"
    slug: "shop2"
  }) {
    id
  }

  S2C4: createCategory(input: {
    id: "C4"
    shopId: "S2"
    title: "S2C4"
    slug: "shop2"
  }) {
    id
  }
  
}

query List {
  listShops {
    items {
      id
      title
      slug
      categories {
        items {
          id
          shopId
          title
          slug
        }
      }
    }
  }
}
```

The behavior you see is by design, since you specify the `slug` field as part of the key component, which means that it will be matched between `shop` and `category` together with `shop`s partition key. I assume that it is different what you meant by including the `slug` field in the `@key` definition and the value of the `slug`s are different between `Shop` and `Category`.

If you execute the `listShops` query above, you'll notice that `shop1` will have no `Category` items, since the slug is mismatching between those, but `shop2`, will list its `Category` items correctly as the `slug` value `shop2` is matching as well.

If you have a suggestion about how could we make this behavior more clear in our documentation, please share it with us.

**Comment by attilah** [comment]
Closing due to lack of response, please comment if you can provide some feedback on how could we enhance the documentation around `@key`.
