### ISSUE TITLE
Usage question about "has many" relationships 

### ISSUE THREAD

**Issue by amirmishani** [aws-amplify/amplify-cli#3471]
**Which Category is your question related to?**
Amplify API - GraphQL

**Amplify CLI Version** 
4.10.0

**Question:**
I'm using slightly modified code from the [documentation.](https://aws-amplify.github.io/docs/cli-toolchain/graphql?sdk=js#connection) I have two questions. 

1. Is it ok to use the same keyName `byPost` in the Post model since the secondary index name is being set on Comment and Rating models. Will there be conflict? 

2. Does the connection respect hash and sort composite keys? Would the following connections work out of the box? 

Like so: 
`@connection(keyName: "byPost", fields: ["tenant_id", "id"])`

Where as the documentation is using only a hash key: 
`@connection(keyName: "byPost", fields: ["id"])`

**Code snippet:**
```graphql
type Post @model 
  @key(fields: ["tenant_id", "id"]) {
  tenant_id: ID!
  id: ID!
  title: String!
  comments: [Comment] @connection(keyName: "byPost", fields: ["tenant_id", "id"])
  ratings: [Comment] @connection(keyName: "byPost", fields: ["tenant_id", "id"])
}

type Comment @model
  @key(fields: ["tenant_id", "id"])
  @key(name: "byPost", fields: ["tenant_id", "postID", "content"]) {
  tenant_id: ID!
  id: ID!
  postID: ID!
  content: String!
}

type Rating @model
  @key(fields: ["tenant_id", "id"])
  @key(name: "byPost", fields: ["tenant_id", "postID", "userID"]) {
  tenant_id: ID!
  id: ID!
  postID: ID!
  userID: ID!
  rating: String!
}
```

**Comment by attilah** [comment]
@amirmishani the schema you supplied is invalid and not compiling:
- comments and ratings @connection has a partial field listing, does not match the field list on the other side of the connection, if you try to compile with the latest CLI you'll get `InvalidDirectiveError: Invalid @connection directive  comments. fields does not accept partial sort key` error.
- ratings has the wrong type as it `[Comment]`, I guess that's a typo only.

> Is it ok to use the same keyName byPost in the Post model since the secondary index name is being set on Comment and Rating models. Will there be conflict?

Technically not, because the field types are different and those are being matched when looking up connections, but I'd advise against it, later it can create confusion.

> Does the connection respect hash and sort composite keys? Would the following connections work out of the box?

I'd recommend to use the newer construct `@connection` with `@key`, and yes you can have composite keys. The fields from the 2nd field will be concatenated which enables richer filtering and queries for the given type through the GSI. For more information check the documentation here: https://aws-amplify.github.io/docs/cli-toolchain/graphql#connection

I'm closing the issue as the question has been answered, feel free to reopen it if something new comes up or open a new issue.

**Comment by marianolc** [comment]
Just if someone find this issue... I solved using the following model:

```
type Post @model 
  @key(fields: ["tenant_id", "id"]) {
  tenant_id: ID!
  id: ID!
  title: String!
  comments: [Comment] @connection(keyField: "tenant_id", sortField: "id")
}

type Comment @model
  @key(fields: ["tenant_id", "postID", "content"]) {
  tenant_id: ID!
  id: ID!
  postID: ID!
  content: String!
}

```
