### ISSUE TITLE
Case insensitive user pools?

### ISSUE THREAD

**Issue by claym** [aws-amplify/amplify-cli#3494]
**Which Category is your question related to?**
Auth 

**Amplify CLI Version** 
14.13.4

**What AWS Services are you utilizing?**
Cognito

Per [this article](https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-cognito-user-pools-service-now-supports-case-insensitivity-for-user-aliases/), newly created user pools are created to have case-insensitive usernames. Manually created pools have this enabled by default.

However, pools created through amplify push do NOT have case insensitive pools. How do I enable case insensitivity for new or existing pools (i expect the latter is not possible)?

**Comment by ammarkarachi** [comment]
@claym We don't have this feature available on CLI but it's scheduled for release. For the time being you can enable it in the Cloudformation template more information can be found at https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html under _UsernameConfiguration_

**Comment by claym** [comment]
```
      UsernameConfiguration:
        CaseSensitive: false
```

That worked. Thanks!

**Comment by xitanggg** [comment]
I received the error "Updates are not allowed for property - UsernameConfiguration" when perform `amplify push` after adding this to my .yml file manually.

**Comment by simeon-smith** [comment]
It's not really feasible for me to remove auth and recreate it. Is there a fix for https://github.com/aws-amplify/amplify-cli/issues/3494#issuecomment-598194358 that doesn't require that?

**Comment by alexandprivate** [comment]
Hi there guys, any update on this? The User Pool create via Amplify CLI is yet with the "Enable case insensitivity for username input" unchecked and disabled to be marked, any ideas?

**Comment by meducati** [comment]
Please help (any kind soul out there)!

I tried the above solution on my "test" env. (Also have dev+prod).

1. I removed Auth -> userPoolGroups (I still have another Auth (labelled cadcognito))
2. Tried the changes (UsernameConfiguration: CaseSensitive: false). It did not work. (This is not my concern)
3. Tried to revert back by:
- a) first adding userPoolGroups back and when that didn't work
- b) pull my dev env and push that into my test cloudformation.
4.  "Amplify status" now says it wants to Create userPoolGroups , but when I try I get the following error:
UPDATE_FAILED               authcadcognito          AWS::CloudFormation::Stack Thu Aug 06 2020 11:15:26 GMT+0200 (GMT+02:00) Parameters: [allowUnauthenticatedIdentities, identityPoolName, thirdPartyAuth] do not exist in the template

I have checked both in console and locally and allowUnauthenticatedIdentities, identityPoolName, thirdPartyAuth all exist in the template.

I´d like to save my test env if possible but not required, but more alarmingly, amplify now wants to make updates to both my dev and prod envs... so I am afraid that when I do my next push to dev or prod (which are working ok now), amplify will insert the same error that now is crashing test.... :/

I want things back they were before trying this :(

Is there a way to either:
1. Pull my production env, and add+push to a new "test2" environment, and will this remove any requests from amplify to want to commit changes to my prod env in the future?
2. If I create "test2", is there an easy way to transfer my dynamodb-data from test to test2?
3. Would another attempt to remove BOTH  userPoolGroups AND cadcognito and repush possibly work? I am a bit afraid of "update api" at this point, since I have a running prod with clients :/ (Is there a way to print the current api settings?)

I´ve spent 1+ week on this and still feel lost

**Comment by alexandprivate** [comment]
I'm getting the same 400 error when adding the UsernameConfiguration

```
Resource Name: us-east-1_24x1azsMU (AWS::Cognito::UserPool)
Event Type: update
Reason: Updates are not allowed for property - UsernameConfiguration. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: null; Proxy: null)
```

**Comment by devpresleycobb** [comment]
I just ran into this issue and for me the problem was you cant update this setting after the pool has been created. 
From docs: "This configuration is immutable once it has been set." 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html#cfn-cognito-userpool-usernameconfiguration

Once I deleted my cloudformation stack and deployed the stack again it all worked.

Hope this helps

**Comment by bmw46033** [comment]
I removed Auth, then added it back.

I am using React JS.  The backend file is a JSON and not a YML.  After I edit the JSON and add:

"UsernameConfiguration": {
  "caseSensitive": false
}

After I save the file and issue an "amplify push", I notice that the file reverts back to what is pulled from the backend.  I tried to update the YML file in S3 but that didn't seem to work.

1. Can you tell me when you plan to add the option for case sensitive to the CLI?
2. The workaround mentioned adding it manually here doesn't seem to work.

**Comment by josefaidt** [comment]
Hey folks :wave: this feature has since been released and can be toggled behind the [`enablecaseinsensitivity` feature flag](https://docs.amplify.aws/cli/reference/feature-flags/#enableCaseInsensitivity). Closing 🙂
