### ISSUE TITLE
Why does lastPushTimeStamp update on env checkout?

### ISSUE THREAD

**Issue by chrisco255** [aws-amplify/amplify-cli#3555]
**Which Category is your question related to?**
env

**Amplify CLI Version** 
4.13.4

**What AWS Services are you utilizing?**
AppSync, Console

**Provide additional details e.g. code snippets**
I've set up `master` and `dev` branches in Console, with environments `master` and `dev` respectively.

When I develop locally, I follow the pattern in the documentation. I will `git checkout master` then `amplify init` and point it to the `master` env. I'll then switch back to `git checkout dev` and then `amplify init` with `dev` as an env. Whenever I do that, the CLI modifies the `amplify-meta.json` file with an updated timestamp on the `lastPushTimeStamp` property.

This is annoying when switching between environments with no changes. It forces me to either commit the changes to `amplify-meta.json` or `git reset --hard` to ignore the automatic change. 

Is this field update absolutely necessary? What are the implications of ignoring that change? Why doesn't it update only on `amplify push`?

**Comment by attilah** [comment]
@chrisco255 The `amplify-meta.json` file is part of the `.gitignore` file it should not be checked into source control, so the update of it would not be a problem. I tried the use case you were specifying and because it is ignored I had no problems switching between branches and such.

Is there a particular reason why you don't have it in your `.gitignore` file?

**Comment by chrisco255** [comment]
It's not in my `.gitignore` file. I can definitely add it, I'm not sure why the CLI setup didn't augment my file with that.

**Comment by attilah** [comment]
If you initialize the project with `amplify init` for the first time, the CLI creates a `.gitignore` file with these entries:

```
#amplify
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/mock-data
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
build/
dist/
node_modules/
aws-exports.js
awsconfiguration.json
amplifyconfiguration.json
amplify-gradle-config.json
amplifyxc.config
```

If you create your app through `amplify-app` then this step is not done, because it can be inside existing project and such.

Add these entries to your `.gitignore` and remove from the above files from source control and you will not see the issue.
