### ISSUE TITLE
amplify add codegen : choosing code generation language.

### ISSUE THREAD

**Issue by blomm** [aws-amplify/amplify-cli#3674]
**Which Category is your question related to?**

amplify add codegen

**Amplify CLI Version** 

4.2

I'm working on an Angular project, and I'm a bit confused about which choice I should go with for my code generation language target? Two options are angular and typescript

angular is written in typescript, I really have no clue which one to choose (apologies if I'm being thick)

**Comment by yuth** [comment]
Codegen for Angular generates a service  where as typescript just generates the typings

**Comment by UnleashedMind** [comment]
Closing the issue.
You can still comment on it if needed.

**Comment by rob3c** [comment]
While it's true the angular codegen technically generates an angular service, it does so using the very un-angular and incompatible zen-observable library for its graphql subscriptions!

As anyone who has used angular at all in the past several years knows, `rxjs` has been a deeply-ingrained part of angular for a long time now. Using anything else for observables in generated services meant to be used with angular is pretty ridiculous. Not only do we have to load an unnecessary (and inferior IMO) extra observable implementation, it's completely incompatible with the one used everywhere else throughout angular.

It's obvious from all of the docs, samples and blog posts that the amplify team heavily favors react over angular (or anything else). The fact that they don't even bother to use rxjs for the token angular support is incredibly disappointing and suggests caring more about getting the library name in the marketing descriptions rather than actually providing a truly 'native' angular experience.
