### ISSUE TITLE
Guide/documentation on using appsync in lambda

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-cli#3720]
**Which Category is your question related to?**
Auth, Appsync, Datastore, lambda

**What AWS Services are you utilizing?**
Cognito, AWS AppSync, Datastore, Lambda

**Provide additional details e.g. code snippets**
First of all I want to thank you for adding built in support for dynamodb streams. Using this will make delta sync much more easier and automatic.

However I do not see any documentation on how make graphql request with lambda. All my attempts resulted in massive failure because I was thinking there is no difference between Node.js environment and browser environment. Apparantly there is big difference.

Few things to keep in mind. I use auth with admin queries and Datastore. So I want to make sure I won't have any issues with auth restriction at lambda side and any changes I make should be automatically synched with client. Is there anything extra that needs to be done besides updating records to ensure changes are synched with client?

**Comment by apoorvmote** [comment]
I found code on #1678 and even though its unofficial it works. 

But its rediculous why are we using low level `aws-sdk` and creating post request and writing our own headers in official documentation. Its absolutely crazy to me. Why not recommend using`aws-amplify` in official documentation or at very least `aws-appsync` and `graphql-tag`. 

Is this about performance or something?

Because I was using 128 memory lambda and my memory usage was about ~100 mb each time.  So I bumpted it to 256 memory lambda just out of fear of lambda crashing. There is no improvement on time it takes to finish task. Just cost's me twice of the previous.

So is the `aws-sdk` will save me money in lambda cost than using `aws-amplify` or `aws-appsync`?

**Comment by undefobj** [comment]
`aws-sdk` is built in to the Lambda runtime which means you don't have to manage dependencies which you would need to do with other solutions like `aws-appsync` and `graphql-tag`. 

Amplify libraries such as the API category are not supported in NodeJS as this time and would add overhead as well and dependency management. The link in our documentation is the lowest level and most performant route you can go.

**Comment by apoorvmote** [comment]
I tested both `aws-amplify` & `aws-appsync` with `graphql-tag`. Both are working fine in nodejs environment with lambda. And I will be using `aws-amplify` for my production. It only requires `lodash` to be installed as dependancy. So far no problems.

**Comment by 24jr** [comment]
@apoorvmote hey you seem knowledgeable about this. Did you get working? You prob saw where I'm at in trying to get this working in the issue you linked to above. If you got it working would you mind sending your lambda code if not a problem? Thanks!

**Comment by apoorvmote** [comment]
> @apoorvmote hey you seem knowledgeable about this. Did you get working? 

@24jr Yes I did get it working. But I am absolutely not knowledgeable about it. I did lots of trial and error. And somehow it works. Even though officially its not recommended. 

The official answer is go to https://aws-amplify.github.io/docs/cli-toolchain/quickstart#graphql-from-lambda

> but there's no like terminal to install stuff right? if so what do I type and where?

Yes with terminal you need to go inside lambda src folder. Then type `npm i aws-amplify lodash`.
Then right next to mutation or query input variables add `{authMode: 'AWS_IAM'}`
At the top of the page add `const Amplify = require('aws-amplify')`
Inside lambda initialize the Amplify like this
```
const region = process.env.REGION
const apiTrystGraphQLAPIEndpointOutput = process.env.API_TRYST_GRAPHQLAPIENDPOINTOUTPUT
Amplify.default.configure({
    aws_appsync_graphqlEndpoint: apiTrystGraphQLAPIEndpointOutput,
    aws_appsync_region: region,
    aws_appsync_authenticationType: 'AWS_IAM'
  })
```
make sure to use your own graphql endpoint not copy paste mine.

**Comment by 24jr** [comment]
@apoorvmote how do I find the terminal? I'm just in the lambda page on aws website not in like vs code or something. Also, I think the other example was using app-sync not amplify but I think amplify is prob better. And you're using a different auth method here I think which makes no difference to me for my case. In which case though, if you don't mind could you send your complete lambda function code. I could prob piece it together on my own but may take me like a week haha. And thanks for response!!

**Comment by apoorvmote** [comment]
@24jr  I am not sure what your situation is. 
1. It seems like you are more comfortable with `aws-amplify` but you are adding lambda manually from aws website. 
1. You keep mentioning the other example that is lambda function added along side amplify project (not done manually from aws website lambda section like you are doing) and is backed by REST API.
1. And I am doing neither of things from above. I am using dynamodb stream for data aggregation. 
1. As per the auth issue. Only this lambda function has permission to connect to API with IAM credentials. My guess is you are hard coding admin user name and password into lambda and using cognito to access API or hard coding API key. Both solutions are flawed. Because these things may end up in git repo and can be accessible by anyone inside your team.

The rest of the lambda code is not relevent to the problem and even if I did share it then it will not help you.

**Comment by 24jr** [comment]
@apoorvmote Yeah I am more comfortable with aws-amplify for sure from my web app I've just never used it from lambda. I guess I just use it the same way most likely then.

Well I created the DynamoDB table from my GraphQL schema in the app and did amplify push. I what to get a stock price and add it to the table every minute using a cloud watch function that triggers it every minute. I figured out how to add it directly to the dynamodb table but if instead I can use GraphQL to add the item to the table then my app will have the ability to subscribe to the new created items.

My app doesn't need to interact with the lambda function in anyway and I haven't really made lambda functions in the CLI with my app and was more comfortable just going to my account on aws website and making function on that where I can easily ass env variables, adjust time limit, permissions, etc. Just figured best for me to do it straight from lambda console. (Although still not sure where people would run like `npm i aws-amplify lodash` in aws website or if its different there.

I don't need like an owner field for the items because their just prices and I want everybody to be able to query them so it doesn't matter to me if I get authenticated through an app user that has Admin access to create to the graphql or IAM which I think is just when I click the existing role and add a policy allowing idk something like AppSync access or something. 

I didn't know about your brought up auth issues. Yes I was going to just have the Cognito username and password set as environment variables and used in function. But also if lambda isn't necessarily associated with app could anyone see it? Also, I am just a team one right now anyway.

As for understanding the code I know to make the code to sign people in and create a grapple mutation from my app with aws amplify but I have never done it on lambda and also need to write in the code so the lambda connects to my specific apps graphql stuff. These are intricacies I'm not quite sure how do and expect to find very little online for so there is a chance I never figure it out and try some other method as I am new to this way of doing it.

It does sound like you are using this in a different way though and perhaps most of it won't help me and I don't expect you to send anything you don't feel comfortable sending or find relevant. But yeah for me pretty much anything helps and I appreciate your communication thus far as its been very helpful!
