### ISSUE TITLE
compiled String return type does not match actual return type

### ISSUE THREAD

**Issue by jnathanh** [aws-amplify/amplify-cli#3853]
**Describe the bug**
The compiled typescript API query return type does not match the actual data returned for the echo lambda example.

**Amplify CLI Version**
4.17.2

**To Reproduce**
On an angular 8 amplify project
Follow this example: https://aws-amplify.github.io/docs/cli-toolchain/graphql#usage-1
`amplify mock` to create the API.service.ts
compare `APIService.Echo` return type (`string`) to actual data type returned (`{echo: string}`)

**Expected behavior**
The generated APIService method return type should match the actual return type.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v13.12.0

**Comment by akshbhu** [comment]
Hi @jnathanh 

Is the APIservice query returning null type with an error in GraphiQL explorer?
Try the above function handler with a JSON parse statement to see if that works i.e.
```javascript
exports.handler = function (event, context) {
  context.done(null, JSON.parse(event).arguments.msg);
};
```

**Comment by nhanna-suplari** [comment]
> Hi @jnathanh
> 
> Is the APIservice query returning null type with an error in GraphiQL explorer?
> Try the above function handler with a JSON parse statement to see if that works i.e.
> 
> ```js
> exports.handler = function (event, context) {
>   context.done(null, JSON.parse(event).arguments.msg);
> };
> ```

@akshbhu, I didn't observe any issue with a null type. The problem is the js API codegen. For the schema
```
type Query {
  echo(msg: String): String @function(name: "echofunction-${env}")
}
```
with return type string, and the lambda (the default created by `amplify add function`)
```js
exports.handler = function (event, context) {
  context.done(null, event.arguments.msg);
};
```
which also returns a string, and the codegen API function `Echo` looks like
```js
  async Echo(msg?: string): Promise<string | null> {
    const statement = `query Echo($msg: String) {
        echo(msg: $msg)
      }`;
    const gqlAPIServiceArguments: any = {};
    if (msg) {
      gqlAPIServiceArguments.msg = msg;
    }
    const response = (await API.graphql(
      graphqlOperation(statement, gqlAPIServiceArguments)
    )) as any;
    return <string | null>response.data;
  }
```
but the actual returned object shape is 
```js
{
   echo: string
}
```.
So, there is no way to correctly reference the returned object without triggering a typescript compilation error. Either the shape of the returned object should be different, or the return type of the generated `Echo` function should be `Promise<{echo:string}|null>`.
