### ISSUE TITLE
@searchable directive Elasticsearch costs

### ISSUE THREAD

**Issue by AlessandroAnnini** [aws-amplify/amplify-cli#3860]
** Which Category is your question related to? **
Appsync + Elasticsearch
** What AWS Services are you utilizing? **
Cognito + Appsync
** Provide additional details e.g. code snippets **
I am using `@searchable` directive on one or two appsync graphql nodes and used it a few times for a search query but my amazon bill is very high, this is the Elasticsearch detail for September:
![image](https://user-images.githubusercontent.com/3852307/67141074-63673080-f260-11e9-9d7d-51a98327e55e.png)
Is it normal? I think that it is extremely expensive, how could I set the service so that I can contain the costs? This is holding me back from starting new projects!

**Comment by undefobj** [comment]
As @raelmiu noted you need to remove `@searchable` from your schema to decommission the Elasticsearch instance. At this time AWS does not have a "serverless" solution for Full Text Search so keeping that GraphQL directive without Elasticsearch has no implementation. We can however open up options or give documentation for using another instance size if that would be helpful.

**Comment by raelmiu** [comment]
@Undefobj that would indeed help, not only for developing at lower cost, but also for scaling the system via amplify Cli instead of console settings.

**Comment by AlessandroAnnini** [comment]
Hi @raelmiu, I tried to remove `@searchable` from my schema but I had troubles with that. So you're telling that I can remove that keyword from a working schema? If so I will try again.

**Comment by raelmiu** [comment]
@AlessandroAnnini Yes it did work for me. It get's removed after I `amplify push` to each environment. In my experience amplify is really fragile with backend updates though, so make sure you only make ONE change per push.

**Comment by GeorgeBellTMH** [comment]
it would be nice if multiple environments could use the same es instance...even better is if multiple projects could...at the least we should be able to run dev/uat/prod off the same ES instance...

**Comment by starpebble** [comment]
[bonsai.io](https://bonsai.io) hosts a free ElasticSearch endpoint.  It's kinda a little hacky though it can save money. Here's a little [code](https://github.com/starpebble/amplify-cli/tree/bonsai/packages/graphql-elasticsearch-transformer/streaming_lambda_bonsai).  The code examples modifying the DynamoDB event replicator that the amplify-cli creates for @searchable to replicate to Bonsai.io. This hackiness may be acceptable for development purposes when AWS's costs are absolutely prohibitive. An AppSync custom HTTP resolver to resolve a GraphQL query that searches with ES on Bonsai is necessary too, just add one.

**Comment by akshbhu** [comment]
Hi All
Currently t2.small is the lowest instance that amplify-cli support which works with version >= 6.0. Only instance which is smaller than this is t2.micro but it only supports elasticsearch version 1.5 and 2.3. 
Since t2.micro support is there on very older versions  and there are breaking changes in elasticsearch version from 2.x to 6.x , we decided to stay with default instance as t2.small with version >=6.

**Comment by quorth0n** [comment]
Note that 12 months of free t2.small usage are in fact covered by the free tier for any new AWS developers looking to try it.

**Comment by GeorgeBellTMH** [comment]
The problem really is that every environment needs its own ES instance...which is costly when you have a lot of environments...since instantiating ES mid-project is labour intensive you can't just delete and recreate easily...so each environment has a high long-term cost...would be great if you could share an instance between many environments...maybe with @searchable(use:"ESInstance")
