### ISSUE TITLE
How to combine key with custom resolvers with amplify or appsync graphql queries?

### ISSUE THREAD

**Issue by subhendukundu** [aws-amplify/amplify-cli#3888]
**Which Category is your question related to?**
GraphQl query

**Amplify CLI Version** 
4.17.2
I am using amplify graphql APIs. I have added a few `@key` for my search and sort of the events data. Then I have added a custom `Query` to search nearby events by lat and long. Now if had to search the nearby events by `creatorId` or `status` with `location` with a limit, how do I do it?

```
type Event @model
  @key(name: "byOwnerUser", fields: ["creatorId"])
  @searchable
{
  id:  ID!
  name: String!
  location: Location
  date: AWSDate!
  creatorId: ID!
  status: Boolean
  createdAt: AWSTimestamp
  updatedAt: AWSTimestamp
  users: [UserEvents] @connection(name: "EventsUser")
}

type Location {
  lat: Float!
  lon: Float!
}

input LocationInput {
  lat: Float
  lon: Float
}

type Query {
  nearbyEvents(location: LocationInput!, km: Int): EventConnection
}
```

I am stuck with this for a while now. Do I have to write custom resolvers? Is there a way to do this without custom resolvers?
Thank you in advance

**Comment by SwaySway** [comment]
Hello @subhendukundu if you are referring to how to do a geo search this is currently being tracked as a feature request, There are a few workaround implementations discussed in this thread as well https://github.com/aws-amplify/amplify-cli/issues/707

**Comment by subhendukundu** [comment]
Well yes I am aware of that. I am following https://medium.com/@tobinc/aws-amplify-graphql-with-geo-point-and-custom-resources-free-elasticsearch-provider-d1742fbc4ceb for enabling the geo search for now which is working great. Sorry if my question didn't make much sense but let me put it this way. If I had to use these workarounds and also add few more @key with it, will that be possible?
In other words from my event table if I had to search an event by Geo location with status and creatorId, how would I do that? Give me a lead?

**Comment by SwaySway** [comment]
Are you trying to see if adding `@key` would need a different implementation than what is listed in the article? If so `@key` shouldn't affect this since it pertains more to how you query your DynamoDB table. In this case you are looking at changing the query to your elasticsearch cluster to include creatorID and Status. This would involve adding those parameters as fields in the input type and editing the request resolver to include them in the filter.

**Comment by subhendukundu** [comment]
Thank you so much for explaining that.
Is there any reference where I can get some idea of how to add elastic search cluster to include creatorID and Status? Any tutorial or docs or example will be great.

**Comment by Jmales** [comment]
I'm having the same doubt.

I have and entity and was trying to use @key instead of @connection (due to https://github.com/aws-amplify/amplify-cli/issues/1656). 

But now I have a non-scalar in my entity and the filters are not generated automatically for that non-scalar "Location".

Is there any example where this is implemented in such way? The documentation is really bad at the moment
