### ISSUE TITLE
Single Tenancy Guidance

### ISSUE THREAD

**Issue by alexkates** [aws-amplify/amplify-cli#3925]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Auth, Api, Function

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.18.0

**What AWS Services are you utilizing?**
Cognito, APIGW, Lambda, S3, DDB, AppSync

**Provide additional details e.g. code snippets**
This is a general design/architecture guidance question... We are building a SaaS platform on which it is important for us to do the following,
1. Physically segregate client data
2. Track infrastructure cost on a per client basis

We are really excited about using Amplify to solve for this. We'd like to leverage amplify environments to solve for single tenant environments. For example `amplify env add newClient1` would give us a completely isolated environment including our User Pool, AppSync, Lambdas, API Gateways and DDBs dedicated to that newClient1.

The purpose of this ticket is really to make sure this sounds like viable use case for Amplify. Are you able to provide any guidance here?

**Comment by alexkates** [comment]
Any more information needed on my end in order to help answer this?

**Comment by attilah** [comment]
@alexkates for SAAS environments you as a provider has 2 choices. Deploying resources to the customers' accounts and interact with those or manage them through IAM permissions or the other solution is that the resources for a given tenant is created in an AWS account you own, then data isolation, data security, data storage location are the things you've to be careful about and address them. As most SAAS solutions involving multiple types of AWS service resources you can model a tenant as a group of resources with least privilege designed IAM policies around them, which gives you the isolation you'd like, but easier to run into 'per account' limits as your customer base grows. Because of that I'd do the same as above, but deploy each tenant into a separate AWS account under yours, the governance for those accounts can be well managed with AWS Organizations or AWS Control Tower which builds on top of Organizations. This would give a full separation not just from resource and security, but from billing perspective as well.

I hope my answer can give you pointers on where to look.

**Comment by alexkates** [comment]
Thanks @attilah . I'm familiar with both approaches you've suggested from an architectural perspective. My question really is geared towards how Amplify influences this SAAS and Single Tenancy approaches in AWS. Specifically, Amplify's environment management and segregation seems to lend itself well to managing multiple tenants. 

For example, imagine building a SAAS application where data segregation is a top priority. Let's also imagine we have 2 customers that use this application to service their own customers. It appears that Amplify would handle this environment segregation nicely by simply standing up 2 environments, `customer-env-1` and `customer-env-2` for example. 

I'm thinking about such a use case for Amplify and hoping to spark a conversation about Amplify's efficacy here.
