### ISSUE TITLE
How to find list of Event which user not already requested in amplify appsync?

### ISSUE THREAD

**Issue by subhendukundu** [aws-amplify/amplify-cli#3939]
Which Category is your question related to?
GraphQl query

Amplify CLI Version
4.17.2

I am trying to find a list of events where the user is already not requested. I have two tables, user and event, each time user requests for an event I am adding it to EventRequest table. Now how do I filter the listEvent which user not requested for already?

My tables look like this.

```gql
type User @model {
  id:  ID!
  firstName: String!
  lastName: String
  age:  Int
  gender:  String
  about: String
  eventRequest:  [EventRequest] @connection(name: "userRequests", keyName:  "byEventRequestStatus",  fields: ["id"])
}

type Event @model
  @key(name: "byOwnerUser", fields: ["creatorId"])
{
  id:  ID!
  name: String!
  description: String
  location: Location
  date: AWSDate!
  category: String
  creatorId: ID
  requestedUsers: [EventRequest] @connection(name: "eventRequests", keyName:  "byEventAlreadyAddedByUserId",  fields: ["id"])
}

type EventRequest @model
  @key(name: "byEventRequestStatus", fields: ["userId", "status"])"status", "eventDate"])
  @key(name: "byEventAlreadyAddedByUserId", fields: ["userId", "status"])
{
  id: ID
  status: String!
  userId: ID
  eventId: ID
  eventDate: AWSDate
  user: User @connection(name: "userRequests")
  event: Event @connection(name: "eventRequests")
}
```

I really need help on this one. Thanks

**Comment by edwardfoyle** [comment]
Hi @subhendukundu I think you will either need to use a [custom resolver](https://aws-amplify.github.io/docs/js/datastore#how-it-works) or execute two queries and perform some logic on the client to get the data you need.

Either way the logic is the same: you'll need to run one query to get all the events the user has already requested and another to get all events. Then do a set subtraction to get the un-requested events.

If your total number of events is large I would recommend storing the data differently because a scan to get all of the events will become more expensive the more events you have.

**Comment by subhendukundu** [comment]
Would be possible to share an example of how to do this? I am completely new to this tech stack, not able to get this working. :)
