### ISSUE TITLE
Access Denied after deploy frontend.

### ISSUE THREAD

**Issue by 2manoj1** [aws-amplify/amplify-cli#3974]
After Build and deploy got access denied issue. Please help

amplify -v
4.17.1

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>BCE70BB688B50E63</RequestId>
<HostId>
lVjnhXblaLjJ1t3COi0imqlBclAh7SUx4+7Ddsoth+th9EuTJwtU1bgwdMyVeEgFk7xWteOM24Y=
</HostId>
</Error>
```

**Comment by edwardfoyle** [comment]
Hi @2manoj1 You can set up an Express lambda function using [`amplify function add`](https://docs.amplify.aws/cli/function). When picking your runtime, select NodeJS (the default) and then when picking your template, select "serverless." This will set up a bare-bones Express lambda that you can modify to your needs. If you want to connect this lambda to a REST API, you can add that using [`amplify api add`](https://docs.amplify.aws/cli/restapi)

**Comment by LessCodeMoreAction** [comment]
So was the problem solved?

**Comment by Amber-Williams** [comment]
Having this issue as well using NextJS on Amplify. Any solutions?

**Comment by lanpmse61548** [comment]
> Having this issue as well using NextJS on Amplify. Any solutions?

I followed this https://dev.to/dabit3/5-minute-tutorial-deploying-a-next-app-with-aws-amplify-hosting-5199 and it worked for me.

**Comment by mikeahirsch** [comment]
@Amber-Williams @lanpmse61548 What worked for me was going into the build settings and changing `baseDirectory: .next` to `baseDirectory: out`

**Comment by Huciko** [comment]
Note
When you create the zip folder, make sure you zip the contents of your build output and not the top level folder. For example, if your build output generates a folder named “build” or “public”, first navigate into that folder, select all of the contents, and zip it from there. If you do not do this, you will see an “Access Denied” error because the site's root directory will not be initialized properly.

<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>4442587FB7D0A2F9</RequestId>
  <HostId>...</HostId>
</Error>
