### ISSUE TITLE
CloudFront redirects to S3 bucket when trying to use own domain | Solution attached

### ISSUE THREAD

**Issue by domezi** [aws-amplify/amplify-cli#3999]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
I run "amplify add hosting" and selected S3 and CloudFront. Then I ran "amplify publish".
The CloudFront distro was created successfuly and I was able to add a record in Route53. But when calling the Route53 url, I got redirected to the S3 static website bucket.
I fixed it by changing the origin from the <bucket-name>.s3.<aws-region>.amazonaws.com to <bucket-name>.s3-website.<aws-region>.amazonaws.com manually. Would be great, if amplify did that on its own.

**Amplify CLI Version**
4.18.0

**To Reproduce**
create new amplify project
amplify add hosting (select s3 and cloudfront)
amplify publish

**Expected behavior**
Automatically configure CloudFront for use with own domain

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 19.3
 - Node Version: v12.16.2

**Additional context**

**Comment by UnleashedMind** [comment]
The redirect only happens at the beginning when you first setup the `PROD` hosting, and it is because the CloudFront has not finished caching the web app in its edges at that point.
The redirect will actually fail, because the S3 bucket's contents are private, and only the CloudFront's [Origin Access Identity](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-restricting-access-to-s3.html) can access the private bucket's contents.
In the `PROD` configuration, the S3 bucket is not configured as webhost, so the URL `.s3-website..amazonaws.com` will not work.

**Comment by kaustavghosh06** [comment]
@domezi Please let us know if you're still facing this issue. Closing this issue for now due to lack of further response.
