### ISSUE TITLE
Add React to existing project

### ISSUE THREAD

**Issue by rvanbael** [aws-amplify/amplify-cli#4017]
Hey, I have an iOS running app on AWS backend, managed through Amplify. I want to add an admin react website to manage easily the backend data. I will [add a group to my cognito for admin](https://aws.amazon.com/fr/blogs/mobile/amplify-cli-enables-creating-amazon-cognito-user-pool-groups-configuring-fine-grained-permissions-on-groups-and-adding-user-management-capabilities-to-applications/). I will add a dedicated API for this group. Looks good.

But I am struggling for the react part. There are tons of tuto on how to create a new amplify project on react. But I cannot find how to add react on an existing project. To be precise, the "amplify init" command generates, after a push, a "aws-exports.js" file. My project does not have any "aws-exports.js" file. And I do not want to "init" a new project.

Any idea how could I leverage my existing backend with a react front-end?

**Comment by akshbhu** [comment]
Hi @rvanbael 

We have a command ```amplify pull``` to fetch the existing backend so that it can be used with multiple frontends.This command will have question walkthrough for the app you are building and will generate ```awsexports.js``` file.

For more clarity , follow this link : https://aws-amplify.github.io/docs/cli-toolchain/quickstart#multiple-frontends.

Try this and let me know if you are still facing any issue

**Comment by kaustavghosh06** [comment]
@rvanbael Let us know if you're still stuck on this based on @akshbhu's response. Closing this issue.
