### ISSUE TITLE
RegEx Usage not clear or bug

### ISSUE THREAD

**Issue by MShah-Fintech** [aws-amplify/amplify-cli#4025]
** Please describe which feature you have a question about? **
I have made model with @searchable directive

Schema is as follows:

type Category @model @searchable {
	title: String!
	hierarchy: String
}

Now I want to search for string using RegEx in hierarchy field with searchCategory query.

My data items are stored in following fashion.

Sports#Cricket#
Sports#Cricket#T20#

My RegEx is `^Sports#[a-zA-Z0-9]+#`

Which should give me 
**Sports#Cricket#**

But getting 0 items in result of query using AppSync console

Any suggestions will be helpful. Am I using it wrong? or Is there bug in the system?

** Provide additional details**
With same RegEx Got the right result full match on following website:

https://regex101.com/

**Comment by akshbhu** [comment]
Hi @MShah-Fintech 

Since the data you are searching on is analyzed data, it wont find **Sports#Cricket#** in the inverted table created by elasticsearch. Thats why it is coming as empty.

You can try regex for "Sports" or "cricket" separately  to get the desired result.
```Regex : "[sS][a-zA-Z]+```, this regex will return documents having Sports in it.

**Comment by akshbhu** [comment]
Let me know if above issue is solved. For now I am closing this issue , if you are still stuck , you can comment on this and I will reopen this issue.
