### ISSUE TITLE
Unable to add a Lambda Trigger using CLI

### ISSUE THREAD

**Issue by varunpsr** [aws-amplify/amplify-cli#4053]
**Describe the bug**
When trying to add a Lambda trigger using `amplify add function` the process fails at this step `Do you want to edit the local lambda function now? (Y/n)`

**Amplify CLI Version**
4.17.1

**To Reproduce**
1. Run `amplify add function`
2. Select Lambda Trigger for function type.
3. Select Amazon DynamoDB Stream
4 Select `Use API category graphql @model backed DynamoDB table(s) in the current Amplify project` as DynamoDB event source.

**Expected behavior**
A lambda function should have been created.

**Screenshots**
![image](https://user-images.githubusercontent.com/6907640/80131006-2edd8400-85b7-11ea-86b2-bd5cc3304f6c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node Version. 12.14.0

**Comment by edwardfoyle** [comment]
@varunpsr part of this issue is fixed in the latest version of the CLI (4.18.1). There is another known issue that is fixed by #3990 that will land in an upcoming release of the CLI. Until then, you can update to the latest version of the CLI and select 'No' when asked if you want to edit the file now, then manually navigate to the function folder and edit the index.js file there.

**Comment by edwardfoyle** [comment]
@varunpsr This is now fixed in the latest version of the CLI (4.19.0)
