### ISSUE TITLE
How to fetch records based on array of ID's with graphql API

### ISSUE THREAD

**Issue by apoorvmote** [aws-amplify/amplify-cli#4106]
**Which Category is your question related to?**
API

**What AWS Services are you utilizing?**
Cognito, AWS AppSync, graphql API

**Provide additional details e.g. code snippets**
I have array of `todoID` how do I fetch only records matching these ID's.

Currently I fetch everything and filter.

`const allTodos = await API.graphql(graphqlOperation(listTodos));`

**Comment by edwardfoyle** [comment]
Hi @apoorvmote, there are a few ways to accomplish this. The simplest is to pass in a filter expression to the list operation like this:
```graphql
query FilteredLIst {
  listTodos(filter: {
    or: [
      {
        id: {
          eq: "id1"
        }
      },
      {
        id: {
          eq: "id2"
        }
      }
    ]
  }) {
    items {
      id
      title
    }
  }
}
```
This will save you a bit of bandwidth over the wire, but it will still cost you an entire scan of the ddb which can be quite expensive as the number of entries grows.

The recommended approach to perform this query efficiently (ie without a scan) is to have a [GSI](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GSI.html) that correlates all of the todos you want to fetch. For example, say you had a "Project" entity that had multiple "Todo"s in it. Instead of storing all of the Todo IDs as a list in the Project, you could store the project ID as a field in the Todo and make that field the primary key of a GSI:
```graphql
type Project @model {
  id: ID!
  name: string!
  tasks: [Todo!]! @connection(keyName: "byProject", fields: ["id"])
}

type Todo @model @key(name: "byProject", fields: ["projectId"]) {
  id: ID!
  title: string!
  description: string
  projectId: ID!
}
```
This way, when resolving the list of tasks in the project, a query (not a scan) is performed on the Todo table against the "byProject" GSI. You can read more about the @key and @connection directives [here](https://docs.amplify.aws/cli/graphql-transformer/directives#key)

**Comment by jamesalester** [comment]
Hi @edwardfoyle. What would you suggest if I wanted to get all of the Todos for multiple projects? So instead of the query being: 
```
type Query {
    byProject(projectId: ID!): ModelTodoConnection
}

type ModelTodoConnection {
  items: [Todo]
  nextToken: String
}
```
it was: 
```
type Query {
    byProjects(projectIds: [ID]!): ModelTodoConnection
}
```
Is there a better way to do this than just having a lambda resolver that loops through the `byProject` query?

**Comment by edwardfoyle** [comment]
@jamesalester If the client is specifying projectIDs on the fly, you would have to either have the client issue multiple byProject() queries or have a lambda resolver as you mentioned. If the projects that you are querying are known in advance though (such as "all projects in an organization" then you could include another field in the todo table such as "organizationID" and have a GSI on that field so you could query Todos "byOrganization"

**Comment by jamesalester** [comment]
Thanks @edwardfoyle. I really appreciate the answer!

**Comment by vincent38wargnier** [comment]
Hi, 
Do you know if there is a trick with Amplify to filter like this :
`{filter: element hasOneOf : ["102265475","102265476" ]}`

It's like a reversed "contains" that I'm trying to do.

Because for now the only solution I found was to dynamically draw the json filter, or call a query for every element of the array.
