### ISSUE TITLE
CFN template modified when deploying 2nd environment

### ISSUE THREAD

**Issue by cyrfer** [aws-amplify/amplify-cli#4335]
**Describe the bug**

The following block of my infrastructure code was modified when I deployed a new environment. I do not expect my template to change because the template is under version control.

```json
"Code": {
  "S3Bucket": "amplify-foo-dev-212449-deployment",
  "S3Key": "amplify-builds/foo-786931524e3951785a44-build.zip"
},
```

**Amplify CLI Version**
```bash
$ amplify --version
4.19.0
```

**To Reproduce**
After running these, the template was modified.
```
amplify init .... dev
amplify function add...
amplify push
amplify env add qa
amplify push
```

**Expected behavior**
I think these values should be passed via CFN parameters for each environment instead of changing the template.

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version:

```bash
$ node -v
v12.16.2
```

**Comment by kaustavghosh06** [comment]
@cyrfer This behavior is due to the dynamic S3Bucket and key which is required in the CloudFormation template for the CloudFormation service to detect for any changes to the Lambda function and deploy the Lambda function. This is generated dynamically on every push and due to this change you can see an "update" status when switching environments since these values are different between environments. This shouldn't affect any of your deployments as we dynamically re-generate it during an `amplify push`.
We're working on a better way to handle this - but at this point this is the way we're handling uploading updates to the Lambda function via CloudFormation.

**Comment by cyrfer** [comment]
I don't like seeing git changes to templates. It makes me nervous. If you must change something, please change a parameters file, specific to the environment. Parameter changes still cause CF to deploy.

Can you link me to the issue where you're tracking "a better way to handle this" ?

@kaustavghosh06

**Comment by kaustavghosh06** [comment]
Here is the duplicate issue which we're tracking for the issue - https://github.com/aws-amplify/amplify-cli/issues/3068
