### ISSUE TITLE
How to share common code between functions, am getting "Error: Cannot find module '../../*.js'

### ISSUE THREAD

**Issue by contractorwolf** [aws-amplify/amplify-cli#4412]
**Which Category is your question related to?**
Amplify Functions

**Amplify CLI Version** 
4.18.1

**What AWS Services are you utilizing?**
This path to a local file and folder outside my function does not appear to work in amplify:
**const newsfeed = require('../../scraping/newsfeed.js');**

I wrote a js module (called newsfeed) that has a method to scrape a web url (newsfeed.GetGoogleNews()).  The path to the file has to go up 2 levels from the folder containing the function because it _needs to be used by multiple AWS Amplify Functions_ in my application.

**Provide additional details e.g. code snippets**
I have tested this using mock to run the function locally and everything works file, but when I deploy the function I get this error shown in CloudWatch:

"Error: Cannot find module '../../scraping/newsfeed.js'
Require stack:
- /var/task/index.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js"

It appears that I cannot use a common path for code shared between functions.  Is there a way to do this or will I have to copy the file into each function folder that needs to use it? That cant be the only way to do this right?

**Comment by RossWilliams** [comment]
The amplify functionn build process copies the contents of $FUNCTION_NAME/src  into $FUNCTION_NAME/dist as a zip file, and uploads this zip file to S3. Anything outside of ./src will not be packaged. You are seeing this issue on the server because the file you are referencing is not in the ./src folder when its contents are zipped up.

The project level package.json file can contain a script with the name "amplify:$FUNCTION_NAME" which is run by the CLI before packaging. You can use this to create your own system to manage dependencies outside the $FUNCTION_NAME/src folder, as long as the result is having all needed references inside of ./src. See documentation [here](https://docs.amplify.aws/cli/function/build-options).

One option is to have a lerna workspace completely outside of amplify, and have the node script build your workspace, locate the package that lines up with your function name, and copy that into $FUNCTION_NAME/src . With this you can have a collection of functions all sharing code and not be tied down to the amplify folder structure.

Or, you could use a simple bundler tool that outputs a single index.js file, and you can manage your code outside of ./src. The documentation linked above assumed that source code lived in ./lib. (yes this is backwards, but probably done for backward compatibility).
