### ISSUE TITLE
Unable to filter query on self referencing 0 to Many optional ID field

### ISSUE THREAD

**Issue by neilime** [aws-amplify/amplify-cli#4425]
Hi,

**Describe the bug**

I have declared a GraphQL model "SampleGroup"  that is a multi level group organization (A SampleGroup can have 0 to many SampleGroup as children)

I can query SampleGroups having a given parent ID but **I cannot query SampleGroups having no parent ID.**

I don't if I'm doing something wrong but I have read many docs and examples I've found, without success.

----

**Context**

* Graphql schema:
```graphql
type SampleGroup
  @model
  @key(name: "byParent", fields: ["parentId"]) {
  id: ID!
  label: String!
  parentId: ID
  children: [SampleGroup] @connection(keyName: "byParent", fields: ["id"])
}
```

* Existing item without `parentId` (first level group) in DynamoDB : 

```json
{
  "__typename": "SampleGroup",
  "id": "a3c9e21b-a0ce-4f78-a1b6-6603c4a1654f",
  "label": "Group 1"
}
```

* Query:

```graphql
query ListSampleGroups($filter: ModelFilterFilterInput, $limit: Int, $nextToken: String) {
  listSampleGroups(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      id
     }
  }
}
```

**Attempts**

1. Filter with `eq: null`

* Variables: 
```js
{
  filter: { 
    parentId: { eq: null}
  }
}
```

* Result: Empty items

```json
{"data":{"listSampleGroups":{"items":[]}}}
```

2. Filter with `attributeExists: false`

* Variables: 
```js
{
  filter: { 
    parentId: { attributeExists: false}
  }
}
```

* Result: Error

`ExpressionAttributeValues must not be empty (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: ...)`

3. Filter with `not: attributeExists: false`

* Variables: 
```js
{
  filter: {
    not: {
      parentId: {attributeExists: true}
    }
  }
}
```

* Result: Error

`ExpressionAttributeValues must not be empty (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: ...)`

**Comment by thomasklein-winemaker** [comment]
Hi guys! Any news on this one?

**Comment by paulsson** [comment]
@edwardfoyle @SwaySway @litwicki @aws-amplify-cli-ops the amplify graphql transform for filtering using `attributeExists` is broken. This ticket was opened in May 2020 and looks like the Amplify team has known about this bug since a minimum of Aug 2020. It is now, 2022. How can such a simple and easy to reproduce bug be ignored for 1.5+ years?
This should probably take someone on the Amplify team who works on graphql transforms about 10 minutes to fix and would make the Amplify UX for 1000s of developers better!
Here's another github issue for the same bug that has been closed for some reason: https://github.com/aws-amplify/amplify-cli/issues/5589
`</rant>`

For the Amplify community / users here's a way to work around this issue using a `size` filter for now until this bug is fixed.

Instead of:
```
filter: {
  ssoDomain: { attributeExists: true }
}
```
Use:
```
filter: {
  ssoDomain: { size: { gt: 0 }}
}
```

**Comment by cjihrig** [comment]
I just tried to recreate this with version 2 of the GraphQL Transformer, and `attributeExists` filtering appears to be working there.
