### ISSUE TITLE
amplify mock function

### ISSUE THREAD

**Issue by steveparkerSG** [aws-amplify/amplify-cli#4428]
How should I be configuring credentials to run ```amplify mock function```? The posts I've found in research it suggest it follows the normal credential chain on my machine, but that is not accurate. 

I have:

- Environment variables setup that are valid, aka  `aws s3 ls` works using those credentials
- Configured the profile used by the amplify app

Yet running the function mock results in "Missing credentials in config",

**Comment by nikhname** [comment]
For the second set of credentials, were they set up using ```amplify configure``` ?

**Comment by SwaySway** [comment]
Hello @steveparkerSG 
Mockinga lambda function does not currently use environment variables. This is something we are tracking in this issue here: https://github.com/aws-amplify/amplify-cli/issues/3961

The CLI will generate the necessary credentials to access the resources you specify when adding a function through the CLI question workflow. Is there a resource you are trying to access in the lambda function that results in this error? Or is it a resource you gave it access to?
