### ISSUE TITLE
Evolving API keys example?

### ISSUE THREAD

**Issue by Alex-Mann** [aws-amplify/amplify-cli#4468]
Going through the docs of [Evolving API Keys](https://docs.amplify.aws/cli/graphql-transformer/directives#evolving-apis-with-key) but I am still a bit confused with the "backfilling" and what the actual process looks like for evolving API keys.
- What happens when you want to change or update the primary key?
- What happens when you update a composite key to include a new just added field to the DB?

Is there anywhere that describes this more in-depth? If so I'll go through it and would be happy to contribute an example to make the process more clear.

Thanks.

**Comment by kaustavghosh06** [comment]
Responding to both your questions below:

What happens when you want to change or update the primary key?
After your initial @model creation, currently you won't be allowed to change it due to DDB limitation. You'd have to remove the @model do a deployment (which will result in the DDB deletion) and then re-add the @model with the changed primary-key schema with @key. You'd have to backup the data before removing the @model to avoid loss in data and Amplify CLI doesn't provide a data migration path today.

What happens when you update a composite key to include a new just added field to the DB?
Currently, when you update the composite-key - you can do it only with the GSI's i.e @key's with a name field, DDB re-indexes your data for you based on your new hash-key and composite-key pair (which has the newly added field as a part of it.)

**Comment by kaustavghosh06** [comment]
@Alex-Mann  Please let us know if you've more questions on this issue but closing this issue for now based on the response above.
