### ISSUE TITLE
Multiple authorization rules using different providers

### ISSUE THREAD

**Issue by maespinoza** [aws-amplify/amplify-cli#4590]
**Which Category is your question related to?**
API

**Amplify CLI Version** 

4.21.1

**What AWS Services are you utilizing?**

Cognito, AppSync and DynamoDB

**Provide additional details e.g. code snippets**

I am trying to setup the following authorization rules

- Authorize public access to read models
- Authorize any authenticated user to create and **read models**
- Authorize owner only to  delete and update models
- Authorize authenticated users that belong to the "Admin" group to delete and update models

I tried setting the above rules with the following implementation:

```graphql
type Team
  @model 
  @auth(rules: [
    { allow: owner, operations: [create, delete, update] },
    { allow: groups, groups: ["Admin"] },
    { allow: public, operations: [read] }
 ]) {
  id: ID!
  name: String
}
```

The use case is that I want non-authenticated users to be able to list all the existing teams, which works if I use apiKey auth. The problem is that when I use an authenticated user I can successfully create but I cannot list anymore if I use the authenticated user credentials. I want this functionality since I would not want to keep changing auth modes back and forth plus I would also like to monitor when the request was made by an authenticated user or by an anonymous user. 

I what I am trying to accomplish possible? I tried changing the order of the rules but its not clear from the documentation if that has any effect. 

Things I tried:
```graphql
  { allow: owner, operations: [create, delete, update, read] },
  { allow: groups, groups: ["Admin"] },
  { allow: public, operations: [read]}
```

Allows listing only the models created by that user

```graphql
{ allow: owner, operations: [create, delete, update] }
```

Allows all authenticated users to list all models but no public access available.

**Comment by attilah** [comment]
@maespinoza: When you are using Cognito User Pools you don't have to stick to API_KEY since for Cognito we create an Unauthenticated role which is like "public" access, but the API requests will be SIG4 signed instead of API_KEY which is more secure and does not require additional maintenance, like API_KEY.

On the other hand if you'd leverage the multiple client capabilities from AmplifyJS (or other language), then you can have 2 instances of the client so you could still use the public grant for authenticated users by using that specific client instance or just different credentials with the same client instance, it is your choice.

So you can use your first rules, but change the provider for the public one:
```
    { allow: owner, operations: [create, delete, update] },
    { allow: groups, groups: ["Admin"] },
    { allow: public, operations: [read], provider: userPools }
```

I'm closing the issue as I answered your question, if something new comes up feel free to reopen it, but for how-to questions our [discord community](https://discord.gg/amplify) is perhaps a better place as community members helping out all the time.
