### ISSUE TITLE
How to order a simple list query

### ISSUE THREAD

**Issue by lexlemmens** [aws-amplify/amplify-cli#4616]
**Which Category is your question related to?**
AppSync / Amplify API

**Amplify CLI Version** 
4.18.1

**What AWS Services are you utilizing?**
AppSync

**Provide additional details e.g. code snippets**

I have the following schema.graphql which the codegen generates the API from, how is it possible to sort it based on one column for instance name. As I understand this has to be done with `@key` but I want to do it without passing a argument to the query request / don't have extra parameter inside mutation.

```
type Company @model @key(fields: ["id","name"]) {
    id: ID!
    name: String!
}
```

This gives me the listCompany query with the sortDirection / ordering but when looking at mutation it requires me to fill in a id as input field. When I change schema to below it requires me to input the name as parameter which I don't want because I want the whole list not filtered by name.

```
type Company @model @key(name: "byName", fields: ["id","name"], queryField: "GetCompanyByName") {
    id: ID!
    name: String!
}
```

I think there should be an option to do this and maybe there is but can't find it. If someone knows solution let me know.

**Comment by attilah** [comment]
@lexlemmens since the generated AppSync API is backed by DynamoDB it is different from the relational databases and sorting works differently. As you suggested you are right you have to use the `@key` directive.

If you are coming from a relational background I suggest to watch some DynamoDB related materials from AWS or the community to get a good understanding how you've to think differently from SQL when selecting a partition key and range key.

You can define a common key 'type' for partition key and name for range key for the `@key` directive, that enables the sorting on the name, but there can be other ways as well depending on your use case.

```graphql
type Company @model  @key(name: "byName", fields: ["type", "`name"], queryField: "GetCompanyByName")
{
    id: ID!
    type: String!
    name: String!
}
``` 

test queries:
```graphql
mutation M {
  M1:createCompany(input: {
    id: "C1"
    type: "company"
    name: "Foo"
  }) {
    id
  }

  M2:createCompany(input: {
    id: "C2"
    type: "company"
    name: "Bar"
  }) {
    id
  }
}

query Q {
  GetCompanyByName(type: "company" sortDirection:DESC) {
    items {
      id
      name
    }
  }
}
```

I'm closing the question as it has been answered. I'd suggest to reach out to our community on discord to get answers for similar questions from our community members. https://discord.gg/amplify

**Comment by lexlemmens** [comment]
Hi @attilah, thank you for your response. Would this mean that I have to pass in the id myself. This needs to be generated automatically to make sure it's unique right. If not you could come in collision with adding same ids.
