### ISSUE TITLE
List input to @connection fields parameter

### ISSUE THREAD

**Issue by antantonton** [aws-amplify/amplify-cli#4851]
**Which Category is your question related to?**
API, GraphQL, schema defnitions, documentation

**Amplify CLI Version** 
4.24.0

**What AWS Services are you utilizing?**
API

**Provide additional details e.g. code snippets**
Hi guys, I have a type of relation in my data that I have been trying to solve for quite a while now. I have gone over the documentation but could find any information on how to achieve the desired result.

Lets say that I have two @models, one for Characters and one for Items. Characters can own items, which means there is a one way connection. If we are restricted to just a single item per character, I could define the schema like below:
```
type Character @model
{
    id: ID!
    itemId: String
    item: Item @connection(fields: ["itemId"])
}
type Item @model
{
    id: ID!
}
```
In this, multiple characters could own the same item, but there wouldn't have to be any duplicate entries in the item database (because the characters point to the same object).

But now to my question, how do I achieve this kind of relation when a character can own many items? My hope was that I could do something like this:
```
type Character @model
{
    id: ID!
    itemIds: [String]
    items: [Item] @connection(fields: ["itemIds"])
}
type Item @model
{
    id: ID!
}
```
and that the resolver would loop over itemIds in order to fetch all of the items specified. However, as you can probably guess it does not work in this way and does not accept list inputs. So what is the recommended approach for these kinds of relations?

**Comment by RossWilliams** [comment]
There are two approaches.
1. Create a many-to-many mapping. This means having a CharacterItems model that holds connections to both the Character and Items model. This has a latency impact, as there is another round trip to the database.
2. Create a custom resolver for Character.items.req.vtl instead of the auto-generated one created when you use the @connection directive. In your custom resolver, use a BatchGet dynamodb operation to get all items in your items list. There is an AppSync tutorial on using BatchGet / TransactGet in templates. Using this approach, you are limited to 100 items, so choose it if you have a bounded list of items < 100.

**Comment by antantonton** [comment]
Thank you for the elaborate response. Great that there are multiple approaches. The second one seems like it would be a great fit for my use case if I can figure how to write the custom resolvers.

Both approaches seem to enable what I am looking to do, which is having a single source of truth to edit when it comes to item property values. 

Just to make sure I am understanding the first approach correctly. To me, it seems that the schema would then look something like this:
```
type Character
@model
{
    id: ID!
    characterItems: [CharacterItem] @connection( keyName: "byCharacter" fields: ["id"]  )
}

type CharacterItem
@model
@key ( name: "byCharacter" fields: ["characterId"] queryField: "characterItemByCharacter" )
{
    id: ID!
    characterId: String!
    itemId: String!
    item: Item @connection( fields: ["itemId"] )
}

type ItemTemplate
@model
{
    id: ID!
}
```
You mention that this approach leads to extra latency. But to me it seems that it also leads to a new table with a number of entries, which would incur higher storage costs as well?

Also, does the second approach using custom resolver have any kind of drawback compared to the first approach, aside from the 100 items limit?

**Comment by RossWilliams** [comment]
I wouldn't worry about storage costs.

2nd approach downsides - you are now writing a custom template, which means for that field you will no longer be able to use other amplify directives. So adding an @auth directive to the 'items' field will have no effect. It will take you 100x longer to write than just having a many-to-many setup, at least the first time you do this. But it could be interesting knowledge.

Regarding your proposed schema, I'd set a table key to @key(fields: ["id","itemId"]) instead of using a named key, and have the 'id' field mapped to the characterId, rather than an autogenerated field. This sets the keys on the table rather than a GSI, which takes half the storage costs. In addition, by doing this, you can ensure users do not have duplicate items (so only use this if you don't want multiple of the same item for a character). You could also track the item count in this CharacterItem model if you do want to allow users to have duplicate items.

The reason I suggest mapping id -> characterId rather than using the characterId field directly is that a lot of graphql clients expect to see an 'id' field for all model types in order to perform caching, but this is not required and you could set 'characterId' as the partition key (first key).

To help with googling how to make a custom resolver template, look for references to CustomResources.json, you are going to need this to create a field resolver. And then you will need to add your template into the /resolvers directory inside your API file (not the build folder). See screenshot.

<img width="253" alt="Screenshot 2020-07-16 at 13 45 10" src="https://user-images.githubusercontent.com/1443442/87672324-aeb85c00-c76a-11ea-8349-702d2d51f4fd.png">

**Comment by antantonton** [comment]
Thank you again for taking the time to write these detailed answers. 

The speed of implementing the first approach is definitely worth any potential performance loss for me personally in this project.

That's a great suggestion on the key setup, not just for this example but overall, I will keep it mind.
