### ISSUE TITLE
How to switch between environments for amplify mock api?

### ISSUE THREAD

**Issue by tobiasfeil** [aws-amplify/amplify-cli#4878]
When switching between environments, the data present when using the GraphiQL view exposed by `amplify mock api` stays the same. This impairs my testing workflow since I don't want automated tests to have the same data as when I'm playing around with the API manually. Can an isolation be accomplished?

**Which Category is your question related to?**
API

**Amplify CLI Version** 
4.42.3

**What AWS Services are you utilizing?**
auth
api

**Comment by nikhname** [comment]
Hi tobiasfeil, after switching environments did you try running the command `amplify api gql-compile` ?

**Comment by nikhname** [comment]
@tobiasfeil this may also be an issue with GraphiQL persisting data, you could try a hard refresh of the browser/clearing cookies or running in an incognito browser.

**Comment by tobiasfeil** [comment]
I tried switching envs, then compiling, opening in an incognito window, hard refreshing, and it still shows the data from the other environment. Additionally, I verified that before and after switching envs, the contents of `amplify/mock-data/dynamodb/fake_us-fake-1.db` are the same, which is where the data reside, right?

So it seems that data aren't saved per environment, but per project. It would be highly desirable for data of different environments be isolated. 

Or is there a better approach to local testing that I haven't thought of yet?

**Comment by edwardfoyle** [comment]
Hi @tobiasfeil you are correct that mock DynamoDB does not store data per environment. Implementing that is out of scope for mock at this time. If you want to have a separate local db for your tests, you could have a pre and post step to your test to swap out the .db file. However, you'll have to take care to keep that other test .db file up to date with any model changes. Instead, I would recommend that you modify your tests to initialize the data they need and clean up that data after the fact so that the tests can be run with any db

**Comment by tobiasfeil** [comment]
OK that sounds reasonable, thank you!
