### ISSUE TITLE
API: Usage of object Types with generated builders

### ISSUE THREAD

**Issue by Trivoc** [aws-amplify/amplify-cli#493]
** Which Category is your question related to? **
AWS Amplify API (Android SDK)

** Provide additional details e.g. code snippets **

Hi, 
Using the autogenerated code pertaining to GraphQL operations has left me a little confused; for the sake of the example i use the template schema: 

```
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @connection(name: "BlogPosts")
}
type Post @model {
  id: ID!
  title: String!
  blog: Blog @connection(name: "BlogPosts") 
  comments: [Comment] @connection(name: "PostComments")
}
type Comment @model {
  id: ID!
  content: String
  post: Post @connection(name: "PostComments")
}
```
It generates the expected classes, but only the scalar values have a builder method associated with them; `CreatePostInput.builder() ` allows me to add a title, but no values for 'comments'. On the other hand, I _can_ add a postBlogId - I guess this is how I can have a Post entry relate to a Blog entry. Don't I have to something "the other way around" as well(add a reference to a Post entry to the Blog.post list)?

**Comment by mikeparisstuff** [comment]
When you use @model and @connection, you use what are conceptually foreign keys (although not really since this is NoSQL) to create connected objects. For example, let's look at a single connection in your schema:

```graphql
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @connection(name: "BlogPosts")
}
type Post @model {
  id: ID!
  title: String!
  blog: Blog @connection(name: "BlogPosts") 
  comments: [Comment] @connection(name: "PostComments")
}
```

The compiled schema will contain:

```graphql
input CreateBlogInput {
  id: ID
  name: String!
}
input CreatePostInput {
  id: ID
  title: String!
  postBlogId: String
}
```

Notice the **postBlogId** field that was added to the **CreatePostInput** type. When creating post objects, you can add that post the connection by providing the id of the parent blog. For example,

```graphql
mutation CreateBlog {
  createBlog(input: { name: "A blog" }) {
    id
    name
  }
}
mutation CreatePost {
  createPost(input: { title: "A post", postBlogId: "id-from-previous-mutation" }) {
    id
    title
  }
}
```

The reason for this is that @connection creates a Global Secondary Index (GSI) on the many side of the relationship and uses a DynamoDB query operation to efficiently fetch all posts for a blog in this example.

**Comment by kaustavghosh06** [comment]
Closing this issue. Please feel free to re-open the issue if you've any other questions related to your initial query.
