### ISSUE TITLE
Error Parameters: [hostedUIDomainName, oAuthMetadata, authProvidersUserPool, hostedUIProviderMeta, hostedUIProviderCreds] do not exist in the template

### ISSUE THREAD

**Issue by alexandrefilipiak** [aws-amplify/amplify-cli#5011]
I got following error while doing push, after converting my api setting from "api-key" to  "cognito user pools";
Here is the error :
Parameters: [hostedUIDomainName, oAuthMetadata, authProvidersUserPool, hostedUIProviderMeta, hostedUIProviderCreds] do not exist in the template

**Amplify CLI Version**
4.26.0

**To Reproduce**
1) I modified the api configuration in the aws console to use "cognito user pools" instead of "api key"
2) I did an "amplify pull"
3) I then modified my graphql schema (just added a space)
4) I did an "amplify update api"
5) I did an "amplify push"
then I got the error

**Expected behavior**
Push should be successful

**Screenshots**
![image](https://user-images.githubusercontent.com/65644177/89331303-9325de80-d6a2-11ea-94e3-e48691920090.png)

 - OS: Windows 10
 - Node Version: v12.18.0

**Additional context**
All the informations mentioned in the error are present in the file : /backend/auth/<resource>/parameters.json
But not in : /backend/api/<resource>/build/parameters.json
I tried to delete the "build" directory and do "amplify api gql-compile", it did not solve the error
I tried to do "amplify init", it did not solve the error

**Comment by akshbhu** [comment]
Hi @alexandrefilipiak 

Can you provide further details on how you set up resource ```authmanydone8459f8d``` in the auth category?

**Comment by alexandrefilipiak** [comment]
Hello akshbhu,

I join you the 2 files related to authmanydone8459f8d that I have in the backend.

Alexandre
[manydone84d59f8d.zip](https://github.com/aws-amplify/amplify-cli/files/5025962/manydone84d59f8d.zip)

**Comment by akshbhu** [comment]
Hi @alexandrefilipiak 

I am not sure why this is happening since error is related to parameters in CFN which are present in your parameters.json.

Can you answer this questions so that I can reproduce this on my end:

- Did you add the Cognito userpool when created the project first time or just with API_KEY with the api or both?

- What changes you did in ```amplify update api ```command?

- Did you modified the auth configuration in AWS Amplify console or AWS Appsync console or is it just for testing  queries?

**Comment by alexandrefilipiak** [comment]
Hi @akshbhu

Here you go:
1) Yes, I created the Cognito userpool when creating the project first time
2) I did not perform the change by using "amplify update api", but rather by modifying the api directly in the aws console to change from "API key" mode to "User pool" mode
3) As far as I can remember, I did not change the auth configuration

Thanks for your help

Alexandre

**Comment by akshbhu** [comment]
Hi @alexandrefilipiak 

Amplify-CLI  doesn't take changes from console. You can try ```amplify update api``` and select the auth related changes you want for your API and then do ```amplify push```.  Let me know if that works?
If this doesn't work , then you can mail the amplify folder to amplify-cli@amazon.com with issue name in the subject.

**Comment by alexandrefilipiak** [comment]
Hello akshbhu,

That's what I did.

Just a little reminder of my steps :

To Reproduce

I modified the api configuration in the aws console to use "cognito user pools" instead of "api key"
I did an "amplify pull"
I then modified my graphql schema (just added a space)
I did an "amplify update api"
I did an "amplify push"
then I got the error

I send you the folder.

Thank you

Alexandre

**Comment by tacnoman** [comment]
I have a similar issue, but the error is in domainName
I added a new endpoint to api using amplity update api, but when I try to push I receive this error message:

```
UPDATE_FAILED myAmplifyApi
AWS::CloudFormation::Stack Thu Oct 22 2020 12:28:44 GMT-0300 (GMT-03:00) Parameters: [domainName, domainCertificateArn, myenvDomainCertificateArn] do not exist in the template
```

And the last error message is:

```
Following resources failed

✖ An error occurred when pushing the resources to the cloud

Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete
```

Someone may help me?

**Comment by mihallabrin** [comment]
I've been dealing with this same error for a while now. Updating the api or auth various ways did nothing to resolve the issue. Now what I did find that somehow when deploying between different environments my CallbackURLs and LogoutURLs inside of parameters.json were pointing to an old environment and were not valid. These should match your redirectSignIn and redirectSignOut URLs which are generated when you run amplify pull in your aws-exports.js. I used amplify to update auth and changed these URLs to the correct ones (which I had saved) and pushed that change. Everything worked as it should. 

I should mention I did have to also manually reset my federated sign in in Cognito, user pools, MY_POOL, App client settings after this.

My assumption is that wherever amplify stores these settings (as the URL's are correct when I log into my cognito pool and check) gets out of sync and forcing an auth update to change one or more of these values resets it. The error message seems to have nothing to do with the actual problem.

**Comment by akroll1** [comment]
You've got to be kidding me. I"m supposed to trust this in production?? Same errors, error messages are a block box.

Look, I appreciate the scale of the Amplify project but I left it a couple years ago because it wasn't ready... and now, it's still not ready to support production work.

**Comment by kaipi** [comment]
Exact same thing has been there last 8months using amplify and really getting on my nerves because there is no solution this same issue going rounds again and again.

**Comment by ammarkarachi** [comment]
@akroll1 @kaipi Is this error after pulling and then pushing?

**Comment by akroll1** [comment]
I believe that is what I did.

**Comment by ammarkarachi** [comment]
@akroll1 I am testing with the latest version, which version are you using?

**Comment by akroll1** [comment]
4.40.0

**Comment by akroll1** [comment]
@ammarkarachi Where is the best place to report bugs? I have a couple for you guys.

**Comment by rajmayank** [comment]
This is an expected behaviour and one, that is ideal for production workloads if you get the reasoning behind it.
 
Allow me to explain : Amplify is nothing but a wrapper for AWS CloudFormation and so are other AWS Dev Tools like AWS CDK, SAM etc. At some level they all come down to taking the user's preferences and translating them into CF Templates.
This means all the rules for CF apply to all these wrappers as well.
Now coming to CloudFormation, it is infrastructure-as-a-code so you are expected to provision, monitor and update the infrastructure via ... you guessed it... code i.e. your cloudformation template. In such scenarios AWS Console is meant to be just a visual interface to look and consume resources, not really modify them. This is because if the resources are updated OUTSIDE CF, then the next time you push your template (which by the way doesn't have the changes you made via the console) they will be overwritten or your push will error out as the resources have _drifted_
 
 
Coming to why this decision - it's to make sure your infrastructure is reproducible. Any action done via AWS Console on resources provisioned via CF is not reproducible in an automated environment. 
This is great if you think about it in production environments. You can have the exact same infrastructure synced across multiple environments, regions and even AWS accounts ! 
 
As for why `amplify pull` doesn't pull updates you do via the Console - well that is not how CF works. As I mentioned earlier, CF resources are supposed to be managed by Templates only ! No getting around that.

**Comment by ammarkarachi** [comment]
We have pushed a change the does an empty array by default if hostedUIProviderCredentials are not found in the deployment-secrets.json file
