### ISSUE TITLE
Lambda Layer versions CLI - Console

### ISSUE THREAD

**Issue by whahoo** [aws-amplify/amplify-cli#5072]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
The Lambda layer versions are not being kept upto date, between console deployments and local deployments
When I use amplify push from the CLI a new version of the Layer is created and the local state is updated and I can select that version for use with my other functions.
When the repository is pushed and triggers a CI build/deploy, AND a new lambda layer is created, this new layer version is not available to the CLI.
If I now push a 3rd layer version, the local CLI "names" it layer 2, but it is actually layer 3.

**Amplify CLI Version**
4.27.1

**To Reproduce**
CLI:
Add Layer function. (Creates layer function)
Amplify Push (deploys lambda layer 1)
Modify Layer Function
GIT Commit & Push
[Console CI Build triggered] (deploy lambda layer 2)
Amplify Push ( deploy lambda layer 3, but thinks its 2)

**Expected behavior**
Amplify push should retrieve actual lambda layer versions from cloud and not rely on local state, as it can be out of date

**Screenshots**
<img width="945" alt="Screen Shot 2020-08-13 at 10 44 44 am" src="https://user-images.githubusercontent.com/12714564/90083104-fecc1380-dd54-11ea-8b3c-5ad0622a678d.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. v12.18.0

**Additional context**
Compounding my issue here is the fact that the CI build is incorrectly adding new lambda layers, as the amplifyPush is not running an npm install on the lambda layers, and was creating empty layers.

I understand __now__ that the layer expectation is that the repo is complete and self contained, but it has really complicated my workflow.
The problem of the versions remains however, that I can not configure my functions with the correct version as the local CLI state isn't correct.

**Comment by tomhirschfeld** [comment]
+1, I have the same issue, its making my deployments very brittle as there is no real effective workaround that I know of besides just manually setting the layer version in the console

**Comment by slatemates** [comment]
+1 same issue

**Comment by micduffy** [comment]
+1 also same issue, Workaround is to amplify function remove all my lambdas and then remove the layer - then add them all back again. Results in them going haywire again shortly after

**Comment by praneybehl** [comment]
+1

**Comment by benmj** [comment]
Any update on this @jhockett? Our team is interested in offloading the build to the CI console, but so far the Amplify CI console does not appear to pick up changes to our layer code?

**Comment by kennandavison** [comment]
Seems like best workaround is creating a new layer for every version. :X

**Comment by arturocanalda** [comment]
+1

**Comment by arturocanalda** [comment]
+1

**Comment by rodrigovive** [comment]
+1

**Comment by 6foot3foot** [comment]
Same here, I have to manually change the layer in the console.  The description will say 'layer version 5' but the actual layer version in the console is 10.  But the CLI only shows up to 5. 

@kennandavison I tried this, however now I'm unable to delete the layer as it thinks it's still in use by the function.  (It isn't I've moved it to the new layer)  now I have a dangling layer I can't remove, and all my layers are out of sync in amplify resulting in me manually making changes through the console, which isn't great for the CI/CD pipeline.

**Comment by kennandavison** [comment]
@6foot3foot - yeah, I had that as well. I ended up grepping/deleting references in the cloudformation files.

**Comment by micduffy** [comment]
for me its a lot like a box of chocolates, you never know what you're going to get (version wise)

**Comment by arturocanalda** [comment]
@micduffy same feeling here. Decided to refactor the code to have less dependencies of my lambda layer. Now I only use it to pack all the heavy node_modules together and it's used by a single function.

Just one extra issue I had (on top of versioning). When changing amplify environments, sometimes, somehow, a new version of the layer was created (which we already know) + the `node_modules` folder was empty. That was making all the lambdas depending on the layer break.

**Comment by 6foot3foot** [comment]
![lamba_layer_version_issue](https://user-images.githubusercontent.com/26568579/96182881-95ee5b00-0f92-11eb-8e86-5d254cd35a27.PNG)
This is the issue I'm seeing.  amplify is going by the description not the actual version.  so version 8 doesn't have the right code, it's version 12 I need.  But amplify will only show up to 8.  (As a note all my uploads of this function have only been through the amplify CLI, so not sure why the version stayed at 1 for a while, jumped to 2 then back to 1)

**Comment by kennandavison** [comment]
Not sure if related, but 

> @micduffy same feeling here. Decided to refactor the code to have less dependencies of my lambda layer. Now I only use it to pack all the heavy node_modules together and it's used by a single function.
> 
> Just one extra issue I had (on top of versioning). When changing amplify environments, sometimes, somehow, a new version of the layer was created (which we already know) + the `node_modules` folder was empty. That was making all the lambdas depending on the layer break.

+1, so many things broken here

**Comment by cc-bojan** [comment]
+1
I'm facing the same issue. My latest version for *dev* environment is 4, however when I'm updating function using amplify-cli, I'm only able to select version 1:

<img width="1271" alt="1" src="https://user-images.githubusercontent.com/44865325/98832939-bc8e9d00-243d-11eb-9abd-ef3b88529d55.png">

<img width="1117" alt="2" src="https://user-images.githubusercontent.com/44865325/98832972-c57f6e80-243d-11eb-94c1-8dd375f983d9.png">

**Comment by jhockett** [comment]
Hi all, we are actively looking into reworking how layer versions work in the CLI so that this version de-synchronization doesn't happen.

**Comment by micduffy** [comment]
Thats great to hear. In our application, we always use latest version with our shared layer. We have a temporary workaround in place which is to associate to the latest version, and then remove all other old versions.

This seems to work okay as an interim measure - but there are still manual steps when we move between environment.

Hope this helps

**Comment by danieletieghi** [comment]
Workaround Here :-)

So, I'm working on a Gatsy project where I use console re-deployment any time I need to update the contents.
Since Lambda layers became available in amplify I thought to tidy up a bit and implemented one for starter (and arrived to version 3 on the same day). Today I needed to update it and the lambda using it kept giving error, then I discovered me and Amplify thought we were at layer version 4 but in reality we were at layer version 30 :-D

(so, beside fixing the misalignment could you please also work on avoiding un-needed re-deployments?)

Anyway after playing for a while I found that if I manually changed the last version number (from 4 to 30) in the dedicated part of team-provider-info.json file.

`
"nonCFNdata": {
      "function": {
        "<lambda-layer-name>": {
          "layerVersionMap": {
            "1": {...},
            "2": {...},
            "3": {...},
            "30": {...}
}}}}
`

and then re-updating the consuming lambda amplify proposed me to use layers 1, 2, 3 and 30. Selecting 30 simply worked.
After this I needed to do a few more changes and amplify automatically created/used layer version 31 without further intervention ;-)

**Comment by micduffy** [comment]
That is good, but try it with a multi environment deployment. In different
environments U can can very possibly get burned

**Comment by danieletieghi** [comment]
I have it :-/ but luckily I'm still not in production so for now I'm burying my head in the sand and waiting for the fix before merging branches

**Comment by micduffy** [comment]
We have a script we run after deployments that causes all of our lambdas to
use latest version of our shared layer

**Comment by danieletieghi** [comment]
Great Idea! If I have more problems I'll create something similar. Do you simply change the layer version in every lambda cloudformation template json or else?

PS: do you know if there is a repository of amplify-lifesaving scripts? I also created a useful bunch of those and it should be nice to share them.

**Comment by micduffy** [comment]
we use python to update the cloudformation template json.

Closest thing to a repo of amplify-lifesaving scripts would be this I reckon : https://github.com/dabit3/awesome-aws-amplify

**Comment by Nxtra** [comment]
Just ran into this too.
Would it be solution to create the layer as a custom resource in the custom resources stack.
And then, when configuring the function, reference the layer as an external layer using the arn of the layer?

**Comment by matansagee** [comment]
+1

**Comment by patrickliechtypersonal** [comment]
@micduffy could you share your script to use the latest layer version after deploy?

**Comment by tomhirschfeld** [comment]
ok friends, when can we expect a fix here?

This has been a terrible issue on my team of 5 developers and it really slows us down. When I think of my canonical reason why I advise people to avoid amplify I think of this specific github issue. This specific problem is such a classic example of everything wrong with amplify.
 
1) very basic functionality is completely broken when used in a team environment
2) amplify maintainers know its an issue and decide instead to focus on things that will get them promoted like launching flutter support or new lambda runtimes, instead of things that will make the framework actually productive, like fixing the devastating bugs that make amplify unusable.


I have lost so much trust in the amplify framework in the past year as I have seen countless things break on version updates, not work in team environments, and the focus of the team seems to be on launching new features, not making anything useable. 

I am very happy to work with anyone on the amplify team to help improve the product! I consistently file bug reports, but it seems like nothing gets done. Is there some what I can get a pm/em contact within the amplify team and have our team do a brain dump with the highest value improvements we see?

**Comment by houmark** [comment]
Well said @tomhirschfeld — agree 100%.

If you get such a call, please include me :) Nearing two years with Amplify and I while it's very powerful, the amount of unsolved bugs that are introduced constantly makes me hate having decided on Amplify more often than I'm happy about it. The Amplify team seems to be lacking leadership and focus on stabilizing the platform, before they add new stuff that's halfway broken.

**Comment by litwicki** [comment]
@tomhirschfeld we are actively working on this right now in fact. I assure you we take these bug reports very seriously, and I take responsibility for the lack of communication and transparency. We can do better. I would love to setup a call with you and/or your team so we can make sure we're addressing this and any other issues you're having. Please let me know how we can get in touch to schedule a meeting at your convenience. 

@houmark of course we'd be happy to do the same with you. Please let me know how we can be in touch and I will make sure both I and someone on the team is available.

**Comment by renebrandel** [comment]
@tomhirschfeld @houmark - to add to Jake's comment. We've spent the last few weeks redesigning the Lambda layers (and other areas of the function category) architecture as a whole to address this class of issues holistically. Our intention is to tackle all the Lambda layer issues listed [here](https://github.com/aws-amplify/amplify-cli/projects/14) with that redesign. We are starting the implementation of the redesign this week. 

This redesign focuses on removing the local layer version tracking, an updated template to simplify the CLI workflows, and a different change detection algorithm. Once we have a testable version, we can provide a beta release for you to also verify the changes.

In terms of "functions improvements roadmap" - the improvements projects are currently worked on in this order:
[Function mock](https://github.com/aws-amplify/amplify-cli/projects/17) - the latest release this week should close out all 15 issues
[Function triggers](https://github.com/aws-amplify/amplify-cli/projects/13)
[Function layers](https://github.com/aws-amplify/amplify-cli/projects/14)

**Comment by tomhirschfeld** [comment]
Thanks, I appreciate the reply! 

I apologize if I sounded harsh in my message, I was fairly frustrated that we had a blowup on our system with layers this week that ended up wasting a day and made one of our devs pretty depressed, and I checked the workboard posted above and it seemed that none of the tasks had any progress and have been in the "todo column" for a long time.

I am trying to be a good player here and help things work for everyone.      

@litwicki please email me at tom@productwind.com and we can schedule a call. Before we chat, I want to through the issues our team has logged, organize/rank it in terms of our pain so that we can be as productive as possible.

**Comment by houmark** [comment]
@renebrandel Thanks for coming back so fast. I did see you became PM for Amplify fairly recently, so I was hoping that would be good news.

I'd love to do some type of roundtable with other Amplify users and some of the Amplify team at AWS — in a good spirit. I think this could be beneficial to everyone and if followed up with a roadmap for both fixes, but also important missing features, Amplify may have a future for many that have started to discard it, or like us, considering to do so.

Just adding one thing I have mentioned in the past. The changelog is really a mess. In the past there was no working changelog at all. Now it seems there is some kind of changelog, but it's not detailed. It makes it virtually impossible to spot any breaking changes. For that reason, we are currently trailing Amplify CLI updates by 1-2 months (we learned the hard way one too many times that it's not a good idea to update too often). We actually enter the Issue tracker and look for really breaking bugs before deciding which version we will attempt updating to, but that's not really the way to do this.

I think Amplify can do better on that also. Many even small open-source libraries follow SemVer carefully and write very precise changelogs that are broken down into features, bug fixes, and breaking changes. The nature of Amplify should really require a well-updated changelog at the least.

**Comment by waynebrantley** [comment]
@renebrandel I would suggest something more like a zoom meeting as there would be many people on it!

**Comment by benmj** [comment]
I'd love to be involved in any sort of call along with some of my engineers.

**Comment by micduffy** [comment]
Maybe we start another thread to arrange this meet up? Suggestion only

**Comment by biddster** [comment]
I'm really suffering from this too. 

I have an app with 2 apis. 1 public, 1 private. Both apis share a common lambda layer. Each env has its own AWS account and I mostly push versions to dev before releasing to prod. It's only a small project so I'm just git tagging locally and publishing to prod locally. No pipelines yet.

However, I now have 30 common layer versions in dev versus 8 in prod. In team-provider-info.json I have 26 layers listed for dev and 6 for prod. I've no idea how those have got out of sync. 

Looking in the respective AWS accounts for dev and prod, I can see that there are lots of discrepancies between the actual layer version and the lambda layer version in the description of the layer. 

If I use the cli to update the functions in prod, I'm only offered 6 versions (presumably this is due to the omissions in team-provider-info.json?). Dev suffers similarly.

I'm working around this at the moment by manually editing the respective cloudformation function templates and setting the correct lambda layer version for the environment in the layer arn. 

Looking in the function-parameters.json for each function, there is a lambda layer version which doesn't appear to be scoped by environment so I don't see how that could ever work.

I really want this to just work. If I make changes to the layer, I want the 2 functions to immediately be using it. I want to be able to say latest layer and my functions just follow the common layer.

Have I missed something?

**Comment by pagameba** [comment]
Also really suffering on this. I just added lambda layers to my project to solve a problem somewhat elegantly and it has completely screwed up our environments, everyone on my team has their own account and every change to the layer basically fails to deploy for lambda versioning issues. We are going to have to remove the lambda layer and I don't even know how we are going to solve this. The problem seems to be that I have a previous layer by the same name and even though I deleted my stack, it now creates the new layers at an incrementally larger number than the previous ones in the console but amplify thinks its back at version 1 (which no longer exists and cannot be recovered).  I think I'm going to have to delete my AWS account.  What we need is a way to update layers and have all the references point at LATEST unless specifically pinned to a particular version.  I'm not sure what the use case is for updating a layer and NOT updating all the referencing functions to it by default.  Sorry if I sound frustrated, but ... I am!

**Comment by jhockett** [comment]
Hi all!

We have an alpha build of our redesign of Lambda layers in Amplify CLI available to try. This includes several bug fixes and new features. It also includes a **one-way migration** step for existing layer resources. Lambda layer resources pushed with this build will not work with any other version of the Amplify CLI.

**DO NOT USE THIS IN PRODUCTION!**

To test it out: `npm i -g @aws-amplify/cli@not-for-production-layers`

Notable changes:

- Complete redesign of layer version tracking. New code does not make assumptions about what layer versions exist in the cloud and always pulls the latest data from the Lambda service
- Option to automatically update dependent functions to the latest deployed Lambda layer version
- Added ability to delete individual layer versions
- Layers now have a dependency installation step that will install dependencies based on what's in `package.json` for NodeJS or `Pipfile` for Python
- Support editing layer version descriptions
- Removes local version state tracking from `amplify-meta.json` and `team-provider-info.json`

We'd love to hear any community feedback!
