### ISSUE TITLE
Duplicate Pinpoint projects created when creating new Amplify environment (breaks push notifications)

### ISSUE THREAD

**Issue by mdoesburg** [aws-amplify/amplify-cli#5079]
**Describe the bug**
I have a project which uses push notifications. Upon creating a new environment by following the steps outlined [here](https://docs.amplify.aws/cli/teams/overview#setting-up-prod-and-dev-environments), the Amplify CLI prompts the user for APNS and FCM credentials prior to pushing. After supplying the credentials, the Pinpoint project gets created on AWS. This all happens before pushing the project to the cloud. After successfully going through all the `amplify env add` steps, and finishing with `amplify push`, the Amplify CLI creates another Pinpoint project, resulting in 2 Pinpoint projects.

I compared the `amplify-meta.json` files from my initial env (dev) and my new env (test), and noticed that the new (test) environment has a different `output.Id` under `analytics` than the `output.Id` under `notifications`. The initial env has the same output IDs for these categories.

This is problematic, because I have 2 Lambda functions which send out push notifications. They both have all the permissions for the 'analytics' category. Whenever one of these functions attempts to send a push notification in the test env, it fails because the function has the wrong Pinpoint ID.

**Amplify CLI Version**
@aws-amplify/cli@4.27.1

**To Reproduce**
1. Create an Amplify project
2. Add push notifications
3. Create a new environment
4. Witness duplicate Pinpoint project

**Expected behavior**
I expect only one Pinpoint project to be created, and my new enviroment to match my original environment.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina
 - Node Version. v14.4.0

**Comment by mdoesburg** [comment]
The [Amplify docs](https://docs.amplify.aws/lib/push-notifications/getting-started/q/platform/js#requirements) suggest that you need to setup the Analytics category before adding the Notifications category:

> Push Notifications category is integrated with AWS Amplify Analytics category to be able to track notifications. Make sure that you have configured the Analytics category in your app before configuring the Push Notifications category.

[This Medium post](https://medium.com/@dantasfiles/setting-up-android-push-notifications-with-aws-amplify-e6334c6356d8) suggest you shouldn't:

> Note: Do NOT also run amplify add analytics because amplify add notifications already initializes an AWS Pinpoint project, called AmplifyAndroidPushXXXXX-env

I did run `amplify analytics add` prior to running `amplify notifications add` in my initial environment. Could this be what causes the issue when making a new environment?

**Comment by mdoesburg** [comment]
For anyone else facing this issue, the workaround for now is:

1. Remove Lambda Analytics category dependencies/permissions
2. Remove Analytics category
3. Remove Notifications category
4. Push changes
5. Add Analytics category
6. Push changes
7. Add Notifications category
8. Add Lambda Analytics category dependencies/permissions

After basically removing and re-adding the Analytics and Notifications categories, your new environment will only end up with one shared Pinpoint project.

**Comment by avlonder** [comment]
Any decent solution yet?

**Comment by johnf** [comment]
I've spent most of the day debugging this issue.

Adding of notifications needs to happen first,
When you then add analytics, the pinpoint provider detects that notifications exist and it writes the appId to the parameters.json
The cloudformation doesn't create a new pinpoint instance if an appId is passed.

The problem though is that this will then fail when creating a new environment or switching between envronments.

When creating a new environment the first thing it does before the push is setup notifications and therefore creates a pinpoint instance.

If you then perform the push, because the AppId is saved in parameters.json it doesn't create a duplicate but now the aws-exports will reference an instance from a different stage that doesn't exist.

**Comment by johnf** [comment]
Current workaround when adding a new environment
* amplify env add NAME - to create the new environment
* Find the appid in team-provider.json for pinpoint
* Update amplify/backend/analytics/NAME/parameter.skon and set AppId
* amplify push

**Comment by dylan-westbury** [comment]
Seems to be still a problem.

Separate pinpoint created for notifications / analytics.

Deleted one thinking it wasn't in use, now we got a whole bunch of problems 😅

**Comment by michaetto** [comment]
It just happened to us using amplify cli version 7.6.23.

**Comment by Pickleboyonline** [comment]
Still happening to us as well, except when using the recommended fix to hardcode the appId in the parameters amplify ends up deleting the original Pinpoint Application. The only way for Amplify to create a new Pinpoint application is to remove the appId and have it blank.

**Comment by biller-aivy** [comment]
asked for the .p12 again and again... some error here.

**Comment by bgneu** [comment]
Since the previous workaround no longer seems to work, this may help some of you facing this issue. 

I just went through this process and it is what worked for me as of version 9.1.0 of the CLI.

```
1. amplify env add <YOUR_ENV>
    - Follow the prompts to setup notifications
3. amplify remove notifications
    - Choose what to remove. The Pinpoint application
    - Confirm that you want to delete the associated Amazon Pinpoint application Yes
4. amplify status
    - Notifications should no longer be showing, while Auth and Analytics should be in Create
![Screen Shot 2022-08-02 at 4 00 35 PM](https://user-images.githubusercontent.com/29488885/182462688-f62547d3-5d82-43be-9aaf-23de7bb6f385.png)
5.  amplify push
    - Are you sure you want to continue? Yes
6. amplify add notifications
    - Follow prompts to setup notifications again
```

At the end of this I only had one pinpoint project that was setup as I expected it to be. Hope it helps

**Comment by Duder-onomy** [comment]
This is still a problem,  even on the latest Amplify CLI.  
Makes CI/CD with fresh backend environments really frustrating when anything that depends on Pinpoint starts failing. 
For me, this breaks anything that touches Pinpoint.

**Comment by Etep15** [comment]
I believe I just ran into this as well. I'm not sure why since I've had a dev and test environment for months and the CI/CD has been working great. But what I didn't realize is that notifications weren't working on the test side (testers glossed over it). I now need to add the project ID in my code to send notifications in the test environment but of course I have two (actually three for some reason all with the same creation date back in March of this year). 

Regardless of getting notifications working on our TEST environment I ran into the CI/CD issue where it hangs and then eventually times out after 30 minutes. In the amplify build logs it gets stuck at :

`2022-10-06T17:36:49.610Z [WARNING]: - Building resource auth/[REDACTED]`

Not much to go on but between this ticket and #2541 listed above I'm drilling down into this pinpoint issue. I'll try the solution @bgneu has suggested on our test environment and see what happens.

**Comment by lazpavel** [comment]
Hi @mdoesburg the issue with duplicate pinpoint projects should be fixed in latest Amplify CLI

**Comment by osehmathias** [comment]
Further, when I pull down

`amplify pull --appId d1p8jrlphkviwn --envName dev`

Then check my amplify config file, I can see it's referencing the deleted pinpoint project. 

```
    "analytics": {
        "plugins": {
            "awsPinpointAnalyticsPlugin": {
                "pinpointAnalytics": {
                    "appId": "d2beb632edfb40f38d7a62526b8c2c8b",
                    "region": "ap-southeast-2"
                },
                "pinpointTargeting": {
                    "region": "ap-southeast-2"
                }
            }
        }
    },
```

There is no Pinpoint project with this ID in my account.
