### ISSUE TITLE
sorted @connection with @key with multiple fields

### ISSUE THREAD

**Issue by hanzhaodeng** [aws-amplify/amplify-cli#5101]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[official AWS Amplify Console forum](https://forums.aws.amazon.com/forum.jspa?forumID=314&start=0)

**Which Category is your question related to?**
Key

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
4.26.0

**What AWS Services are you utilizing?**
Amplify API

**Provide additional details e.g. code snippets**

How would you go about making @connection work with a @key with multiple fields and having the result sorted?
Say we have:
```graphql
type Work
  @model
  @key(fields: ["name"]) {
  name: String!
  description: String!
  articles: [Article] @connection(fields: ["name"])
}

type Article
  @model
  @key(fields: ["workName", "index"]) {
  workName: String!
  index: Int!
  name: String!
  paragraphs: [Paragraph]  @connection(keyName: "byWorkNameArticleName", fields: ["workName", "name"])
}

type Paragraph
  @key(fields: ["workName", "articleName", "index"])
  @key(name: "byWorkNameArticleName", fields: ["workName", "articleName"])
  @model {
  workName: String!
  articleName: String!
  index: Int!
  text: String!
}
```

The @connection between Work and article works perfectly, as we supply work's name as partition key, and we can sort by the index, which is a sort key, in the query.

However with article and paragraph, as @key only support making first field the partition key, the articleName and index become sort keys, and when trying to make @connection between article and paragraph, the fields have to match all the keys. How do I make the index the sort key for paragraph then?
Essentially I want to achieve making the paragraph sorted by index.

One way I see out of it is to one partition key field instead of this "workName", "articleName". Do I need to maybe manually generate a composite key if I want to keep it related to the names? Is there a way to make it automatic like the composite sort key?

**Comment by edwardfoyle** [comment]
@hanzhaodeng I'm not 100% sure of your query pattern, but it seems like you could have a connection between the Article and Paragraph that's the same as the connection between Work and Article? ie
```graphql
type Article
  @model
  @key(fields: ["workName", "index"]) {
  workName: String!
  index: Int!
  name: String!
  paragraphs: [Paragraph]  @connection(keyName: "byArticleName", fields: ["name"])
}

type Paragraph
  @key(fields: ["workName", "articleName", "index"])
  @key(name: "byArticleName", fields: ["articleName", "index"])
  @model {
  workName: String!
  articleName: String!
  index: Int!
  text: String!
}
```

**Comment by hanzhaodeng** [comment]
Sorry I wasn't clear earlier.
I want to find the paragraphs that are by a article of a work. Namely I want to provide both the work name and the article name for the connection and have them sorted by index. 

If I provide them for the primary key   @key(fields: ["workName", "articleName", "index"]) it will say I am missing index, if I provide them for  @key(name: "byWorkNameArticleName", fields: ["workName", "articleName"]) then it is not sorted by index.

So I guess my question is, if you have a key of a,b,c 3 fields, and you want a connection that is a list of a,b and sorted by c, what do you do?

**Comment by hanzhaodeng** [comment]
Thanks for the reply btw.

**Comment by edwardfoyle** [comment]
Based on your schema, it looks like an Article can only be associated with one Work and a Paragraph can only be associated with one Article. So looking up Paragraphs for an Article transitively means all of those paragraphs belong to the Work that the Article is associated with correct? If that is true, then it seems to me that an `@key(name: "byArticleName", fields: ["articleName", "index"])` index on the Paragraph model will suffice. You can do one query to get the article for the work and another query to get the paragraphs for the article.

If you want to be able to do a single query at the expense of another GSI, you could use the following scheme:

```graphql
type Work
  @model
  @key(fields: ["name"])
{
  name: String!
  description: String!
  articles: [Article] @connection(keyName: "byWork", fields: ["name"])
}

type Article
  @model
  @key(name: "byWork", fields: ["workName", "index"]) {
    id: ID!
  workName: String!
  index: Int!
  name: String!
  paragraphs: [Paragraph] @connection(keyName: "byArticle", fields: ["name"])
}

type Paragraph
  @key(name: "byArticle", fields:["articleName", "index"])
  @key(name: "byWorkArticleIndex", fields: ["workName", "articleName", "index"], queryField:"queryByWorkArticleIndex")
  @model {
  id: ID!
  workName: String!
  articleName: String!
  index: Int!
  text: String!
}
```
This will allow the connections to work properly as well as give you another query "queryByWorkArticleIndex" that you could query like:
```graphql
query getParagraphs {
  queryByWorkArticleIndex(workName: "work1", articleNameIndex: {beginsWith: {articleName: "article1"}}) {
    items {
      index
      text
    }
  }
}
```
This will be sorted by the compound sort key `<articlename>#<index>`. If you go with this approach, I would recommend changing index to be a string and padding the front with 0s because the sort of the compound key is alphabetical (and '10' comes before '2' alphabetically).

**Comment by edwardfoyle** [comment]
@hanzhaodeng The CLI does not provide a way to create a compound primary key automatically. If you wanted to do that you would need to modify the VTL resolvers manually. Based on that other issue you linked, we may consider adding that feature in the future, but generally speaking making the partition key of the index a UUID is a good idea to minimize partition hot spots (see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-uniform-load.html)

I would recommend giving the Articles a unique identifier (you can use `id: ID!` which the autogenerated resolver will populate for you if one is not specified in the create mutation) and then modify the "byArticle" index to query based on article id rather than article name.

**Comment by hanzhaodeng** [comment]
Thank you.
Yes it just seems a bit not intuitive when you can automatically generate a query that list things yet it can be made to work with @connection. Thanks for the help and considering adding it the CLI.
