### ISSUE TITLE
How can I send push notifications from a lambda function?

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-cli#5113]
Hello, 

Every time a specific events happens, for example, a user visits another user's profile, I want to send a push notification to that user. 

Reading amplify docs, I see that we can use pin point
https://docs.amplify.aws/sdk/push-notifications/getting-started/q/platform/ios#manual-configuration

but I am very confused. I don't want to run a campaign or use analytics, I just want to send a push notification to a very specific user when using a lambda function. (BTW, my app uses Cognito and Aurora Serverless).

Reading the docs, it appears it is possible to target a specific user:
"The Amazon Pinpoint console enables you to target your app users with push messaging. You can send individual messages or configure campaigns that target a group of users that match a profile that you define. "

But I don't see how to do that. There are 3 pages in the documentation but nothing about how to do it.

Should I use SNS in my lambda functions? (it seems to me it is not integrated in the same level as pin point)

Apart from that, can I use amplify environments to have dev and production certificates, each one in a different environment?

Any ideas? Thanks!

**Comment by edwardfoyle** [comment]
Hi @Ricardo1980 this seems like a good question to ask the Amplify communtiy on our discord channel: [discord.gg/amplify](https://discord.gg/amplify)!

**Comment by Ricardo1980** [comment]
@edwardfoyle 
I did that before posting this question here, but no reply.

I think one of the reasons is because Discord itself. There are a lot of questions and all of them are mixed, not different threads like Slack for example. This is very confusing if you want to help people.

**Comment by edwardfoyle** [comment]
@Ricardo1980 if you want to stay purely within resources supported by Amplify you could probably get something like this working with API Gateway + Lambda + Pinpoint. However, as you mention, Pinpoint is primarily designed around marketing campaigns rather than individual notifications. You could set up an SNS resource in a custom stack and connect that to your Lambda.

I'm not sure what you mean by "dev and production certificates" but you can certainly have separate environments for dev and prod. Each environment has it's own instance of all resources configured in the project.
