### ISSUE TITLE
How to manage DependsOn with amplify-cli and graphql-transformer?

### ISSUE THREAD

**Issue by Hideman85** [aws-amplify/amplify-cli#5182]
I'm working on a custom GraphQL transformer that needs to transform current generated unit resolver to pipeline resolver. The only issue I have is during the deployment:

```
CREATE_FAILED AWS::AppSync::Resolver The specified functions must exist before referencing them from a resolver.
```

So my new Resolver needs to wait for the Pipeline Function and this is done by CloudFormation thanks to `DependsOn`

  - I need to DependsOn inside the same stack UserGetResolver need to DependsOn UserPipelineFunction resource done like this:
  ```js
  //  The resolver need to wait the creation of the pipeline function
  if (typeof resolver.DependsOn === 'string') {
    resolver.DependsOn = [resolver.DependsOn]
  } else if (!Array.isArray(resolver.DependsOn)) {
    resolver.DependsOn = []
  }
  resolver.DependsOn.push(pipelineFunctionID)
  ```
  - But more tricky stuff, all generated nested stacks need to DependsOn the stack CommonPipelineFunctions but it looks like the stacks does not exist yet even in the `after(ctx: TransformerContext)` function of the GraphQL transformer

So how I attach the DependsOn for my nested stacks?

**Comment by yuth** [comment]
GraphQL transformer starts with single stack and splits the stack into separate stacks at the end of execution of the transformer. The splitting happens based on the [stack mapping](https://github.com/aws-amplify/amplify-cli/blob/c9ef47ca4720b873ef90894dd41cb5a090c5ed10/packages/graphql-transformer-core/src/TransformerContext.ts#L694-L696) of the resource when its being added. In order to add dependsOn you would get the resource that you want to depend on and add [`dependsOn`](https://github.com/aws-amplify/amplify-cli/blob/a8cdac5aabc3bf7cc2457b1cd0d454b6e4e4bfa2/packages/graphql-function-transformer/src/FunctionTransformer.ts#L127-L128) similar to what other transformers are doing

**Comment by Hideman85** [comment]
Of course I already found that piece of code but the issue is that the stacks are still not created in the template but I need to add the dependsOn on the resource that manage the stack `AWS::CloudFormation::Stack`

**Comment by Hideman85** [comment]
Hi @yuth I made progress on this side and made some changes to allow GraphQL transformers to apply updates on generated nested stacks you can find the changes there: https://github.com/Hideman85/amplify-cli/commit/847038d712a7ce65a2602d350211833e0e304b22

The transformation is working as expected. Maybe you can think to integrates these changes into the CLI.

**Comment by kaustavghosh06** [comment]
@Hideman85 Do you think you can submit a PR for this based on the changes you've made above in your fork? Our team would be happy to review and provide feedback for the same.

**Comment by Hideman85** [comment]
I've linked the commit in my previous message if they want to have a look (the commit is less than 20 modified lines). My fork is for testing purpose it does not follow any coding style or standard you have in the project.
