### ISSUE TITLE
Why does "amplify pull" require s3:PutObject permissions?

### ISSUE THREAD

**Issue by mrgrue** [aws-amplify/amplify-cli#5341]
I'm using amplify-cli version 4.27.3 on MacOS.

I've been trying to come up with a security policy for the least amount of access needed for developers to use Amplify. I want to make sure they can only pull changes, not push, so I stripped out all the update, delete, add, create, and so forth that I found here:

https://docs.amplify.aws/cli/usage/iam

It's a little out of date; for example, I had to add a bunch of stuff related to Pinpoint mobiletargeting.

The thing that surprised me, though, was that I had to add s3:PutObject for "amplify pull" to work. Without that action, I got access denied errors.

Why would Amplify need write access to S3 for an "amplify pull"?

Thanks!

**Comment by UnleashedMind** [comment]
The IAM policies documented here https://docs.amplify.aws/cli/usage/iam are for the Amplify CLI commands as a whole to properly function, not just for one command such as `amplify pull`. 
The amplify pull command's workflow depends on the current status of the project and user intention (specified with command line parameters). And it uses the project's deployment S3 bucket to store/update project artifacts for it to properly function. 
Some workflows, such as attaching an existing backend to a new frontend project needs to upload the updated metadata files to the deployment bucket, that's why the `s3:PutObject` is needed.

**Comment by mrgrue** [comment]
Ok, that makes sense. It's still a little concerning that someone that I'm trying to restrict to read-only access to the project is modifying files just as part of the pull. Are there specific S3 objects that "amplify pull" needs to modify that I can restrict access to?

**Comment by UnleashedMind** [comment]
it's the deployment bucket, you can find its name in the `amplify/team-provider-info.json` file for each of the backend envs.

**Comment by mrgrue** [comment]
Thanks for your help!
