### ISSUE TITLE
Amplify CLI fails with Error: Cannot add S3Triggera54de6aa due to a cyclic dependency

### ISSUE THREAD

**Issue by duncangroenewald** [aws-amplify/amplify-cli#5550]
**Describe the bug**
I am following the aws amplify photo albums tutorial but when building a new environment the S3 trigger fails with 'access denied' when calling S3.getObject().

Is there a separate step required to set permission for the S3 Trigger on the S3 bucket?  Perhaps I missed it.

In any event then I tried to run 'amplify function update' to give the function access to the S3 bucket and I then get the following error:

```
Error: Cannot add S3Triggera54de6aa due to a cyclic dependency
    at checkForCyclicDependencies (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/update-amplify-meta.js:188:15)
    at AmplifyToolkit.updateamplifyMetaAfterResourceUpdate [as _updateamplifyMetaAfterResourceUpdate] (/usr/local/lib/node_modules/@aws-amplify/cli/lib/extensions/amplify-helpers/update-amplify-meta.js:114:9)
    at updateFunctionResource (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/provider-utils/awscloudformation/index.js:144:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.executeAmplifyCommand (/usr/local/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-function/lib/index.js:193:5)
    at async executePluginModuleCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:153:5)
    at async Object.executeCommand (/usr/local/lib/node_modules/@aws-amplify/cli/lib/execution-manager.js:35:9)
    at async Object.run (/usr/local/lib/node_modules/@aws-amplify/cli/lib/index.js:82:9)
```

**Amplify CLI Version**
4.29.5

**To Reproduce**
N/A

**Expected behavior**
I would expect the function to work

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Node Version. v12.18.1

**Additional context**
N/A

**Comment by ammarkarachi** [comment]
@duncangroenewald You wouldn't need to add additional permissions on your trigger functions. 
To debug this I would make sure the files exists or not 
and the path to the object is valid

**Comment by duncangroenewald** [comment]
The issue appears to be that after creating the S3Trigger I added permission to the trigger to access API by using the 'amplify function update'.  

This created a policy with the same name as the S3Trigger's bucket access policy which clobbered the bucket access policy.

Seems like a flaw in the amplify-cli logic that allows this to happen.  Eventually I had to manually rename one of the policies as a workaround but you have to watch this each time you run the amplify-cli or it might get replaced if you subsequently run 'amplify function update' or 'amplify storage update'

**Comment by ammarkarachi** [comment]
Can you reiterate what steps you followed?

**Comment by walter-scott** [comment]
I just ran into this problem as well, so here is how I ran into it: 

1. used `amplify add function` to create new function "S3Trigger"
2. while creating "S3Trigger" I set gave it full create, read, update, delete access on my amplify configured S3 Storage bucket "MyBucket"
3. used `amplify update storage` and attempted to make "S3Trigger" the trigger
4. Amplify CLI fails with the message "Cannot add S3Trigger due to a cyclic dependency"

**Comment by cybercussion** [comment]
I just ended up in this situation too.  I had a Lambda Function given access to a storage S3Bucket, then I went back to the Lambda Function to allow it to post to the DynamoDB GraphQL storage and ended up with the same error.

**Comment by arealmaas** [comment]
Getting the same error as you @walter-scott . Were you able to fix it? .. or is this fixed?

**Comment by walter-scott** [comment]
@arealmaas This is how I got around it:

1. Delete the old trigger lambda and the storage bucket you already created in the cli. 
2. Create a "Hello World" lambda to be used as the trigger, granting it no access to the storage bucket (you can't do grant access to storage anyways because it doesn't exist).
3. Create your storage bucket & while creating select your newly created lambda as the trigger for that bucket.

Doing this creates adds this policy below to the `s3-cloudformation-template.json` file for the storage bucket, so there is no need to further grant the function access to the storage. I assume the fact that this policy is created by adding the lambda as a trigger to the bucket is what causes a "cyclic dependency" when you try to grant access through modification of the lambda in the cli. They should make it clear that there is no need to grant the lambda access. Hope this helps!

```json
"S3TriggerBucketPolicy": {
            "DependsOn": [
                "S3Bucket"
            ],
            "Type": "AWS::IAM::Policy",
            "Properties": {
                "PolicyName": "amplify-lambda-execution-policy",
                "Roles": [
                    {
                        "Ref": "functionYourLambdaTriggerNameLambdaExecutionRole"
                    }
                ],
                "PolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Action": [
                                "s3:PutObject",
                                "s3:GetObject",
                                "s3:ListBucket",
                                "s3:DeleteObject"
                            ],
                            "Resource": [
                                {
                                    "Fn::Join": [
                                        "",
                                        [
                                            "arn:aws:s3:::",
                                            {
                                                "Ref": "S3Bucket"
                                            },
                                            "/*"
                                        ]
                                    ]
                                }
                            ]
                        }
                    ]
                }
            }
        },
```
