### ISSUE TITLE
Field level @auth has unexpected behaviour (iam provider)

### ISSUE THREAD

**Issue by cm-datrics** [aws-amplify/amplify-cli#5582]
**Describe the bug**
When I use field level authentication on a `@model` so that public (unauth IAM requests) have `update` permissions on a given field, public users can then update any of the fields.

Also, when making a graphql mutation request to update the field in question, the update succeeds but the response always contains `null` for that value.

**Amplify CLI Version**
4.29.7

**To Reproduce**
Using IAM as the authentication method, with the front end users either logged in (authenticated) or not (unauthenticated)
Say I have this model
```gql
type Order 
@model
@key(name: "byOrderMonth", fields: ["month", "createdAt"], queryField: "byOrderMonth")
@auth(rules: [{allow: public, operations: [read], provider: iam}, {allow: private, provider: iam}]) {
  id: ID!
  month: String!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime
  items: [ItemLine!]!
  status: Status!
  total: Int!
  orderNotes: String
  customerArrived: Boolean
}
```
As expected, the unauthenticated front end users can read an order but any mutations are blocked as they don't have permissions. Now say I modify the `customerArrived` field to be:

```gql
customerArrived: Boolean @auth(rules: [{allow: public, operations: [read, update], provider: iam}])
```

I can then update this field from the front end `Amplify.API` client with gql mutation,
e.g.
```js
const input = {
    id: orderId, customerArrived: true, orderNotes: 'hello',
  };
const result = await API
  .graphql(graphqlOperation(mutations.updateOrder, { input }));
```

 but:
1. When updating the field, the response from the mutation will always have `customerArrived: null`
2. I can also update any of the other fields with an unauthenticated user (`orderNotes` is changed to 'hello' and this is returned on the mutation response as well)

**Expected behavior**
I would expect that after modifying the schema like so, I can then only update that field with unauth user, and if I try to update any other fields it should fail the request.

Also, I would expect that on the mutation response, I would get the updated value e.g. `customerArrived: true`

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version. 10.15.0

**Additional context**

My solution to get around this issue will have to be removing the field level auth and exposing a lambda endpoint just to update that one field as the lambda will have sufficient permissions.

**Comment by RossWilliams** [comment]
Hi, your point 2 is a security flaw that has been pointed out before. The documentation was updated to note this possibility, although I can understand that it is very hard to catch the nuance unless you already know the details

From the docs:
>  In addition an owner can perform an update operation on the Todo object, only when the content field is present as a part of the input. 

The issue was first pointed out in #2241 , I've previously fed back that the documentation needs to be more explicit [here](https://github.com/aws-amplify/amplify-cli/issues/2241#issuecomment-560940349) and [here](https://github.com/aws-amplify/amplify-cli/issues/2241#issuecomment-533888322)

**Comment by yuth** [comment]
The GraphQL transformer does not support `IAM` and `API Key` provider in field level. The reason is that the passed context doesn't have the necessary information in when executing resolver code like a JWT token from Cognito User Pools has. I have created an [PR to update the docs](https://github.com/aws-amplify/docs/pull/2548) to clarify this further, and also we can make a DX improvement to warn when field level auth is added with either `IAM` or `API Key` provider. I've added a [backlog task](https://github.com/aws-amplify/amplify-cli/issues/5594) for this and will raise it with the team.

For explanation on the `null` issue when updating the field, the response from the mutation will always have `customerArrived: null`. This is an [documented](https://docs.amplify.aws/cli/graphql-transformer/directives#field-level-authorization) behavior to protect field level results in subscriptions as subscription uses the output of a mutation and publishes it to all the subscribers.
> Per-Field with subscriptions

> When setting per-field @auth the Transformer will alter the response of mutations for those fields by setting them to null in order to prevent sensitive data from being sent over subscriptions. For example in the schema below:"
