### ISSUE TITLE
Auto generated id is getting by default

### ISSUE THREAD

**Issue by meetrij** [aws-amplify/amplify-cli#5650]
**Describe the bug**
Automatically generating `id` when defining graph model

This is my original schema
```
type MasterCompProm @model(timestamps:null) {
  compPromId: ID!
  compProm: String
  cropId: ID
  status: Int
}
```

After amplify publish when I checked it from aws console Appsync schema section seen this
```
type MasterCompProm {
  id: ID!
  compPromId: ID!
  compProm: String
  cropId: ID
  status: Int
}
```

An extra row item `id` is generated which I don't need

**Amplify CLI Version**
4.29.2

**Expected behavior**
I should get like this
```
type MasterCompProm {
  compPromId: ID!
  compProm: String
  cropId: ID
  status: Int
}
```

**Comment by RossWilliams** [comment]
@meetrij how do you want to identity this item in the database? Do you want compPromId to be the primary key? If so, you need to add @key(fields: ["compPromId"]) directive to the object

**Comment by meetrij** [comment]
> @RossWilliams Thanks for the reply, yes that's my objective and will try as per your suggestion

**Comment by kaustavghosh06** [comment]
@meetrij Yeah, you can use @key to have custom primary-key's as @RossWilliams otherwise the Amplify CLI makes "id" the default primary key for every model. Closing this issue. Let us know if you face any issues with @key. You can find more docs on @key out here - https://docs.amplify.aws/cli/graphql-transformer/directives#key

**Comment by meetrij** [comment]
@kaustavghosh06, @RossWilliams it worked thanks once again
