### ISSUE TITLE
How to recover from a deleted user pool and link back a new userpool to an existing backend ?

### ISSUE THREAD

**Issue by maximelebastard** [aws-amplify/amplify-cli#5704]
**Which Category is your question related to?**
Auth

**Amplify CLI Version** 
4.30.0

This morning, I accidentally deleted my development UserPool.
It was still listed in the auth resources in CloudFormation - but when I clicked on it I was redirected to the list of the 
UserPools.
I tried to redeploy the project, but nothing recreates the pool - even an empty one.
I wanted to recrate the UserPool manually, but I had no way to create a new Userpool with the same ID than the one used by Amplify.

So I was stuck in this situation where Amplify was still trying to use a deleted UserPool and I had no way to recreate it with the same ID.

After hours of trying to find a solution, I deleted my dev environment (with all the DynamoDB data, all the S3 files, everything) and recreated a new one.

I just can't believe how a nightmare it would have been if the production UserPool had been accidentally deleted - because in addition to losing all my users I would have had no way to link back a UserPool to my production environment in Amplify.

What would have been the proper way to deal with a such situation ?

**Comment by edwardfoyle** [comment]
@maximelebastard In general, if you push a delete operation, there is no way to recover the deleted resource. Can you explain what you did to accidentally delete the UserPool? Did you remove it using the CLI or the Console. Under normal situations, you should be able to create a new UserPool without blowing away the whole environment and starting over.

If you want to create a new UserPool in the console and use that in an existing environment, you could look into the import auth feature that we recently launched: https://docs.amplify.aws/cli/auth/import. However, if you went that route, you would have to manually manage the UserPool rather than the CLI managing it for you

**Comment by maximelebastard** [comment]
@edwardfoyle First of all, thank you for answering me that fast. I appreciate it. 

It was actually a manual error from the Cognito Console. I was deleting a lot of UserPools created with the Amplify preview feature (they were in a Retain deletion policy) and I deleted the one from my dev environment with it.

What suprised me is that I was not able to have Amplify recreating it by running a new `amplify push`. Moreover, the user pool was still apearing into the CloudFormation stack but pointed to nowhere.

The push operation deleting the resources is an intersting case too. Do I have a way to avoid all my users to push from the CLI to my production environment ? What if someone runs a `amplify auth remove` and then pushes that to the production environment ?

**Comment by edwardfoyle** [comment]
@maximelebastard Likely the reason that the CLI was not recreating it is because the CLI uses hash diffs of the last push and the current push to determine which resources have changed. So if the last push contained the UserPool and the next one does as well, the CLI would think nothing has changed with the UserPool and not push it, even if the UserPool had been deleted in the Console. You could try running `amplify push --force` which will push all resources regardless of whether Amplify detects and update is necessary.

To your second question, I'm assuming by "users" you mean other developers working on your project? In that case you can (and should) scope the IAM policy that you grant your developers based on what we document here: https://docs.amplify.aws/cli/usage/iam. You could further restrict permissions by only allowing those operations on certain resources as documented here: https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_resource.html. Because all amplify-created resources have the environment name in the resource name, you can probably construct resource ARNs with wildcards to cover your development stage resources and not your prod stage resources. However, doing something like that will likely take some manual management on your part to keep the policy up to date.

**Comment by maximelebastard** [comment]
That's great pieces of information, thank you very much sir !
