### ISSUE TITLE
The formatWithJDF doesn't work `nowFormattedTypeError: moment(...).formatWithJDF is not a function breaking builds`

### ISSUE THREAD

**Issue by keng0o** [aws-amplify/amplify-cli#5709]
**Describe the bug**
output:
```
TypeError: moment_1.default(...).formatWithJDF is not a function
```

**Amplify CLI Version**
`"serverless-appsync-simulator": "^0.5.0"`

**To Reproduce**
- write vtl `#set($today = $util.time.nowFormatted("yyyy-MM-dd"))`
- run test(amplify-appsync-simulator)
- output error

**Desktop (please complete the following information):**
 - OS: MacOS
 - Node Version. v12.6.0

**Comment by edwardfoyle** [comment]
@keng0o Are you running into issues with a custom VTL resolver due to this? I am unable to repro any issue using `$util.time.nowFormatted()`. Also where are you getting the "serverless-appsync-simulator" dependency from? Amplify uses [amplify-appsync-simulator](https://www.npmjs.com/package/amplify-appsync-simulator). What version of the Amplify CLI are you using?
