### ISSUE TITLE
Public mutations with iam provider - No Current User Error

### ISSUE THREAD

**Issue by cnbrkkaya** [aws-amplify/amplify-cli#5876]
**Describe the bug**
I want to make a graphql mutation without cognito user pools provider. I want to use IAM as a Appsync authorization provider and give public access. My schema.graphql file is in the below. 

When i give **read** permission with public provider iam there is no error. But when i want to make permission to unauthenticated users to **create** orders i get no current user error.

**Expected behavior**
- Unauthenticated users with iam provider can create orders.
- Authenticated users with cognito (company owner) can read and delete this orders.

**Code Snippet**
```
type Order @model @aws_iam @aws_cognito_user_pools @auth(rules: [
                    { allow: owner, operations: [read, delete] }, 
                    { allow: public, provider: iam, operations: [create] }]) {

                    id: ID!
                   name: String
                   company: Company @connection(name: "CompanyOrders")
                  }
```

**Comment by amlcodes** [comment]
hey hey @sammartinez  is there any way around this at the moment?

**Comment by edwardfoyle** [comment]
@cnbrkkaya This sounds like the expected behavior to me. Owner based auth works by setting an "owner" field in the record to the username of the owner. But if unauthenticated users can create records, then there's nothing to put in the owner field and thus no way to authorized subsequent reads / deletes. You can either modify the mutation to include an owner field, or restrict this operation to authenticated users

**Comment by cnbrkkaya** [comment]
@edwardfoyle  Yes you are right, thanks. I restrict creating order operation to authenticated users only and no problem now.
