### ISSUE TITLE
amplify delete does not remove S3 deployment bucket

### ISSUE THREAD

**Issue by jaxondu** [aws-amplify/amplify-cli#60]
**Do you want to request a feature or report a bug?**

A bug.

**What is the current behavior?**

Issuing "amplify delete" command does not remove the S3 deployment bucket. 

**What is the expected behavior?**

If the removal of the S3 deployment bucket can not be done due to limitation of S3 and/or CloudFormation, it would be useful for "amplify delete" to list out those resources not removed by the command.

* **Output of ``amplify --version``**:

0.1.14

**Comment by kaustavghosh06** [comment]
@jaxondu Yes, we are aware of the S3 deployment buckets not getting deleted due to the limitation of Cloudformation of not deleting S3 buckets with content in it. 
That's the reason we have associated an "experimental" tag to the `amplify delete` command in the main README.md to get user feedback on this and then proceed with the next steps.
Thanks for the feedback.

**Comment by shasan-marsdd** [comment]
when rollback happens due to errors such as permissions (setting it up for users in our organization that shouldn't have full admin permissions).  "amplify init" or "amplify env add" fails due to "failed to create bucket, it already exists".  Even after we fix the permissions, deployment doesn't happen without manual delete of the buckets (not deployment, but other buckets such as hosting etc).  On a deployment that fails and rolls back it should deleting the bucket.
