### ISSUE TITLE
Cannot open AWS AppSync console from CLI (amplify console api)

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-cli#6053]
**Describe the bug**
I cannot deep link to AWS AppSync Console from the CLI

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.37.0

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable
1. Create GraphQL API `amplify add api`, `amplify push` 
2. Run `amplify console api`
```
? Please select from one of the below mentioned services: GraphQL
Error opening console.
Missing AmplifyAppId in amplify-meta.json
```

**Expected behavior**
`amplify console api` for GraphQL

**Comment by SwaySway** [comment]
Was the app created with an Amplify App Id?

**Comment by lawmicha** [comment]
no it wasn't

**Comment by kaustavghosh06** [comment]
@lawmicha I'm suspecting this happened since you hit the 25 app limit in your Amplify Console - only in that case an Amplify appId is not generated in your project (could you please check on that for me please?) and the `amplify console api` doesn't fall-back on just using the appId for the AppSync API which is a bug on our side.

**Comment by lawmicha** [comment]
Hi @kaustavghosh06 , i ran `amplify console` and went to "All Apps", under there are exactly 25 apps. they look like old samples of mine, i'll go and delete each app from that page. I usually clean up process is to go cloud formation stack and delete root stack when I want to clear my sample projects
