### ISSUE TITLE
How can I get a lambda layer code change to be detected by the CD pipeline, creating a new layer version?

### ISSUE THREAD

**Issue by djsmedes** [aws-amplify/amplify-cli#6100]
**Which Category is your question related to?**
Lambda layers, continuous delivery

**Amplify CLI Version** 
4.37.0

**What AWS Services are you utilizing?**
Lambda (Layers), CloudFormation, Amplify

**Provide additional details e.g. code snippets**
We are using a lambda layer to contain some bulky, infrequently changing dependencies for a single lambda function. However, we want to keep all of our environments isolated from one another, so we are deploying one lambda layer per environment.

This results in a file structure that looks like this (though this is much simplified):

```
.
└── amplify/backend/function/
    |
    ├── thisIsTheFunction/
    |   ├── src/
    |   └──thisIsTheFunction-cloudformation-template.json
    |
    └── thisIsTheLayer/
        ├── lib/nodejs/
        |   ├──package.json
        |   └──yarn.lock
        └──thisIsTheLayer-cloudformation-template.json
```

We have a couple of custom solutions that we've built to make this work nicely.

## Not committing `node_modules`
We are not committing the `node_modules` folder to version control for our layer. Instead, we run `yarn install` during our prebuild script that runs as part of the CD, so when it comes time for the `amplifyPush --simple` command, the files are there to be zipped. I describe this in a little bit more detail [on this comment on another issue](https://github.com/aws-amplify/amplify-cli/issues/4916#issuecomment-736820733).

## Not pointing out lambda at a specific version of the lambda layer
We are not pointing our lambda at a specific version of the lambda layer; instead, we're pointing it at whatever the most recent version of the layer is - or at least that's what we'd like to do. We have absolutely no need to even retain old versions of a layer, but obviously the way lambda layers function obligates us to do so.

In order to point our function at the most recent version of the layer, we've manually edited the cloudformation template such that `Resources.LambdaFunction.Properties.Layers` just points directly to the ARN of the layer, which is an `Output` of the layer's cloudformation template. Since the ARN includes the version, this results in us not needing to update the function if we were to make an update resulting in a new layer version. 

Much more importantly, this means that we can effectively spin up new environments at arbitrary times in the future. By hardcoding a lambda version in a cloudformation template, if you ever go past version 1, it seems that you would be breaking any ability to spin up a new environment from that point. Because the lambda layer wouldn't recreate its entire version history up to that point - it would just create layer version 1 using whatever the state of the code was at the point in time that you created the environment. So if your CF template told a lambda to look for layer version 2, it wouldn't exist, and presumably the thing would break.

# The problem

Our problem is that we cannot seem to convince the amplify CD to actually create a new version of our lambda layer. We've tried updating the `package.json` and `yarn.lock`, and also adding in an `opt/` folder and putting arbitrary markdown and javascript files in there (hoping that something somewhere would be detecting that diff and creating a new version)

How can we indicate to the amplify CD pipeline that our lambda layer has changed, and a new version should be created?

**Comment by attilah** [comment]
@jhockett @renebrandel I think this input can be valuable to our discussion around version handling and as when we change/enhance it perhaps we could enable this specific scenarios as well.

**Comment by btelman96** [comment]
Is there any way to force CI/CD to create another version or detect changes currently? Although I did not before now due to reasons below, manually updating the version in the json does not seem to be having an impact when using amplify CI/CD. I have the environment setup in team-provider-info.json, and am versioning a version 2 for the version everywhere to try to make it create that.

---

I think I am also running into this issue. The environment setup I am working with is pretty much structured the same. Don't really care about older versions (also can't seem to tell it to auto delete old ones as well, but that is a separate issue), just using it as shared code, and telling all of the lambdas via cloudformation to use the ARN instead of hardcoding the layer version. Whenever there is a deploy that should update it, amplify CI/CD appears to create the layer like it did not exist, but leaves the old version 1, and does not update its version number. Even though there have been multiple changes since the start of using it, I only see one lambda layer for each environment that is used (except for environments running `amplify push` locally). It tries to call code from it that should exist, but fails since the layer is old. I don't usually version lambda version number changes.

This is just a snippet of the beginning of the log
```
[INFO]: # Retrieving cache...
[INFO]: # Extracting cache...
[INFO]: # Extraction completed
[INFO]: # Retrieving environment cache...
[INFO]: # Retrieved environment cache
[INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
[INFO]: # Patching NPM package '@aws-amplify/cli' from 4.29.4 to 4.39.0...
[INFO]: # Done patching NPM package '@aws-amplify/cli'
[INFO]: ## Starting Backend Build
        # Starting phase: build
        # Executing command: amplifyPush --simple
[INFO]: 
[INFO]: [0mFor more information on AWS Profiles, see:[0m
        [0mhttps://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html[0m
[INFO]: [0mAmplify AppID found: redacted. Amplify App name is: redacted[0m
[INFO]: [0mBackend environment develop found in Amplify Console app: redacted[0m
[WARNING]: - Fetching updates to backend environment: develop from the cloud.
[WARNING]: ✔ Successfully pulled backend environment develop from the cloud.
[INFO]: [0mAdding Lambda layer apiUtils to develop environment.[0m
[INFO]: 
[INFO]: [33mNote: It is recommended to run this command from the root of your app directory[39
[WARNING]: - Initializing your environment: develop
[WARNING]: ✔ Initialized provider successfully.
[WARNING]: - Uploading files...
...
```

I see the layer gets updated below this snippet (that part was not included), but don't see any logs further below this indicating that code changes were detected, or that the version was increased, which does happen when running `amplify push` locally.

Below snippet was found in the local `amplify push` log when something changed, but not the log for amplify CI
```
UPDATE_IN_PROGRESS LambdaLayer AWS::Lambda::LayerVersion Thu Dec 17 2020 09:55:14 GMT-0600 (Central Standard Time) Resource creation Initiated
```

I could try manually handling versions, but not quite sure how well that works with multiple environments where they are not guaranteed to be running the same version. The flow is usually `test environment`(which gets pushed to via amplify cli instead of CI/CD) -> `staging/develop` -> `production`, where the local environment's layer version can be significantly ahead of `staging` and `production` , and there are multiple test environments, each with their own version.
As noted at the beginning though, that appears to not work either.

**Comment by btelman96** [comment]
Not the best way, but I was able to come up with a way to force update it for now without digging through amplify itself, although it will create versions when it does not need to, and sometimes create 2 versions in one deploy, but looks like the most reliable way I can find to make sure its updated. Please let me know if I overlooked part of the lambda layers api that would have allowed it to update without something like this.

Sometimes after adding this change, the first deploy detects changes, but if I remove the 2nd push and modify command, the first one will no longer detect changes every time when there are any. There is also the issue where it would be nice to change the DeletionPolicy, to delete instead of Retain, as the extra layers have to be removed via automated custom script, or manually. Errors are thrown if layer version 1 ever gets deleted though, assuming that version 1 is set in the jsons.

This will also increase the time of deploys, but would probably vary based on environment.

amplify.yml. Root of project
```
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
    postBuild:
      commands:
        - node ./force-update-layer.js #add this
        - amplifyPush --simple #add this
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
Those commands can probably be part of the build command, but I personally have them as postBuild

force-update-layer.js, where `{layer}` is the name of your lambda layer. Root of project. Pretty much just modifies a specific text file in the lambda layer by pasting in the current time, which forces a lambda update, ignoring whether or not an update is actually needed though.
```
var fs = require('fs');

let path = './amplify/backend/function/{layer}/opt/date-created.txt'
let date = new Date().toString()
console.log(`Update layer text file to ${date}`);

fs.writeFile(path, date, function (err) {
    if (err) throw err;
    console.log('Saved date!');
});
```


After this, the 2nd amplify push somewhere outputs this line
```
...
Content changes in Lambda layer apiUtilLayer detected. Layer version increased to 2
...
```

The version is upped to the next available version (ex. 7 if the latest version was 6). Internally in amplify cli, not sure which lambda it is checking for changes in, if it checks for changes compared to 6, or compared to version 1.

lambda layer cloudformation template
```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "Lambda layer resource stack creation using Amplify CLI",
  "Parameters": {
    "layerVersion": {
      "Type": "String",
      "Default": "1"
    },
    "env": {
      "Type": "String"
    },
    "s3Key": {
      "Type": "String"
    },
    "deploymentBucketName": {
      "Type": "String"
    }
  },
  "Resources": {
    "LambdaLayer": {
      "Type": "AWS::Lambda::LayerVersion",
      "Properties": {
        "CompatibleRuntimes": [
          "nodejs12.x"
        ],
        "Content": {
          "S3Bucket": {
            "Ref": "deploymentBucketName"
          },
          "S3Key": {
            "Ref": "s3Key"
          }
        },
        "Description": {
          "Fn::Sub": [
            "Lambda layer version ${latestVersion}",
            {
              "latestVersion": {
                "Ref": "layerVersion"
              }
            }
          ]
        },
        "LayerName": {
          "Fn::Sub": [
            "apiUtilLayer-${env}",
            {
              "env": {
                "Ref": "env"
              }
            }
          ]
        }
      },
      "DeletionPolicy": "Retain",
      "UpdateReplacePolicy": "Retain"
    },
    "LambdaLayerPermissionprivate1": {
      "Type": "AWS::Lambda::LayerVersionPermission",
      "Properties": {
        "Action": "lambda:GetLayerVersion",
        "LayerVersionArn": {
          "Ref": "LambdaLayer"
        },
        "Principal": {
          "Ref": "AWS::AccountId"
        }
      }
    }
  },
  "Conditions": {
    "HasEnvironmentParameter": {
      "Fn::Not": [
        {
          "Fn::Equals": [
            {
              "Ref": "env"
            },
            "NONE"
          ]
        }
      ]
    }
  },
  "Outputs": {
    "Arn": {
      "Value": {
        "Ref": "LambdaLayer"
      }
    },
    "Region": {
      "Value": {
        "Ref": "AWS::Region"
      }
    }
  }
}
```

parameters.json
```
{
  "layerVersion": 1
}
```

**Comment by djsmedes** [comment]
I mentioned in my original comment that we had tried putting a markdown file in the `opt/` directory -- we were basically trying to do the same thing. We named it `amplify-layer-version-forcer-3000.md` and all it contained was a single number, the idea being that you could manually increment it when you knew you were changing the layer.

So pretty similar to what you're doing @btelman96 except we were committing it to source control and manually changing it instead of running every time. But, it didn't seem to do anything for us. Did you try the approach of committing the file and find that it didn't work? What about having that script to update the file run in prebuild and then still only do one push?

I'm glad you found a workaround but unfortunately for us doing two `amplifyPush` operations as part of the build isn't going to work - as you say, increased deploy time depending on environment, and ours are already pretty long.

I wonder if you could get it to only run when there's been an actual change, but do it automatically, by having a script that instead of setting a timestamp, runs like an md5 hash of the entire `node_modules` directory and writes that hash to the file? I suppose you'd have to still have to get the new hash into your committed source code when it changes, which would still be a manual process, so it doesn't really gain you much 🤔

**Comment by btelman96** [comment]
I have tried running the date modify script at the beginning, or versioning it, but does not appear to affect it. After running the way it currently does, if I version a new date, and remove the 2nd push option in the `amplify.yml`, it creates a new layer the first time on its own, but does not detect changes after versioning a new date from local.

Here is pretty much what I am seeing in relation to when it decides to make a layer version change. Just including the relevant part of the `amplify.yml` file as an example of changes to that config on each git push.

Git push 1 config, no actual layer changes (layer update occurs only on 2nd push):
```
amplifyPush --simple
node ./force-update-layer.js
amplifyPush --simple
```

Git push 2 config, with layer changes (layer update occurs twice sometimes, or all times if actual layer changes occurred):
```
amplifyPush --simple
node ./force-update-layer.js
amplifyPush --simple
```

Git push 3 config with date changed before push, as well as the config itself (layer update occurs):
```
amplifyPush --simple
```

Git push 4 config with date changed before push (layer update does not occur):
```
amplifyPush --simple
```

---

I have not played around with it, but this may be useful to change amplify.yml more, but not quite sure how to best utilize it yet though.
https://docs.amplify.aws/cli/usage/headless
Was thinking with that, you could do a flow like this (commands could be slightly wrong):
```
amplify init //parameters are needed here for it to initialize correctly. Those commands are in the docs
amplify pull --yes //will pull the environment from the backend. Hopefully will use this to up layer if needed
git reset HEAD --hard //resets changes back to HEAD, since pull just overwrote files
git clean -f -d //removes any potentially added untracked files from the pull, but leaves gitignored files alone
amplify push --yes
```
I can test this later to see how well it works, but not quite sure if that will do what we want it to. For now, I will just use the first solution I supplied.

**Comment by akash87** [comment]
The changes are not detected for me no matter what changes I do on layer via CI/CD method. Layers on amplify is very buggy - request the amplify team to please look into this.

**Comment by jhockett** [comment]
Hi all!

We have an alpha build of our redesign of Lambda layers in Amplify CLI available to try. This includes several bug fixes and new features. It also includes a **one-way migration** step for existing layer resources. Lambda layer resources pushed with this build will not work with any other version of the Amplify CLI.

**DO NOT USE THIS IN PRODUCTION!**

To test it out: `npm i -g @aws-amplify/cli@not-for-production-layers`

Notable changes:

- Complete redesign of layer version tracking. New code does not make assumptions about what layer versions exist in the cloud and always pulls the latest data from the Lambda service
- Option to automatically update dependent functions to the latest deployed Lambda layer version
- Added ability to delete individual layer versions
- Layers now have a dependency installation step that will install dependencies based on what's in `package.json` for NodeJS or `Pipfile` for Python
- Support editing layer version descriptions
- Removes local version state tracking from `amplify-meta.json` and `team-provider-info.json`

We'd love to hear any community feedback!

**Comment by frank-unovica** [comment]
@jhockett thanks, the auto update is great, but the hashLayerVersionContents function (amplify-cli/packages/amplify-category-function/src/provider-utils/awscloudformation/utils/packageLayer.ts/) only looks at package.json, ignoring .js file changes, i.e. my shared code.

Also, any chance we can run lambda + layers locally at some point?
