### ISSUE TITLE
Public API - AppSync vs ApiGateway

### ISSUE THREAD

**Issue by davidbiller** [aws-amplify/amplify-cli#6206]
I would like to make parts of my Amplify AppSync Api public. 

I am currently working with 

generatePdf(user_id: ID, career_id: ID!, type: String): AWSJSON
    @function(name: "pdfGenerator-${env}")
    @aws_api_key
    @aws_iam
    @aws_cognito_user_pools

So anyone with the api key can access this function. 
But so can any other function declared with @aws_api_key. 

I have several partners where I want to enable different outputs later and charge money for api access. 

ApiGateway I know. However, I am considering whether it makes sense to set up an api on top of an existing api. I already have my GraphQL. 

Is there a good solution from Amplify or the CLI? 

How else do you solve something like this?

**Comment by yuth** [comment]
@davidbiller You could use `@auth` directive instead of using the `@aws_*` directives with your function. You probably wont need `api key` if you use ` @auth(rules: [{ allow: public, provider: iam }])` as this allows access to the field for `unauth` users.

I am not sure I understand the question. Are you asking if where to put the logic to change the behavior of the function based on if the customer is paying or not paying?

**Comment by kaustavghosh06** [comment]
Closing due to lack of response.
