### ISSUE TITLE
After creating a new environment aws-exports.js is not updated

### ISSUE THREAD

**Issue by ktmdan** [aws-amplify/amplify-cli#6292]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
After creating a new environment it does not update aws-export.js, you must use amplify env checkout to update

**Amplify CLI Version**
4.40.0

**To Reproduce**
Create new env and push, then check the aws-exports file it will be the previous values

**Expected behavior**
Should update the values in aws-exports

**Desktop (please complete the following information):**
 - OS: Windows
 - Node Version. 14.7.0

**Comment by Prinzhorn** [comment]
Just happened to me as well (`4.41.2`), got me mad confused. I was working on `dev` for a while. Created a `staging` just now. `amplify status` said I was on `staging`. Did `amplify publish` and now the `staging` link was actually `dev` :confused: . An `amplify env checkout staging` fixed it, which should absolutely happen automatically when creating a new env. Otherwise you end up _in an inconsistent state_.
