### ISSUE TITLE
bug when 2 amplify api have the same name

### ISSUE THREAD

**Issue by anisg** [aws-amplify/amplify-cli#6354]
**Describe the bug**
I created 2 api, one GraphQL api named "testBlog", another REST api named "testblog". in ./amplify/backend/api/ , there should have been 2 folders, one named "testblog", the other one named "testBlog", but only "testblog" appeared, which created errors when pushing to the cloud

**Amplify CLI Version**
4.41.0

**To Reproduce**
- create a new project
- use amplify to create 2 api, one GraphQL api named "testBlog", another REST api named "testblog".

**Expected behavior**
in ./amplify/backend/api/ , there should have been 2 folders, one named "testblog", the other one named "testBlog", but only "testblog" appeared.

**Comment by attilah** [comment]
@anisg thanks for reporting the issue it exists in the API category for both, I just confirmed it. I'm curious how `api add` succeeded for you since for me it failed in `AmplifyToolkit.updateamplifyMetaAfterResourceAdd` function.

**Comment by attilah** [comment]
Update: this issue present in function category as well, and probably in other categories where we can have multiple resources as well.

**Comment by johnpc** [comment]
> Expected behavior
in ./amplify/backend/api/ , there should have been 2 folders, one named "testblog", the other one named "testBlog", but only "testblog" appeared.

This behaves as expected on case-sensitive filesystems, like linux.

Unfortunately, since Mac and Windows both default to case insensitive filesystems, this expectation does not hold. We'll have to think about what the behavior should be in this case.
