### ISSUE TITLE
Creating a new API with IAM as default results in no Identity Pool and policyless-roles

### ISSUE THREAD

**Issue by cosimtaiuz** [aws-amplify/amplify-cli#6521]
I created a new test API via `amplify add api`, a GraphQL one.
When it asked me what auth to use, I said IAM; this was the first API I was adding to a completely fresh project.

After the command finished I went to the IAM console and opened the 2 roles the script created, the auth one and the unauth one: both were policyless with no trusted entities.
Also the script didn't create an identity pool.

I would have expected that selecting IAM as the starting and only auth option would have created an identity pool like the Cognito User Pool auth method does normally.

**Comment by jhockett** [comment]
Hi @cosimtaiuz, did you run `amplify push` after `amplify add api`? Also please fill out the issue template so we can better debug what's happening:


**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system

**To Reproduce**
Steps to reproduce the behavior or terminal output if applicable

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. Mac/Windows/Ubuntu]
- Node Version. You can use `node -v` to check the node version on your system

**Log output**
Include any relevant log output under `~/.amplify/logs/amplify-cli-<issue-date>.log`

**Additional context**
Add any other context about the problem here.

**Comment by kaustavghosh06** [comment]
@cosimtaiuz Did you add the @auth rules to your models in the schema?

**Comment by cosimtaiuz** [comment]
Hello both, sorry I have been busy with other things, I will try to get back to you both asap.
I solved this by creating another fresh Amplify project and setting Cognito as the default auth mode, then also adding IAM.
