### ISSUE TITLE
Sort data on a property of the connected object

### ISSUE THREAD

**Issue by mjza** [aws-amplify/amplify-cli#6609]
Assume I have the following model:

```graphql
type Employee
@model 
@key(name: "byInstitute", fields: ["instituteId"], queryField: "listEmployeesByInstitute")
{
  id: ID!
  instituteId: ID @assert(condition: ".length() > 1") 
  institute: Institute @connection(keyField: "instituteId")
  userId: ID @assert(condition: ".length() > 1") 
  user: User @connection(keyField: "userId")
}
```

The question is if I want to have list of employees of an institute sorted by their names, how can I create the sort key?

I mean something like this:

```graphql
@key(name: "byInstitute", fields: ["instituteId", "user.name"], queryField: "listEmployeesByInstitute")
```
Is it possible?

**Comment by SwaySway** [comment]
@mjza You can add additional fields to use as the sort key.
`@connection` docs: https://docs.amplify.aws/cli/graphql-transformer/connection
`@key` docs: https://docs.amplify.aws/cli/graphql-transformer/key

**Comment by mjza** [comment]
What do you mean by adding additional field? Should I have `username` as an extra column?
I know this way myself. I am looking for a way to not do that and access to `name` in `user` field. 
Sorry but you didn't answer my question.

**Comment by SwaySway** [comment]
Apologies for the late reply on this, I see you are looking at indexing by a value in the user. This is not supported since`@key` generates a GSI from the fields in the record. Though from my understanding you are looking at sorting nested User by the name field. You can achieve that by using a specified key in User to be referenced by `@connection`. Such as `@key(name: "byUsername", fields: ["name"])` on User and then on the connection you specify the sort direction `@connection(keyName: "byUsername")`.

We are are also looking at improving relational modeling in the next version of the transformer, closing in favor of the vNext RFC. Should you run into any issues with this please comment below.

RFC: https://github.com/aws-amplify/amplify-cli/issues/6217
