### ISSUE TITLE
Why deleteItem(input: DeleteItemInput!) vs getItem(id: ID!)

### ISSUE THREAD

**Issue by YikSanChan** [aws-amplify/amplify-cli#666]
** Which Category is your question related to? **
API

** What AWS Services are you utilizing? **
AppSync, Amplify

** Provide additional details e.g. code snippets **
Curious about the design philosophy under codegen. Let's assume I define:
```graphql
type Item @model {...}
```
`amplify push` will create:
```graphql
type Mutation {
  deleteItem(input: DeleteItemInput!): Item
}

type Query {
  getItem(id: ID!): Item
}

input DeleteItemInput {
  id: ID
}
```
Why does such inconsistency exist? Is there any reason behind?

**Comment by mikeparisstuff** [comment]
The reason is to preserve the pattern between all the generated mutations. By convention, we say that all mutations take a single argument named input so that during create and update mutations you are operating on an object instead of having to destructure every field which can help when integrating client applications. Delete follows the same convention as it is also a mutation. Queries do not have the same convention and take arguments that dictate which and how many records get returned.

**Comment by YikSanChan** [comment]
Yes, it is not about correct or wrong, but more about the convention. I feel we can apply the same convention to queries, too. But I am OK with the current solution.
