### ISSUE TITLE
Large number of PRs in "Review Required"....

### ISSUE THREAD

**Issue by GeorgeBellTMH** [aws-amplify/amplify-cli#6823]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

ALL

### What operating system are you using?

ALL

### Amplify Categories

Not applicable

### Amplify Commands

Not applicable

### Describe the bug

Large number of PRs in "Review Required"

### Expected behavior

PRs should be reviewed in a timely manner...

### Reproduction steps

Count the number of PRs in "Review Required"

It appears that 46/63 PRs are still in "review required"...I am curious if there is a reason that reviews aren't happening in a timely manner? It seems that a lot of them are waiting on some sort of approval, rejection or feedback to get them moving again...if you won't be accepting PRs from the public, or the process is not prioritized please let us know...

I would hope there is some sort of SLA for PRs to be reviewed, and that especially for small PRs the review happens within a week at the most...

**Comment by siegerts** [comment]
Hi @GeorgeBellTMH, Thanks for reaching out and voicing your concern.
 
We take community feedback seriously and we're continuously working to improve as the ecosystem grows - community contributions are _always_ welcome and encouraged.

The PR process prioritizes security, bug fixes, and library compatibility (across the Amplify ecosystem). Currently, the best steps to take for submitting and discussing a PR are listed in the [contribution guidelines](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#pull-requests). Because of this, community PRs and those from the Amplify team are all listed, reviewed, and discussed in the repo. 

Moving forward, we're working to build on the above foundation to be more transparent and communicative in terms of timelines, requested information, and general feedback for PRs (and issues, questions, feature requests, etc.).

**Comment by siegerts** [comment]
Hi @GeorgeBellTMH, I'm glad to see that there is movement on this and I know that the team is working to get the correct information.

If it's okay with you, I'll mark this specific issue as closed as to shift conversation to the PR. It will help keep the discussion in one area moving forward. It's not the intent that these go unanswered, so I'm glad that you raised this - Thanks again for your patience with this!
