### ISSUE TITLE
InvalidClientTokenId for federated login (because of missing sessionToken)

### ISSUE THREAD

**Issue by hakanson** [aws-amplify/amplify-cli#709]
**Describe the bug**
A version sometime after 0.1.38 seems to have broken federated login, which means the entries in AWS credentials are temporary and include a `aws_session_token` that is required.

**To Reproduce**
1. Use a profile with temporary credentials, like a SAML federated login
2. run `amplify init` and for `Do you want to use an AWS profile?` pick  `Yes`
3. see the `InvalidClientTokenId` error

**Expected behavior**
Don't get an `InvalidClientTokenId`, and also a better error message.  Maybe have the cli call `sts = AWS.STS(); sts.getCallerIdentity({})` right after profile selection to validate.

**Screenshots**
Here is the console output (without the stack trace)
```
⠇ Initializing project in the cloud...An error occurred when creating the CloudFormation stack
✖ Root stack creation failed
init failed
{ InvalidClientTokenId: The security token included in the request is invalid.
    at <removed stack track>
  message: 'The security token included in the request is invalid.',
  code: 'InvalidClientTokenId',
  time: 2019-01-15T01:23:34.153Z,
  requestId: '2cece707-1864-11e9-8dc0-97b669EXAMPLE',
  statusCode: 403,
  retryable: false,
  retryDelay: 24.22827745857856 }
```

**Additional context**
I made a local fix by updating `normalizeKeys` in `amplify-provider-awscloudformation/lib/system-config-manager.js` to map `aws_session_token` to the `sessionToken` required by AWS.Credentials.  This seems to work, but I'm not sure how it broke, so this might not be the only fix.
```
function normalizeKeys(config) {
  if (config) {
    config.accessKeyId = config.accessKeyId || config.aws_access_key_id;
    config.secretAccessKey = config.secretAccessKey || config.aws_secret_access_key;
    config.sessionToken = config.sessionToken || config.aws_session_token;
    delete config.aws_access_key_id;
    delete config.aws_secret_access_key;
    delete config.aws_session_token;
  }
  return config;
}
```
To find this I looked over all of the changes from https://github.com/aws-amplify/amplify-cli/releases/tag/%40aws-amplify%2Fcli%400.1.38 for something that dealt with credentials.
```
@aws-amplify/cli@0.1.38
tagged 26 days ago · 40 commits to master since this tag
```

Note: An interesting side effect of trying to install an older version is that it still seems to get "current" versions of dependencies (e.g the most recent aws-sdk-js and amplify-provider-awscloudformation) because of how package.json is structured with ^ version numbers.  This made it hard to figure out what changed, because a clean install of 0.1.38 included the new bug.

**Comment by UnleashedMind** [comment]
@hakanson 
Thanks for the feedbacks. 
Your fix would work, but you will need to maintain the session for the temp credential, and that's not the recommended way. Because the session could end during in the middle of an `amplify push`, and it will break the current end to end workflow of the cli. 
The latest update of the both the @latest and the @multienv versions added feature to support assuming IAM role, and the cli is maintaining the session for you. 
By the way, federated log in was never supported, so the old CLI wouldn't be able work. 
A soon to be released version will support MFA.

**Comment by hakanson** [comment]
It might not have been supported, but I had it working when 0.1.38 was the current cli version without modification.  Since we (and many larger customers) use federated login and [AssumeRoleWithSAML](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRoleWithSAML.html), the IAM User or AssumeRole option would keep us from using this great tool. We happen to use 10 hour timeouts, but I see your point.

Other options may involve the decoupling of gathering project info during `amplify init` from the "Initializing project in the cloud".  If the step to generate the cloudformation template was split from the `push`, this could give us the control we need.

**Comment by hakanson** [comment]
A related question is why all the custom logic for parsing the `.aws/credentials` file and normalizing the keys instead of using the built in [AWS.SharedIniFileCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html) from the AWSJavaScriptSDK?

I used my internal login tool to generated temporary credentials that are set under `myprofile`, and this code correctly returns the caller identity using that named profile.
```
let AWS = require('aws-sdk');

let creds = new AWS.SharedIniFileCredentials({profile: 'myprofile'});
AWS.config.credentials = creds;

let sts = new AWS.STS();
sts.getCallerIdentity({}, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});
```

**Comment by UnleashedMind** [comment]
Thanks for the feedbacks, we are working to improve the UX.

**Comment by hakanson** [comment]
@UnleashedMind Thanks, and since this is critical to a project of mine, I am willing to participate on other related issues or proposed solutions - so feel free to tag me.

**Comment by UnleashedMind** [comment]
@hakanson
Thanks. 
BTW, the reason that we don't use [AWS.SharedIniFileCredentials](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SharedIniFileCredentials.html)
is because we want to cache temp credentials in our future updates (e.g. #718), and I can not find a good way to load cached credentials, check expiration, and call STS assume role to refresh temp credentials in our CLI workflow.<br/>
There are constructs defined in the Credentials class with similar concepts, e.g. `expired`, `expiredTime`, `expireWindow` and `refresh`, etc. , but I found it awkward to put them into use in our CLI's workflow.

**Comment by UnleashedMind** [comment]
The fix by @hakanson is released in the @latest and the @multienv versions.
