### ISSUE TITLE
Reset team-provider-info.json

### ISSUE THREAD

**Issue by johnEthicalTechnology** [aws-amplify/amplify-cli#7145]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

There was an accident on a code base I'm working on where the `team-provider-info.json` file was exposed on a public repo. What is the best way to deal with this so as to minimise any security issues?

I'm assuming I can't just delete the file and publish the app again? Will I have to create entirely new infrastructure again? Or is there another way?

**Which Category is your question related to?**
Infrastructure

**Amplify CLI Version** 
4.45
You can use `amplify -v` to check the amplify cli version on your system

**What AWS Services are you utilizing?**

**Provide additional details e.g. code snippets**

**Comment by edwardfoyle** [comment]
@johnEthicalTechnology if your team-provider-info.json file contained any sort of access tokens or credentials you should revoke / rotate the exposed credentials immediately and update your team-provider-info.json file with new credentials. But you shouldn't need to recreate any infra because knowing the ARNs in the file does not grant any access to those resources

We also recommend adding this file to .gitignore if your project will be public.

**Comment by johnEthicalTechnology** [comment]
@edwardfoyle Thankfully, there were no credentials in the file. I had a feeling the ARN references weren't a security risk, I just wanted to sure.

Thanks a lot! :)
