### ISSUE TITLE
A deployment is in progress.

### ISSUE THREAD

**Issue by varmab** [aws-amplify/amplify-cli#7237]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

12.16.2

### Amplify CLI Version

4.50.0

### What operating system are you using?

Mac

### Amplify Categories

auth, storage, function, api, analytics

### Amplify Commands

push

### Describe the bug

Hi,

I got stuck with this error since command aborted in the middle of deployment.

```
A deployment is in progress.
If the prior rollback was aborted, run:
`amplify push --iterative-rollback` to rollback the prior deployment
`amplify push --force` to re-deploy
```

Even i tried above commands it suggested, 

```
amplify push --iterative-rollback

✖ An error occurred when pushing the resources to the cloud

Cannot iteratively rollback as the following step does not contain a previousMetaKey: {"status":"WAITING_FOR_DEPLOYMENT"}
An error occurred during the push operation: Cannot iteratively rollback as the following step does not contain a previousMetaKey: {"status":"WAITING_FOR_DEPLOYMENT"}
```

if I do `amplify push --force`. I am getting same error

```
Cannot iteratively rollback as the following step does not contain a previousMetaKey: {"status":"WAITING_FOR_DEPLOYMENT"}
An error occurred during the push operation: Cannot iteratively rollback as the following step does not contain a previousMetaKey: {"status":"WAITING_FOR_DEPLOYMENT"}
```

I got stuck. Let me know if any ideas to get this resolved.

### Expected behavior

Successful push

### Reproduction steps

You may try to abort in the middle of deployment after amplify push, it may cause this error may show up.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by attilah** [comment]
@varmab please tell more about what do you mean the deployment was aborted? 
what error message you got?
what type of updates your project had that triggered an iterative update?
can you share a repro with is?

**Comment by varmab** [comment]
Hi @attilah, While CLI is deploying changes to cloud after amplify push, something was taking time and still waiting long, so I aborted push (CTRL+ c) while in the middle. Since then, Any next time push, I am getting above error. I am unable to push. 

When I look through Amplify Admin UI, I don't see any bad things or no incomplete things in CloudFormation. You can see above what error messages I am getting when I do amplify push.

![image](https://user-images.githubusercontent.com/4167060/116952293-ef587600-aca7-11eb-87e8-234a1b20c75f.png)

Even I tried to do setup clean folder by doing amplify pull from cloud, then do push again, it is showing same deployment in progress error.

I tried other commands it suggested i.e amplify push --iterative-rollback or amplify push --force, both giving this error below

![image](https://user-images.githubusercontent.com/4167060/116952537-7efe2480-aca8-11eb-9890-113574063611.png)

I will see how to share my repo.

**Comment by attilah** [comment]
When you hit ctrl+c then it is only stopping the local CLI, but cannot stop the already started CloudFormation deployment and CLI cannot finish updating of state files locally and in your deployment bucket. You get the error message because your deployment lock file was not removed by the CLI at the end of the deployment.

I have one idea on trying to get the project to a deployable state:
1. download `deployment-state.json` from the deployment bucket that you can see in the `amplify-meta.json` file
2. delete `deployment-state.json` from the deployment bucket
3.a. try amplify push
3.b. try to pull to an empty dir and then make modifications and try the push

It is hard to recover from broken situations like this due to the possible missing information from your state files so in the future avoid hitting ctrl+c, iterative updates taking several rounds of CFN updates, which takes time.

Get back to me with the results.
