### ISSUE TITLE
Amplify headless pull - do not update .gitignore

### ISSUE THREAD

**Issue by Nxtra** [aws-amplify/amplify-cli#7250]
**Is your feature request related to a problem? Please describe.**
I have a setup with multiple frontends for one backend. I do a headless checkout of the amplify environment. 
`.gitignore` ignores contains `amplify/` to ignore the entire amplify directory.
When you run the headless checkout / pull. It updates the `.gitignore` file and the amplify dir is no longer ignored.

**Describe the solution you'd like**
I want an option to indicate that amplify should keep its hands of my `.gitignore` file :) 

**Describe alternatives you've considered**
Now I always have to manually update the gitignore.

**Comment by attilah** [comment]
@Nxtra do I understand correctly that you have removed the entries what Amplify CLI added to your `.gitignore` file and broadened the scope to the whole `amplify` directory as you manage that differently but since the CLI cannot locate the ignore pattern it always modifies your .gitignore file?

**Comment by Nxtra** [comment]
Yes, It's a frontend only repo and I only need to pull the amplify env to generate the `aws-exports.js` file.
Amplify changes the content of `.gitignore` from : 
```
#amplify
amplify/
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/logs
amplify/mock-data
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
amplify/backend/.temp
build/
dist/
node_modules/
aws-exports.js
awsconfiguration.json
amplifyconfiguration.json
amplifyconfiguration.dart
amplify-build-config.json
amplify-gradle-config.json
amplifytools.xcconfig
.secret-*
```
to this:

```
#amplify
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/logs
amplify/mock-data
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
amplify/backend/.temp
build/
dist/
node_modules/
aws-exports.js
awsconfiguration.json
amplifyconfiguration.json
amplifyconfiguration.dart
amplify-build-config.json
amplify-gradle-config.json
amplifytools.xcconfig
.secret-*
```

It's removing the `amplify/`  entry.

**Comment by johnpc** [comment]
Ultimately, this is expected behavior from the CLI. The Amplify CLI reserves the right to maintain the gitignore contents within the `#amplify` pragma block.

However, this behavior is not clear and is currently not documented. I've created a pull request to change the block to begin with a `#amplify-do-not-edit-begin` line and end with a `amplify-do-not-edit-end` line. I've also created a pull request to document that behavior.

@Nxtra - you should move the additional `amplify/` line outside of the `#amplify` block - either above the `#amplify` line or below the block, after an empty line defining the end of the `#amplify` block.
