### ISSUE TITLE
Upload progress during push/publish

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#73]
**Do you want to request a feature or report a bug?**
Feature

**What is the current behavior?**
You never quite sure how long things are going to take. Some form of progress indication would be great. This is a nice to have ofcourse.

If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.

**Steps to reproduce the issue:**

1. Execute push or publish
2. There's no real progress feadback to the user.
3. Not sure if the process has hung.

**What is the expected behavior?**
A percentage indicator of how far along the process is.

**Additional environment details**

* **OS version (ie Windows 10 build X, macOS Sierra 10.12.6, etc.)**
MacOS
* **Output of ``amplify --version``**:
0.1.14
* **Did this work in previous versions?**: Y/N
N

**Comment by kaustavghosh06** [comment]
@jarrettj Currently we show the stack events streamed directly from Cloudformation. Does that information seem helpful to know whats going on behind the scenes? 
It's a bit complex to predict the total time estimate beforehand because the provisioning of the various AWS resources varies on several parameters and not trivial to predict, but we can surely work on a naive solution to display which resources are provisioned and how many resources are remaining to be provisioned.

Thoughts?

**Comment by jarrettj** [comment]
Hi

Good day.

Yup that sounds awesome man. And it’s actually the upload of the files that I was talking about. The lambda function to be specific. 

I saw the CF template output. But sometimes I have to kill the amplify process because it’s just not uploading the lambda function. 

The internet my side of the world isn’t that great. So maybe it’s just me.

Thanks. For the update though.

Regards.

**Comment by jarrettj** [comment]
Using the latest version. There's better info while pushing functions to the cloud.
