### ISSUE TITLE
Updating of imported Auth resources is not supported

### ISSUE THREAD

**Issue by bcs-gbl** [aws-amplify/amplify-cli#7409]
**Which Category is your question related to?**

- auth

**Amplify CLI Version** 

- v4.51.2
- windows10

**What AWS Services are you utilizing?**

- amplify update auth
- cognito

**Provide additional details e.g. code snippets**

sadly, I'm stuck in this situation:

`
$ amplify import auth
Auth has already been added to this project. To update run amplify update auth.

$ amplify update auth
Updating of imported Auth resources is not supported.
`

**Comment by SwaySway** [comment]
@bcs-gbl 
The CLI is using the imported auth resource as a reference when any other resource needs an auth resource. Since the auth resource was not created by CLI it does not support auth update. You can make any auth changes from where the auth resource was created (ex. from the console)

Auth Import Docs: https://docs.amplify.aws/cli/auth/import
