### ISSUE TITLE
Migration path for existing AWS users?

### ISSUE THREAD

**Issue by rromanchuk** [aws-amplify/amplify-cli#750]
As an existing aws-sdk-ios user, who uses unauthenticated cognito identities, dynamodb, pinpoint, and s3 transfer utility, is there anyway to move theses services to an amplify managed project, without disruption to an existing live production project? 

This isn't very satisfying =/
```
If you want to use your existing AWS resources with your app you will need to manually configure your app with an awsconfiguration.json file in your code. For example, if you were using Amazon Cognito Identity, Cognito User Pools, AWS AppSync, or Amazon S3:
```

Basically, my intuition is that as these services and support will start becoming tightly integrated with amplify, and i will be swimming my upstream if I don't start embracing now. I'm guessing there isn't an easy way without creating entirely new aws services as it's managed by cloudformation?

**Comment by kaustavghosh06** [comment]
@rromanchuk Yes you're right. Currently due to Cloudformations limitation of not supporting already created services/resources, we're having this issue. At the same time we're actively brainstorming about ways to get around this limitation. Let me know if you've any suggestions.

For the time being, you can manually configure your resources in the Amplify client.

**Comment by rromanchuk** [comment]
I figured that's what would make this complicated, glad you're thinking about it though! I was brainstorming some migration/paths/hacks for fun but it gets messy really quick.
