### ISSUE TITLE
Missing Authentication token

### ISSUE THREAD

**Issue by MedNabilEssefaihi** [aws-amplify/amplify-cli#7522]
I am using AWS Amplify with cognito and DynamoDB with GraphQL API to connect with my app

I am getting this error: Missing Authentication token

**Comment by josefaidt** [comment]
Hey @MedNabilEssefaihi thanks for raising this, in order to gather more context for the team would you mind porting this over to our [bug template](https://github.com/aws-amplify/amplify-cli/issues/new?assignees=&labels=&template=1.bug_report.yaml)?

Closing issue. Please note when adding a GraphQL API with authentication it will need the appropriate authentication headers.

**Comment by MedNabilEssefaihi** [comment]
Dear @josefaidt 
Thank you for your quick answer. in mu case I try to get data from DynamoDB with Graphql API, in my device it works very well but in the devices it doesn't work and returns that error.

Also `Auth.currentUserInfo();` doesn't work.

**Comment by josefaidt** [comment]
This would be a great question for our [community Discord server](https://discord.com/invite/amplify). If you believe this is an error with the JS library, consider filing a [bug report](https://github.com/aws-amplify/amplify-js)

**Comment by MedNabilEssefaihi** [comment]
Dear @josefaidt 

Thank you
