### ISSUE TITLE
Mocking Lambda Trigger for Cognito function not returning

### ISSUE THREAD

**Issue by bombillazo** [aws-amplify/amplify-cli#7531]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

v14.17.0

### Amplify CLI Version

5.0.0

### What operating system are you using?

Ubuntu

### Amplify Categories

function

### Amplify Commands

Not applicable

### Describe the bug

When running a Lambda Trigger for Cognito function using `amplify mock function`, the function never returns to the terminal. Also, execution finishes but I need to press `Ctrl+C` in the terminal to exit the process.

### Expected behavior

The function outputs the return data to the terminal and finishes the process.

### Reproduction steps

1. Create a function through the `amplify auth` Lambda Trigger for Cognito option. (I used a Post Confirmation trigger)
2. Create your own module
3. Fill the custom lambda code:
```js
exports.handler = (event) => {
  try{
    return {
      msg: "Is this working?",
      event
    }
  } catch (error) {
    JSON.stringify(error)
  }
};
```
4. Run function using `amplify mock function <functionName> --event ./src/event.json`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>
Terminal output:

```sh
# Put your logs below this line
Ensuring latest function changes are built...
Starting execution...
amplifyFunction failed with the following error:
Error: Lambda execution timed out after 10 seconds. Press ctrl + C to exit the process.
    To increase the lambda timeout use the --timeout parameter to set a value in seconds.
    Note that the maximum Lambda execution time is 15 minutes:
    https://aws.amazon.com/about-aws/whats-new/2018/10/aws-lambda-supports-functions-that-can-run-up-to-15-minutes/

    at Timeout.<anonymous> (/home/user/.nvm/versions/node/v14.17.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-util-mock/src/func/index.ts:82:42)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)
Finished execution.
```

</details>

**Comment by josefaidt** [comment]
Hey @bombillazo :wave: for this Lambda Trigger it will take a third argument `callback` which can be leveraged to return the value and output it to the terminal. By slightly modifying the Lambda template we're given from the CLI:

```js
exports.handler = (event, context, callback) => {
  // insert code to be executed by your lambda trigger
  callback(null, {
    msg: 'Is this working?',
    event,
  })
}
```

and run `amplify mock function --event src/event.json` we should see the following in the terminal:

```shell
Could not find ref for "GROUP". Using unsubstituted value.
Ensuring latest function changes are built...
Starting execution...
Result:
{
  "msg": "Is this working?",
  "event": {
    "request": {
      "userPoolId": "testID",
      "userName": "testUser"
    },
    "response": {}
  }
}
Finished execution.
```

With that I do believe the command should exit after an unsuccessful execution as we saw with needing to use CTRL+C in order to exit.

**Comment by bombillazo** [comment]
Wowwww that's it! Thank you so much! Works perfect, was not aware that callbacks were required.

**Comment by josefaidt** [comment]
Awesome, glad to hear it! I'm going to re-open this issue to track the bug related to failed mock attempts and the CLI not exiting.

**Comment by edwardfoyle** [comment]
We can't fix this issue any more than printing out the timeout message. The reason is the CLI awaits a response from the lambda function and times out if it takes too long. But JS Promises are not cancelable so the Promise is still waiting even though it will never resolve. Hence why ctrl+c is necessary.

An alternative to the solution proposed above is to use async / await in your lambda function. This avoids having to deal with callbacks altogether:
```js
exports.handler = async (event) => {
  return {
    msg: "Is this working?",
    event
  }
}
```
