### ISSUE TITLE
Export cannot be deleted as it is in use. Renaming of resolver

### ISSUE THREAD

**Issue by AlessandroVol23** [aws-amplify/amplify-cli#7564]
**Which Category is your question related to?**
api / AppSync with Lambda Resolvers

**Amplify CLI Version** 
5.0.0

**What AWS Services are you utilizing?**
api 

**Provide additional details e.g. code snippets**
I am migrating one resolver to another one. So, I want to change all occurences of `resolver1` to `resolver2`. 
It works for all fields except for one I get an error during `amplify push`.

```
 Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: Export 
2xq4p4l4j5a3nh52ch6bibllcm:GetAtt:InvokePriceServiceLambdaDataSource:FunctionId cannot be deleted as it is in use by
 amplify-stockify-develop-173557-apistockify-10MYXVPNIC03Q-ConnectionStack-1OQBEIDPTEDF3
``` 

The field I am changing is: 

```
  security(date: AWSDate): SecurityShadow!
    @function(name: "priceService-${env}")
```

I changed `priceService` to another name. I changed the exact same attribute in another type. 

Do you have any idea where this resource is still needed and how to fix that?

Thanks :-)

**Comment by attilah** [comment]
@AlessandroVol23 you have the function in the project as well that you are trying to rename or that's an existing Lambda function? I tried to reproduce this issue just by changing my schema from `apifunc` to `apifunc1` and it worked as expected, the new stacks were generated and deployed successfully.

How do you exactly try to change the name?

I would strongly advise against running a find and replace in project files if that's how you tried.

**Comment by AlessandroVol23** [comment]
Hi, yes I first ran find & replace which wasn't a good idea. Then I changed it type by type and the error just came with the last type. 

Both functions are present in the project yes.

On another type I could even change the type to:
```
  security(date: AWSDate): SecurityShadow!
    @function(name: "priceService-${env}")
```
without any issues.

**Comment by attilah** [comment]
@AlessandroVol23 and the only thing you change is this?

from:
```graphql
  security(date: AWSDate): SecurityShadow!
    @function(name: "priceService-${env}")
```

to:
```graphql
  security(date: AWSDate): SecurityShadow!
    @function(name: "foobar-${env}")
```

I was not able to reproduce it as I said, it worked.

I noticed something in the error message you get, CFN complains about the EXPORT, so this value is being exported and that is referenced by something, is that the case? Perhaps you need to change it there as well?

**Comment by AlessandroVol23** [comment]
Exactly I just changed it like you showed. I have this type in two different types and I could change it in one but not in the other.
It is correct that the error complains about that another stack is importing something here but I am not sure how to figure out which one it is. Do you have any tips on how to figure this out?

Thanks :-)

**Comment by attilah** [comment]
What is searching for `InvokePriceServiceLambdaDataSource` shows to you?

**Comment by AlessandroVol23** [comment]
If I look in the project files I can't find anything. Or do you mean searching in cloudformation somewhere?

**Comment by attilah** [comment]
On a call we were able to see what is happening, When the function name in `@function` is changed and the stack splitting functionality of GraphQL Transformer kicks in due to the number of resources, it generated Export for the new Lambda DataSource and during deploy since the resource is exported/imported somehow CFN errors out about removing a resource that is being reference, while in reality that resource is not referenced.

Further debugging needed, perhaps a missing DependsOn or something else can cause it.

**Comment by attilah** [comment]
Thanks for sharing the project files with me, based on that I was able to build the exact repro and find a solution with the help of @yuth, to unblock your deployment without downtime.

Step 1:

Add this to `schema.graphql`:
```graphql
type TemporaryType @model(mutations: null)
{
  tempField(param: String): String @function(name: "priceService-${env}")
}
```

Make `transform.conf.json` to look like this:
```json
{
    "Version": 5,
    "ElasticsearchWarning": true,
    "StackMapping": {
        "HoldingsecuritiesResolver": "ConnectionStack",
        "TransactionsecurityResolver": "ConnectionStack",
        "TemporaryTypetempFieldResolver": "ConnectionStack"
    }
}
```

Step 2: `amplify push --yes`

This will enable the renames for the used types to succeed and the temporarily added type will preserve the export/import requirement between stack that caused the failure due to the renames.

Step 3:

- Remove the `TemporaryTypetempFieldResolver` node from `ConnectionsStack.json`
- `amplify push --yes --no-gql-override`, it should succeed

At this point the import to the function id export is gone.

Step 4:

- Remove `TemporaryType` from schema
- Remove the `TemporaryTypetempFieldResolver` entry from `transform.conf.json`
- `amplify push --yes`, it should succeed

This way all the references to the old value is resolved in the deployed and future deployment will also succeed without special steps.

The only thing that cannot be changed due to the deployment limitations is to move `HoldingsecuritiesResolver` and `TransactionsecurityResolver` to the `FunctionDirectiveStack` without downtime.

Let me know if this worked for you.

**Comment by AlessandroVol23** [comment]
Hi @attilah thank you so much for your help. Unfortunately it doesn't work for me. 

Just to be sure I change the resolver of security from `priceService` to `graphqlResolver` **after** executing all of these steps right? 

I still get this issue:
```
UPDATE_FAILED FunctionDirectiveStack AWS::CloudFormation::Stack Mon Jun 28 2021 08:25:20 GMT+0200 (Central European Summer Time) Embedded stack arn:aws:cloudformation:eu-central-1:756487623083:stack/amplify-stockify-develop-173557-apistockify-10MYXVPNIC03Q-FunctionDirectiveStack-1F82QZ4YF21GC/348cc810-9ba6-11eb-b081-027318cdbf96 was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: Export 2xq4p4l4j5a3nh52ch6bibllcm:GetAtt:InvokePriceServiceLambdaDataSource:FunctionId cannot be deleted as it is in use by amplify-stockify-develop-173557-apistockify-10MYXVPNIC03Q-ConnectionStack-1OQBEIDPTEDF3
```

Thank you so much for your help!

**Comment by attilah** [comment]
We can walk through all the steps on Wednesday if you like, I was able to solve it from your exact situation. DM me.

**Comment by AlessandroVol23** [comment]
Everything works as expected. My mistake was to not change the resolver name before executing the steps.

Thank you so much @attilah ! I really appreciate it :-)
