### ISSUE TITLE
RFC - Custom IAM Policies for Lambda and API Containers

### ISSUE THREAD

**Issue by luhanamz** [aws-amplify/amplify-cli#7792]
# RFC - Custom IAM Policies for Lambda and API Containers

*This is a Request For Comments (RFC). RFCs are intended to elicit feedback regarding a proposed change to the Amplify Framework. Please feel free to post comments or questions here.*

## **Summary**

Amplify CLI provisions IAM roles with policies to access different resources. Currently, adding custom IAM policies requires the customer to manually edit the CFN template every time they run `amplify push`. There are no higher-level methods to provide custom IAM policies to attach to the provisioned IAM roles. Our aim is to provide an easier way within the CLI to custom IAM policies. 

## GitHub Issues:

* [How to give serverless container access to non-amplify-managed resourc...](https://github.com/aws-amplify/amplify-cli/issues/6918)
* [How to add SES permission to LambdaExecutionRole · Issue #5432 · aws-a...](https://github.com/aws-amplify/amplify-cli/issues/5432)
*  [Allow functions to have additional policies · Issue #5142 · aws-amplif...](https://github.com/aws-amplify/amplify-cli/issues/5142)
* [Give a Lambda function access to RDS · Issue #6324 · aws-amplify/ampli...](https://github.com/aws-amplify/amplify-cli/issues/6324)
* [allow lambda function to call itself · Issue #7667 · aws-amplify/ampli...](https://github.com/aws-amplify/amplify-cli/issues/7667)

## **Proposed Solutions**

There are two proposed solutions. One is a file based option, customers can edit a file to provide their policies directly and the CLI incorporates the policy in the stack. The other is a CLI based workflow option, which will prompt customers to answer questions. The CLI performs actions to generate the required policies from the input.

## **Proposal 1**: File based

To define a custom policy, the customer would need to create a file 'custom-policies.json' and define it using the structure below. Customers can specify multiple actions for multiple resources in the same service. If customers want to grant access to more than one service, they can add additional blocks to the file. The file is optional if customers don't need any custom policies for their project.

The structure of the file would be:

```
{
   "version": "1.0",
   "policies": [
       {
            "Resources": [
                "<enter resource ARN here>"
            ],
            "Action": [
                "<enter actions here>"
            ]
        },
        {
            "Resources": [
                "<enter resource ARN here>",
                "<enter resource ARN here>"
            ],
            "Action": [
                "<enter actions here>",
                "<enter actions here>"
            ]
        }
    ]
}
```

The ‘Effect’ will be “Allow” as default. If the ‘Effect’ field is defined, the default will be overridden.

Customers can run `amplify push` to get the policies updated.

## **Proposal 2**: CLI based Workflow

The customers will be prompted for the policies in the following workflows:

```
amplify add function
amplify update function
amplify add api
amplify update api
```

By answering questions on the CLI, customers can add and edit custom policies, actions and resource.

### **Workflow**

**`amplify add function`**
Customers can add or attach the custom policies to the new function they just create.
The customers will be prompted with the question

```
Do you want to configure advanced settings?(y/N)
```

After choosing yes, customers will be asked

```
Do you want to access other resources in this project from your Lambda function?(Y/n)
```

If choosing yes, customers will be prompted

```
Select the categories you want this function to have access to. 
(Press <space> to select, <a> to toggle all, <i> to invert selection)
o api
o storage
o ...
o external resource
```

Customers can choose external resource to add or edit custom policies

```
Select the operation you would like:(Use arrow key)
>add new external resources(add custom policies)
 edit external resources(edit custom policies)
```

After choosing to add new custom policies, customers will be prompted to enter resource ARN

```
Enter the resource ARN:
```

Customers will be prompted if they want to add more resources

```
Do you want to add more resource (in the same service)? (Y/n)
```

If customers choose yes, they will be asked to enter another resource. If they choose no, then proceed to next step.
Customers will be prompted actions they want to add to corresponding resource

```
Enter an action you want to add:
```

Customers will be prompted if they wanted to add more actions

```
Do you want to add more actions? (Y/n)
```

If customers choose yes, they will be prompted to enter an action again, if they choose no, then proceed to next step.
If customers choose to edit custom policies, they will be ask to select the resource they want to edit

```
Select the resource you want this function to have access to:(Use arrow key)
...
...
```

After that, customers will be ask if they want to add new or delete actions, add new or delete resources:

```
Which operation do you want to perform on` `<service name>?(Use arrow key)
> add new actions
  delete actions
  add new resources
  delete resources
```

If customers want to delete resources:

```
Which resources you want to delete on <service name>?(Press <space> to select, 
<a> to toggle all, <i> to invert selection)
o ...
o ...
```

If customers want to delete actions:

```
Which actions you want to delete on <service name>?(Press <space> to select, 
<a> to toggle all, <i> to invert selection)
o ...
o ...
```

If customers want to add more actions or resources, they will go over the same workflow as adding custom policies.
After adding all the desired actions, customers will be prompted to change default setting of ‘Effect’:

```
Do you want to change the 'Effect', ‘Effect’ is “Allow” by default? (y/N)
```

If customers choose yes, they will be prompted to enter the effect:

```
Enter the 'Effect' you want to have for the resources:
```

**`amplify update function`:**
When customers update functions, they can also add or edit custom policies.
For amplify update function workflow, the customers will be prompted with the question

```
Which setting do you want to update? (Resource access permissions)

Select the categories you want this function to have access to. 
(Press <space> to select, <a> to toggle all, <i> to invert selection)
o api
o storage
o ...
o external resource
```

Customers can choose external resource to add or edit external resources, or proceed to other options.
When they choose external resource, they will experience the same process as for `amplify add function`.

**`amplify add api`**
Customers can add or edit custom policies when they create a new container. After customers create the container, they can add or edit custom policies to attach to the container they just create.
After customers prompted with question:

```
Do you want to access other resources in this project from your api?(Y/n)
```

Customers will be prompted with the question which resource they want to continue with:

```
Select the categories you want this function to have access to. 
(Press <space> to select, <a> to toggle all, <i> to invert selection)
o api
o storage
o ...
o external resource
```

If they choose external resource, they will experience the same process as for `amplify add function`.

**`amplify update api`**
Customers can add or attach custom policies when they update API. After selecting the API they want to update, they can choose to update the resource or not. If customers choose yes, they want to access other resources, they will be prompted with the question:

```
Select the categories you want this function to have access to. 
(Press <space> to select, <a> to toggle all, <i> to invert selection)
o api
o storage
o ...
o external resource
```

Customers can choose external resource to continue with adding or editing custom policies, they will experience the same process as for `amplify add function`.

## Validation

File based workflow: after executing `amplify push`, the format will be validated before merging to the corresponding CFN template. 

CLI based workflow: after entering actions for custom policies, the format of actions will be first validated before adding to the *function-parameter.json.
*

The resource will be verified against the regex:

```
arn:(aws|aws-cn|aws-us-gov):([a-z0-9])*:(([a-z]{2})-(east|west|south|north|northwest|northeast|southeast|central)-[1-3]){0,1}:([0-9]{12}){0,1}:([a-z|A-Z|0-9|_|:|/|*]+)*
```

The actions will be verified using the following regex:

```
([a-z0-9])*:([a-z|A-Z|0-9|*]+)*
```

If what customers enter is not the correct format, they will have to correct it before proceeding.

## Multi-Environment Workflow

When the customers checkout a new environment, all the policies are copied over and customers can update the setting using the `amplify update <category>` workflow.
When customers enter the resource name, they can specify which environment they are in optionally. For example:

```
`arn:aws:iam::123456789012:user`-{env}
```

If customer is in the dev environment, then the resource name should look like:

```
`arn:aws:iam::123456789012:user`-dev
```

## Question for the community

* Is the structure of the file for proposal 1 easy enough for you to maintain? How can we improve it?
* Is the field ‘Effect’ needed in custom policies? Does it make sense to remove it, and consider all the ‘Effect’ would be ‘allow’.
* How would you like to use custom policies across environments? Do you want to keep the same custom policies across environments?

**Comment by amirhajimirsadeghi** [comment]
Not one of the questions listed at the bottom, but if it's between proposal 1 and 2, as a user of the CLI I'd prefer 2 since it fits into the already existing workflows and it would be a natural place to look for tapping into this functionality. 

Proposal 1 would require further reading of the documentation and potential visits back if you forget where the custom policies are kept.

**Comment by frank-unovica** [comment]
It should be possible to add a **Condition** clause as well (such as s3 prefix partitions linked to auth groups/env), override the Effect to deny part of a resource and define arrays instead of strings (for instance by typing a hyphen). At least in a later version.

A further improvement in any case is to introduce **(recursive) resource groups** as a category, so they can be attached or edited as one. This would greatly reduce unnecessary CLI repetitiveness. It should be trivial to propagate across branches.

It should be possible to attach custom policies to (un)auth roles/groups. Last time I checked this was not reasonably possible at all.

Ideally there are 3 ways:
- The CLI to attract a starter community to quickly get up to speed with typical scenarios.
- (My preference) A minimal definition file for the entire project similar to AWS SAM, from which cloudformation files are generated. The CLI should generate such a file but the developer can choose to write it manually. This attracts developers who need the flexibility but still a reliable ready-to-go boilerplate application basis (i.e. Amplify).
- The generated cloudformation files per function, which the developer can choose to generate or edit manually for tricky situations.

(Both YAML and JSON should be universally supported)

This intermediate approach allows quicker development of Amplify, since new/advanced features don't require writing CLI extensions right away, and the CLI code is separated from cloudformation complexity. It also allows rapid development of different CLI flavors by the community, since the Amplify team cannot anticipate every use case and workflow into a single one, and AWS ultimately wants to sell as much metal as possible.

It would really help to test a resource configuration quickly rather than having to push all the resources for every little edit, and waiting for it to rollback on every typo. It should also be possible to have the Amplify project as a single source of truth (at least on one person branches) and only push directly what has changed rather than needlessly checking dependencies in the cloud.

Specifically, a change in **code** or **policy** is not a change in resources and should therefore not trigger a deletion and regeneration of resources, only a quick update in content, similar to the Lambda console. A webpack-like mode could be added for near-instant lambda updates.

**For real success, it should be easy to map custom resources to the DataStore/Storage/PubSub/Hub interfaces** (e.g. send/receive SES). Authentication schemes of Amplify are currently too limited for serious use (RBAC, shared resources, dynamic groups, private subscriptions, s3 prefixed single buckets, SNS/SES, etc.), rendering DataStore and Storage useless/unreliable for most developers.

It should also be easy to use a single bucket for all deployments (in our case we branch per customer).

**Comment by GeorgeBellTMH** [comment]
I have been adding custom policies into associated templates. Questions:

1. Are you planning for only one custom-policies.json? Or would there be one for each function, each hosting bucket, etc. I would hope at the least each function would get one to help with organization.
2. Would there be a way to pull out custom policies from existing templates etc. or would we have to manually move them over?
3. CLI method is great as long as it can remember the settings between envs etc.

**Comment by asmajlovicmars** [comment]
Great addition!

* Could it be a workflow writing into a file? Sometimes it's easier to update the file to re-generate policies without going through a workflow again? 
* I'd leave the Effect for both: deny and allow

**Comment by luhanamz** [comment]
Hi @GeorgeBellTMH,
Thanks for your comment!
> 1. Are you planning for only one custom-policies.json? Or would there be one for each function, each hosting bucket, etc. I would hope at the least each function would get one to help with organization.

There would be one custom-policies.json for each function for file based workflow. The file is optional and added manually following the template.
> 2. Would there be a way to pull out custom policies from existing templates etc. or would we have to manually move them over?

 For now, we have to manually move the custom policies over.

**Comment by LeoRpc** [comment]
The question "Do you want to access other resources **in this project** from your Lambda function?" is not clear, I would rather prompt something like "Do you want to access other resources (**inside or oustide this project**) from your Lambda function?"

**Comment by fooman** [comment]
It seems support `custom-policies.json` now exists. What is less clear is what variable placeholders can be used and this RFC seems the most comprehensive on this topic.

It seems that `${env}` works but not much else. It would be great to also be able to include 
```
${region}
${account}
${amplifyAppId} (in other places it gets used as secretsPathAmplifyAppId)
```
