### ISSUE TITLE
How to do a complex query in AWS Amplify?

### ISSUE THREAD

**Issue by kgoyal98** [aws-amplify/amplify-cli#7840]
With Amplify API I am trying to implement something like a social network website. In the website, users can follow people and add posts. In the timeline, users can see the posts of people they follow.

Schema is something like this:

```
type User @model {
  id: ID!
  name: String!
  following: [UserFollow] @connection(name: "UserFollowing")
  followers: [UserFollow] @connection(name: "UserFollowers")
  posts: [Post] @connection(name: "UserPosts")
}

type Post @model {
  id: ID!
  content: String
  user: User @connection(name: "UserPosts")
}

type UserFollow @model {
  id: ID!
  user: User @connection(name: "UserFollowing")
  followee: User @connection(name: "UserFollowers")
}
```

While implementing the timeline feature, I need to do a listPosts query.

```
let filter = {
    // need help with this.
};
const result = await API.graphql({ query: listPosts, variables: { filter: filter}}));

```

Can somebody please help me with implementing the filter?
I asked this sometime back here https://github.com/aws-amplify/amplify-cli/issues/7798 but github is not allowing me to reopen the issue when closed by the contributor.

**Comment by johnpc** [comment]
what have you tried? have you read [the documentation on graphql filters](https://docs.amplify.aws/lib/graphqlapi/query-data/q/platform/js#filtering-queries)? More detailed documentation can be found in [the AppSync docs](https://docs.aws.amazon.com/appsync/latest/devguide/using-your-api.html) as well

**Comment by kgoyal98** [comment]
Yes I have read these.

I was thinking of first fetching all the followees of the user and then adding all of the followee user ids in an OR filter.

This had two problems
1. It needs two queries. It would be much simpler if we could do this directly in one call.
2. graphql listPosts query was not allowing to filter on connection field. Any user related field was not there in the generated code.

**Comment by rudyhadoux** [comment]
You can use 
@key(name: "byUserid", fields: ["ID"])
or
@key(name: "byUsername", fields: ["name"])

**Comment by kgoyal98** [comment]
Thanks @rudyhadoux. This will solve problem 2.

Is there any solution for problem 1?

**Comment by rudyhadoux** [comment]
What is exactly Problem 1 ?

**Comment by kgoyal98** [comment]
I proposed one solution that we first query the followee list of the user and then filter the posts using the followee list. This method involves two API calls. Is there any way to do it in one?

**Comment by rudyhadoux** [comment]
I do not understand "the posts using the followee list". What do you mean ?

**Comment by kgoyal98** [comment]
@rudyhadoux can you please provide a sample code for the filter? I think that you as thinking of some other way to query.

**Comment by rudyhadoux** [comment]
I can't ask you because I do not understand your question. Sorry.
Read this whole page.
https://docs.amplify.aws/cli/graphql-transformer/dataaccess

**Comment by kgoyal98** [comment]
Let me explain in more detailed form.

I want to get posts of the people that a user follows.

This is one way to do it:
```

const getFollowees = async (userId: string) => {
    // Makes a graphql call to get the userIds of users which the user follows.
    const result = await API.graphql ( { query: listUserFollows, variables: { filter: { 'userId': userId } } } ) );
    return result.data.items;
}

let filter = {
    'or' : [ ],
};

for(var user in getFollowees(userId)) {
    filter['or'].append( { 'userId' : user.id } );
}

const followeePosts = await API.graphql({ query: listPosts, variables: { filter: filter} } ) );
```

The problem with this approach is that it involves two API calls: listUserFollows and listPosts. I want to do it in one API call only. I want to find a way to do this.

**Comment by rudyhadoux** [comment]
Don't use filters but only @key.
Everything you need is here :
https://docs.amplify.aws/cli/graphql-transformer/dataaccess

To get the posts of the people that a user follows, you have to add results from a loop of requests with :
@key(name: "byUserName", fields: ["name"])

**Comment by rudyhadoux** [comment]
If you add A MEMBER posts to UserFollow (like User), you can have all posts of following or/and followers.
With :
@key(name: "byUserFollowing", fields: ["following"])    OR
@key(name: "byUserFollowers", fields: ["followers"])

**Comment by kgoyal98** [comment]
Note that we would want to support pagination. For that the results have to be in a single query call.

**Comment by rudyhadoux** [comment]
It is a many-to-many.
https://docs.amplify.aws/cli/graphql-transformer/connection#many-to-many-connections
I can't help you any more sorry.

**Comment by rudyhadoux** [comment]
I think I have found what you need here :
https://github.com/aws-amplify/amplify-cli/issues/4106

**Comment by kgoyal98** [comment]
I don't think that #4106 is applicable to my question.  Please paste a code snippet if you got the solution.

**Comment by rudyhadoux** [comment]
Already done. Bye.

**Comment by kgoyal98** [comment]
Thanks for helping but it will not work.
@johnpc Can you please help.

**Comment by johnpc** [comment]
Alright, I can add a couple more alternatives:

1. following the [many-to-many documentation](https://docs.amplify.aws/cli/graphql-transformer/connection#many-to-many-connections) and traversing the graphql structure

[here](http://kgoyal98-20210802014024-hostingbucket-dev.s3-website.us-east-2.amazonaws.com) is an example of that method in action and [here](https://github.com/johnpc/kgoyal98/blob/master/src/App.js#L27) is the underlying source code. What you might not like about this is that, although it can initially be fetched in a single request, each followee is paginated independently. 

2. following the [lambda resolver docs](https://docs.amplify.aws/cli/graphql-transformer/function) to write a custom script

[here](http://kgoyal98-20210802014024-hostingbucket-function.s3-website.us-east-2.amazonaws.com) is an example of that method in action and [here](https://github.com/johnpc/kgoyal98/blob/function/amplify/backend/function/kgoyal98ce44dccd/src/index.js) is the underlying source code. For this method, you'll have to add your own pagination logic to the lambda function. If you have highly relational data, it might be easier to use RDS instead of dynamo db as your data store. 

There are a number of ways to implement what you're trying to do and the optimal solution for you depends on the specifics of your app. Amplify provides the tools you need to invent creative solutions but there's not a catch-all best answer in this case.

**Comment by kgoyal98** [comment]
Thanks @johnpc. This answers my question.
