### ISSUE TITLE
[Question] How do I manage resolver config.

### ISSUE THREAD

**Issue by bokuweb** [aws-amplify/amplify-cli#807]
** Which Category is your question related to? **

amplify-cli / appSync

** What AWS Services are you utilizing? **

appsync

** Provide additional details e.g. code snippets **

I used `0.2.1-multienv.29`.
I update a resolver to use `lambda resolver` in aws appSync console.

### Change resolver manually in aws appsync console

<img width="443" alt="2019-02-03 12 53 25" src="https://user-images.githubusercontent.com/10220449/52172450-b8d2de80-27b2-11e9-9dbb-f6c9822952d7.png">

However I did `amplify push` in my local, this configuration was overwritten... 

### After `amplify push`

<img width="515" alt="2019-02-03 12 59 54" src="https://user-images.githubusercontent.com/10220449/52172483-a311e900-27b3-11e9-8d30-37339749c783.png">

How should I manage it ?? I would like to use `lambda resolver` with amplify-cli??
Is it the only way to wait for this  feature?? (https://github.com/aws-amplify/amplify-cli/issues/574) 

I tried to edit `cloudformation-template.json` but, it was overwritten too...

Ah...Should I use `amplify push --no-gql-override` for now??

**Comment by yuth** [comment]
@bokuweb thanks for reporting this. This is a bug, which is caused by pushing all the CFN templates to the cloud even when those are not changed/updated

We will be fixing this soon, in the mean time,  you could move the AppSync API to a new project and add it to codegen using `--apiId`. This should prevent updating of the AppSync API

__PS:__ We are actively testing the custom resolver which will support adding lambda in the transformer itself with out the use of AWS console.

**Comment by kaustavghosh06** [comment]
@bokuweb We fixed this issue in our main CLI version. You can install it using `npm install -g @aws-amplify/cli` and feel free to re-open the issue if you're still experiencing the same problem.
