### ISSUE TITLE
Merge conflicts with multi-env with amplify remove/update

### ISSUE THREAD

**Issue by alex-fivetalent** [aws-amplify/amplify-cli#819]
# Multi-env with amplify remove/update

## Description 
I have tried this on two different projects, and found similar issues.  I get merge conflicts when running the workflow as follows for multi-env (only conflicts when updating resources or removing resources):

## Example Workflow
**Setup**
1. git checkout -b dev
2. amplify init dev - new env setting in CLI
3. amplify push
4. git add, commit, push -u origin dev
5. git checkout -b stage
6. amplify init stage -- new env setting in CLI
7. amplify push
8. git add, commit, push -u origin stage
(At each change of env, I do amplify status to make sure that its in the right env)

**Adding a resource**
1. git checkout dev
2. amplify env checkout dev
3. amplify add storage (or something)
4. amplify push
5. git add, commit, push
6. git checkout stage
7. amplify env checkout stage
8. git merge dev (no conflicts)
9. amplify env checkout dev ( I am having to switch amplify env back and forth once after merge to get the changes to refresh for me in amplify status.)
10. amplify env checkout stage
11. amplify push
12. git add, commit, push

**Removing/Modifying a resource**
Same as adding resource but in step 3 I try removing storage or modifying read-write permissions in storage ( Have had the same issues with graphql updates).  Then I will get merge conflicts in at least the nested-cloudformation-stack.yml file and in additional files for the graphql updates.

## Expectation
Tried to follow the same pattern of workflow as shown in:
https://aws-amplify.github.io/docs/cli/multienv?sdk=js

I know that the switching env back and forth wasn't needed in the diagrams

## System
- Windows
- Amplify --version  0.2.1-multienv.17
- Using CLI within VScode terminal

**Comment by ajhool** [comment]
I'm using the same setup and am getting merge conflicts, too. I'm still investigating but I think that #current-cloud-backend should be excluded via gitignore but it doesn't seem to be excluded properly.

The amplify env workflow diagrams could use some more detail

**Comment by yuth** [comment]
@alex-fivetalent which are the files that have merge conflict?

**Comment by alex-fivetalent** [comment]
1. awscloudformation/nested-cloudformation-stack.yml
2. ftAppApi/parameters.json
3. src/graphql/schema.json

**Comment by kaustavghosh06** [comment]
It's safe to put the `awscloudformation/` directory in the gitignore file since its a runtime file.
Also, the `src/graphql/schema.json` can be put into the .gitignore directory

We'll look into automating this and adding it to the gitignore file modified/generated by the CLI on init.

Looking into the `ftAppApi/parameters.json` file as I'm not sure about how that is getting manipulated.

**Comment by alex-fivetalent** [comment]
the parameters.json changed after adding in a @searchable directive for the graphql schema.

**Comment by k4roshi** [comment]
parameters.json gets updated with the latest deployment timestamp every time amplify push is called with some modifications to the schema. 
I've tried adding it to the gitignore file but it breaks builds if it's not present and is not regenerated automatically by init or other commands.

**Comment by kaustavghosh06** [comment]
Hey guys, you can upgrade your CLI to the latest version of the CLI and include `build/` and `dist/` in your gitignore s to prevent these git conflicts. Please let me know if you're still seeing this issuea fter upgrading and addding these paths to your gitignore.

**Comment by jonmifsud** [comment]
@kaustavghosh06 we're also/still having some issues with `parameters.json` mentioned above - it might deserve its own issue unless there is one already.

Maybe it's not always a merge conflict. But if I merge across multiple developers then I go to `amplify push` - it will push the APIs into the other dev's bucket. Unless you're both using a different region; where it essentially says it can't upload files due to the bucket being in a different region. The latter is how we picked this up.

**Comment by jeremyburton** [comment]
> Also, the `src/graphql/schema.json` can be put into the .gitignore directory
> 
> We'll look into automating this and adding it to the gitignore file modified/generated by the CLI on init.

@kaustavghosh06 is it still current advice that we can put `src/graphql/schema.json` in .gitignore? I'm using Amplify Console for CI/CD and it seems counter-intuitive to me to not be deploying changes to that file. The reason I ask is because that file often throws up merge conflicts in a multi-env setup and that lead me to this issue and your suggestion.
