### ISSUE TITLE
awsmobile push single function

### ISSUE THREAD

**Issue by jarrettj** [aws-amplify/amplify-cli#822]
Do you want to request a feature or report a bug?
Feature.
What is the current behavior?
awsmobile push command uploads all lambda functions. It actually does it all the time, whether or not things have changed.

What is the expected behavior?
Would be cool if you could specify the lambda function to push. Maybe: 
```
awsmobile push cloud-api function-name
```
Which versions of Amplify, and which browser / OS are affected by this issue? Did this work in previous versions?
1.1.4

You can turn on the debug mode to provide more info for us by setting ```window.LOG_LEVEL = 'DEBUG';``` in your app.
Not applicable.

**Comment by UnleashedMind** [comment]
For the awsmobile-cli, the function is uploaded (the whole function codebase) if there are changes on it after the last push. But the cli does not provide the functionality that lets you push a specific function. Since the aws mobile project has been deprecated, there is no active developments on the awsmobile-cli at this moment.

**Comment by UnleashedMind** [comment]
Closing the issue for now, feel free to re-open it if needed.

**Comment by jarrettj** [comment]
Yup, I'm using the new cli as well. Works fine.
