### ISSUE TITLE
@http directive

### ISSUE THREAD

**Issue by mikeparisstuff** [aws-amplify/amplify-cli#84]
**Feature Request**

Let's use this ticket to track work for the `@http` directive. The goal of the `@http` directive is to make wiring up http resolvers and datasource as simple as possible.

# Use cases

1. Easily make a http call from fields in your schema.graphql.
2. Be able to choose the http method per field.
3. Pass headers per field.
4. Control the payload of the request per field. Probably via the arguments but we should think about how to do general data transformations.
5. Response transformations? I see transformations as a general problem and it may be worth looking into if this is better solved by a dedicated set of directives. `@map`, `@filter`, `@pluck`, etc.

# Definition

First thought for how to do this

```graphql
# Place this directive on a field to add an http resolver.
# Note: The directive says nothing about the shape of the payload. We leave that to the user in the field definition
directive @http(
  url: String!,
  method: HttpMethod = GET,
) on FIELD_DEFINITION
enum HttpMethod {
  GET POST PUT DELETE
}
```

The directive says nothing about data sources. My current thought is to automatically detect and configure datasource's by looking at the urls passed to @http. If two @http fields pointed to two different paths of the same base url, this would have to be smart enough to make a single data source for that call. We could also look into making a data source per @http but ideally we would dedupe.

# Usage

```graphql
type Query {
  # You define whatever input you want. 
  # Args will be sent as query params for GET or the body for POST, PUT
  hitMyApi(value: String): ApiResponse @http(url: "www.api.com/ping")

  # Automatically replace url params
  # If there is an argument of the same name as a param in the url string replace it automatically.
  # This makes many rest(ish) patterns easier to deal with.
  # In this example the body would be { content: "value passed to query" }
  updatePost(id: String, content: String): Post @http(method: PUT, url: "www.api.com/posts/:id")
}
```

The @http resolver has a lot of configuration options and every API works a little differently so lets try to keep it flexible while remaining simple to use.

Let me know what you think.

**Comment by mwudtke** [comment]
Quick update on the `@http` directive. I have been working on this for a week or so and wanted to share some implementation decisions and changes from the initial design discussion.

## Definition
This is largely unchanged from the perspective of what the user sees.
```
# Place this directive on a field to add an http resolver.
# Note: The directive says nothing about the shape of the payload. We leave that to the user in the field definition
directive @http(
  url: String!,
  method: HttpMethod = GET,
) on FIELD_DEFINITION
enum HttpMethod {
  GET POST PUT DELETE
}
```
## Usage
This is also mostly similar, with a few more specifics fleshed out.
```
type Query {
  # You define whatever input you want. 
  # Args will be sent as query params for GET or the body for POST, PUT
  hitMyApi(value: String): ApiResponse @http(url: "www.api.com/ping")

  # Automatically replace url params
  # If there is an argument of the same name as a param in the url string replace it automatically.
  # This makes many rest(ish) patterns easier to deal with.
  # In this example the body would be { content: "value passed to query" }
  updatePost(id: String, content: String): Post @http(method: PUT, url: "www.api.com/posts/:id")
}
```
**Important:** If URL parameters are specified in the URL string, they *must* be provided as non-null arguments on the field. Otherwise, there would be no way to resolve the URL string. This is enforced in the transformer, and it throws an error if the URL parameters are not given.

**Note:** I am currently working on a way to make the usage syntax more flexible, to allow for situations like sending query parameters as well as a body for POST and PUT requests. At the moment, the transformer assumes all arguments (except those consumed as URL parameters) will be used as query parameters for GET, and all arguments (except those consumed as URL parameters) will be used as the body for POST and PUT requests.

## Implementation
- We default to a GET request unless the user specifies otherwise - PATCH will be added in the next few days as well, to ensure parity with the methods supported by the HTTP resolver in AppSync.
- Data sources are created in an intelligent way, only creating one per unique base URL. For example, if an annotated schema contains `@http` directives that reference both `http://myapi.com/ping` and `http://myapi.com/posts/1`, the transformer will only create a single data source with `http://myapi.com` as the endpoint.
- For now, the transformer enforces that the URL argument given to the directive begins with either `http://` or `https://`, since AppSync will not create a data source without being given a protocol. In the future, we may support more protocols, but for now it will accept these.
- Sets both `content-type` and `accept-encoding` to `application/json`, but forwards all other headers from the client (except [those not allowed by the HTTP resolver](https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-http.html#params-field)).
- The shape of the response sent by the API must be defined as a type in the annotated schema, since the body portion of the response is returned to AppSync as JSON.


Work is still ongoing, so feel free to chime in about this design so far.

**Comment by testower** [comment]
Any news on this ref this announcement https://aws.amazon.com/about-aws/whats-new/2019/02/amplify-framework-adds-support-for-multiple-environments-custom-resolvers-larger-data-models-and-iam-roles-including-mfa/ ?

**Comment by mikeparisstuff** [comment]
The recent announcement does not yet include the http directive, however, you can use custom resolvers to write your own resolvers that use custom HTTP data sources. To do so, you can include your own CloudFormation stacks in the `stacks/` directory that implement your custom HTTP data sources & resolvers.

**Comment by testower** [comment]
Ok maybe I'm just confused by this: https://github.com/aws-amplify/amplify-cli/releases/tag/graphql-http-transformer%403.0.6

Is there a way to use this directive even if it's not officially supported? Or would you not recommend it? If not, do you have a timeline for when it will be?

**Comment by grudra7714** [comment]
Any updates on this?

**Comment by ambientlight** [comment]
@testower: 

to use `graphql-http-transformer`, which is not enabled yet, we need to do the following:

1. Update `package.json` in [packages/amplify-provider-awscloudformation/package.json](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-provider-awscloudformation/package.json) to include:
    ```
    "graphql-http-transformer": "^3.4.1"
    ```

2. Add HTTPTransformer() to transformerList:

https://github.com/aws-amplify/amplify-cli/blob/25f035440705fe65b16d025c63506c97fda2170b/packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js#L209

3. `npm run setup-dev` in `amplify-cli` root which will give us a binary ready to use at `bin/amplify`

It will be great though if transformers can be enabled via CLI command or project config.

Judging by the code, `graphql-http-transformer` functionality for now allows you to synthesize object fields to http requests (can be pretty helpful already). Usage examples can be found in end-to-end tests: [packages/graphql-transformers-e2e-tests/src/__tests__/HttpTransformer.e2e.test.ts](https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-transformers-e2e-tests/src/__tests__/HttpTransformer.e2e.test.ts). I did try it and it works as expected for my scenario.

**Comment by davekiss** [comment]
Will there be any way to incorporate environment variables in the http requests (ie. api keys etc.) ?

**Comment by smakinson** [comment]
@ambientlight Investigating the use of HTTP now. Looks like part 1 of your steps was completed. Is it possible to use this yet? I'm looking to wrap a REST api and need to append a query param to each request. Also an env var would be nice for this. Thanks!

**Comment by ambientlight** [comment]
@smakinson: it is now available in release versions(through undocumented?) : https://github.com/aws-amplify/amplify-cli/blob/2ba7435ae2be45f74dbcfdd9d9418d5102ade2e3/packages/amplify-provider-awscloudformation/lib/transform-graphql-schema.js#L371

> I'm looking to wrap a REST api and need to append a query param to each request. 

when query parameters are in URL, `:` can be used to reference graphql parameters in declaration by name https://github.com/aws-amplify/amplify-cli/blob/2ba7435ae2be45f74dbcfdd9d9418d5102ade2e3/packages/graphql-transformers-e2e-tests/src/__tests__/HttpTransformer.e2e.test.ts#L56-L60

But I am not sure if there any support for `application/x-www-form-urlencoded` or `multipart/form-data` payloads here, which you might likely need to use if you are wrapping a third part REST api
