### ISSUE TITLE
Fill field value from related entity on GraphQL entity creation

### ISSUE THREAD

**Issue by j-mastr** [aws-amplify/amplify-cli#8410]
**Which Category is your question related to?**
API (GraphQL)

**Amplify CLI Version** 
6.2.1

**What AWS Services are you utilizing?**
AWS Amplify, DynamoDB, AppSync

**Provide additional details e.g. code snippets**
In our application, we would like to fill a models field value on item creation from a related model.

Imagine the following graphql schema:

```graphql
type Job
    @model

    # Each Job belongs to one Subsidiary, which in turn belongs to an Employer...
    @key(name: "bySubsidiary", fields: ["subsidiaryID"])
    # ... so the job should belong to the same Employer as well.
    @key(name: "byEmployer", fields: ["employerID"]) {

    id: ID!
    Subsidiary: Subsidiary! @connection(fields: ["subsidiaryID"])
    subsidiaryID: ID!
    Employer: Employer! @connection(fields: ["employerID"])
    employerID: ID!
}

type Subsidiary
    @model
    @key(name: "byEmployer", fields: ["employerID"]) {
    id: ID!
    name: String!
    Employer: Employer! @connection(fields: ["employerID"])
    employerID: ID!
}

type Employer
    @model {
    id: ID!
    name: String!
    Subsidiaries: [Subsidiary!] @connection(keyName: "byEmployer", fields: ["id"])
    Jobs: [Job!] @connection(keyName: "byEmployer", fields: ["id"])
}
```

So each Job belongs to a Subsidiary and an Employer, while the Subsidiary must belong to the same Employer. To enforce this relations, we would like to fill the Jobs `employerID` on creation from the linked Subsidiary's `employerID`.

*How can this be achieved using AWS Amplify?*

Do you have any experience with such requirements? Possibly with a sample?

However, we decided on this schema, as there seems to be no other easy way of listing and filtering all the Jobs belonging to an Employer without implementing a full custom `Query`. Additionally, our authentication (not depicted in the snippet above) depends on these relations. If you have any alternative ideas on how to solve this, your input is highly appreciated!

Thank you in advance for any help, ideas and hints.

Best,
Janik

**Comment by edwardfoyle** [comment]
Hi @j-mastr there are a few options you can consider.

The first is to look up the employer id of the subsidiary before creating a job and then create the job with the resulting employer id. This would not enforce the employer id is correct on the service side but should be straightforward to implement.

The second option is to use a [lambda resolver](https://docs.amplify.aws/cli/graphql-transformer/function/) to look up the corresponding employee id in the job creation resolver and insert it into the record on creation

The third option is to not include the employer in the jobs record. When querying for all employer jobs, first query for employer subsidiary, then for each subsidiary query for jobs. Depending on the size of your data set, this may or may not be feasible.

A final option is to implement a custom query as you mention to basically do the above in a lambda instead of on the client side. This will save some network roundtrips and allow you to handle pagination etc on the server side.

Another thing to consider is if the Employer - Subsidiary relationship could ever change it may cause a bunch of headaches if that relationship is duplicated in every job record.

I'd encourage you to join our discord community to discuss further options: https://discord.com/invite/amplify
