### ISSUE TITLE
'amplify init' won't use default AWS profile on a Cloud9 instance

### ISSUE THREAD

**Issue by s37justin** [aws-amplify/amplify-cli#857]
**Describe the bug**
On a Cloud9 instance, the `~/.aws/credentials` and `~/.aws/config` files are managed by AWS. There is a comment at the top of `~/.aws/credentials` saying that the file should not be modified. When I run `amplify init`, it forces me to create a new IAM user account, rather than prompting me to use the `[default]` credentials defined in  `~/.aws/credentials`.

**To Reproduce**
1. Spin up a Cloud9 instance
2. Follow the "Getting Started" steps here: https://aws-amplify.github.io/docs/js/start
3. Step 3 of the instructions (`amplify init`) says "AWS access credentials can not be found. Setup new user (Y/n)", which forces the creation of a new IAM user account
4. Paste in the new`accessKeyId` and `secretAccessKey` when prompted
5. Cloud9 throws warnings about an expired session token

**Expected behavior**
`amplify init` should detect that there is already an existing `[default]` aws-cli profile, and offer the option of selecting and using that profile.

**Additional context**
`amplify init` works as expected on my Mac laptop. I tried adding the same comment to the top of my local `~/.aws/credentials` file, and it still correctly presented me with a list of profiles that I could choose from for the project, so it's not exactly clear what is different about the Cloud9 environment that is throwing it off...

**Comment by kaustavghosh06** [comment]
@s37justin Could you please install the latest version of the CLI > 1.0 and see if you still see the issue? I beleive the issue has been fixed in the latest version.

**Comment by mathewgries** [comment]
was there another update to the CLI done today. This was working this morning, but now I am getting this same reported error again.

I run these commands in the root of the cloud9 terminal:
# Update the AWS CLI 
pip install --user --upgrade awscli

# Install and use Node.js v8.10 (to match AWS Lambda) 
nvm install v8.10.0
nvm alias default v8.10.0

# Install the AWS Amplify CLI 
npm install -g @aws-amplify/cli

npx create-react-app myapp

I cd into the application root directory and run these commands:
npm install --save aws-amplify

npm install --save aws-amplify-react

amplify init

When I run amplify init, I am receiving the same issue the OP is reporting. I was able to do this without issue yesterday, and a few hours ago today. 

No matter what I do, I am being forced to create a new IAM user in the AWS management console.
I tried running amplify configure to reset the credentials, and when I type in an already existing user name within my set up roles, it tells me to set this up as a new IAM user.

**Comment by kaustavghosh06** [comment]
@mathewgries Which version of the CLI were you using before?

**Comment by mathewgries** [comment]
@kaustavghosh06 
I apologize, but I do not know. I ran the same commands before to set up the environment, so it would have been whatever the latest release was. I'm sure that is no help though.

**Comment by UnleashedMind** [comment]
Cloud9 stores the temp credentials and the region in the `~/.aws/credentials` file, and does not allow you to modify that file. And it does not create the `~/.aws/config` file for you.  
But the Amplify CLI checks the `~/.aws/config` file for named profiles, that's why is not getting the default profile. 
Run `amplify configure` won't solve the problem, because the command will attempt to save the new profile credentials into the ~/.aws/credentials file, which is not allowed by Cloud9. 
We will have a discussion among the team on how to overcome this conflict. 

But for now, you can use this workaround: 
1. create the ~/.aws/config file
2. copy the contents in the ./aws/credentials into the ~/.aws/config file; then you will have the default profile when you run `amplify init`. 
3. If you want to add another named profile, just add to the ~/.aws/config file these contents (I named the profile `testInit`):
```ini
[profile testInit]
aws_access_key_id=<access key id>
aws_secret_access_key=<secret access key>
aws_session_token=<optional session token for temp credentials>
region=<region, such as 'us-west-2'>
``` 
Then when you run `amplify init`, you will see the option to select the profiles in the ~/.aws/config file.

**Comment by kay-is** [comment]
I created a symlink, which seems to work too. If Amplify-CLI looks into that file before every push, it will get the current credentials even if Cloud9 updated them.

    $ cd ~/.aws
    $ ln -s credentials config

**Comment by kaustavghosh06** [comment]
Closing this issue based on the response given by @UnleashedMind. Let me know if you're still facing this problem and we can re-open this issue.

**Comment by pseudyx** [comment]
> Cloud9 stores both the aws temp credentials and region as the default profile in the `~/.aws/credentials` file, it uses that profile to connect to other aws services, and does not allow you to modify that file. It puts a comment in the file `# Do not modify this file, if this file is modified it will not be updated. If the file is deleted, it will be recreated on <date>$`
> Cloud9 It does not create the `~/.aws/config` file for you.
> The Amplify CLI, on the other hand, checks the `~/.aws/config` file for named profiles, that's why it is not getting the default profile solely stored in the `~/.aws/credentials` file.
> Run `amplify configure` won't solve the problem, because the command will attempt to save the new profile's credentials into the `~/.aws/credentials` file, which is not allowed by Cloud9.
> We will have a discussion among the team on how to overcome this limitation.
> 
> But for now, you can use this workaround:
> 
> 1. create the `~/.aws/config` file
> 2. copy the contents in the `~/.aws/credentials` into the `~/.aws/config` file; then you will have the default profile when you run `amplify init`.
> 3. If you want to add another named profile, just add to the `~/.aws/config` file these contents (I named the profile `testInit`):
> 
> ```ini
> [profile testInit]
> aws_access_key_id=<access key id>
> aws_secret_access_key=<secret access key>
> aws_session_token=<optional session token for temp credentials>
> region=<region, such as 'us-west-2'>
> ```
> 
> Then when you run `amplify init`, you will see the option to select the profiles in the `~/.aws/config` file.

this shouldn't be the case... this is a violation of bounded contexts.
aws cli and amplify cli should maintain their own contexts
as a user I can set up profiles within aws cli and I can set up profiles in amplify cli. but they should not be the same profiles... I have specific profiles for amplify, and different profiles for other parts of aws

the reason this issue exists is because amplify cli is attempting to use the aws cli bounded context 
if aws cli makes a change to how they manage credentials, it would cause another issue with Amplify cli

the entire point of bounded contexts
to maintain context segregation
