### ISSUE TITLE
Unable to remove Notification resource in Amplify

### ISSUE THREAD

**Issue by PPilestedt** [aws-amplify/amplify-cli#9426]
Hi!

I need help removing a deleted Notification resource that is still existing in my project. I believe it started because we removed the pinpoint project from the GUI...

I have tried deleting notifications through the CLI but this is the response i got:

>amplify remove notifications
? Choose what to remove.: FCM
?api key: xxxxx
× update channel error
Resource not found

tried the same thing but instead of removing FCM i chose "the pinpoint application" and got this rtesponse:
"Pinpoint project deletion error
Application not found"

I can still see the resource under notifications..

![Screenshot 2022-01-05 150428](https://user-images.githubusercontent.com/71870264/148233901-9bb9ce9a-e2eb-4945-bc32-79dfbfc7a585.png)
.

All help is greatly appriciated!

**Comment by edwardfoyle** [comment]
@PPilestedt when you say you "removed the pinpoint project from the GUI" do you mean you removed the pinpoint resources using the AWS console rather than through Amplify?

If so, the resources are deleted but Amplify doesn't know that which is likely the cause of the failures.

**Comment by PPilestedt** [comment]
yes exactly. I removed it from the web console and it seems like the notification resource still thinks the pinpoint project still exists.
its looking for the project called finfollow-pinpoint-dev that is removed.

I cannot create a new FCM connection because aws believes that it is already configured. And if i try to edit the existing resource with the update CLI command it tells me its missing.

no pinpoint projects
![image](https://user-images.githubusercontent.com/71870264/148512496-b7bb8d9d-3f3d-4cee-9683-103ac647467f.png)

unable to remove notification resource
![image](https://user-images.githubusercontent.com/71870264/148512593-71116218-3138-4ed8-be46-79f40bbdb4dd.png)

trying to remove FCM through amplify CLI:
![image](https://user-images.githubusercontent.com/71870264/148512991-85518b07-3b95-4f82-9933-42e01712dcf2.png)

**Comment by PPilestedt** [comment]
Anyone with a suggestion on how to remove the notification resource?

**Comment by edwardfoyle** [comment]
Hi @PPilestedt you'll need to manually remove the notifications category from your local Amplify files. To do that, remove the relevant blocks from the `team-provider-info.json`, `amplify-meta.json` and `backend-config.json` files. You can also safely remove the contents of the `amplify/backend/notifications/<resource name>` directory. Then when you run `amplify push` this should remove the notifications resource from your Amplify project.

In the future, it will generally cause problems if an Amplify-managed resource is modified or removed in the console. This is because those changes are not synced back to the Amplify project and can cause a state where Amplify is no longer able to manage the resource.
