### ISSUE TITLE
OpenSearch can't search @ symbol

### ISSUE THREAD

**Issue by lehoai** [aws-amplify/amplify-cli#9588]
>**Note**: If your question is regarding the AWS Amplify Console service, please log it in the 
[AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
OpenSearch

**Amplify CLI Version** 

You can use `amplify -v` to check the amplify cli version on your system
7.6.9

**What AWS Services are you utilizing?**
OpenSearch

**Provide additional details e.g. code snippets**

I am developing a chat application that uses OpenSearch (@searchable in Graphql file) to search messages, but am unable to search @ character (or some special characters). After a few searches on google, there is a solution: change the analyzer to whitespace. But I don't know how to do it with cli.
Please help thanks.

**Comment by jhockett** [comment]
Hey @lehoai, could you share in more detail the query that you are trying to run?

`@` isn't a special character as far as I know, but there are several special characters listed here that would require escaping with a backslash `\`: https://opensearch.org/docs/latest/opensearch/query-dsl/full-text/#simple-query-string

**Comment by lehoai** [comment]
@jhockett 
Thank you for your response.

here is my query.
```
const data = await API.graphql(graphqlOperation(searchMessagess, {
        nextToken: null,
        filter: {
          room_id: { eq: item },
          content: { wildcard: search }, // search = '@'
        },
        sort: { direction: 'desc', field: "createdAt" }
      }));
```
It can't find out the '@' character.

**Comment by sundersc** [comment]
@lehoai - By default, opensearch uses Standard analyzer and it seems like `@` symbol is considered as delimiter to tokenize the text though I couldn't find any documentation to support it. Since `regex` and `wildcard` run on individual token, it won't match `@` sign. As you stated, changing to Whitespace analyzer would solve your problem but unfortunately there is not an option to do it through CLI today. I'm marking this as feature-request.

Please refer to the screenshots for the difference between standard and whitespace analyzer.

**Standard Analyzer**
![image](https://user-images.githubusercontent.com/83315412/151261333-b1bf2f3e-48d1-45a1-8a5b-927b8e015da4.png)

**Whitespace Analyzer**
![image](https://user-images.githubusercontent.com/83315412/151261355-85106542-ec1a-4776-9c1e-60cb1d1afa93.png)

I'm also checking whether analyzer can be customized using overrides.

**Comment by sundersc** [comment]
It is not possible to configure using overrides. Another option is to create the index manually first through Kibana console. Here is example model `todo` where `description` field use `whitespace` analyzer.

```graphql
type Todo @model @searchable {
  id: ID!
  name: String!
  description: String
}
```

Create Index
```
PUT todo
{
  "mappings": {
    "properties" : {
      "__typename" : {
        "type" : "text",
        "fields" : {
          "keyword" : {
            "type" : "keyword",
            "ignore_above" : 256
          }
        }
      },
      "createdAt" : {
        "type" : "date"
      },
      "description" : {
        "type" : "text",
        "analyzer": "whitespace", 
        "search_analyzer": "whitespace",
        "fields" : {
          "keyword" : {
            "type" : "keyword",
            "ignore_above" : 256
          }
        }
      },
      "id" : {
        "type" : "text",
        "fields" : {
          "keyword" : {
            "type" : "keyword",
            "ignore_above" : 256
          }
        }
      },
      "name" : {
        "type" : "text",
        "fields" : {
          "keyword" : {
            "type" : "keyword",
            "ignore_above" : 256
          }
        }
      },
      "updatedAt" : {
        "type" : "date"
      }
    }
  }
}
``` 

The index needs to be created before adding any data to it. OpenSearch doesn't allow modifying the analyzer if index was already created. In such case, it requires to delete the index, recreate with the new config and backfill the data.

**Comment by redjonzaci** [comment]
Is there any other workaround available for this except for manually creating the index with a non-default analyzer?
