### ISSUE TITLE
How to limit user storage?

### ISSUE THREAD

**Issue by aryan1107** [aws-amplify/amplify-cli#9610]
Hi I have a todo like app for pictures. User can add picture I used s3 bucked (add storage command).

How can I limit storage per user for example a user can use total of 5 GB maximum.

Can it be done? Thanks

**Comment by jhockett** [comment]
Hi @aryan1107, without knowing specifics of what you're trying to solve, I would probably create an API that saves some metadata about the files stored in S3 for a given user in a database, so that on each upload, a Lambda function can efficiently check to see if the upload would surpass the size constraints.

General how-to questions like this are best suited for our [discord](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#community) where we have a helpful and friendly community.
