### ISSUE TITLE
Amplify Publish prompt, publishes regardless of users response.

### ISSUE THREAD

**Issue by mim-Armand** [aws-amplify/amplify-cli#965]
**Bug Description:**
When `amplify publish` command is ran, the CLI prompts the user with `Are you sure you want to continue?`
Even if the user selects **No**, the tool will still publish the project!

**To Reproduce**
1. Set up and init a minimal project
2. `amplify publish`
3. When prompted with `Are you sure you want to continue?` respond `No` and press enter
4. The process will go on to build, upload and publish! and at the end will print `Your app is published successfully`!

**Expected behavior**
To abort and exit the process immediately ( if the user selects `No` )

**Screenshots**
Please have a look [here](https://cdn-images-1.medium.com/max/1600/1*fpC07RfyrcBNLsIg_BqKBQ.png)

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser N/A
 - Version 1.1.4

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser N/A
 - Version N/A

**Additional context**
I'm not sure if this bug's related to other components in the project or if it's a low-level bug of the CLI tool, if you couldn't reproduce the behavior please let me know and I'll try to find out in what situations this happens!

**Comment by yuth** [comment]
Thanks for reporting this. 

We wanted to let user publish hosting changes without updating the backend if the user wanted it, but the confirmation prompt doesn't convey the right message.

There is also another problem that I noticed, if the hosting was just added and user directly ran `publish` command and said `no` in the confirmation prompt, publish fails. We should not go ahead with publishing at all since there is no S3 bucket available to publish
