### ISSUE TITLE
Unable to set ElasticSearchInstanceType in team-provider-info.json

### ISSUE THREAD

**Issue by benjamindoe** [aws-amplify/amplify-cli#9728]
**Which Category is your question related to?**
GraphQL

**Amplify CLI Version**
7.6.15

I've tried to follow the guide on the amplify [documentation on how to set the instance type](https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#set-up-opensearch-for-production-environments). I'm running into the following error:
```
Parameters: [ElasticSearchInstanceType] do not exist in the template
```
My project has been upgraded to the v2 transformer from the v1 transformer. Prior to the upgrade, setting `ElasticSearchInstanceType` worked. I've had a look at the `cloudformation-template.json` file in the `amplify/api/<api-name>/build` folder and discovered that `ElasticSearchInstanceType` is not being set as a parameter for the `SearchableStack`. I've tried making a change to the schema file and I've tried to delete the build folder and rerun `amplify api gql-compile` but these steps do not solve the issue. I have also tried setting `ElasticSearchInstanceType` in `parameters.json` and while it doesn't throw any errors, it doesn't update the instance size.

**Comment by bcs-gbl** [comment]
Im confused about team-provider-info.json and override.ts :

**override.ts:** [doc](https://docs.amplify.aws/cli/graphql/override/#customize-amplify-generated-resources-for-searchable-opensearch-directive)

I can override this values in this config file:
- instanceCount: 1
- instanceType: 'm6g.large.elasticsearch'
- and elasticsearchVersion = 'OpenSearch_1.1'
but, i cannot customize this values by amplify environments

**team-provider-info.json** [doc](https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#set-up-opensearch-for-production-environments)
I can override this values in this config file:
- "OpenSearchInstanceType", but cannot instancecount, opensearch version (1.1 latest), and others, 
but the environments are separated.

So,
I'd like to override this values but in different environments because We dont want 
to pay a lot for Opensearch nodes and no need high availability in all other environments (dev, stage, and so on).

I didnt find any info or documentation about options in team-provider-info.json like instancecount.

Can anybody help with some doc, or parameters, or any other info?

**Comment by benjamindoe** [comment]
@ammarkarachi Thanks for updating the docs.

I've tried using `OpenSearchInstanceType` in the `team-provider-info.json` but I'm still running into the same error:
```
Parameters: [OpenSearchInstanceType] do not exist in the template
```

**Comment by bcs-gbl** [comment]
@benjamindoe same here.

**Comment by sacrampton** [comment]
Hi @ammarkarachi - this is a pretty big hole in the migration to V2 - any chance this can be expedited? Unless there is a workaround I'm missing?

**Comment by nolanperk** [comment]
Hey @marcvberg we see that the PR got approved to solve this, but is there any word on when it’s being released? We are delaying our product release until this is solved.

**Comment by benjamindoe** [comment]
Has this been deployed yet? #9860 suggests not as their cli version is 7.6.22

**Comment by giorgiocarniel** [comment]
Same error on `8.0.2`

**Comment by giulioambrogi** [comment]
Tried using `OpenSearchInstanceType` in 7.6.25, same error. @aws support please reopen or suggest what version we should upgrade to

**Comment by josefaidt** [comment]
Hey folks in the thread :wave: the parameter has changed and confirmed working on the latest version of the CLI (8.3.1), we should now use `OpenSearchInstanceType` https://docs.amplify.aws/cli/graphql/search-and-result-aggregations/#set-up-opensearch-for-production-environments
