### ISSUE TITLE
Query fields changing from non-nullable to nullable, fixed by running 'amplify codegen'

### ISSUE THREAD

**Issue by BrettSGA** [aws-amplify/amplify-cli#9770]
> **Note**: If your question is regarding the AWS Amplify Console service, please log it in the
> [AWS Amplify Console repository](https://github.com/aws-amplify/amplify-console/issues)

**Which Category is your question related to?**
Amplify CLI

**Amplify CLI Version**
7.6.3

**What AWS Services are you utilizing?**
Amplify [API, Auth], DynamoDB, Cognito, S3 

**Provide additional details e.g. code snippets. _Be sure to remove any sensitive data._**
Somewhere along my workflow, my GraphQL queries are changing and I'm receiving this error:

**"Validation error of type VariableTypeMismatch: Variable type 'String' doesn't match expected type 'String!' @ 'activitiesSortedByName'"**

I've realized the reason why is because in my queries, certain fields are being changed from non-nullable to nullable:

**BEFORE:**
```js
export const activitiesSortedByName = /* GraphQL */ `
  query ActivitiesSortedByName(
    $type: String!
    $name: ModelStringKeyConditionInput
    $sortDirection: ModelSortDirection
    $filter: ModelActivityFilterInput
```
**AFTER:**
```js
export const activitiesSortedByName = /* GraphQL */ `
  query ActivitiesSortedByName(
    $type: String
    $name: ModelStringKeyConditionInput
    $sortDirection: ModelSortDirection
    $filter: ModelActivityFilterInput
```

A simple **amplify codegen** fixes the issue, and my queries are correct again. Just curious why this is happening, if anyone has any insight. Thank you.

**Comment by yuth** [comment]
@BrettSGA could you explain your workflow? Does this happen when when codegen is run during `amplify push`?

**Comment by ngnathan** [comment]
Thought I'd also chime in, since I have a similar issue.

Context: 
My main project (React + TypeScript + Amplify Backend definitions) runs fine and when running `amplify codegen` it generates queries with non-nullable fields.

But I have a second front-end (React + TypeScript).  On this project, when I run `amplify pull` and `amplify codegen` it generates queries with nullable fields, which causes the same error as @BrettSGA .

As a workaround (or is it the right way of dealing with this?), I had to copy the schema.json from the main project, over to the second front-end.  After running `amplify codegen` this seems to have resolved the issue for me.

I'm running Amplify CLI 7.6.20

**Comment by BrettSGA** [comment]
Closing as it hasn't happened again after posting. If I do see it again, I'll just run _amplify codegen_.
