### ISSUE TITLE
Amplify Studio: Deployment Fails with Parameters: [parentStack] must have values

### ISSUE THREAD

**Issue by moneeb0930** [aws-amplify/amplify-cli#9800]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.0

### Amplify CLI Version

7.6.21

### What operating system are you using?

Windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

I manually added a Federated Identity pool in the Cognito Console, but I deleted it today and retried the deployment. However, still fails.

### Amplify Categories

auth, api, functions, storage

### Amplify Commands

Not applicable

### Describe the bug

When using Amplify Studio (dev environment), I made some changes to the tables in the Data Modeling module.  I went to Save and Deploy those changes, but the deployment fails with  Parameters: [parentStack] must have values error.  
![image](https://user-images.githubusercontent.com/80500252/154600463-68e0c13e-24f6-48fa-a332-d75169d0b0ed.png)

When performing "Amplify Push" after updating the GraphQL schema, the command fails using CLI as well:
![image](https://user-images.githubusercontent.com/80500252/154608700-2c3ae2e4-2c88-4d9f-b32d-a53eac6caa26.png)
![image](https://user-images.githubusercontent.com/80500252/154599935-146941b9-46ff-4f5f-96ba-2b93670f0772.png)

appId: du4dl9mwnya02

### Expected behavior

The deployment to succeed in Amplify Studio console

### Reproduction steps

Navigate to the Data Tab/Data Modeling
Click Deploy

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by sachscode** [comment]
@moneeb0930  
Since `amplify push` is failing locally, could you provide more details on this ? 
Could you please confirm the following: 
1. The cloudformation in your ./amplify/backend/awscloudformation/nested-cloudformation-stack.yml  has a `Parameters` section . 
2. The amplify/.config/local-env-info.json has the project path correctly configured. (  If this doesn't have the correct path, please run `amplify configure project` or change the path manually by editing the local-env-info.json file. )

If the issue is not addressed above, could you please provide more details on what changes were performed on the Data-Model ?

**Comment by moneeb0930** [comment]
Hi @josefaidt Thanks for helping... :)
So my project doesn't appear to have the above mentioned files, I did try searching for them. I ran the amplify configure project and it went successfully after answering the prompts regarding project settings.  After that, I did the Amplify Push, which still deployed unsuccessfully - same error ( [parentStack] must have values).

Project files - Amplify folder
![image](https://user-images.githubusercontent.com/80500252/155057208-1f5da5e4-2cdc-4c7f-94d4-62b0adb0cc09.png)

![image](https://user-images.githubusercontent.com/80500252/155057333-1d85ccf3-b416-4c4f-95c4-0dd076a1234b.png)

Changes for the Data Model:  I used the Amplify Studio UI and on the Data Modeling tab, I updated a table column from String to Int required on the Cities table.  Then I created a New Table - with just an Email Column.  Went to click Save/Deploy and encountered the error.

**Comment by moneeb0930** [comment]
Just checking if there are any updates on this issue?...

**Comment by ykethan** [comment]
hey @moneeb0930, apologize for the delay in a response. On diving deep and discussing this with the team. In order to mitigate the deployment failing, could you please try the following steps. (Note: before performing this please create a backup of your GQL schema changes and Dynamo DB backup on S3)

1. `amplify pull`  - select the previous deployed version
2.  perform an `amplify gql-compile`
3. `amplify push`  and check if it succeeds.
4. Confirm if the field converted from string to char in the `Cities` table is used as a GSI ( with "@index" ) in any part of the GQL schema. If so, remove the GSI, and do an `amplify push`. Then once this completes, make the change from string to int and perform a push. ( this is to get around any timeouts in DDB table change )
5. Run a Drift check on the DDB table side and confirm if there are any manual changes performed on the tables.

If there are any drift, please do let us know we would be happy in assisting you on this.

**Comment by ykethan** [comment]
Hello @moneeb0930, following up on this to see if you would require any assistance on this.

**Comment by moneeb0930** [comment]
Hi thank you, sorry for the late response. I will save these suggestions for should there be any future encounters with the reported error, but I have since created a new auth user pool and attached my amplify project to the new auth which resolved the issue. Please feel free to close this ticket. Thanks again for your assistance.
