### ISSUE TITLE
Displaying images uploaded with Storage

### ISSUE THREAD

**Issue by kay-is** [aws-amplify/amplify-cli#9895]
**Please describe which feature you have a question about?**

I want to display images uploaded to a `Storage` with an `<img>`

**Provide additional details**

I created an application with auth, hosting, and storage. 

I configured the storage so that authenticated users can write, update, read, and delete, and unauthenticated users can only read.

After uploading a file, I list all public files in storage and generate image URLs and tags. 

But in the end, I only get 403 Access Denied responses.

**What AWS Services are you utilizing?**

- auth
- storage
- hosting

**Provide additional details e.g., code snippets**

```javascript
const bucketUrl =
  "https://" +
  awsconfig.aws_user_files_s3_bucket +
  ".s3." +
  awsconfig.aws_user_files_s3_bucket_region +
  ".amazonaws.com";

async function refreshGallery() {
  const files = await Storage.list("");
  galleryDiv.innerHTML = "";
  files.forEach((file) => {
    const image = document.createElement("img");
    image.src = `${bucketUrl}/public/${file.key.split(" ").join("+")}`;
    galleryDiv.appendChild(image);
  });
}
```

**Comment by josefaidt** [comment]
Hey @kay-is :wave: thanks for raising this! We'll take a look at this soon, however in the meantime this would be a great question for our [community Discord server](https://discord.gg/invite/amplify)!

**Comment by ykethan** [comment]
Hello @kay-is, apologies for the delay in a response. I was able to replciate the error in my Amplify application.
from the code sample provided I see that you are trying to retrive a image url for the file. I was able to mitigate the issue by utilizing the `Storage.get` method.

```js
async function getFileUrls() {
  const files = await Storage.list('')
  const urls = []
  for (const file of files) {
    urls.push(await Storage.get(file.key))
   
  }
  return urls
}
```
The code printed out the URL's for the files in the public folder. Additonally, I was able to find that the 403 error occured due to the access level premission on the object in the S3 bucket. 

Hope this helps, Please do let me if this aligns with your use case.
