### ISSUE TITLE
Can't amplify push due to symlink issue

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-cli#9981]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.6

### Amplify CLI Version

7.6.24

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no

### Amplify Categories

function

### Amplify Commands

push

### Describe the bug

I updated to the latest amplify, and attempted a push. I got this error: 

```
hisham@mb3 ess-app % amplify push
✖ There was an error pulling the backend environment hishamdev.
🛑 An error occurred during the push operation: EEXIST: file already exists, symlink '../acorn/bin/acorn' -> '/Users/hisham/src/ess-app/amplify/.temp/#current-cloud-backend/function/essappCliLambdaLayer/lib/nodejs/node_modules/.bin/acorn'
⚠️ Please refer Amplify CLI troubleshooting guide at : https://docs.amplify.aws/cli/project/troubleshooting/
```

### Expected behavior

amplify push should work fine

### Reproduction steps

I didn't do anything special except update a package my layer uses. 

It seems this is a dupe of https://github.com/aws-amplify/amplify-cli/issues/2948? 

The proposed fix or workaround seems ambigious / hacky. Needs more looking into. 

https://docs.amplify.aws/cli/project/troubleshooting doesn't cover this use case. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by josefaidt** [comment]
Hey @hisham :wave: thanks for raising this! And apologies for the inconvenience, I do agree symlink issues can be handled better. I took a look through the linked issue and although the workarounds should be sufficient I wrote a [few steps](https://github.com/aws-amplify/amplify-cli/issues/9961#issuecomment-1065613889) to show how we can edit the `#current-cloud-backend` folder contents and re-deploy. From the steps, instead of editing a GraphQL schema we will be _removing_ the symlink. Can you try running through the workaround steps and see if that alleviates the issue? And for subsequent pushes we'll want to ensure the symlink is not created and packaged

**Comment by hisham** [comment]
Hey I ended up deleting the .temp folder within my amplify directory then push worked, closing. Thanks for all the help!
